import {useLayoutEffect,useRef,type ReactNode} from 'react';
export type Position={key:string;name:string;active:boolean;description?:string;category?:string;display_order?:number;version?:number};
export type Area={id:string;name:string;active:boolean};
export const groups=['Coaching','Program','Functional Leads','Other Leadership'];
export const linked=(key:string)=>key==='finance_lead'?'Finance approval':['lead_coach_1','lead_coach_2'].includes(key)?'Lead Coach approval':null;
export function Dialog({children,busy,onClose,label='Member editor'}:{children:ReactNode;busy:boolean;onClose:()=>void;label?:string}){
 const ref=useRef<HTMLDialogElement>(null);useLayoutEffect(()=>{const d=ref.current!,opener=document.activeElement as HTMLElement|null;d.showModal();return()=>{d.close();opener?.focus();};},[]);
 return <dialog ref={ref} className="team-dialog" aria-label={label} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}>{children}</dialog>;
}
type Props={busy:boolean;error:string;close:()=>void;save:(action:string,p:Record<string,unknown>)=>Promise<boolean>};
function Frame({title,children,busy,error,close}:{title:string;children:ReactNode}&Omit<Props,'save'>){return <Dialog label={title} busy={busy} onClose={close}><section className="team-editor"><div className="section-heading"><h2>{title}</h2><button disabled={busy} onClick={close}>Close editor</button></div>{children}{error&&<p role="alert">{error}</p>}</section></Dialog>;}
const fields=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form));
export function PositionForm({position,...p}:Props&{position:Position|null}){return <Frame {...p} title={position?'Edit position':'New position'}><p>Team positions describe responsibility. Account roles control broad suite access.</p>{position&&linked(position.key)&&<p className="team-linked">System linked: {linked(position.key)}. Deactivation removes future approval eligibility. The machine key cannot change.</p>}<form onSubmit={async e=>{e.preventDefault();const f=fields(e.currentTarget);if(await p.save('position_save',{...f,key:position?.key||f.key,create:!position,version:position?.version,active:position?f.active==='true':true,display_order:Number(f.display_order)}))p.close();}}><fieldset disabled={p.busy}><div className="team-fields"><label>Position name<input name="name" defaultValue={position?.name} required maxLength={100}/></label>{position?<p>Stable key: <code>{position.key}</code></p>:<label>Position key<input name="key" required pattern="[a-z][a-z0-9_]{1,63}" maxLength={64} placeholder="e.g. safety_lead"/></label>}<label>Description<input name="description" defaultValue={position?.description} maxLength={1000}/></label><label>Group<select name="category" defaultValue={position?.category||'Other Leadership'}>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label>Display order<input name="display_order" type="number" min={0} max={9999} defaultValue={position?.display_order||0} required/></label>{position&&<label>Position state<select name="active" defaultValue={String(position.active)}><option value="true">Active</option><option value="false">Inactive</option></select></label>}<label>Reason for position change<input name="reason" required maxLength={2000}/></label></div><button className="primary">Save position</button></fieldset></form><p>Keys and assignment history are retained. New positions grant no permissions. Deletion is unavailable.</p></Frame>;}
export function AreaForm({area,...p}:Props&{area:Area}){return <Frame {...p} title="Edit area"><p>Renaming preserves the area ID and existing references. Archive areas instead of deleting them.</p><form onSubmit={async e=>{e.preventDefault();const f=fields(e.currentTarget);if(await p.save('area_save',{...f,id:area.id,expected_name:area.name,expected_active:area.active,active:f.active==='true'}))p.close();}}><fieldset disabled={p.busy}><div className="team-fields"><label>Area name<input name="name" defaultValue={area.name} required maxLength={100}/></label><label>Area state<select name="active" defaultValue={String(area.active)}><option value="true">Active</option><option value="false">Archived</option></select></label><label>Reason for area change<input name="reason" required maxLength={2000}/></label></div><button className="primary">Save area</button></fieldset></form><p>Merge is deferred to preserve historical Attendance and Finance attribution. Deletion is unavailable.</p></Frame>;}
export function InviteForm({areas,invite,...p}:Omit<Props,'save'>&{areas:Area[];invite:(p:Record<string,unknown>)=>Promise<boolean>}){
 const id=useRef(crypto.randomUUID());return <Frame {...p} title="Invite member"><p>Send a Team 4418 account invitation. Assign team positions from the member editor after creation.</p><form onSubmit={async e=>{e.preventDefault();if(await invite({...fields(e.currentTarget),id:id.current}))p.close();}}><fieldset disabled={p.busy}><div className="team-fields"><label>Email<input name="email" type="email" required maxLength={254}/></label><label>Display name<input name="display_name" required maxLength={150}/></label><label>Account role<select name="role" defaultValue="student">{['student','lead','mentor','admin','readonly'].map(r=><option key={r}>{r}</option>)}</select></label><label>Functional area<select name="area_id"><option value="">Unassigned</option>{areas.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Registration<select name="member_status"><option value="">Not tracked</option>{['prospective','registered','inactive'].map(r=><option key={r}>{r}</option>)}</select></label><label>Invitation reason<input name="reason" required maxLength={2000}/></label></div><p>Account role controls suite access. Only select mentor/admin for authorized team managers.</p><button className="primary">Send invitation</button></fieldset></form></Frame>;
}
export function StateForm({member,...p}:Props&{member:{id:string;display_name:string;active:boolean;updated_at:string}}){const title=member.active?'Deactivate member':'Reactivate member';return <Frame {...p} title={title}><p>{member.display_name}: {member.active?'Access will be disabled.':'Access will be restored.'} Existing records and attribution are preserved.</p><form onSubmit={async e=>{e.preventDefault();if(await p.save('member_state',{...fields(e.currentTarget),user_id:member.id,expected_updated_at:member.updated_at,active:!member.active}))p.close();}}><fieldset disabled={p.busy}><label>Reason for access change<input name="reason" required maxLength={2000}/></label><button className="primary">Confirm {member.active?'deactivation':'reactivation'}</button></fieldset></form></Frame>;}
