import { useEffect, useState } from 'react';
import {Dialog as MemberDialog,PositionForm,AreaForm,InviteForm,StateForm,groups,linked,type Position,type Area} from './ManagementForms';
import { supabase } from '../attendance/service';
import './team.css';
type Member = { email?:string; id:string; display_name:string; role:string; active:boolean; primary_area_id:string|null; updated_at:string; member_status:string|null; team_area:string|null };
type Assignment = {id:string;user_id:string;position_key:string;assigned_by:string;assigned_at:string;assignment_reason:string;revoked_at:string|null;revoked_by:string|null;revoke_reason:string|null};
type AuditSnapshot={name?:string;active?:boolean;profile?:{role?:string}};
type Context = {members:Member[];areas:Area[];positions:Position[];invitations?:{id:string;email:string;display_name:string;status:string;created_at:string;user_id:string|null}[];assignments:Assignment[];history:{id:number;user_id:string|null;before_data?:AuditSnapshot;after_data?:AuditSnapshot;actor_id:string;action:string;reason:string;created_at:string}[]};
const activity=(h:Context['history'][number])=>h.action==='member'&&h.before_data?.profile?.role!==h.after_data?.profile?.role?`Role changed: ${h.before_data?.profile?.role} → ${h.after_data?.profile?.role}`:h.action==='position_updated'&&h.before_data?.active!==h.after_data?.active?`Position ${h.after_data?.active?'reactivated':'deactivated'}`:h.action==='position_updated'&&h.before_data?.name!==h.after_data?.name?'Position renamed':h.action.replaceAll('_',' ');
const message=(e:unknown)=>e&&typeof e==='object'&&'message' in e?String(e.message):'Unable to load team management.';
async function rpc(name:string,args:Record<string,unknown>={}) {
 if(!supabase) throw new Error('Team connection is not configured.');
 const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);
 try {const r=await supabase.rpc(name,args).abortSignal(controller.signal);if(r.error)throw r.error;return r.data;} finally{clearTimeout(timeout);}
}
export function TeamManagement({workspace}:{workspace:boolean}) {
 const [tab,setTab]=useState('Members');
 const [inviting,setInviting]=useState(false),[position,setPosition]=useState<Position|null|undefined>(),[area,setArea]=useState<Area|null>(null),[stateChange,setStateChange]=useState<Member|null>(null),[roleFilter,setRoleFilter]=useState(''),[activeFilter,setActiveFilter]=useState(''),[areaFilter,setAreaFilter]=useState('');
 const [allowed,setAllowed]=useState(false),[ready,setReady]=useState(false),[data,setData]=useState<Context|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[selected,setSelected]=useState<string|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{
  if(!supabase){setReady(true);return;}
  let live=true,version=0;
  const update=(uid?:string)=>{const v=++version;setAllowed(false);setData(null);setError('');setReady(!uid);if(!uid){clearTimeout(timer);return;}
   setTimeout(()=>{void (async()=>{const {data:p,error:e}=await supabase!.from('profiles').select('role,active').eq('id',uid).abortSignal(AbortSignal.timeout(15000)).single();if(e)throw e;if(!live||v!==version)return;const ok=p.active&&['admin','mentor'].includes(p.role);setAllowed(ok);if(workspace&&ok){const c=await rpc('team_management_context_v2');if(live&&v===version)setData(c);}})().catch(e=>{if(live&&v===version)setError(message(e));}).finally(()=>{if(live&&v===version){clearTimeout(timer);setReady(true);}});},0);
  };
  const timer=setTimeout(()=>{if(live){setReady(true);setError('Team management timed out. Reload to try again.');}},15000);
  const sub=supabase.auth.onAuthStateChange((_event,session)=>update(session?.user.id));
  return()=>{live=false;version++;clearTimeout(timer);sub.data.subscription.unsubscribe();};
 },[workspace]);
 async function save(action:string,p:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{await rpc('team_manage_v2',{action,p});setData(await rpc('team_management_context_v2'));setNotice(action==='create_area'?'Team area added.':'Team management updated.');return true;}catch(e){setError(message(e));if(e&&typeof e==='object'&&'code' in e&&e.code==='42501'){setAllowed(false);setData(null);}return false;}finally{setBusy(false);}}
 async function invite(p:Record<string,unknown>){setBusy(true);setError('');try{const r=await supabase!.functions.invoke('team-invitations',{body:p,timeout:60000});if(r.error){const detail=r.error.context instanceof Response?await r.error.context.json().catch(()=>({})):{};throw Error(detail.error||'Invitation unavailable or needs review. Check Activity and reload before trying again.');}setData(await rpc('team_management_context_v2'));setNotice(r.data.status==='pending'?'Invitation sent.':'Invitation already recorded. Check its status.');return true;}catch(e){setError(message(e));return false;}finally{setBusy(false);}}
 if(!workspace)return allowed?<section className="team-entry" aria-labelledby="administration-heading"><div><h2 id="administration-heading">Administration</h2><p>Members, roles, and team positions.</p></div><a className="system-action" href="#team-management">Team Management →</a></section>:null;
 const member=data?.members.find(m=>m.id===selected);
 return <section className="team-management"><div className="section-heading"><div><h1>Team Management</h1><p>Shared team identity and positions across the 4418 suite.</p></div></div>
 {!member&&error&&<p role="alert">{error}</p>}{!member&&notice&&<p role="status">{notice}</p>}
 {!ready?<p role="status">Loading members…</p>:!allowed?<p>Active mentors and admins can manage the team. <a href="#">Sign in through Team Hub</a>.</p>:!data?<p>Team management is unavailable. <button onClick={()=>location.reload()}>Reload</button></p>:<>
 <nav className="team-tabs" aria-label="Team management views">{['Members','Positions','Areas','Activity'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {tab==='Members'&&<>
 <div className="team-view-heading"><h2>Members <span className="team-count">{data.members.length}</span></h2><button className="primary" onClick={()=>{setError('');setInviting(true);}}>+ Invite member</button></div>
 <label>Find a member<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, email, role, or position"/></label>
 <div className="team-filters"><label>Account role filter<select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="">All roles</option>{['student','lead','mentor','admin','readonly'].map(r=><option key={r}>{r}</option>)}</select></label><label>Account state filter<select value={activeFilter} onChange={e=>setActiveFilter(e.target.value)}><option value="">All states</option><option value="true">Active</option><option value="false">Inactive</option></select></label><label>Area filter<select value={areaFilter} onChange={e=>setAreaFilter(e.target.value)}><option value="">All areas</option>{data.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div>
 {(data.invitations||[]).filter(i=>i.status!=='accepted').map(i=><p className="team-invite-status" key={i.id}>{i.display_name} · {i.email} · Invitation: {i.status==='review'?'Needs review — do not resend':i.status==='pending'?'Pending acceptance':'Processing'}</p>)}
 <div className="team-member-grid">{data.members.filter(m=>(!roleFilter||m.role===roleFilter)&&(!activeFilter||String(m.active)===activeFilter)&&(!areaFilter||m.primary_area_id===areaFilter)).filter(m=>`${m.display_name} ${m.email||''} ${m.role} ${data.assignments.filter(a=>a.user_id===m.id&&!a.revoked_at).map(a=>data.positions.find(p=>p.key===a.position_key)?.name).join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(m=><article className="team-member" key={m.id}><h2>{m.display_name||'Unnamed member'}</h2><p className="team-email">{m.email||'Email unavailable'}</p><p>{m.role} · {m.active?'Active':'Inactive'} · {data.areas.find(a=>a.id===m.primary_area_id)?.name||'Unassigned'}</p><p>Registration: {m.member_status||'Not tracked'}</p><p>Positions: {data.assignments.filter(a=>a.user_id===m.id&&!a.revoked_at).map(a=>data.positions.find(p=>p.key===a.position_key)?.name).join(', ')||'None'}</p><button disabled={busy} onClick={()=>setSelected(m.id)}>Manage {m.display_name||'member'}</button></article>)}</div>
 {!data.members.length&&<p className="team-empty">No team accounts yet. Use Invite member to add the first account.</p>}
 {data.members.length>0&&search&&!data.members.some(m=>`${m.display_name} ${m.email||''} ${m.role} ${data.assignments.filter(a=>a.user_id===m.id&&!a.revoked_at).map(a=>data.positions.find(p=>p.key===a.position_key)?.name).join(' ')}`.toLowerCase().includes(search.toLowerCase()))&&<div className="team-empty"><p>No members match “{search}”.</p><button onClick={()=>setSearch('')}>Clear search</button></div>}
 </>}
 {tab==='Positions'&&<><div className="team-view-heading"><h2>Position ownership</h2><button className="primary" onClick={()=>{setError('');setPosition(null);}}>+ New position</button></div>{groups.map(group=><section className="team-directory-group" key={group}><h2>{group}</h2><div className="team-position-grid">{data.positions.filter(p=>(p.category||(['lead_coach_1','lead_coach_2'].includes(p.key)?'Coaching':p.key==='finance_lead'?'Functional Leads':'Other Leadership'))===group).sort((a,b)=>(a.display_order||0)-(b.display_order||0)||a.name.localeCompare(b.name)).map(p=><article className="team-member" key={p.key}><h2>{p.name}</h2>{linked(p.key)&&<p className="team-linked">System linked: {linked(p.key)}</p>}<p>{p.description}</p><button onClick={()=>{setError('');setPosition(p);}}>Edit {p.name}</button>{!p.active&&<p>Inactive position</p>}{data.assignments.filter(a=>a.position_key===p.key&&!a.revoked_at&&data.members.some(m=>m.id===a.user_id&&m.active&&m.role!=='readonly')).map(a=><button key={a.id} onClick={()=>setSelected(a.user_id)}>{data.members.find(m=>m.id===a.user_id)?.display_name||'Team member'} →</button>)}{!data.assignments.some(a=>a.position_key===p.key&&!a.revoked_at&&data.members.some(m=>m.id===a.user_id&&m.active&&m.role!=='readonly'))&&<><p className="team-vacancy">Unassigned</p><p>Choose a member to assign this position.</p><button onClick={()=>setTab('Members')}>Find a member</button></>}</article>)}</div></section>)}</>}
 {member&&<MemberDialog busy={busy} onClose={()=>setSelected(null)}><section className="team-editor" aria-label="Member editor"><div className="section-heading"><h2>{member.display_name||'Member'}</h2><button disabled={busy} onClick={()=>setSelected(null)}>Close editor</button></div>
 <form key={member.id+member.updated_at+member.member_status} onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void save('member',{...f,user_id:member.id,active:f.active==='true',member_status:f.member_status||null,expected_updated_at:member.updated_at,expected_member_status:member.member_status,expected_team_area:member.team_area});}}><fieldset disabled={busy}><div className="team-fields">
 <label>Display name<input name="display_name" defaultValue={member.display_name} required maxLength={150}/></label>
 <label>Account role<select name="role" defaultValue={member.role}>{['student','lead','mentor','admin','readonly'].map(r=><option key={r}>{r}</option>)}</select></label>
 <label>Active<select name="active" defaultValue={String(member.active)}><option value="true">Active</option><option value="false">Inactive</option></select></label>
 <label>Functional area<select name="primary_area_id" defaultValue={member.primary_area_id||''}><option value="">Unassigned</option>{data.areas.filter(a=>a.active||a.id===member.primary_area_id).map(a=><option key={a.id} value={a.id} disabled={!a.active}>{a.name}{!a.active?' (inactive)':''}</option>)}</select></label>
 <label>Registration<select name="member_status" defaultValue={member.member_status||''}>{!member.member_status&&<option value="">Not tracked</option>}{['prospective','registered','inactive'].map(r=><option key={r}>{r}</option>)}</select></label>
 <label>Reason for change<input name="reason" required maxLength={2000}/></label></div><button className="primary">Save member</button></fieldset></form>
 <p>Account role controls broad suite access; team positions describe responsibility.</p><button disabled={busy} onClick={()=>{setStateChange(member);setSelected(null);setError('');}}>{member.active?'Deactivate member':'Reactivate member'}</button>
 <details className="team-position-editor"><summary>Team positions</summary><form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void save('assign_position',{...f,user_id:member.id});}}><fieldset disabled={busy||!member.active||member.role==='readonly'}><div className="team-fields"><label>Position<select name="position_key" required><option value="">Choose position</option>{data.positions.filter(p=>p.active&&!data.assignments.some(a=>a.user_id===member.id&&a.position_key===p.key&&!a.revoked_at)).map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</select></label><label>Assignment reason<input name="reason" required maxLength={2000}/></label></div><button className="primary">Assign position</button></fieldset></form>
 {data.assignments.filter(a=>a.user_id===member.id&&!a.revoked_at).map(a=><form key={a.id} onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void save('revoke_position',{...f,user_id:member.id,assignment_id:a.id});}}><fieldset disabled={busy}><h4>{data.positions.find(p=>p.key===a.position_key)?.name}</h4><label>Removal reason<input name="reason" required maxLength={2000}/></label><button>Remove position</button></fieldset></form>)}
 </details>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </section></MemberDialog>}
 {tab==='Areas'&&<><div className="team-view-heading"><h2>Team areas</h2><span>Shared across the suite</span></div><div className="team-area-list">{data.areas.map(a=><div key={a.id}><strong>{a.name}</strong><span>{a.active?'Active':'Archived'} · {data.members.filter(m=>m.primary_area_id===a.id).length} members</span><button onClick={()=>{setError('');setArea(a);}}>Edit {a.name}</button></div>)}</div>{!data.areas.length&&<p className="team-empty">No areas yet. Add the team’s first functional area below.</p>}
 <details><summary>+ New area</summary><p>Existing area IDs and inventory ownership are preserved.</p><form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void save('create_area',f);}}><fieldset disabled={busy}><div className="team-fields"><label>Area name<input name="name" required maxLength={100}/></label><label>Area key<input name="slug" required maxLength={100} pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="e.g. fabrication"/></label><label>Reason for new area<input name="reason" required maxLength={2000}/></label></div><button className="primary">Add area</button></fieldset></form></details>
 </>}
 {tab==='Activity'&&<><div className="team-view-heading"><h2>Recent team changes</h2><span>Latest 100 recorded changes</span></div>{!data.history.length&&<p className="team-empty">No changes recorded yet. Member and position updates will appear here.</p>}<div className="team-activity">{data.history.map(h=><p key={h.id}>{data.members.find(m=>m.id===h.actor_id)?.display_name||'Administrator'} · {activity(h)} · {data.members.find(m=>m.id===h.user_id)?.display_name||h.after_data?.name} · {new Date(h.created_at).toLocaleString()} · {h.reason}</p>)}</div><details><summary>Position history</summary>{!data.assignments.length&&<p>No position assignments yet.</p>}{data.assignments.map(a=><p key={a.id}><strong>{data.members.find(m=>m.id===a.user_id)?.display_name||'Team member'}</strong> · {data.positions.find(p=>p.key===a.position_key)?.name} · {a.revoked_at?'Removed':'Assigned'} {new Date(a.revoked_at||a.assigned_at).toLocaleString()} · {a.revoke_reason||a.assignment_reason}</p>)}</details></>}</>}
 {allowed&&data&&inviting&&<InviteForm areas={data.areas} busy={busy} error={error} close={()=>setInviting(false)} invite={invite}/>}
 {allowed&&data&&position!==undefined&&<PositionForm position={position} busy={busy} error={error} close={()=>setPosition(undefined)} save={save}/>}
 {allowed&&area&&<AreaForm area={area} busy={busy} error={error} close={()=>setArea(null)} save={save}/>}
 {allowed&&stateChange&&<StateForm member={stateChange} busy={busy} error={error} close={()=>setStateChange(null)} save={save}/>}
 </section>;
}
