import {test,expect,type Locator,type Page} from '@playwright/test';
import {sprintReviewUIFixture,uiActor,uiId,uiReview} from './fixtures/sprint-review-ui';
import {blankDecisionWorkflow} from '../src/planning/reviews/decision-model';
import {validateReviewPayload} from '../src/planning/reviews/model';
import type {DecisionWorkflow} from '../src/planning/reviews/decision-types';
import type {ReviewMutation,ReviewMutationReceipt,SprintReviewContext,UpdateSave} from '../src/planning/reviews/types';

test.use({screenshot:'only-on-failure'});

function comparisonFixture():DecisionWorkflow{
 const workflow=blankDecisionWorkflow();
 return {...workflow,status:'recorded',owner_id:uiActor,target_date:'2026-10-08',decided_on:'2026-10-06',chosen_option_id:workflow.options[1].id,reopen_criteria:'Reopen if retries exceed 2 in 20 loaded cycles.',requirements:[{label:'Cable clearance requirement',url:'https://example.com/requirements/7',reference_id:'REQ-7'}],options:workflow.options.map((option,index)=>({...option,label:index?'Accessible route':'Short route',weight:index?'0.8 kg':'0.6 kg',reliability:index?'20 / 20 loaded cycles':'17 / 20 loaded cycles',evidence:[{label:index?'Accessible route bench log':'Short route bench log',url:`https://example.com/bench/${index}`,reference_id:`TEST-${index+20}`}]}))};
}

/** Entirely synthetic service boundaries; the browser never contacts production. */
async function setup(page:Page,adjust?:(context:SprintReviewContext)=>void){
 const context=sprintReviewUIFixture(),mutations:ReviewMutation[]=[],external:string[]=[],receipts=new Map<string,ReviewMutationReceipt>();adjust?.(context);
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(['127.0.0.1','localhost'].includes(url.hostname))return route.continue();external.push(url.origin+url.pathname);return route.abort('blockedbyclient');});
 await page.addInitScript(actor=>localStorage.setItem('4418-team-hub-auth',JSON.stringify({access_token:'synthetic-decision-token',refresh_token:'synthetic-refresh',expires_at:4000000000,token_type:'bearer',user:{id:actor,aud:'authenticated',app_metadata:{},user_metadata:{}}})),context.user_id);
 await page.route('**/rest/v1/**',route=>route.fulfill({json:new URL(route.request().url()).pathname.endsWith('/profiles')?{display_name:'Synthetic team member',role:'student',active:true}:[]}));
 await page.route('**/rpc/planning_context',route=>route.fulfill({json:{user_id:context.user_id,can_manage:context.can_manage,season_id:context.season_id,seasons:context.seasons.map(season=>({...season,start_date:null,end_date:null,version:1})),members:context.members,areas:[],groups:[],boards:context.boards.map(board=>({...board,kind:'project',description:'',area_id:null,display_order:0,version:1})),items:[],tasks:context.tasks.filter(task=>task.available).map(task=>({...task,description:'Existing Planning task',priority:'normal',area_id:null,start_date:null,blocked_reason:'',version:1}))}}));
 await page.route('**/rpc/sprint_review_context',route=>route.fulfill({json:context}));
 await page.route('**/rpc/sprint_review_save',route=>{
  const body=route.request().postDataJSON() as ReviewMutation;expect(body.expected_actor).toBe(context.user_id);expect(body.action).toBe('update');
  const p=body.p as UpdateSave;expect(context.boards.find(board=>board.id===p.board_id)?.can_edit_update).toBe(true);expect(validateReviewPayload('update',p)).toBe(null);mutations.push(body);
  const update={...p,version:(p.version||0)+1,decision_owner:context.members.find(person=>person.id===p.decision_workflow?.owner_id)||null,reported_students:context.members.filter(person=>p.reported_by_student_ids.includes(person.id)),linked_task:context.tasks.find(task=>task.id===p.linked_task_id)||null,carried_from:null,recorded_by:context.user_id,recorded_at:'2026-10-06T15:00:00Z'};
  const existing=context.updates.find(item=>item.id===p.id);if(existing)Object.assign(existing,update);else context.updates.push(update);
  const receipt:ReviewMutationReceipt={request_id:body.request_id,status:'applied',action:'update',entity_id:p.id,version:update.version};receipts.set(body.request_id,receipt);return route.fulfill({json:receipt});
 });
 await page.route('**/rpc/sprint_review_mutation_status',route=>{const body=route.request().postDataJSON();return route.fulfill({json:receipts.get(body.request_id)||{request_id:body.request_id,status:'unknown',action:null,entity_id:null,version:null}});});
 return {context,mutations,external};
}
const project=(page:Page,n=201)=>page.locator(`#review-project-${uiId(n)}`);
async function startComparison(page:Page){await project(page).getByRole('button',{name:'Weekly update',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Compare design options',exact:true}).click();return dialog;}
async function footerVisible(page:Page,dialog:Locator){
 const footer=await dialog.locator('.sr-dialog-footer').boundingBox(),save=await dialog.getByRole('button',{name:'Save weekly update'}).boundingBox();expect(footer).not.toBeNull();expect(save).not.toBeNull();expect(save!.y).toBeGreaterThanOrEqual(footer!.y);expect(save!.y+save!.height).toBeLessThanOrEqual(page.viewportSize()!.height);
 const scroll=await dialog.locator('.sr-update-scroll').boundingBox();expect(scroll).not.toBeNull();expect(scroll!.height).toBeGreaterThan(0);expect(scroll!.y+scroll!.height).toBeLessThanOrEqual(footer!.y+1);
 await expect(dialog.getByRole('button',{name:'Save weekly update'})).toBeInViewport();expect(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth)).toBe(true);
}

for(const width of [390,1440])test(`student compares, explicitly chooses and saves a decision at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:800});const state=await setup(page),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('/#planning/reviews');const dialog=await startComparison(page);
 await expect(dialog.getByRole('tab',{name:'2 · Compare options'})).toHaveAttribute('aria-selected','true');await dialog.getByLabel('Decision needed',{exact:true}).fill('Which control layout should we test next?');await dialog.getByLabel('Decision owner',{exact:true}).selectOption(uiActor);await expect(dialog.getByLabel('Decision owner').locator('option')).not.toContainText(['Morgan Facilitator','Jamie Observer']);await dialog.getByLabel('Target decision date').fill('2026-10-08');
 await dialog.getByRole('button',{name:'Add requirement link'}).click();await dialog.getByLabel('Requirement 1 label').fill('Driver input requirement');await dialog.getByLabel('Requirement 1 link').fill('https://example.com/requirements/8');await dialog.getByLabel('Requirement 1 source ID').fill('REQ-8');
 await dialog.getByLabel('Option 1 name',{exact:true}).fill('Layout A');await dialog.getByLabel('Option 2 name',{exact:true}).fill('Layout B');await dialog.locator('.sr-decision-option').nth(0).getByText('Qualitative observations and evidence',{exact:true}).click();await dialog.locator('.sr-decision-option').nth(1).getByText('Qualitative observations and evidence',{exact:true}).click();await dialog.getByLabel('Option 1 weight',{exact:true}).fill('0.4 kg; estimate');await dialog.getByLabel('Option 2 reliability',{exact:true}).fill('12 / 12 correct inputs');await dialog.getByRole('button',{name:'Add option 2 evidence link'}).click();await dialog.getByLabel('Option 2 evidence 1 label').fill('Synthetic driver test');await dialog.getByLabel('Option 2 evidence 1 link').fill('https://example.com/driver-test');await dialog.getByLabel('Option 2 evidence 1 source ID').fill('TEST-22');await dialog.locator('.sr-decision-option').nth(1).getByText('SWOT (optional)',{exact:true}).click();await dialog.getByLabel('Option 2 strengths',{exact:true}).fill('Fewer missed inputs in the trial.');await dialog.getByLabel('Option 2 threats',{exact:true}).fill('A new driver may prefer a different layout.');
 await dialog.getByRole('button',{name:'Add engineering trade study',exact:true}).click();await dialog.getByRole('button',{name:'Add criterion',exact:true}).click();await dialog.getByLabel('Criterion 1 name',{exact:true}).fill('Mass');await dialog.getByLabel('Criterion 1 unit',{exact:true}).fill('kg');await dialog.getByLabel('Criterion 1 direction',{exact:true}).selectOption('lower');await dialog.getByLabel('Criterion 1 comparison range low',{exact:true}).fill('0');await dialog.getByLabel('Criterion 1 comparison range high',{exact:true}).fill('2');await dialog.getByRole('checkbox',{name:'Criterion 1 is a must-have',exact:true}).check();await dialog.getByLabel('Criterion 1 must-have maximum',{exact:true}).fill('0.7');await dialog.getByLabel('Layout A Mass raw value',{exact:true}).fill('0.4');const study=dialog.getByRole('region',{name:'Engineering trade study editor',exact:true});await expect(study).toContainText('Weighted total unavailable');await expect(study).toContainText('Must-have not verified');await dialog.getByLabel('Layout B Mass raw value',{exact:true}).fill('0.8');await expect(study).toContainText('Does not meet must-have');await dialog.getByText('Layout B Mass notes and evidence',{exact:true}).click();await dialog.getByLabel('Layout B Mass measurement notes',{exact:true}).fill('Measured on a bench scale; ±0.01 kg.');

 await footerVisible(page,dialog);await dialog.locator('.sr-update-scroll').evaluate(element=>element.scrollTop=0);await page.screenshot({path:`test-results/design-decisions/comparison-${width}.png`});await footerVisible(page,dialog);
 await dialog.getByRole('tab',{name:'3 · Student decision'}).click();await expect(dialog.getByLabel('Chosen option',{exact:true})).toHaveValue('');await dialog.getByLabel('Decision status').selectOption('recorded');await dialog.getByLabel('Chosen option',{exact:true}).selectOption({label:'Layout B'});await expect(dialog.getByRole('region',{name:'Engineering trade study results',exact:true})).toContainText('Does not meet must-have');await dialog.getByLabel('Actual decision date').fill('2026-10-06');await dialog.getByLabel('Reopen criteria').fill('Reopen if a new driver misses more than one input.');await dialog.getByLabel('Reported student decision').fill('Students chose Layout B for the next practice.');await dialog.getByLabel('Decision rationale').fill('Every input was correct in the observed trial. Reduce the measured mass before the next test.');await dialog.getByRole('checkbox',{name:'Alex Student',exact:true}).check();await dialog.getByRole('button',{name:'Add decision reference link'}).click();await dialog.getByLabel('Decision reference 1 label').fill('Existing controls architecture decision');await dialog.getByLabel('Decision reference 1 link').fill('https://example.com/architecture/14');await dialog.getByLabel('Decision reference 1 source ID').fill('AD-14');await footerVisible(page,dialog);
 await dialog.getByRole('tab',{name:'4 · Next action'}).click();await dialog.getByLabel('Next test or action').fill('Repeat with another driver.');await dialog.getByLabel('Linked Planning task').selectOption(uiId(301));await dialog.getByRole('button',{name:'Save weekly update'}).click();await expect(dialog).toHaveCount(0);
 expect(state.mutations).toHaveLength(1);const payload=state.mutations[0].p as UpdateSave;expect(payload.decision_workflow).toMatchObject({status:'recorded',owner_id:uiActor,target_date:'2026-10-08',decided_on:'2026-10-06',chosen_option_id:payload.decision_workflow!.options[1].id});expect(payload).toMatchObject({linked_task_id:uiId(301),reported_by_student_ids:[uiActor],decision_references:[{reference_id:'AD-14'}]});expect(payload.decision_workflow!.options[1].swot?.strengths).toBe('Fewer missed inputs in the trial.');expect(payload.decision_workflow!.trade_study?.criteria[0]).toMatchObject({label:'Mass',unit:'kg',scale_min:0,scale_max:2,direction:'lower',must_have:true,maximum:0.7});expect(payload.decision_workflow!.trade_study?.assessments.map(row=>row.value)).toEqual([0.4,0.8]);expect(payload).not.toHaveProperty('owner_ids');expect(payload).not.toHaveProperty('due_date');
 await project(page).getByText('Trade-offs & student decision',{exact:true}).click();const summary=project(page).getByRole('region',{name:'Design decision comparison'});await expect(summary).toContainText('Decision recorded');await expect(summary).toContainText('Alex Student');await expect(summary).toContainText('Layout B');await expect(summary).toContainText('Reopen if a new driver');await expect(summary).toContainText('Does not meet must-have');await expect(summary).toContainText('Measured on a bench scale');await expect(summary.getByRole('link',{name:'Driver input requirement'})).toHaveAttribute('href','https://example.com/requirements/8');await expect(project(page).getByRole('link',{name:'Existing controls architecture decision'})).toHaveAttribute('href','https://example.com/architecture/14');await page.evaluate(()=>{(document.activeElement as HTMLElement|null)?.blur();window.scrollTo({top:0,left:0,behavior:'instant'});});await page.waitForFunction(()=>window.scrollY===0);await page.screenshot({path:`test-results/design-decisions/recorded-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(state.external.every(url=>url.includes('fonts.googleapis.com')||url.includes('fonts.gstatic.com'))).toBe(true);
});

test('closing a comparison discards all local choices without a write',async({page})=>{
 const state=await setup(page);await page.goto('/#planning/reviews');const dialog=await startComparison(page);await dialog.getByLabel('Option 1 name').fill('Unsaved option');await dialog.getByRole('button',{name:'Add option',exact:true}).click();await dialog.getByLabel('Option 3 name').fill('Unsaved third option');await dialog.getByRole('tab',{name:'3 · Student decision'}).click();await dialog.getByLabel('Chosen option',{exact:true}).selectOption({label:'Unsaved third option'});await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(dialog).toHaveCount(0);expect(state.mutations).toHaveLength(0);await project(page).getByRole('button',{name:'Weekly update',exact:true}).click();await expect(dialog.getByRole('tab',{name:'2 · Compare options'})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Compare design options',exact:true})).toBeVisible();await dialog.press('Escape');expect(state.mutations).toHaveLength(0);
});

test('incomplete recorded decisions stay editable while comparing drafts can be saved',async({page})=>{
 const state=await setup(page);await page.goto('/#planning/reviews');const dialog=await startComparison(page);await dialog.getByLabel('Option 1 name').fill('First option');await dialog.getByLabel('Option 2 name').fill('Second option');await dialog.getByLabel('Decision owner',{exact:true}).selectOption(uiActor);await dialog.getByRole('tab',{name:'3 · Student decision'}).click();await dialog.getByLabel('Decision status').selectOption('recorded');await dialog.getByRole('button',{name:'Save weekly update'}).click();await expect(dialog.getByRole('alert')).toContainText('To record the decision');expect(state.mutations).toHaveLength(0);await expect(dialog.getByLabel('Decision status')).toHaveValue('recorded');await dialog.getByLabel('Decision status').selectOption('comparing');await dialog.getByRole('button',{name:'Save weekly update'}).click();await expect(dialog).toHaveCount(0);expect(state.mutations).toHaveLength(1);expect((state.mutations[0].p as UpdateSave).decision_workflow?.chosen_option_id).toBe(null);
});

test('removing a chosen option clears its selection without choosing another',async({page})=>{
 const state=await setup(page);await page.goto('/#planning/reviews');const dialog=await startComparison(page);await dialog.getByLabel('Option 1 name').fill('First option');await dialog.getByLabel('Option 2 name').fill('Second option');await dialog.getByRole('tab',{name:'3 · Student decision'}).click();await dialog.getByLabel('Chosen option',{exact:true}).selectOption({label:'Second option'});await dialog.getByRole('tab',{name:'2 · Compare options'}).click();await dialog.getByRole('button',{name:'Remove option 2',exact:true}).click();await expect(dialog.getByRole('button',{name:'Remove option 1',exact:true})).toBeDisabled();await dialog.getByRole('tab',{name:'3 · Student decision'}).click();await expect(dialog.getByLabel('Chosen option',{exact:true})).toHaveValue('');await dialog.getByRole('button',{name:'Close',exact:true}).click();expect(state.mutations).toHaveLength(0);
});

test('read-only comparison preserves source IDs and makes unsafe links inert',async({page})=>{
 const state=await setup(page,context=>{context.boards.forEach(board=>board.can_edit_update=false);context.members.find(person=>person.id===uiActor)!.can_write=false;const workflow=comparisonFixture();workflow.status='reopened';workflow.options[0].evidence[0].url='javascript:alert(1)';context.updates[0].decision_workflow=workflow;context.updates[0].decision_owner={...context.members.find(person=>person.id===uiActor)!,name:'Former Student',active:false,can_write:false};});await page.goto('/#planning/reviews');await project(page,200).getByText('Trade-offs & student decision',{exact:true}).click();const summary=project(page,200).getByRole('region',{name:'Design decision comparison'});await expect(summary).toContainText('Reopened for comparison');await expect(summary).toContainText('Previous chosen option');await expect(summary).toContainText('Former Student · inactive');await expect(summary).toContainText('Accessible route');await expect(summary).toContainText('REQ-7');await expect(summary).toContainText('Short route bench log · link unavailable');await expect(summary.locator('a[href^="javascript:"]')).toHaveCount(0);for(const name of ['Weekly update','Edit update','Compare design options'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);expect(state.mutations).toHaveLength(0);
});

test('editing a saved comparison and closing leaves nested evidence and SWOT unchanged',async({page})=>{
 const state=await setup(page,context=>{const workflow=comparisonFixture();workflow.options[0].swot={strengths:'Simple assembly',weaknesses:'Tight service access',opportunities:'Use existing stock',threats:'Supplier lead time'};context.updates[0].decision_workflow=workflow;});const original=structuredClone(state.context.updates[0]);await page.goto('/#planning/reviews');await project(page,200).getByRole('button',{name:'Edit update',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('tab',{name:'2 · Compare options'}).click();await dialog.getByLabel('Option 1 name',{exact:true}).fill('Unsaved replacement');await dialog.locator('.sr-decision-option').nth(0).getByText('SWOT (optional)',{exact:true}).click();await dialog.getByLabel('Option 1 strengths',{exact:true}).fill('Unsaved strength');await dialog.locator('.sr-decision-option').nth(0).getByText('Qualitative observations and evidence',{exact:true}).click();await dialog.getByLabel('Option 1 evidence 1 label',{exact:true}).fill('Unsaved source title');await dialog.getByRole('button',{name:'Close editor',exact:true}).click();await expect(dialog).toHaveCount(0);expect(state.mutations).toHaveLength(0);expect(state.context.updates[0]).toEqual(original);await project(page,200).getByRole('button',{name:'Edit update',exact:true}).click();await dialog.getByRole('tab',{name:'2 · Compare options'}).click();await expect(dialog.getByLabel('Option 1 name',{exact:true})).toHaveValue('Short route');await dialog.locator('.sr-decision-option').nth(0).getByText('SWOT (optional)',{exact:true}).click();await expect(dialog.getByLabel('Option 1 strengths',{exact:true})).toHaveValue('Simple assembly');await dialog.press('Escape');
});

test('focused review queue moves to another project and Show all clears the focus',async({page})=>{
 const state=await setup(page);await page.goto(`/#planning/reviews/${uiReview}/project/${uiId(200)}`);await expect(project(page,200)).toBeVisible();await expect(project(page,201)).toHaveCount(0);await page.getByRole('complementary',{name:'Review discussion queue'}).getByRole('button',{name:'Driver practice & controls',exact:true}).click();await expect(page).toHaveURL(new RegExp(`#planning/reviews/${uiReview}/project/${uiId(201)}$`));await expect(project(page,201)).toBeVisible();await expect(project(page,200)).toHaveCount(0);await page.getByRole('link',{name:'Show all review projects',exact:true}).click();await expect(page).toHaveURL(new RegExp(`#planning/reviews/${uiReview}$`));await expect(project(page,200)).toBeVisible();await expect(project(page,201)).toBeVisible();await page.goto(`/#planning/reviews/${uiReview}/project/${uiId(999)}`);await page.getByRole('button',{name:'Show all projects',exact:true}).click();await expect(page).toHaveURL(new RegExp(`#planning/reviews/${uiReview}$`));await expect(project(page,200)).toBeVisible();expect(state.mutations).toHaveLength(0);
});

test('Planning Design decisions opens the same focused weekly review record',async({page})=>{
 const state=await setup(page,context=>context.updates[0].decision_workflow=comparisonFixture());await page.goto(`/#planning/boards/${uiId(200)}`);await page.getByRole('group',{name:'Board view',exact:true}).getByRole('button',{name:'Design decisions',exact:true}).click();await expect(page).toHaveURL(new RegExp(`#planning/boards/${uiId(200)}/decisions$`));const entry=page.getByRole('region',{name:'Project design decisions',exact:true});await expect(entry).toContainText('Decision recorded');await expect(entry).toContainText('Accessible route');await expect(entry.getByRole('link',{name:'Open decision workflow',exact:true})).toHaveAttribute('href',`#planning/reviews/${uiReview}/project/${uiId(200)}`);await entry.getByRole('link',{name:'Open decision workflow',exact:true}).click();await expect(project(page,200)).toBeVisible();await expect(project(page,201)).toHaveCount(0);expect(state.mutations).toHaveLength(0);
});


test('decision selects keep exact accessible names as selected values and status change',async({page})=>{
 const state=await setup(page);await page.goto('/#planning/reviews');const dialog=await startComparison(page);
 const owner=dialog.getByRole('combobox',{name:'Decision owner',exact:true});await expect(owner).toHaveAccessibleName('Decision owner');await owner.selectOption(uiActor);await expect(dialog.getByLabel('Decision owner',{exact:true})).toHaveValue(uiActor);
 await dialog.getByLabel('Option 1 name',{exact:true}).fill('Compact layout');await dialog.getByLabel('Option 2 name',{exact:true}).fill('Accessible layout');await dialog.getByRole('tab',{name:'3 · Student decision'}).click();
 const status=dialog.getByRole('combobox',{name:'Decision status',exact:true});await expect(status).toHaveAccessibleName('Decision status');const chosen=dialog.getByRole('combobox',{name:'Chosen option',exact:true});await chosen.selectOption({label:'Accessible layout'});await expect(chosen).toHaveAccessibleName('Chosen option');const selected=await chosen.inputValue();
 await status.selectOption('reopened');await expect(status).toHaveAccessibleName('Decision status');await expect(dialog.getByRole('combobox',{name:'Previous chosen option',exact:true})).toHaveValue(selected);await expect(dialog.getByLabel('Previous decision date',{exact:true})).toBeVisible();
 await status.selectOption('comparing');await expect(dialog.getByRole('combobox',{name:'Chosen option',exact:true})).toHaveValue(selected);await dialog.getByRole('button',{name:'Close',exact:true}).click();expect(state.mutations).toHaveLength(0);
});

for(const width of [390,1440])test(`short-screen evidence controls remain clickable above the save footer at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:520});const state=await setup(page);await page.goto('/#planning/reviews');await project(page).getByRole('button',{name:'Weekly update',exact:true}).click();const dialog=page.getByRole('dialog'),scroll=dialog.locator('.sr-update-scroll');
 await dialog.getByRole('button',{name:'Carry forward open items',exact:true}).click();await dialog.getByLabel('Progress this week',{exact:true}).fill('Compared layouts using repeatable synthetic trials.');
 for(let index=1;index<=3;index++){
  const add=dialog.getByRole('button',{name:'Add evidence link',exact:true});await add.click();await dialog.getByLabel(`Evidence ${index} label`,{exact:true}).fill(`Trial ${index}`);await dialog.getByLabel(`Evidence ${index} link`,{exact:true}).fill(`https://example.com/trials/${index}`);await footerVisible(page,dialog);
 }
 await expect.poll(()=>scroll.evaluate(element=>element.scrollHeight>element.clientHeight)).toBe(true);await expect.poll(()=>scroll.evaluate(element=>element.scrollTop)).toBeGreaterThan(0);
 const add=dialog.getByRole('button',{name:'Add evidence link',exact:true});await add.scrollIntoViewIfNeeded();const addBox=await add.boundingBox(),footer=await dialog.locator('.sr-dialog-footer').boundingBox();expect(addBox).not.toBeNull();expect(addBox!.y+addBox!.height).toBeLessThanOrEqual(footer!.y);
 expect(await add.evaluate(element=>{const bounds=element.getBoundingClientRect();return element.contains(document.elementFromPoint(bounds.x+bounds.width/2,bounds.y+bounds.height/2));})).toBe(true);
 await dialog.getByRole('tab',{name:'2 · Student decision',exact:true}).click();await expect.poll(()=>scroll.evaluate(element=>element.scrollTop)).toBe(0);await footerVisible(page,dialog);
 await dialog.getByRole('tab',{name:'1 · Progress',exact:true}).click();await expect(dialog.getByLabel('Progress this week',{exact:true})).toHaveValue('Compared layouts using repeatable synthetic trials.');await dialog.getByRole('button',{name:'Save weekly update',exact:true}).click();await expect(dialog).toHaveCount(0);
 expect(state.mutations).toHaveLength(1);expect((state.mutations[0].p as UpdateSave).evidence).toHaveLength(3);expect((state.mutations[0].p as UpdateSave).carry_from_update_id).toBe(uiId(501));
});
