import {test,expect} from '@playwright/test';
import {buildSync} from 'esbuild';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createRequire} from 'node:module';
import {sprintReviewUIFixture,uiActor,uiId} from './fixtures/sprint-review-ui';
let dir='',api:any;
test.beforeAll(()=>{dir=mkdtempSync(join(tmpdir(),'design-decision-model-'));const file=join(dir,'model.cjs');buildSync({stdin:{contents:`export * from './src/planning/reviews/model';export * from './src/planning/reviews/decision-model';export * from './src/planning/reviews/export/snapshot';export * from './src/planning/reviews/export/plan';export * from './src/planning/reviews/DecisionSummary';export * from './src/planning/reviews/DecisionEditor';export {createElement} from 'react';export {renderToStaticMarkup} from 'react-dom/server';`,resolveDir:resolve('.')},bundle:true,platform:'node',format:'cjs',jsx:'automatic',loader:{'.css':'empty'},define:{'import.meta.env':'{}'},outfile:file,logLevel:'silent'});api=createRequire(import.meta.url)(file);});
test.afterAll(()=>rmSync(dir,{recursive:true,force:true}));
function workflow(){const w=api.blankDecisionWorkflow();w.options[0].label='Prototype A';w.options[1].label='Prototype B';w.requirements=[{label:'Robot envelope',reference_id:'REQ-021',url:'https://example.com/requirements#REQ-021'}];w.options[0].evidence=[{label:'Bench trials',reference_id:'TEST-7',url:'https://example.com/bench'}];return w;}
function recorded(){const w=workflow();return {...w,status:'recorded',owner_id:uiActor,decided_on:'2026-10-06',chosen_option_id:w.options[0].id,reopen_criteria:'Loaded cycles exceed 4 seconds.'};}
function study(w:any){return {criteria:[{id:uiId(881),label:'Mass',unit:'kg',weight:3,scale_min:2,scale_max:8,direction:'lower',must_have:true,minimum:null,maximum:6}],assessments:[{option_id:w.options[0].id,criterion_id:uiId(881),value:4,reason:'Weighed prototype',evidence:[{label:'Scale photograph',reference_id:'TEST-M1',url:'https://example.com/mass'}]}]};}
test('comparison is opt-in and old review payloads preserve absence',()=>{const c=sprintReviewUIFixture();expect(api.updatePayload(c.updates[0]).decision_workflow).toBeUndefined();expect(api.assertReviewContext(c,uiActor).updates[0].decision_workflow).toBeUndefined();const p=api.updatePayload(c.updates[0]);p.decision_workflow=workflow();expect(api.validateReviewPayload('update',p)).toBeNull();expect(api.blankUpdate(c.selected_review_id,c.boards[0].id).decision_workflow).toBeUndefined();});
test('strict option identity, size, reference, date and chosen membership bounds',()=>{const w=workflow();expect(api.decisionWorkflowIssue(w)).toBeNull();for(const bad of [{...w,owner_id:'bad'},{...w,target_date:'2026-02-30'},{...w,decided_on:'0000-01-01'},{...w,options:[]},{...w,options:[...w.options,...Array(5).fill(w.options[0])]},{...w,chosen_option_id:uiId(991)},{...w,reopen_criteria:'x'.repeat(2001)},{...w,unknown_field:'ignored?'},{...w,options:[{...w.options[0],description:'x'.repeat(2001)}]},{...w,options:[{...w.options[0],weight:'x'.repeat(1001)}]},{...w,requirements:[{label:'Unsafe',reference_id:'REQ-1',url:'javascript:alert(1)'}]}])expect(api.decisionWorkflowIssue(bad)).not.toBeNull();});
test('recording requires accountable student outcome without mentor approval',()=>{const c=sprintReviewUIFixture(),p=api.updatePayload(c.updates[0]);p.decision_workflow=recorded();expect(api.validateReviewPayload('update',p)).toBeNull();for(const patch of [{owner_id:null},{decided_on:null},{chosen_option_id:null},{reopen_criteria:''}])expect(api.validateReviewPayload('update',{...p,decision_workflow:{...p.decision_workflow,...patch}})).toContain('record');for(const patch of [{reported_decision:''},{decision_rationale:''},{reported_by_student_ids:[]}])expect(api.validateReviewPayload('update',{...p,...patch})).toContain('record');expect(api.validateReviewPayload('update',{...p,decision_workflow:{...p.decision_workflow,status:'reopened'},reported_decision:'',decision_rationale:''})).toBeNull();expect(Object.keys(p.decision_workflow)).not.toContain('mentor_approval');});
test('optional SWOT and engineering trade study have bounded structured fields',()=>{const w=workflow();w.options[0].swot={strengths:'Compact',weaknesses:'Service access',opportunities:'Test another linkage',threats:'Manufacturing lead time'};w.trade_study=study(w);expect(api.decisionWorkflowIssue(w)).toBeNull();expect(api.decisionWorkflowIssue({...w,trade_study:{...w.trade_study,assessments:[{...w.trade_study.assessments[0],option_id:uiId(990)}]}})).not.toBeNull();w.options[0].swot.threats='x'.repeat(2001);expect(api.decisionWorkflowIssue(w)).toContain('SWOT');});
test('read normalization disables unsafe nested links and retains existing source IDs',()=>{const c=sprintReviewUIFixture(),w=workflow();w.trade_study=study(w);w.requirements[0].url='javascript:unsafe';w.options[0].evidence[0].url='https://name:secret@example.com';w.trade_study.assessments[0].evidence[0].url='data:text/html,bad';(c.updates[0] as any).decision_workflow=w;const safe=api.assertReviewContext(c,uiActor).updates[0].decision_workflow;expect(safe.requirements[0].url).toBe('');expect(safe.requirements[0].reference_id).toBe('REQ-021');expect(safe.options[0].evidence[0].url).toBe('');expect(safe.trade_study.assessments[0].evidence[0].url).toBe('');expect(api.decisionWorkflowIssue(safe)).not.toBeNull();});
test('edit copies are detached; prior evidence and choices are not silently carried forward',()=>{const c=sprintReviewUIFixture();(c.updates[0] as any).decision_workflow=workflow();const p=api.updatePayload(c.updates[0]);p.decision_workflow.options[0].label='Edited';expect((c.updates[0] as any).decision_workflow.options[0].label).toBe('Prototype A');const next=api.blankUpdate(uiId(993),c.updates[0].board_id),carried=api.carryOpenItems(next,{...c.updates[0],unresolved:true});expect(carried.decision_workflow).toBeUndefined();expect(carried.carry_from_update_id).toBe(c.updates[0].id);});
test('open and reopened comparisons appear in discussion queue even with empty free-text question',()=>{const c=sprintReviewUIFixture(),u=c.updates[0];(u as any).decision_workflow=workflow();u.unresolved=false;u.decisions_needed='';expect(api.reviewQueueReasons(c.boards[0],u)).toContain('decision');(u as any).decision_workflow.status='reopened';expect(api.reviewQueueReasons(c.boards[0],u)).toContain('decision');(u as any).decision_workflow=recorded();expect(api.reviewQueueReasons(c.boards[0],u)).not.toContain('decision');});
test('Planning focus links retain exact review and board identity and reject malformed routes',()=>{const review=uiId(401),board=uiId(201),route=`#planning/reviews/${review}/project/${board}`;expect(api.reviewRoute(route)).toEqual({valid:true,id:review});expect(api.reviewProjectFocus(route)).toBe(board);for(const r of [route+'/extra',`#planning/reviews/project/${board}`,route.replace(board,'-'.repeat(36)),route+'?edit=1'])expect(api.reviewRoute(r).valid).toBe(false);expect(api.reviewProjectFocus('#planning/reviews')).toBeNull();});
test('detached deck snapshot includes source IDs, measurements, SWOT and student reason without fetching',()=>{const c=sprintReviewUIFixture(),w=recorded();w.trade_study=study(w);w.options[0].swot={strengths:'Low mass',weaknesses:'Tight clearance',opportunities:'Fixture improvement',threats:'Tolerance stack'};(c.updates[0] as any).decision_workflow=w;const snapshot=api.createReviewExportSnapshot(c),d=snapshot.projects.find((p:any)=>p.update?.decisionStudy)?.update.decisionStudy;expect(d.requirements[0].referenceId).toBe('REQ-021');expect(d.tradeStudy.assessments[0].value).toBe(4);const plan=api.buildReviewDeckPlan(snapshot),content=JSON.stringify(plan);for(const token of ['Engineering trade study','Trade criterion 1','REQ-021','TEST-M1','kg','Tolerance stack','Reopen criteria'])expect(content).toContain(token);w.options[0].swot.strengths='Later edit';w.trade_study.assessments[0].value=999;expect(d.options[0].swot.strengths).toBe('Low mass');expect(d.tradeStudy.assessments[0].value).toBe(4);});
test('read-only comparison escapes notes and never grants write authority',()=>{const w=workflow();w.options[0].description='<script>example</script>';const html=api.renderToStaticMarkup(api.createElement(api.DecisionSummary,{workflow:w}));expect(html).toContain('&lt;script&gt;example&lt;/script&gt;');expect(html).not.toContain('<script>');expect(html).not.toContain('<button');expect(html).toContain('REQ-021');expect(html).not.toContain('approval');});
test('inactive owner identity comes from the authorized update projection and cannot be forged',()=>{const c=sprintReviewUIFixture(),w=recorded();w.owner_id=uiId(889);(c.updates[0] as any).decision_workflow=w;(c.updates[0] as any).decision_owner={id:w.owner_id,name:'Former student lead',active:false,is_student:true,can_write:false};expect(api.assertReviewContext(c,uiActor).updates[0].decision_owner.name).toBe('Former student lead');const snap=api.createReviewExportSnapshot(c);expect(snap.projects[0].update.decisionStudy.owner).toBe('Former student lead');const saved=api.updatePayload(c.updates[0]);expect(saved.decision_owner).toBeUndefined();(c.updates[0] as any).decision_owner.id=uiId(888);expect(()=>api.assertReviewContext(c,uiActor)).toThrow();});
test('deck preserves each criterion outcome and both failed and unverified constraints',()=>{const c=sprintReviewUIFixture(),w=recorded(),t=study(w);t.assessments[0].value=7;t.criteria.push({...t.criteria[0],id:uiId(882),label:'Reliability',unit:'%',weight:0,scale_min:0,scale_max:100,direction:'higher',minimum:90,maximum:null});w.trade_study=t;(c.updates[0] as any).decision_workflow=w;const plan=api.buildReviewDeckPlan(api.createReviewExportSnapshot(c));const content=JSON.stringify(plan);for(const value of ['Criterion desirability','16.7 / 100','Criterion must-have result','Does not meet must-have','Must-have not verified','1 failed, 1 unverified'])expect(content).toContain(value);});

test('trade measurement continuation slides retain stable criterion and option identity',()=>{const c=sprintReviewUIFixture(),w=recorded(),t=study(w);t.criteria[0].label='Mechanism mass';t.assessments[0].reason='Long calculation explanation '.repeat(120);w.options[0].label='Option Alpha';w.trade_study=t;(c.updates[0] as any).decision_workflow=w;const plan=api.buildReviewDeckPlan(api.createReviewExportSnapshot(c)),pages=plan.slides.filter((s:any)=>s.title==='Criterion 1 / Option 1');expect(pages.length).toBeGreaterThan(2);for(const page of pages){expect(page.slots.TITLE).toBe('Criterion 1 / Option 1');expect(JSON.stringify(page.slots)).toContain(c.boards[0].name);}expect(plan.slides.some((s:any)=>s.title==='Criterion 1 / Option 2')).toBe(true);});

test('read canonicalizes a case-insensitive owner UUID to its projected person identity',()=>{const c=sprintReviewUIFixture(),w=recorded(),id='abcdef01-abcd-abcd-abcd-abcdef123456';w.owner_id=id.toUpperCase();(c.updates[0] as any).decision_workflow=w;(c.updates[0] as any).decision_owner={id,name:'Named historical owner',active:false,is_student:true,can_write:false};const result=api.assertReviewContext(c,uiActor).updates[0];expect(result.decision_workflow.owner_id).toBe(id);expect(result.decision_owner.id).toBe(id);});

test('an inactive historical owner remains identifiable in the editor without becoming eligible',()=>{const w=recorded(),person={id:w.owner_id,name:'Retired project lead',active:false,is_student:true,can_write:false};const html=api.renderToStaticMarkup(api.createElement(api.DecisionEditor,{workflow:w,people:[],decisionOwner:person,onChange:()=>{}}));expect(html).toContain('Retired project lead');expect(html).toContain('no longer active');});
