import {test,expect,type Download,type Page} from '@playwright/test';
import {createHash} from 'node:crypto';
import {revisionIssue} from '../src/fabrication/Editor';
import {fabricationUIFixture,fabActor,fabId,fabPart,fabProject,fabSeason,fixtureActions,syntheticDxf} from './fixtures/fabrication-ui';
import type {FabricationContext,FabricationMutation,FabricationPart,FabricationReceipt,FabricationSubmission,FabricationUpload} from '../src/fabrication/types';

async function setup(page:Page,adjust?:(context:FabricationContext)=>void){
 const context=fabricationUIFixture();adjust?.(context);const external:string[]=[],mutations:FabricationMutation[]=[],uploads:FabricationUpload[]=[],downloads:{revision_id:string;file_kind:string}[]=[],versionReads:{part_id:string;expected_actor:string}[]=[],receipts=new Map<string,FabricationReceipt>();
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(['127.0.0.1','localhost'].includes(url.hostname))return route.continue();external.push(url.origin+url.pathname);return route.abort('blockedbyclient');});
 await page.addInitScript(actor=>localStorage.setItem('4418-team-hub-auth',JSON.stringify({access_token:'synthetic-fabrication-token',refresh_token:'synthetic-refresh',expires_at:4000000000,token_type:'bearer',user:{id:actor,aud:'authenticated',app_metadata:{},user_metadata:{}}})),context.user_id);
 await page.route('**/rest/v1/**',r=>r.fulfill({json:new URL(r.request().url()).pathname.endsWith('/profiles')?{display_name:'Synthetic team member',role:'student',active:true}:[]}));
 await page.route('**/rpc/fabrication_context',r=>{const {selected_season,selected_project}=r.request().postDataJSON();if(selected_season&&selected_season!==context.season_id||selected_project&&!context.projects.some(p=>p.id===selected_project))return r.fulfill({status:403,json:{code:'FB403',message:'Unavailable'}});const parts=context.parts.filter(p=>!selected_project||p.board_id===selected_project);return r.fulfill({json:{...context,selected_project_id:selected_project,parts,revisions:context.revisions.filter(rev=>parts.some(p=>p.id===rev.part_id))}});});
 await page.route('**/rpc/fabrication_part_version',r=>{const p=r.request().postDataJSON();versionReads.push(p);const part=context.parts.find(part=>part.id===p.part_id);return p.expected_actor===context.user_id&&part?r.fulfill({json:part.version}):r.fulfill({status:403,json:{code:'FB403',message:'Unavailable'}});});
 const allowed=(part:FabricationPart)=>{part.allowed_actions=fixtureActions(part,context.user_id,context.is_operator&&context.seasons.find(s=>s.id===context.season_id)?.status!=='archived',context.can_manage);};
 function apply(body:FabricationMutation):FabricationReceipt{
  mutations.push(structuredClone(body));const saved=receipts.get(body.request_id);if(saved)return saved;const part=context.parts.find(p=>p.id===body.p.part_id)!;if(body.expected_actor!==context.user_id||body.p.version!==part.version||body.p.revision_id!==part.current_revision_id||!part.allowed_actions.includes(body.action))throw Error('Invalid synthetic mutation');
  if(body.action==='claim'){part.claimed_by=context.user_id;part.claimant={id:context.user_id,name:'Alex Builder',active:true};part.acknowledged_revision_id=null;}
  if(body.action==='release'){part.claimed_by=null;part.claimant=null;part.acknowledged_revision_id=null;if(part.status==='in_progress'){part.status='needs_review';part.reviewed_revision_id=null;}}
  if(body.action==='acknowledge')part.acknowledged_revision_id=part.current_revision_id;
  if(body.action==='ready'){part.status='ready';part.reviewed_revision_id=part.current_revision_id;}
  if(body.action==='start')part.status='in_progress';
  if(body.action==='done')part.status='done';
  if(body.action==='hold'||body.action==='rework'){part.status=body.action==='hold'?'on_hold':'needs_review';part.acknowledged_revision_id=null;part.reviewed_revision_id=null;}
  part.version++;part.status_note=body.p.note;allowed(part);const receipt:FabricationReceipt={request_id:body.request_id,status:'applied',action:body.action,entity_id:part.id,version:part.version};receipts.set(body.request_id,receipt);return receipt;
 }
 function applyUpload(body:FabricationUpload):FabricationReceipt{
  uploads.push(structuredClone(body));const saved=receipts.get(body.request_id);if(saved)return saved;const p=body.p,existing=context.parts.find(part=>part.id===p.part_id),revision={...p,id:p.revision_id,revision_number:(existing?.current_revision.revision_number||0)+1,dxf:{name:'synthetic-upload.dxf',size:syntheticDxf.length,sha256:'a'.repeat(64)},pdf:null,created_by:context.user_id,created_at:'2026-10-06T15:00:00Z'};
  context.revisions.push(revision);const part:FabricationPart=existing||{id:p.part_id,board_id:p.board_id,status:'needs_review',status_note:'',version:0,current_revision_id:p.revision_id,current_revision:revision,claimed_by:null,claimant:null,acknowledged_revision_id:null,reviewed_revision_id:null,created_by:context.user_id,created_at:revision.created_at,updated_at:revision.created_at,can_revise:true,allowed_actions:[]};Object.assign(part,{status:'needs_review',version:(p.version??0)+1,current_revision_id:revision.id,current_revision:revision,acknowledged_revision_id:null,reviewed_revision_id:null});allowed(part);if(!existing)context.parts.push(part);const receipt:FabricationReceipt={request_id:body.request_id,status:'applied',action:'revision',entity_id:part.id,version:part.version};receipts.set(body.request_id,receipt);return receipt;
 }
 await page.route('**/rpc/fabrication_mutate',r=>r.fulfill({json:apply(r.request().postDataJSON())}));
 await page.route('**/rpc/fabrication_mutation_status',r=>{const p=r.request().postDataJSON();return r.fulfill({json:receipts.get(p.request_id)||{request_id:p.request_id,status:'unknown',action:null,entity_id:null,version:null}});});
 await page.route('**/functions/v1/fabrication-files',r=>{const request=r.request();if(request.headers()['content-type']?.includes('multipart/form-data'))return r.fulfill({json:applyUpload(parseUpload(request.postData()!))});const p=request.postDataJSON();if(p.action==='cancel'){const receipt=receipts.get(p.request_id)||{request_id:p.request_id,status:'cancelled' as const,action:null,entity_id:null,version:null};receipts.set(p.request_id,receipt);return r.fulfill({json:receipt});}if(p.action==='download'){downloads.push(p);const body=p.file_kind==='dxf'?syntheticDxf:'%PDF-1.4\nsynthetic fixture\n%%EOF';
   // Mirror the gateway's CORS contract: fetch otherwise hides the verification headers.
   return r.fulfill({body,headers:{
    'Content-Type':p.file_kind==='dxf'?'application/octet-stream':'application/pdf','Content-Length':String(Buffer.byteLength(body)),
    'Content-Disposition':`attachment; filename="synthetic-${p.revision_id}.${p.file_kind}"`,
    'X-Fabrication-Revision':p.revision_id,'X-Fabrication-Kind':p.file_kind,'X-Fabrication-SHA256':createHash('sha256').update(body).digest('hex'),
    'Access-Control-Allow-Origin':new URL(page.url()).origin,
    'Access-Control-Expose-Headers':'Content-Disposition, X-Fabrication-Revision, X-Fabrication-Kind, X-Fabrication-SHA256, Content-Length',
    'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Vary':'Origin',
   }});}return r.fulfill({status:400,json:{code:'FB422',message:'Unknown synthetic action'}});});
 return {context,mutations,uploads,downloads,versionReads,external,receipts,apply,applyUpload};
}
function parseUpload(body:string):FabricationUpload{const field=(name:string)=>new RegExp(`name="${name}"\\r\\n\\r\\n([\\s\\S]*?)\\r\\n--`).exec(body)?.[1]||'';return {request_id:field('request_id'),expected_actor:field('expected_actor'),p:JSON.parse(field('p')) as FabricationSubmission};}
const project=(page:Page,id=fabProject)=>page.locator(`#fabrication-project-${id}`);
async function openPart(page:Page,name='Intake side plate, left'){await page.getByRole('button',{name,exact:true}).click();return page.getByRole('dialog');}
async function fillNewPart(page:Page,name='Synthetic new mounting plate'){const dialog=page.getByRole('dialog');await dialog.getByLabel('Part name',{exact:true}).fill(name);await dialog.getByLabel('Material',{exact:true}).fill('6061-T6 aluminum');await dialog.getByLabel('Material thickness',{exact:true}).fill('0.125');await dialog.getByLabel('Thickness units').selectOption('in');await dialog.getByLabel('Quantity',{exact:true}).fill('3');await dialog.getByLabel('Needed by',{exact:true}).fill('2026-10-20');await dialog.locator('input[type=file]').first().setInputFiles({name:'synthetic-mount.dxf',mimeType:'application/dxf',buffer:Buffer.from(syntheticDxf)});await dialog.getByLabel('DXF drawing units',{exact:true}).selectOption('mm');return dialog;}
async function changeActor(page:Page,id:string|null){await page.evaluate(actor=>{const channel=new BroadcastChannel('4418-team-hub-auth');if(actor){const session={access_token:'synthetic-other-token',refresh_token:'synthetic-refresh',expires_at:4000000000,token_type:'bearer',user:{id:actor,aud:'authenticated',app_metadata:{},user_metadata:{}}};localStorage.setItem('4418-team-hub-auth',JSON.stringify(session));channel.postMessage({event:'SIGNED_IN',session});}else{localStorage.removeItem('4418-team-hub-auth');channel.postMessage({event:'SIGNED_OUT',session:null});}channel.close();},id);}

for(const width of [390,768,1440])test(`Fabrication screenshots and accessible workspace at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:980});const state=await setup(page),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#fabrication');await expect(page.getByRole('heading',{name:'Fabrication',exact:true})).toBeVisible();await expect(project(page).locator('.fab-part-row')).toHaveCount(3);await expect(project(page).getByRole('progressbar')).toHaveAccessibleName('Intake parts completed');await expect(project(page).getByText('1 of 3 done')).toBeVisible();await expect(page.locator('main')).toHaveCount(1);await page.screenshot({path:`test-results/fabrication/projects-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Ready queue'}).click();await expect(page.getByRole('region',{name:'Ready fabrication queue'})).toBeVisible();await expect(page.locator('.fab-queue .fab-part-row').first()).toContainText('Elevator carriage mount');await page.screenshot({path:`test-results/fabrication/queue-${width}.png`,fullPage:true});await page.getByRole('button',{name:'Projects',exact:true}).click();let dialog=await openPart(page);await expect(dialog.getByRole('region',{name:'Immutable revision history'})).toContainText('Revision 1');await page.screenshot({path:`test-results/fabrication/part-${width}.png`});await dialog.getByRole('button',{name:'New revision',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('This part is claimed',{exact:false})).toBeVisible();await page.screenshot({path:`test-results/fabrication/revision-${width}.png`});expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog).toHaveCount(0);expect(state.mutations).toHaveLength(0);expect(state.uploads).toHaveLength(0);expect(errors).toEqual([]);expect(state.external.every(u=>u.includes('fonts.googleapis.com')||u.includes('fonts.gstatic.com'))).toBe(true);
});
test('Fabrication is one active Systems link beside Planning',async({page})=>{
 await setup(page);await page.goto('/#fabrication');const nav=page.getByRole('navigation',{name:'Hub workspace'}),link=nav.getByRole('link',{name:'Fabrication',exact:true});await expect(link).toHaveCount(1);await expect(link).toHaveAttribute('href','#fabrication');await expect(link).toHaveAttribute('aria-current','page');const grouping=await link.evaluate(element=>{let previous=element.previousElementSibling,group='';const before=previous?.textContent;while(previous){if(previous.classList.contains('hub-nav-label')){group=previous.textContent||'';break;}previous=previous.previousElementSibling;}return {group,before};});expect(grouping).toEqual({group:'Systems',before:'Planning'});
});
test('submits distinct parts under the canonical project with mandatory DXF and explicit independent units',async({page})=>{
 const state=await setup(page);await page.goto('/#fabrication');await page.getByRole('button',{name:'Add part to Intake'}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Submit part for review'}).click();await expect(dialog.getByRole('alert')).toContainText('part name');await expect(dialog.getByLabel('DXF drawing units',{exact:true})).toHaveValue('');await fillNewPart(page);await dialog.getByLabel('DXF drawing units',{exact:true}).selectOption('mm');await dialog.locator('form').evaluate(f=>{(f as HTMLFormElement).requestSubmit();(f as HTMLFormElement).requestSubmit();});await expect(dialog).toHaveCount(0);expect(state.uploads).toHaveLength(1);expect(state.uploads[0].p).toMatchObject({board_id:fabProject,version:null,thickness:0.125,thickness_unit:'in',drawing_unit:'mm',quantity:3,needed_date:'2026-10-20'});expect(state.uploads[0].p.part_id).not.toBe(fabPart);await expect(project(page).locator('.fab-part-row')).toHaveCount(4);expect(state.context.parts.find(p=>p.current_revision.name==='Synthetic new mounting plate')?.status).toBe('needs_review');
});
test('an ordinary active member claims, acknowledges, starts and completes the current revision',async({page})=>{
 const state=await setup(page);await page.goto('/#fabrication');let dialog=await openPart(page,'Intake side plate, right');await expect(dialog.getByRole('button',{name:'Start work',exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'Claim part',exact:true}).click();await expect(dialog.getByRole('button',{name:'Acknowledge revision 1',exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Acknowledge revision 1',exact:true})).toBeDisabled();await dialog.getByRole('checkbox',{name:'I reviewed revision 1'}).check();await dialog.getByRole('button',{name:'Acknowledge revision 1',exact:true}).click();await dialog.getByRole('button',{name:'Start work',exact:true}).click();await expect(dialog.locator('.fab-status')).toHaveText('In progress');await dialog.getByRole('button',{name:'Mark Done',exact:true}).click();await expect(dialog.locator('.fab-status')).toHaveText('Done');expect(state.context.can_manage).toBe(false);expect(state.mutations.map(m=>m.action)).toEqual(['claim','acknowledge','start','done']);expect(state.mutations.every(m=>m.p.revision_id===fabId(402))).toBe(true);
});
test('new revision warns on in-progress work, keeps its claim, clears acknowledgement and preserves old files',async({page})=>{
 const state=await setup(page);await page.goto('/#fabrication');let dialog=await openPart(page,'Shaft support bracket');await dialog.getByRole('button',{name:'New revision',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByText('This part is claimed and work is in progress')).toBeVisible();await expect(dialog.getByLabel('Part name',{exact:true})).toHaveValue('Shaft support bracket');await dialog.locator('input[type=file]').first().setInputFiles({name:'synthetic-shaft-r2.dxf',mimeType:'application/dxf',buffer:Buffer.from(syntheticDxf)});await dialog.getByLabel('DXF drawing units',{exact:true}).selectOption('mm');await dialog.getByRole('button',{name:'Submit new revision',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Confirm');await dialog.getByRole('checkbox',{name:'I understand the operator'}).check();await dialog.getByLabel('What changed in this revision?',{exact:true}).fill('Synthetic hole spacing correction.');await dialog.getByRole('button',{name:'Submit new revision',exact:true}).click();await expect(dialog).toHaveCount(0);const part=state.context.parts.find(p=>p.id===fabId(304))!;expect(part).toMatchObject({status:'needs_review',claimed_by:fabActor,acknowledged_revision_id:null,reviewed_revision_id:null});expect(state.context.revisions.filter(r=>r.part_id===part.id)).toHaveLength(2);expect(part.current_revision.pdf).toBeNull();await openPart(page,'Shaft support bracket');await expect(page.getByRole('button',{name:'Start work',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Mark Done',exact:true})).toHaveCount(0);
});
test('hold and rework require an explicit reason and go back through review',async({page})=>{
 const state=await setup(page);await page.goto('/#fabrication');const dialog=await openPart(page,'Shaft support bracket');await dialog.getByRole('button',{name:'Put on hold',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('short reason');await dialog.getByLabel('Workflow note',{exact:false}).fill('Material needs checking.');await dialog.getByRole('button',{name:'Put on hold',exact:true}).click();await expect(dialog.locator('.fab-status')).toHaveText('On hold');await dialog.getByLabel('Workflow note',{exact:false}).fill('Material confirmed; review latest drawing.');await dialog.getByRole('button',{name:'Return for review',exact:true}).click();await expect(dialog.locator('.fab-status')).toHaveText('Needs review');expect(state.mutations.map(m=>m.action)).toEqual(['hold','rework']);expect(state.context.parts.find(p=>p.id===fabId(304))?.acknowledged_revision_id).toBeNull();
});
test('read-only roles and archived seasons keep history and downloads without mutations',async({page})=>{
 const state=await setup(page,c=>{c.is_operator=false;c.projects.forEach(p=>{p.can_submit=false;p.can_operate=false;p.can_review=false;});c.parts.forEach(p=>{p.can_revise=false;p.allowed_actions=[];});});await page.goto('/#fabrication');await expect(page.getByRole('button',{name:'Add part to Intake'})).toHaveCount(0);let dialog=await openPart(page);await expect(dialog.getByRole('button',{name:'New revision',exact:true})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Acknowledge revision 2',exact:true})).toHaveCount(0);await expect(dialog.getByRole('region',{name:'Immutable revision history'})).toBeVisible();await dialog.getByRole('button',{name:'Close',exact:true}).click();state.context.seasons[0].status='archived';state.context.parts.forEach(p=>{p.can_revise=true;p.allowed_actions=['claim','ready','acknowledge'];});state.context.projects.forEach(p=>p.can_submit=true);await page.getByRole('button',{name:'Refresh Fabrication'}).click();await expect(page.getByText('This archived season is read only.',{exact:false})).toBeVisible();dialog=await openPart(page);await expect(dialog.getByRole('region',{name:'Part workflow'})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'New revision',exact:true})).toHaveCount(0);expect(state.mutations).toHaveLength(0);
});
test('unknown write resolves by receipt without replaying its payload or saving draft content',async({page})=>{
 const state=await setup(page);await page.route('**/rpc/fabrication_mutate',async r=>{state.apply(r.request().postDataJSON());await r.abort('failed');});await page.goto('/#fabrication');const dialog=await openPart(page,'Intake side plate, right');await dialog.getByRole('button',{name:'Claim part',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('region',{name:'Pending fabrication save'})).toBeVisible();expect(state.mutations).toHaveLength(1);const stored=await page.evaluate(()=>sessionStorage.getItem('4418-fabrication-receipts-v1'));expect(Object.keys(JSON.parse(stored!)[0]).sort()).toEqual(['expected_actor','request_id']);await expect(page.getByRole('button',{name:'Add part to Intake'})).toBeDisabled();await page.getByRole('button',{name:'Check save status'}).click();await expect(page.getByRole('region',{name:'Pending fabrication save'})).toHaveCount(0);expect(state.mutations).toHaveLength(1);await expect(page.getByRole('button',{name:'Add part to Intake'})).toBeEnabled();
});
test('closing a delayed upload clears the draft; explicit cancel fences a later completion',async({page})=>{
 const state=await setup(page);let release!:()=>void,started=false;const held=new Promise<void>(resolve=>release=resolve);await page.route('**/functions/v1/fabrication-files',async r=>{if(!r.request().headers()['content-type']?.includes('multipart/form-data'))return r.fallback();const body=parseUpload(r.request().postData()!);started=true;await held;await r.fulfill({json:state.applyUpload(body)}).catch(()=>{});});await page.goto('/#fabrication');await page.getByRole('button',{name:'Add part to Intake'}).click();const dialog=await fillNewPart(page,'Private unsaved synthetic draft');await dialog.getByRole('button',{name:'Submit part for review'}).click();await expect.poll(()=>started).toBe(true);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog).toHaveCount(0);await page.getByRole('button',{name:'Check save status'}).click();await expect(page.getByText('This save is not confirmed yet.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Cancel pending save'}).click();release();await expect.poll(()=>state.uploads.length).toBe(1);expect(state.context.parts).toHaveLength(5);await page.getByRole('button',{name:'Add part to Intake'}).click();await expect(page.getByRole('dialog').getByLabel('Part name',{exact:true})).toHaveValue('');expect(await page.evaluate(()=>sessionStorage.getItem('4418-fabrication-receipts-v1'))).not.toContain('Private');
});
test('stale version rejection leaves current form reviewable and permits a safe close and refresh',async({page})=>{
 const state=await setup(page);await page.route('**/rpc/fabrication_mutate',r=>r.fulfill({status:409,json:{code:'FB409',message:'Stale version'}}));await page.goto('/#fabrication');const dialog=await openPart(page,'Shaft support bracket');await dialog.getByLabel('Workflow note',{exact:false}).fill('Synthetic note stays in this view.');await dialog.getByRole('button',{name:'Put on hold',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Another teammate');await expect(dialog.getByLabel('Workflow note',{exact:false})).toHaveValue('Synthetic note stays in this view.');await expect(page.getByRole('region',{name:'Pending fabrication save'})).toHaveCount(0);await dialog.press('Escape');await expect(dialog).toHaveCount(0);expect(state.mutations).toHaveLength(0);
});
test('project deep links filter canonical parts and Back clears unsaved editor state',async({page})=>{
 const state=await setup(page);await page.goto('/#fabrication');await project(page).getByRole('link',{name:'Intake',exact:true}).click();await expect(page).toHaveURL(new RegExp(`#fabrication/projects/${fabProject}$`));await expect(page.getByRole('button',{name:'Elevator carriage mount',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Add part',exact:true}).click();await page.getByRole('dialog').getByLabel('Part name',{exact:true}).fill('Discard on Back');await page.goBack();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Elevator carriage mount',exact:true})).toBeVisible();await page.goForward();await expect(page.getByRole('dialog')).toHaveCount(0);expect(state.uploads).toHaveLength(0);
});
test('malformed routes never load a queue; denied and empty contexts remain clear',async({page})=>{
 const state=await setup(page);let reads=0;await page.route('**/rpc/fabrication_context',r=>{reads++;return r.fulfill({status:403,json:{code:'FB403',message:'Unavailable'}});});await page.goto(`/#fabrication/projects/${fabProject}/extra`);await expect(page.getByText('This Fabrication link is invalid.',{exact:false})).toBeVisible();expect(reads).toBe(0);await page.goto('/#fabrication');await expect(page.getByRole('alert')).toContainText('access');await expect(page.getByRole('button',{name:'Intake side plate, left',exact:true})).toHaveCount(0);await page.unroute('**/rpc/fabrication_context');state.context.projects=[];state.context.parts=[];state.context.revisions=[];await page.route('**/rpc/fabrication_context',r=>r.fulfill({json:state.context}));await page.getByRole('button',{name:'Retry Fabrication'}).click();await expect(page.getByRole('heading',{name:'No project boards yet'})).toBeVisible();
});
test('immutable revision download verifies exact revision and never requests public storage',async({page})=>{
 const state=await setup(page);await page.goto('/#fabrication');const dialog=await openPart(page),downloads:Download[]=[];
 page.on('download',download=>downloads.push(download));
 await dialog.getByRole('region',{name:'Immutable revision history'}).getByRole('button',{name:'Download DXF revision 1',exact:true}).click();
 // Surface the service's verification error immediately instead of timing out on a missing download.
 await expect.poll(async()=>downloads.length>0||await dialog.getByRole('alert').isVisible(),{message:'Expected a verified revision download or an explicit error.'}).toBe(true);
 expect(await dialog.getByRole('alert').allTextContents()).toEqual([]);expect(downloads).toHaveLength(1);
 const download=downloads[0];expect(download.suggestedFilename()).toBe(`synthetic-${fabId(400)}.dxf`);expect(await download.failure()).toBeNull();expect(state.downloads).toMatchObject([{revision_id:fabId(400),file_kind:'dxf'}]);expect(state.mutations).toHaveLength(0);expect(state.external.some(u=>u.includes('/storage/'))).toBe(false);
});
test('account switch hides the former draft, files and recovery receipt immediately',async({page})=>{
 const state=await setup(page);await page.goto('/#fabrication');await page.getByRole('button',{name:'Add part to Intake'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Part name',{exact:true}).fill('Former actor private draft');await page.evaluate(({actor,id})=>sessionStorage.setItem('4418-fabrication-receipts-v1',JSON.stringify([{expected_actor:actor,request_id:id}])),{actor:fabActor,id:fabId(900)});state.context.user_id=fabId(2);state.context.projects=[];state.context.parts=[];state.context.revisions=[];await changeActor(page,fabId(2));await expect(dialog).toHaveCount(0);await expect(page.getByText('Former actor private draft',{exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'Pending fabrication save'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Intake side plate, left',exact:true})).toHaveCount(0);
});
test('signout prevents a late context from repopulating old account data',async({page})=>{
 await setup(page);let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);await page.route('**/rpc/fabrication_context',async r=>{await held;await r.fulfill({json:fabricationUIFixture()}).catch(()=>{});});await page.goto('/#fabrication');await expect(page.getByText('Loading Fabrication…')).toBeVisible();await changeActor(page,null);await expect(page.getByRole('heading',{name:'Team sign in',exact:true})).toBeVisible();release();await expect(page.getByRole('region',{name:'Fabrication workspace'})).toHaveCount(0);
});
test('leaving a detail dialog suppresses a delayed verified file download',async({page})=>{
 const state=await setup(page);let release!:()=>void,started=false;const held=new Promise<void>(resolve=>release=resolve),downloads:string[]=[];page.on('download',d=>downloads.push(d.suggestedFilename()));await page.route('**/functions/v1/fabrication-files',async r=>{if(r.request().postDataJSON().action!=='download')return r.fallback();started=true;await held;return r.fallback().catch(()=>{});});await page.goto('/#fabrication');const dialog=await openPart(page);await dialog.getByRole('region',{name:'Immutable revision history'}).getByRole('button',{name:'Download DXF revision 1',exact:true}).click();await expect.poll(()=>started).toBe(true);await dialog.getByRole('button',{name:'Close',exact:true}).click();release();await expect.poll(()=>state.downloads.length).toBe(1);expect(downloads).toEqual([]);await expect(dialog).toHaveCount(0);
});


test('focus refresh reveals a newer revision in an open operator detail without losing the claim',async({page})=>{
 const state=await setup(page);await page.goto('/#fabrication');const dialog=await openPart(page,'Shaft support bracket');await expect(dialog.locator('.fab-status')).toHaveText('In progress');const part=state.context.parts.find(p=>p.id===fabId(304))!,revision={...structuredClone(part.current_revision),id:fabId(888),revision_number:2,created_at:'2026-10-06T16:00:00Z',notes:'Synthetic newer revision from another member.'};state.context.revisions.push(revision);Object.assign(part,{current_revision_id:revision.id,current_revision:revision,status:'needs_review',version:part.version+1,acknowledged_revision_id:null,reviewed_revision_id:null});part.allowed_actions=fixtureActions(part,fabActor);await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(dialog.getByText('Current revision 2',{exact:true})).toBeVisible();await expect(dialog.getByText('Current revision needs acknowledgement',{exact:true})).toBeVisible();await expect(dialog.getByText('Claimed by Alex Builder',{exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Mark Done',exact:true})).toHaveCount(0);await expect(dialog.getByRole('region',{name:'Immutable revision history'})).toContainText('Revision 1');expect(state.mutations).toHaveLength(0);expect(state.uploads).toHaveLength(0);
});
test('focus and visible-tab polling never replace an open revision draft',async({page})=>{
 const state=await setup(page);let reads=0;page.on('request',request=>{if(request.url().endsWith('/rpc/fabrication_context'))reads++;});await page.clock.install();await page.goto('/#fabrication');await page.getByRole('button',{name:'Add part to Intake'}).click();const dialog=await fillNewPart(page,'Synthetic draft must remain');const prior=reads;state.context.projects[0].name='Updated project name from teammate';await page.evaluate(()=>{window.dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'));});await page.clock.runFor(31000);await expect(dialog.getByLabel('Part name',{exact:true})).toHaveValue('Synthetic draft must remain');await expect(dialog.getByLabel('DXF drawing units',{exact:true})).toHaveValue('mm');expect(reads).toBe(prior);expect(state.versionReads).toHaveLength(0);expect(state.uploads).toHaveLength(0);expect(state.mutations).toHaveLength(0);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('link',{name:'Updated project name from teammate',exact:true})).toBeVisible();
});


test('polling checks only the open part version and reloads full history only when it changes',async({page})=>{
 const state=await setup(page);let fullReads=0;page.on('request',request=>{if(request.url().endsWith('/rpc/fabrication_context'))fullReads++;});await page.clock.install();await page.goto('/#fabrication');await expect(project(page)).toBeVisible();const landingReads=fullReads;await page.clock.runFor(31000);expect(state.versionReads).toHaveLength(0);expect(fullReads).toBe(landingReads);const dialog=await openPart(page,'Shaft support bracket'),detailReads=fullReads;await page.clock.runFor(31000);await expect.poll(()=>state.versionReads.length).toBe(1);expect(state.versionReads[0]).toEqual({part_id:fabId(304),expected_actor:fabActor});expect(fullReads).toBe(detailReads);const part=state.context.parts.find(p=>p.id===fabId(304))!,revision={...structuredClone(part.current_revision),id:fabId(889),revision_number:2,created_at:'2026-10-06T16:30:00Z'};state.context.revisions.push(revision);Object.assign(part,{current_revision_id:revision.id,current_revision:revision,status:'needs_review',version:part.version+1,acknowledged_revision_id:null,reviewed_revision_id:null});part.allowed_actions=fixtureActions(part,fabActor);await page.clock.runFor(31000);await expect(dialog.getByText('Current revision 2',{exact:true})).toBeVisible();await expect(dialog.getByText('Current revision needs acknowledgement',{exact:true})).toBeVisible();expect(fullReads).toBe(detailReads+1);expect(state.versionReads).toHaveLength(2);expect(state.mutations).toHaveLength(0);expect(state.uploads).toHaveLength(0);
});

// These contract checks need no browser and remain useful when Chromium is unavailable.
test.describe('Editor contract (node)',()=>{
 const submission=():FabricationSubmission=>{const c=fabricationUIFixture(),r=c.parts[0].current_revision;return {...r,part_id:fabId(800),board_id:fabProject,revision_id:fabId(801),version:null};};
 test('requires a DXF for every new revision and validates optional PDF independently',()=>{const p=submission(),dxf=new File([syntheticDxf],'synthetic.dxf');expect(revisionIssue(p,null,null)).toContain('Choose a DXF');expect(revisionIssue(p,dxf,null)).toBeNull();expect(revisionIssue(p,dxf,new File(['oops'],'notes.txt'))).toContain('PDF');expect(revisionIssue(p,new File([syntheticDxf],'unsafe.exe.dxf'),null)).toContain('simple filenames');expect(revisionIssue(p,new File([syntheticDxf],'CON.dxf'),null)).toContain('simple filenames');});
 test('strict metadata boundaries reject missing units, impossible date, invalid Onshape, and excessive notes',()=>{const p=submission(),dxf=new File([syntheticDxf],'synthetic.dxf');for(const changes of [{drawing_unit:''},{thickness:0},{thickness:1001},{quantity:1.5},{needed_date:'2026-02-30'},{onshape_url:'https://evil.example/documents/x'},{notes:'a'.repeat(2001)},{material:'a'.repeat(121)}])expect(revisionIssue({...p,...changes} as FabricationSubmission,dxf,null)).not.toBeNull();});
 test('each revision requires a nonempty bounded file and a safe basename',()=>{const p=submission();expect(revisionIssue(p,new File([],'empty.dxf'),null)).toContain('nonempty DXF');expect(revisionIssue(p,new File([syntheticDxf],'../escape.dxf'),null)).toContain('simple filenames');expect(revisionIssue(p,new File([syntheticDxf],`${'a'.repeat(117)}.dxf`),null)).toContain('120 characters');expect(revisionIssue(p,new File([syntheticDxf],'safe part (rev 2).dxf'),new File(['%PDF-1.4\n%%EOF'],'reference.pdf'))).toBeNull();});
});
