import {test,expect,type Page} from '@playwright/test';
import {onboardingFixture} from './fixtures/onboarding';
async function leadFixture(page:Page,active=true){const f=await onboardingFixture(page,'lead');const actor={...f.data.members[0],active};f.data.members=[];await page.route('**/rest/v1/profiles*',route=>route.fulfill({json:actor}));const calls:string[]=[];await page.route('**/rest/v1/rpc/team_invitation_context',async route=>{calls.push('invite-context');await f.control.context?.();await route.fulfill({json:f.data});});await page.route('**/rest/v1/rpc/team_management_context_v2',async route=>{calls.push('manager-context');await route.fulfill({status:403,json:{code:'42501',message:'Active mentor or admin required'}});});return {...f,calls,actor};}
for(const width of [390,1440])test(`lead invitation-only workspace and single invite at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});const {sent,calls}=await leadFixture(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#team-management');
 await expect(page.getByRole('heading',{name:'Member invitations',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Invite Members',exact:true})).toHaveCount(1);await expect(page.getByRole('button',{name:'Members',exact:true})).toHaveCount(0);for(const name of ['Positions','Areas','Manage'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'+ Invite member',exact:true}).click();let d=page.getByRole('dialog',{name:'Invite member'});await expect(d.getByLabel('Account role',{exact:true}).locator('option')).toHaveText(['student']);await page.keyboard.press('Escape');await expect(d).toHaveCount(0);expect(sent).toHaveLength(0);
 await page.getByRole('button',{name:'+ Invite member',exact:true}).click();d=page.getByRole('dialog',{name:'Invite member'});await d.getByLabel('Display name',{exact:true}).fill('Synthetic Student');await d.getByLabel('Email',{exact:true}).fill('student@example.test');await d.getByLabel('Invitation reason').fill('Joining team');await page.screenshot({path:`test-results/invite-cleanup/lead-single-${width}.png`,fullPage:true});await d.getByRole('button',{name:'Send invitation',exact:true}).click();await expect(d).toHaveCount(0);expect(sent).toHaveLength(1);expect(sent[0].role).toBe('student');await expect(page.getByRole('region',{name:'Team onboarding'})).toContainText('student@example.test');expect(calls).not.toContain('manager-context');expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('lead batch keeps review, one-at-a-time, pause and no-resend safeguards',async({page})=>{
 const {sent,control}=await leadFixture(page);await page.goto('/#team-management');const ui=page.getByRole('region',{name:'Team onboarding'});await ui.getByText('Invite a group',{exact:true}).click();await ui.getByLabel('Names and emails',{exact:true}).fill('First Student, first@example.test\nSecond Student, second@example.test');await ui.getByLabel('Reason for these invitations',{exact:true}).fill('Joining team');await ui.getByRole('button',{name:'Add pasted recipients'}).click();for(const n of [1,2])await expect(ui.getByLabel(`Role for recipient ${n}`).locator('option')).toHaveText(['student']);
 await ui.getByRole('button',{name:'Review batch'}).click();await expect(ui.getByRole('button',{name:'Send 2 reviewed invitations'})).toBeDisabled();await ui.getByRole('checkbox').check();let release!:()=>void;const gate=new Promise<void>(r=>release=r);control.send=async(p,route)=>{await gate;await route.fulfill({status:202,json:{id:p.id,status:'pending'}})};await ui.getByRole('button',{name:'Send 2 reviewed invitations'}).click();await expect.poll(()=>sent.length).toBe(1);await ui.getByRole('button',{name:'Pause after current invitation'}).click();release();await expect(ui).toContainText('Paused. The current request has settled');expect(sent).toHaveLength(1);await expect(ui.getByRole('checkbox')).not.toBeChecked();await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Resume 1 reviewed invitation'}).click();await expect.poll(()=>sent.length).toBe(2);await expect(ui).toContainText('This batch has finished');expect(sent.every(p=>p.role==='student')).toBe(true);expect(new Set(sent.map(p=>p.id)).size).toBe(2);
});
test('inactive lead sees no invitation controls or context',async({page})=>{const {calls,sent}=await leadFixture(page,false);await page.goto('/#team-management');await expect(page.getByText('Active leads can invite students.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'+ Invite member'})).toHaveCount(0);expect(calls).toEqual([]);expect(sent).toEqual([]);});
test('lead uncertain send remains locked and cannot be repeated',async({page})=>{const {sent,control}=await leadFixture(page);control.send=async(p,route)=>route.fulfill({status:502,json:{id:p.id,status:'review',error:'Needs review; do not resend.'}});await page.goto('/#team-management');await page.getByRole('button',{name:'+ Invite member'}).click();const d=page.getByRole('dialog',{name:'Invite member'});await d.getByLabel('Display name',{exact:true}).fill('Synthetic Student');await d.getByLabel('Email',{exact:true}).fill('uncertain@example.test');await d.getByLabel('Invitation reason').fill('Joining team');await d.getByRole('button',{name:'Send invitation'}).click();await expect(d.getByRole('button',{name:'Send invitation'})).toBeDisabled();await d.getByRole('button',{name:'Close editor'}).click();await page.getByRole('button',{name:'+ Invite member'}).click();await d.getByLabel('Email',{exact:true}).fill('uncertain@example.test');await expect(d.getByRole('button',{name:'Send invitation'})).toBeDisabled();expect(sent).toHaveLength(1);});
