import {test,expect,type Page} from '@playwright/test';
import {session} from './hub-session';
async function setup(page:Page){await session(page);const calls:any[]=[];const items:any[]=[{id:'one',source:'finance',title:'PO #27 needs approval',message:'Robot supplier',created_at:'2026-10-01T12:00:00Z',read_at:null,href:'https://finance.frc4418.org/#po/00000000-0000-0000-0000-000000000027',action_needed:true},{id:'two',source:'attendance',title:'Your absence request was approved',message:'Build meeting',created_at:'2026-10-01T11:00:00Z',read_at:null,href:'#attendance/notices',action_needed:false},{id:'three',source:'announcements',title:'New announcement',message:'Load-in details',created_at:'2026-10-01T10:00:00Z',read_at:'2026-10-01T12:00:00Z',href:'#home-announcements',action_needed:false}];
 await page.route('**/rest/v1/rpc/notification_center',r=>{const {filter}=r.request().postDataJSON();return r.fulfill({json:{unread:items.filter(x=>!x.read_at).length,attention:items.filter(x=>x.action_needed).slice(0,5),items:items.filter(x=>filter==='all'||filter==='unread'&&!x.read_at||filter==='action'&&x.action_needed),has_more:false}});});
 await page.route('**/rest/v1/rpc/notification_read',r=>{const p=r.request().postDataJSON();calls.push(p);for(const n of items)if(p.notification_id===null||p.notification_id===n.id)n.read_at=p.unread?null:n.read_at||new Date().toISOString();return r.fulfill({status:204});});return {items,calls};}
for(const width of [390,1440])test(`Notification bell/page read vs action, keyboard, links and layout ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});const {items,calls}=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#notifications');
 const bell=page.getByRole('button',{name:'Notifications, 2 unread',exact:true});await expect(bell).toBeVisible();await bell.click();const panel=page.getByRole('region',{name:'Recent notifications'});await expect(panel.getByRole('heading',{name:'Needs your attention'})).toBeVisible();await expect(panel.getByRole('heading',{name:'Recent',exact:true})).toBeVisible();await expect(panel.getByRole('button',{name:'Close notifications'})).toBeFocused();
 await page.screenshot({path:`test-results/notification-bell-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.keyboard.press('Escape');await expect(panel).toHaveCount(0);await expect(bell).toBeFocused();
 const main=page.locator('main');await main.getByRole('button',{name:'Action needed',exact:true}).click();await expect(main.locator('.notification-list li')).toHaveCount(1);await main.getByRole('button',{name:'Mark read',exact:true}).click();await expect(page.getByRole('button',{name:'Notifications, 1 unread',exact:true})).toBeVisible();await expect(main.locator('.notification-list li')).toHaveCount(1);await expect(main.getByRole('button',{name:'Mark unread'})).toBeVisible();expect(items[0].action_needed).toBe(true);
 items[0].action_needed=false;await main.getByRole('button',{name:'Refresh',exact:true}).click();await expect(main.getByText('Nothing needs your attention.')).toBeVisible();await main.getByRole('button',{name:'All',exact:true}).click();await expect(main.locator('.notification-list li')).toHaveCount(3);await expect(main.getByRole('link',{name:'PO #27 needs approval'})).toHaveAttribute('href',items[0].href);
 await main.getByRole('button',{name:'Mark all read'}).click();await expect(page.getByRole('button',{name:'Notifications',exact:true})).toBeVisible();await main.getByRole('button',{name:'Unread',exact:true}).click();await expect(main.getByText('You’re all caught up.')).toBeVisible();expect(calls.some(c=>c.notification_id===null)).toBe(true);
 await main.getByRole('button',{name:'All',exact:true}).click();await expect(main.locator('.notification-list li')).toHaveCount(3);await page.screenshot({path:`test-results/notifications-page-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('empty, error, read failure and unsafe link remain contained',async({page})=>{
 const {items}=await setup(page);items.splice(0);await page.goto('/#notifications');await expect(page.getByText('No notifications yet.')).toBeVisible();await page.getByRole('button',{name:'Notifications',exact:true}).click();await expect(page.getByText('You’re all caught up.')).toBeVisible();await page.keyboard.press('Escape');
 items.push({id:'bad',source:'finance',title:'Safe fallback',message:'Example',created_at:new Date().toISOString(),read_at:null,href:'javascript:alert(1)',action_needed:false});await page.locator('main').getByRole('button',{name:'Refresh'}).click();await expect(page.getByRole('link',{name:'Safe fallback'})).toHaveAttribute('href','#notifications');
 await page.route('**/rest/v1/rpc/notification_read',r=>r.fulfill({status:503,json:{message:'private internal failure'}}));await page.getByRole('button',{name:'Mark read',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Read status was not saved');await expect(page.getByRole('alert')).not.toContainText('private internal failure');
});
test('signed-out notification route never fetches or flashes recipient content',async({page})=>{let calls=0;await page.route('**/rest/v1/rpc/notification_center',r=>{calls++;return r.fulfill({json:{items:[]}});});await page.goto('/#notifications');await expect(page.getByRole('heading',{name:'Team sign in'})).toBeVisible();await expect(page.getByRole('button',{name:/Notifications/})).toHaveCount(0);expect(calls).toBe(0);});
test('Load more uses a bounded cursor and appends unique history',async({page})=>{
 const {items}=await setup(page);const cursors:any[]=[];await page.route('**/rest/v1/rpc/notification_center',r=>{const p=r.request().postDataJSON();cursors.push(p);return r.fulfill({json:{unread:2,attention:[],items:p.before_id?[items[2]]:items.slice(0,2),has_more:!p.before_id}});});await page.goto('/#notifications');await expect(page.locator('main .notification-list li')).toHaveCount(2);await page.getByRole('button',{name:'Load more'}).click();await expect(page.locator('main .notification-list li')).toHaveCount(3);await expect(page.getByRole('button',{name:'Load more'})).toHaveCount(0);expect(cursors.at(-1)).toMatchObject({before_id:'two',before_at:items[1].created_at});
});
