import {test,expect} from '@playwright/test';
import {onboardingFixture,openOnboarding,prepareBatch} from './fixtures/onboarding';
for(const width of [390,768,1440])test(`reviewed batch requires explicit approval and preserves role/payload ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000});const {sent}=await onboardingFixture(page);const ui=await prepareBatch(page);
 await expect(ui.getByRole('button',{name:'Send 2 reviewed invitations',exact:true})).toBeDisabled();expect(sent).toEqual([]);
 await expect(ui.locator('.onboarding-review-values')).toHaveCount(2);await expect(ui).toContainText('alex@example.test');await expect(ui).toContainText('Joining the build team');
 await page.screenshot({path:`test-results/onboarding-review-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Send 2 reviewed invitations',exact:true}).click();
 await expect(ui.locator('.onboarding-recipient.is-accepted')).toHaveCount(2);expect(sent).toHaveLength(2);expect(new Set(sent.map(row=>row.id)).size).toBe(2);expect(sent[0]).toMatchObject({display_name:'Alex Rivera',email:'alex@example.test',role:'student',reason:'Joining the build team',area_id:'',member_status:''});
 await expect(ui).toContainText('Inbox delivery is not confirmed');await expect(ui.getByRole('button',{name:'Start a new batch'})).toBeEnabled();
});
test('duplicate recipients and existing accounts cannot become a sendable batch',async({page})=>{
 const {sent}=await onboardingFixture(page);const ui=await openOnboarding(page);await ui.getByLabel('Names and emails',{exact:true}).fill('One, SAME@example.test\nTwo, same@example.test\nManager, manager@example.test');await ui.getByLabel('Reason for these invitations',{exact:true}).fill('Joining team');await ui.getByRole('button',{name:'Add pasted recipients'}).click();await ui.getByRole('button',{name:'Review batch'}).click();await expect(ui.getByRole('alert')).toContainText('Fix the marked recipients');await expect(ui).toContainText('more than once');await expect(ui).toContainText('already belongs to a team member');expect(sent).toEqual([]);await expect(ui.getByRole('checkbox')).toHaveCount(0);
});
test('pause settles one request and resume never repeats it',async({page})=>{
 const {sent,control}=await onboardingFixture(page);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);
 control.send=async(payload,route)=>{if(sent.length===1)await gate;await route.fulfill({status:202,json:{id:payload.id,status:'pending'}});};
 const ui=await prepareBatch(page);await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Send 2 reviewed invitations'}).click();await expect(ui.locator('.is-sending')).toHaveCount(1);await expect.poll(()=>sent.length).toBe(1);
 await ui.getByRole('button',{name:'Pause after current invitation'}).click();release();await expect(ui).toContainText('Paused. The current request has settled');await expect(ui.getByRole('checkbox')).not.toBeChecked();expect(sent).toHaveLength(1);
 await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Resume 1 reviewed invitation',exact:true}).click();await expect(ui.locator('.is-accepted')).toHaveCount(2);expect(sent).toHaveLength(2);expect(sent[1].id).not.toBe(sent[0].id);
});
test('pause during latest-roster check sends nothing',async({page})=>{
 const {sent,control}=await onboardingFixture(page);const ui=await prepareBatch(page);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);control.context=()=>gate;
 await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Send 2 reviewed invitations'}).click();await expect(ui).toContainText('Checking the latest team list');await ui.getByRole('button',{name:'Pause after current invitation'}).click();release();await expect(ui).toContainText('Paused before sending');expect(sent).toEqual([]);
});
test('latest roster is rechecked before sending any reviewed recipient',async({page})=>{
 const {data,sent}=await onboardingFixture(page);const ui=await prepareBatch(page);data.invitations.push({id:'another-request',email:'alex@example.test',display_name:'Alex',status:'pending',created_at:'2026-10-05',user_id:null});await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Send 2 reviewed invitations'}).click();await expect(ui.getByRole('alert')).toContainText('team list changed');expect(sent).toEqual([]);await expect(ui.getByRole('button',{name:'Review batch'})).toBeVisible();
});
test('uncertain recipient stops the batch and remains blocked across tabs and new batches',async({page})=>{
 const {sent,control}=await onboardingFixture(page);control.send=async(payload,route)=>{await route.fulfill(sent.length===1?{status:502,json:{id:payload.id,status:'review',error:'Unconfirmed'}}:{status:202,json:{id:payload.id,status:'pending'}});};
 const ui=await prepareBatch(page);await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Send 2 reviewed invitations'}).click();await expect(ui.locator('.onboarding-recipient.is-review')).toHaveCount(1);expect(sent).toHaveLength(1);
 await page.getByRole('button',{name:'Members',exact:true}).click();await page.getByRole('button',{name:'+ Invite member',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Invite member'});await dialog.getByLabel('Email',{exact:true}).fill('ALEX@example.test');await expect(dialog.getByRole('button',{name:'Send invitation'})).toBeDisabled();await dialog.getByRole('button',{name:'Close editor'}).click();
 await page.getByRole('button',{name:'Onboarding',exact:true}).click();await expect(ui.locator('.onboarding-recipient.is-review')).toHaveCount(1);await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Resume 1 reviewed invitation',exact:true}).click();await expect(ui.locator('.onboarding-recipient.is-accepted')).toHaveCount(1);expect(sent).toHaveLength(2);
 await ui.getByRole('button',{name:'Start a new batch'}).click();await ui.getByLabel('Names and emails',{exact:true}).fill('Alex, alex@example.test');await ui.getByRole('button',{name:'Add pasted recipients'}).click();await ui.getByRole('button',{name:'Review batch'}).click();await expect(ui).toContainText('do not resend');expect(sent).toHaveLength(2);
});
test('status refresh reconciles only the attempted UUID and never sends',async({page})=>{
 const {data,sent,control}=await onboardingFixture(page);control.send=async(payload,route)=>{await route.fulfill({status:502,json:{id:payload.id,status:'review'}});};const ui=await prepareBatch(page,'Alex, alex@example.test');await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Send 1 reviewed invitation'}).click();await expect(ui.locator('.onboarding-recipient.is-review')).toHaveCount(1);
 data.invitations.push({id:'wrong-id',email:'alex@example.test',display_name:'Other',status:'pending',created_at:'2026-10-05',user_id:null});await ui.getByRole('button',{name:'Refresh status'}).click();await expect(ui.locator('.onboarding-recipient.is-review')).toHaveCount(1);
 data.invitations.push({id:sent[0].id,email:'alex@example.test',display_name:'Alex',status:'pending',created_at:'2026-10-05',user_id:null});await ui.getByRole('button',{name:'Refresh status'}).click();await expect(ui.locator('.onboarding-recipient.is-accepted')).toHaveCount(1);expect(sent).toHaveLength(1);await expect(ui).toContainText('account setup is still pending');
});
test('registration follows member ID, not matching email or invite label',async({page})=>{
 const {data}=await onboardingFixture(page);data.members.push({id:'member',email:'same@example.test',display_name:'Same email member',role:'student',active:true,primary_area_id:null,updated_at:'2026-10-05T12:00:00Z',member_status:'registered',team_area:null});data.invitations.push({id:'unknown-link',email:'same@example.test',display_name:'Unlinked invite',status:'account_active',created_at:'2026-10-05',user_id:null},{id:'linked',email:'linked@example.test',display_name:'Linked invite',status:'account_active',created_at:'2026-10-05',user_id:'member'});
 const ui=await openOnboarding(page);const unlinked=ui.locator('.onboarding-status-row').filter({hasText:'Unlinked invite'});await expect(unlinked).toContainText('Attendance: Unavailable');await expect(unlinked.getByRole('button')).toHaveCount(0);await expect(ui.locator('.onboarding-status-row').filter({hasText:'Linked invite'})).toContainText('Attendance: Registered');await expect(ui).toContainText('does not confirm FIRST registration or school forms');
});
test('student cannot access batch invitations through management',async({page})=>{const {sent}=await onboardingFixture(page,'student');await page.goto('/#team-management');await expect(page.getByText('Active mentors and admins can manage the team.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Onboarding',exact:true})).toHaveCount(0);expect(sent).toEqual([]);});

test('auth refresh pauses safely, preserves the reviewed batch, and releases busy state',async({page})=>{
 const {sent,control}=await onboardingFixture(page);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);control.send=async(payload,route)=>{await gate;await route.fulfill({status:202,json:{id:payload.id,status:'pending'}});};
 const ui=await prepareBatch(page);await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Send 2 reviewed invitations'}).click();await expect(ui.locator('.is-sending')).toHaveCount(1);await expect.poll(()=>sent.length).toBe(1);
 const refreshed=page.waitForResponse(response=>response.url().includes('/rpc/team_management_context_v2'));
 await page.evaluate(()=>{const session=JSON.parse(localStorage.getItem('4418-team-hub-auth')!);const channel=new BroadcastChannel('4418-team-hub-auth');channel.postMessage({event:'TOKEN_REFRESHED',session});channel.close();});
 await refreshed;await expect(page.getByRole('button',{name:'Onboarding',exact:true})).toBeVisible();release();await expect(ui.getByRole('button',{name:'Refresh status',exact:true})).toBeEnabled();await expect(ui.locator('.is-accepted')).toHaveCount(1);await expect(ui.locator('.is-ready')).toHaveCount(1);expect(sent).toHaveLength(1);
});

test('a different signed-in account cannot inherit drafts or delayed outcomes',async({page})=>{
 const {sent,control}=await onboardingFixture(page);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);control.send=async(payload,route)=>{await gate;await route.fulfill({status:202,json:{id:payload.id,status:'pending'}});};
 const ui=await prepareBatch(page);await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Send 2 reviewed invitations'}).click();await expect(ui.locator('.is-sending')).toHaveCount(1);await expect.poll(()=>sent.length).toBe(1);
 await switchFixtureIdentity(page,'00000000-0000-0000-0000-000000000002');
 await page.getByRole('button',{name:'Onboarding',exact:true}).click();await expect(ui.locator('.onboarding-recipient')).toHaveCount(0);await expect(ui.getByLabel('Names and emails',{exact:true})).toHaveValue('');release();await expect(ui.getByRole('button',{name:'Refresh status',exact:true})).toBeEnabled();await expect(ui.locator('.onboarding-recipient')).toHaveCount(0);expect(sent).toHaveLength(1);
});

async function switchFixtureIdentity(page:import('@playwright/test').Page,id:string){const loaded=page.waitForResponse(response=>response.url().includes('/rpc/team_management_context_v2'));await page.evaluate(id=>{const session=JSON.parse(localStorage.getItem('4418-team-hub-auth')!);session.user.id=id;localStorage.setItem('4418-team-hub-auth',JSON.stringify(session));const channel=new BroadcastChannel('4418-team-hub-auth');channel.postMessage({event:'SIGNED_IN',session});channel.close();},id);await loaded;await expect(page.getByRole('button',{name:'Members',exact:true})).toHaveAttribute('aria-pressed','true');}
test('switching away and back cannot revive an older batch generation',async({page})=>{
 const {sent,control}=await onboardingFixture(page);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);control.send=async(payload,route)=>{await gate;await route.fulfill({status:202,json:{id:payload.id,status:'pending'}});};const ui=await prepareBatch(page);await ui.getByRole('checkbox').check();await ui.getByRole('button',{name:'Send 2 reviewed invitations'}).click();await expect(ui.locator('.is-sending')).toHaveCount(1);await expect.poll(()=>sent.length).toBe(1);
 await switchFixtureIdentity(page,'00000000-0000-0000-0000-000000000002');await page.getByRole('button',{name:'Onboarding',exact:true}).click();await expect(ui.locator('.onboarding-recipient')).toHaveCount(0);await switchFixtureIdentity(page,'00000000-0000-0000-0000-000000000001');await page.getByRole('button',{name:'Onboarding',exact:true}).click();release();await expect(ui.getByRole('button',{name:'Refresh status',exact:true})).toBeEnabled();await expect(ui.locator('.onboarding-recipient')).toHaveCount(0);expect(sent).toHaveLength(1);
});
test('old single-invite completion cannot close another account’s newer editor',async({page})=>{
 const {control,sent}=await onboardingFixture(page);await page.goto('/#team-management');await page.getByRole('button',{name:'+ Invite member',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Invite member'});await dialog.getByLabel('Display name',{exact:true}).fill('Fixture new teammate');await dialog.getByLabel('Email',{exact:true}).fill('new@example.test');await dialog.getByLabel('Invitation reason',{exact:true}).fill('Joining the team');let release!:()=>void,entered=false;const gate=new Promise<void>(resolve=>release=resolve);control.context=()=>{entered=true;return gate;};await dialog.getByRole('button',{name:'Send invitation'}).click();await expect.poll(()=>entered).toBe(true);control.context=undefined;
 await switchFixtureIdentity(page,'00000000-0000-0000-0000-000000000002');await page.getByRole('button',{name:'+ Invite member',exact:true}).click();await dialog.getByLabel('Display name',{exact:true}).fill('New actor draft');const settled=page.waitForResponse(response=>response.url().includes('/rpc/team_management_context_v2'));release();await settled;await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(null)))));await expect(dialog).toBeVisible();await expect(dialog.getByLabel('Display name',{exact:true})).toHaveValue('New actor draft');expect(sent).toHaveLength(1);
});
