import {test,expect,type Page} from '@playwright/test';
import {session} from './hub-session';
import {outreachFixture,outreachId as id,outreachActor as actor} from './fixtures/outreach';
import type {OutreachContext} from '../src/outreach/types';
/** Browser checks and screenshots are synthetic and never contact production. */
async function setup(page:Page,{role='mentor',finance=true,denied=false,broken=false}={}) {
 await page.route('https://**',r=>r.abort());
 await session(page);const ctx=outreachFixture(finance),writes:any[]=[],reads:string[]=[];
 await page.route('**/rest/v1/profiles*',r=>r.fulfill({json:{id:actor,display_name:'Alex Mentor (demo)',role,active:true}}));
 await page.route('**/rest/v1/rpc/notification_center',r=>r.fulfill({json:{unread:0,attention:[],items:[],has_more:false}}));
 await page.route('**/rest/v1/rpc/outreach_context',r=>{reads.push(r.request().url());return r.fulfill(denied?{status:403,json:{code:'42501',message:'Denied'}}:broken?{status:404,json:{code:'PGRST202',message:'Function absent'}}:{json:ctx});});
 await page.route('**/rest/v1/rpc/outreach_save',r=>{const body=r.request().postDataJSON();writes.push(body);const list=({organization:'organizations',contact:'contacts',engagement:'engagements',conversation:'conversations',pledge:'pledges',recognition:'recognition'} as Record<string,keyof OutreachContext>)[body.entity];const rows=ctx[list] as any[];const record={...body.p,version:body.p.version+1,created_at:'2026-10-06T12:00:00Z',updated_at:'2026-10-06T12:00:00Z',created_by:actor};const index=rows.findIndex(row=>row.id===record.id);if(index<0)rows.push(record);else rows[index]=record;return r.fulfill({json:{id:record.id,version:record.version}});});
 return {ctx,writes,reads};
}
async function expectReadableProfileHeading(page:Page,width:number) {
 if(width>900)return;
 const layout=await page.locator('.outreach-profile-heading').evaluate(element=>{const header=element.getBoundingClientRect(),title=element.querySelector(':scope > div')!.getBoundingClientRect(),edit=element.querySelector(':scope > button')!.getBoundingClientRect();return {headerWidth:header.width,titleWidth:title.width,titleBottom:title.bottom,editTop:edit.top};});
 expect(layout.titleWidth).toBeGreaterThanOrEqual(layout.headerWidth*.75);
 expect(layout.editTop).toBeGreaterThanOrEqual(layout.titleBottom);
}
async function expectReadableInKindHeading(page:Page,width:number) {
 if(width>900)return;
 const layout=await page.locator('.outreach-pledge[data-kind=in_kind] .outreach-item-heading').evaluate(element=>{const header=element.getBoundingClientRect(),description=element.querySelector(':scope > div')!.getBoundingClientRect(),status=element.querySelector(':scope > .outreach-pill')!.getBoundingClientRect(),edit=element.querySelector(':scope > button')!.getBoundingClientRect();return {headerWidth:header.width,descriptionWidth:description.width,descriptionBottom:description.bottom,statusTop:status.top,editTop:edit.top,overflows:element.scrollWidth>element.clientWidth};});
 expect(layout.descriptionWidth).toBeGreaterThanOrEqual(layout.headerWidth*.95);
 expect(layout.statusTop).toBeGreaterThanOrEqual(layout.descriptionBottom);
 expect(layout.editTop).toBeGreaterThanOrEqual(layout.descriptionBottom);
 expect(layout.overflows).toBe(false);
}
for(const width of [390,768,1440])test(`synthetic outreach portfolio and profile work at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:1000});await setup(page);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/#outreach');await expect(page.getByRole('heading',{name:'Sponsor & Outreach',exact:true})).toBeVisible();await expect(page.getByText('8 profiles',{exact:true})).toBeVisible();await expect(page.getByText('$2,000.00 linked funds received')).toBeVisible();
 expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await page.screenshot({path:`test-results/outreach-review/portfolio-${width}.png`,fullPage:true});
 await page.getByRole('searchbox',{name:'Search sponsors or contacts'}).fill('Jamie');await expect(page.locator('.outreach-directory-row')).toHaveCount(1);await page.locator('.outreach-directory-row').click();await expect(page.getByRole('heading',{name:'Cedarline Fabrication (demo)',exact:true})).toBeVisible();await expect(page.getByText('Jamie Example',{exact:true})).toBeVisible();await expectReadableProfileHeading(page,width);expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await page.screenshot({path:`test-results/outreach-review/profile-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Commitments & recognition',exact:true}).click();await expect(page.getByText('$2,000.00 linked funds received')).toBeVisible();await expect(page.getByText('DEMO-INCOME-002',{exact:false})).toBeVisible();await expect(page.getByText('Fulfilled Oct 3, 2026')).toBeVisible();await expectReadableInKindHeading(page,width);expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await page.screenshot({path:`test-results/outreach-review/commitments-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Add promise',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByLabel('What was promised?')).toBeVisible();await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});const modalCapture=await page.screenshot({path:`test-results/outreach-review/editor-${width}.png`,fullPage:false,scale:'css'});expect(modalCapture.readUInt32BE(16)).toBe(width);expect(modalCapture.readUInt32BE(20)).toBe(1000);await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(errors).toEqual([]);
});
test('manager navigation exposes outreach, while student direct routes and absent backend fail closed',async({page})=>{
 await setup(page,{role:'student',denied:true});await page.goto('/#outreach');await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();await expect(page.getByText('Cedarline Fabrication (demo)',{exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Sponsor & Outreach',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Add sponsor',exact:true})).toHaveCount(0);
 await setup(page,{broken:true});await page.reload();await expect(page.getByText('Sponsor & Outreach is not available on this connection yet.')).toBeVisible();await expect(page.getByRole('button',{name:'Add sponsor',exact:true})).toHaveCount(0);
});
test('contact and conversation edits preserve private actor, append history and never send communications',async({page})=>{
 const {writes}=await setup(page);await page.goto(`/#outreach/${id(100)}`);await page.getByRole('button',{name:'Add contact',exact:true}).click();await page.getByLabel('Contact name',{exact:true}).fill('New Demo Contact');await page.getByLabel('Email',{exact:true}).fill('new@example.invalid');await page.getByRole('button',{name:'Save record',exact:true}).dblclick();await expect(page.getByText('New Demo Contact',{exact:true})).toBeVisible();expect(writes).toHaveLength(1);expect(writes[0].expected_actor).toBe(actor);
 await page.getByRole('button',{name:'Conversations (2)',exact:true}).click();await page.getByRole('button',{name:'Log conversation',exact:true}).click();await page.getByLabel('Conversation summary').fill('Synthetic follow-up note, no external message sent.');await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByRole('button',{name:'Conversations (3)',exact:true})).toBeVisible();expect(writes).toHaveLength(2);expect(writes[1].entity).toBe('conversation');expect(writes[1].request_id).not.toBe(writes[0].request_id);
});
test('restricted Finance capability hides income details and receipt-link action',async({page})=>{
 await setup(page,{finance:false});await page.goto(`/#outreach/${id(100)}`);await page.getByRole('button',{name:'Commitments & recognition',exact:true}).click();await expect(page.getByText('Finance receipt details restricted')).toBeVisible();await expect(page.getByRole('button',{name:'Link income record'})).toHaveCount(0);await expect(page.getByText('DEMO-INCOME',{exact:false})).toHaveCount(0);await expect(page.getByText('Fulfilled Oct 3, 2026')).toBeVisible();
});
test('uncertain saves survive close, route changes and reload; not_found never enables a replacement save',async({page})=>{
 const {writes}=await setup(page);let requestId='';await page.route('**/rest/v1/rpc/outreach_save',async r=>{const body=r.request().postDataJSON();writes.push(body);requestId=body.request_id;await r.abort('failed');});
 await page.route('**/rest/v1/rpc/outreach_request_status',r=>r.fulfill({json:{status:'not_found'}}));
 await page.route('**/rest/v1/rpc/outreach_cancel_request',r=>{expect(r.request().postDataJSON()).toEqual({request_id:requestId,expected_actor:actor});return r.fulfill({json:{status:'canceled'}});});
 await page.goto('/#outreach');await page.getByRole('button',{name:'Add sponsor',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Private Synthetic Draft');await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByText('We could not confirm whether this change saved. Check its status before entering it again.')).toBeVisible();await page.getByRole('button',{name:'Close and review',exact:true}).click();await expect(page.getByText('A previous save needs checking')).toBeVisible();
 const persisted=await page.evaluate(()=>sessionStorage.getItem('4418-outreach-pending-v1'));expect(persisted).not.toContain('Private Synthetic Draft');expect(persisted).toContain(requestId);
 await page.locator('.outreach-directory-row').first().click();await expect(page.getByText('A previous save needs checking')).toBeVisible();await page.reload();await expect(page.getByText('A previous save needs checking')).toBeVisible();await page.getByRole('button',{name:'Check previous save',exact:true}).click();await expect(page.getByText('No completed save was found yet.',{exact:false})).toBeVisible();expect(writes).toHaveLength(1);
 await page.getByRole('button',{name:'Cancel unconfirmed change',exact:true}).click();await expect(page.getByText('A previous save needs checking')).toHaveCount(0);await page.getByRole('button',{name:'Edit profile',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();expect(writes).toHaveLength(1);
});
test('leaving or canceling an in-flight editor prevents a late save from opening or closing a newer view',async({page})=>{
 await setup(page);let finish!:()=>void,seen!:()=>void;const started=new Promise<void>(resolve=>seen=resolve);await page.route('**/rest/v1/rpc/outreach_save',async r=>{const body=r.request().postDataJSON();seen();await new Promise<void>(resolve=>finish=resolve);await r.fulfill({json:{id:body.p.id,version:body.p.version+1}}).catch(()=>{});});
 await page.goto(`/#outreach/${id(100)}`);await page.getByRole('button',{name:'Edit profile',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Late Demo Name');await page.getByRole('button',{name:'Save record',exact:true}).click();await started;await page.getByRole('button',{name:'Close form',exact:true}).click();await page.getByRole('link',{name:'All sponsors',exact:true}).click();finish();await expect(page.getByRole('heading',{name:'Sponsor relationships',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByText('Late Demo Name',{exact:true})).toHaveCount(0);
});
test('sign-in preserves only valid outreach deep links and malformed paths never reveal a profile',async({page})=>{
 await page.route('https://**',r=>r.abort());await page.route('**/rest/v1/**',r=>r.fulfill({json:new URL(r.request().url()).pathname.endsWith('/profiles')?{display_name:'Alex Mentor (demo)',role:'mentor',active:true}:{unread:0,attention:[],items:[],has_more:false}}));await page.route('**/rest/v1/rpc/outreach_context',r=>r.fulfill({json:outreachFixture()}));await page.route('**/auth/v1/token?grant_type=password',r=>r.fulfill({json:{access_token:'fixture-token',refresh_token:'fixture-refresh',expires_at:4000000000,expires_in:3600,token_type:'bearer',user:{id:actor,aud:'authenticated',app_metadata:{},user_metadata:{}}}}));
 await page.goto(`/#outreach/${id(100)}`);await expect(page.getByRole('heading',{name:'Team sign in',exact:true})).toBeVisible();await page.getByLabel('Email',{exact:true}).fill('demo@example.invalid');await page.getByLabel('Password',{exact:true}).fill('fixture-only-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Cedarline Fabrication (demo)',exact:true})).toBeVisible();expect(page.url()).toContain(`#outreach/${id(100)}`);
 await page.goto(`/#outreach/${id(100)}/extra`);await expect(page.getByRole('heading',{name:'Outreach profile not found'})).toBeVisible();await expect(page.getByText('Jamie Example',{exact:true})).toHaveCount(0);
});
