import {test,expect,type Page} from '@playwright/test';
import {session} from './hub-session';
import {outreachFixture,outreachStudentFixture,outreachStudent as student,outreachId as id,outreachActor as actor} from './fixtures/outreach';
import type {OutreachContext} from '../src/outreach/types';
/** Browser checks and screenshots are synthetic and never contact production. */
async function setup(page:Page,{role='mentor',finance=true,denied=false,broken=false}={}) {
 await page.route('https://**',r=>r.abort());
 await session(page);const ctx=['student','lead'].includes(role)?outreachStudentFixture():outreachFixture(finance),writes:any[]=[],reads:string[]=[];
 if(!ctx.can_manage)await page.addInitScript(({identity})=>{const stored=JSON.parse(localStorage.getItem('4418-team-hub-auth')!);stored.user.id=identity;localStorage.setItem('4418-team-hub-auth',JSON.stringify(stored));},{identity:ctx.user_id});
 await page.route('**/rest/v1/profiles*',r=>r.fulfill({json:{id:ctx.user_id,display_name:ctx.can_manage?'Alex Mentor (demo)':'Alex Student (demo)',role,active:true}}));
 await page.route('**/rest/v1/rpc/notification_center',r=>r.fulfill({json:{unread:0,attention:[],items:[],has_more:false}}));
 await page.route('**/rest/v1/rpc/outreach_context',r=>{reads.push(r.request().url());return r.fulfill(denied?{status:403,json:{code:'42501',message:'Denied'}}:broken?{status:404,json:{code:'PGRST202',message:'Function absent'}}:{json:ctx});});
 await page.route('**/rest/v1/rpc/outreach_save',r=>{
  const body=r.request().postDataJSON();writes.push(body);const base={version:body.p.version+1,created_at:'2026-10-06T12:00:00Z',updated_at:'2026-10-06T12:00:00Z',created_by:ctx.user_id};
  if(body.entity==='prospect'){
   const p=body.p;ctx.organizations.push({...base,id:p.id,kind:p.kind,name:p.name,website:p.website,notes:null,notes_redacted:true,active:true,can_edit:true,can_add_contact:true,can_create_engagement:false});
   ctx.engagements.push({...base,id:p.engagement_id,organization_id:p.id,season_id:p.season_id,stage:'prospect',owner_id:ctx.user_id,next_follow_up_on:p.next_follow_up_on,notes:null,notes_redacted:true,can_edit:true,can_log:true,can_assign:false});
   return r.fulfill({json:{id:p.id,version:1}});
  }
  const list=({organization:'organizations',contact:'contacts',engagement:'engagements',conversation:'conversations',pledge:'pledges',recognition:'recognition'} as Record<string,keyof OutreachContext>)[body.entity],rows=ctx[list] as any[],index=rows.findIndex(row=>row.id===body.p.id);
  const record={...(index>=0?rows[index]:{}),...body.p,...base};
  if(['organization','contact','engagement'].includes(body.entity)){record.notes_redacted=!ctx.can_manage;record.notes=ctx.can_manage?(body.p.notes||''):null;record.can_edit=true;}
  if(['organization','contact'].includes(body.entity))record.active=true;
  if(body.entity==='organization'){record.can_add_contact=true;record.can_create_engagement=true;}
  if(body.entity==='engagement'){record.owner_id=ctx.can_manage?body.p.owner_id:ctx.user_id;record.can_log=true;record.can_assign=ctx.can_manage;}
  if(body.entity==='conversation'){record.summary_redacted=false;record.can_edit=false;record.author_name=ctx.owners.find(o=>o.id===ctx.user_id)?.name||'Demo team member';}
  if(index<0)rows.push(record);else rows[index]=record;return r.fulfill({json:{id:record.id,version:record.version}});
 });
 return {ctx,writes,reads};
}
async function expectReadableProfileHeading(page:Page,width:number) {
 if(width>900)return;
 const layout=await page.locator('.outreach-profile-heading').evaluate(element=>{const header=element.getBoundingClientRect(),title=element.querySelector(':scope > div')!.getBoundingClientRect(),edit=element.querySelector(':scope > button')!.getBoundingClientRect();return {headerWidth:header.width,titleWidth:title.width,titleBottom:title.bottom,editTop:edit.top};});
 expect(layout.titleWidth).toBeGreaterThanOrEqual(layout.headerWidth*.75);
 expect(layout.editTop).toBeGreaterThanOrEqual(layout.titleBottom);
}
async function expectReadableInKindHeading(page:Page,width:number) {
 if(width>900)return;
 const layout=await page.locator('.outreach-pledge[data-kind=in_kind] .outreach-item-heading').evaluate(element=>{const header=element.getBoundingClientRect(),description=element.querySelector(':scope > div')!.getBoundingClientRect(),status=element.querySelector(':scope > .outreach-pill')!.getBoundingClientRect(),edit=element.querySelector(':scope > button')!.getBoundingClientRect();return {headerWidth:header.width,descriptionWidth:description.width,descriptionBottom:description.bottom,statusTop:status.top,editTop:edit.top,overflows:element.scrollWidth>element.clientWidth};});
 expect(layout.descriptionWidth).toBeGreaterThanOrEqual(layout.headerWidth*.95);
 expect(layout.statusTop).toBeGreaterThanOrEqual(layout.descriptionBottom);
 expect(layout.editTop).toBeGreaterThanOrEqual(layout.descriptionBottom);
 expect(layout.overflows).toBe(false);
}
for(const width of [390,768,1440])test(`synthetic outreach portfolio and profile work at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:1000});await setup(page);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/#outreach');await expect(page.getByRole('heading',{name:'Sponsor & Outreach',exact:true})).toBeVisible();await expect(page.getByText('8 profiles',{exact:true})).toBeVisible();await expect(page.getByText('$2,000.00 linked funds received')).toBeVisible();
 expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await page.screenshot({path:`test-results/outreach-review/portfolio-${width}.png`,fullPage:true});
 await page.getByRole('searchbox',{name:'Search sponsors or contacts'}).fill('Jamie');await expect(page.locator('.outreach-directory-row')).toHaveCount(1);await page.locator('.outreach-directory-row').click();await expect(page.getByRole('heading',{name:'Cedarline Fabrication (demo)',exact:true})).toBeVisible();await expect(page.getByText('Jamie Example',{exact:true})).toBeVisible();await expectReadableProfileHeading(page,width);expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await page.screenshot({path:`test-results/outreach-review/profile-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Commitments & recognition',exact:true}).click();await expect(page.getByText('$2,000.00 linked funds received')).toBeVisible();await expect(page.getByText('DEMO-INCOME-002',{exact:false})).toBeVisible();await expect(page.getByText('Fulfilled Oct 3, 2026')).toBeVisible();await expectReadableInKindHeading(page,width);expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await page.screenshot({path:`test-results/outreach-review/commitments-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Add promise',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByLabel('What was promised?')).toBeVisible();await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});const modalCapture=await page.screenshot({path:`test-results/outreach-review/editor-${width}.png`,fullPage:false,scale:'css'});expect(modalCapture.readUInt32BE(16)).toBe(width);expect(modalCapture.readUInt32BE(20)).toBe(1000);await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(errors).toEqual([]);
});
test('eligible navigation exposes outreach, while readonly direct routes and absent backend fail closed',async({page})=>{
 await setup(page,{role:'readonly',denied:true});await page.goto('/#outreach');await expect(page.getByRole('heading',{name:'Workspace unavailable'})).toBeVisible();await expect(page.getByText('Cedarline Fabrication (demo)',{exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Sponsor & Outreach',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Add sponsor',exact:true})).toHaveCount(0);
 await setup(page,{broken:true});await page.reload();await expect(page.getByText('Sponsor & Outreach is not available on this connection yet.')).toBeVisible();await expect(page.getByRole('button',{name:'Add sponsor',exact:true})).toHaveCount(0);
});
test('contact and conversation edits preserve private actor, append history and never send communications',async({page})=>{
 const {writes}=await setup(page);await page.goto(`/#outreach/${id(100)}`);await page.getByRole('button',{name:'Add contact',exact:true}).click();await page.getByLabel('Contact name',{exact:true}).fill('New Demo Contact');await page.getByLabel('Email',{exact:true}).fill('new@example.invalid');await page.getByRole('button',{name:'Save record',exact:true}).dblclick();await expect(page.getByText('New Demo Contact',{exact:true})).toBeVisible();expect(writes).toHaveLength(1);expect(writes[0].expected_actor).toBe(actor);
 await page.getByRole('button',{name:'Conversations (2)',exact:true}).click();await page.getByRole('button',{name:'Log conversation',exact:true}).click();await page.getByLabel('Conversation summary').fill('Synthetic follow-up note, no external message sent.');await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByRole('button',{name:'Conversations (3)',exact:true})).toBeVisible();expect(writes).toHaveLength(2);expect(writes[1].entity).toBe('conversation');expect(writes[1].request_id).not.toBe(writes[0].request_id);
});
test('restricted Finance capability hides income details and receipt-link action',async({page})=>{
 await setup(page,{finance:false});await page.goto(`/#outreach/${id(100)}`);await page.getByRole('button',{name:'Commitments & recognition',exact:true}).click();await expect(page.getByText('Finance receipt details restricted')).toBeVisible();await expect(page.getByRole('button',{name:'Link income record'})).toHaveCount(0);await expect(page.getByText('DEMO-INCOME',{exact:false})).toHaveCount(0);await expect(page.getByText('Fulfilled Oct 3, 2026')).toBeVisible();
});
test('uncertain saves survive close, route changes and reload; not_found never enables a replacement save',async({page})=>{
 const {writes}=await setup(page);let requestId='';await page.route('**/rest/v1/rpc/outreach_save',async r=>{const body=r.request().postDataJSON();writes.push(body);requestId=body.request_id;await r.abort('failed');});
 await page.route('**/rest/v1/rpc/outreach_request_status',r=>r.fulfill({json:{status:'not_found'}}));
 await page.route('**/rest/v1/rpc/outreach_cancel_request',r=>{expect(r.request().postDataJSON()).toEqual({request_id:requestId,expected_actor:actor});return r.fulfill({json:{status:'canceled'}});});
 await page.goto('/#outreach');await page.getByRole('button',{name:'Add sponsor',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Private Synthetic Draft');await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByText('We could not confirm whether this change saved. Check its status before entering it again.')).toBeVisible();await page.getByRole('button',{name:'Close and review',exact:true}).click();await expect(page.getByText('A previous save needs checking')).toBeVisible();
 const persisted=await page.evaluate(()=>sessionStorage.getItem('4418-outreach-pending-v1'));expect(persisted).not.toContain('Private Synthetic Draft');expect(persisted).toContain(requestId);
 await page.locator('.outreach-directory-row').first().click();await expect(page.getByText('A previous save needs checking')).toBeVisible();await page.reload();await expect(page.getByText('A previous save needs checking')).toBeVisible();await page.getByRole('button',{name:'Check previous save',exact:true}).click();await expect(page.getByText('No completed save was found yet.',{exact:false})).toBeVisible();expect(writes).toHaveLength(1);
 await page.getByRole('button',{name:'Cancel unconfirmed change',exact:true}).click();await expect(page.getByText('A previous save needs checking')).toHaveCount(0);await page.getByRole('button',{name:'Edit profile',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();expect(writes).toHaveLength(1);
});
test('leaving or canceling an in-flight editor prevents a late save from opening or closing a newer view',async({page})=>{
 await setup(page);let finish!:()=>void,seen!:()=>void;const started=new Promise<void>(resolve=>seen=resolve);await page.route('**/rest/v1/rpc/outreach_save',async r=>{const body=r.request().postDataJSON();seen();await new Promise<void>(resolve=>finish=resolve);await r.fulfill({json:{id:body.p.id,version:body.p.version+1}}).catch(()=>{});});
 await page.goto(`/#outreach/${id(100)}`);await page.getByRole('button',{name:'Edit profile',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Late Demo Name');await page.getByRole('button',{name:'Save record',exact:true}).click();await started;await page.getByRole('button',{name:'Close form',exact:true}).click();await page.getByRole('link',{name:'All sponsors',exact:true}).click();finish();await expect(page.getByRole('heading',{name:'Sponsor relationships',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByText('Late Demo Name',{exact:true})).toHaveCount(0);
});
test('sign-in preserves only valid outreach deep links and malformed paths never reveal a profile',async({page})=>{
 await page.route('https://**',r=>r.abort());await page.route('**/rest/v1/**',r=>r.fulfill({json:new URL(r.request().url()).pathname.endsWith('/profiles')?{display_name:'Alex Mentor (demo)',role:'mentor',active:true}:{unread:0,attention:[],items:[],has_more:false}}));await page.route('**/rest/v1/rpc/outreach_context',r=>r.fulfill({json:outreachFixture()}));await page.route('**/auth/v1/token?grant_type=password',r=>r.fulfill({json:{access_token:'fixture-token',refresh_token:'fixture-refresh',expires_at:4000000000,expires_in:3600,token_type:'bearer',user:{id:actor,aud:'authenticated',app_metadata:{},user_metadata:{}}}}));
 await page.goto(`/#outreach/${id(100)}`);await expect(page.getByRole('heading',{name:'Team sign in',exact:true})).toBeVisible();await page.getByLabel('Email',{exact:true}).fill('demo@example.invalid');await page.getByLabel('Password',{exact:true}).fill('fixture-only-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Cedarline Fabrication (demo)',exact:true})).toBeVisible();expect(page.url()).toContain(`#outreach/${id(100)}`);
 await page.goto(`/#outreach/${id(100)}/extra`);await expect(page.getByRole('heading',{name:'Outreach profile not found'})).toBeVisible();await expect(page.getByText('Jamie Example',{exact:true})).toHaveCount(0);
});
for(const width of [390,768,1440])test(`student shared contacts and manual log views at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:1000});await setup(page,{role:'student'});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#outreach');
 await expect(page.getByRole('button',{name:'Add prospect',exact:true})).toBeVisible();await expect(page.locator('.outreach-workspace')).not.toContainText(/Cash pledged|Promises to fulfill|\$0|DEMO-INCOME/);await expect(page.getByText('8 profiles',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await page.screenshot({path:`test-results/outreach-review/student-portfolio-${width}.png`,fullPage:true});
 await page.locator(`.outreach-directory-row[href="#outreach/${id(100)}"]`).click();await expect(page.getByText('Jamie Example',{exact:true})).toBeVisible();await expect(page.getByText('jamie@sponsor.example.invalid',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Log sent email',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Edit profile',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Commitments & recognition',exact:true})).toHaveCount(0);await expect(page.locator('.outreach-workspace')).not.toContainText(/local manufacturing supporter|Synthetic secondary contact|DEMO-INCOME/);
 await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await page.screenshot({path:`test-results/outreach-review/student-profile-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Conversations (2)',exact:true}).click();await expect(page.getByText('Manually recorded by Alex Mentor (demo)',{exact:true})).toBeVisible();await expect(page.getByText('Conversation details are visible only to the author, mentors, and admins.',{exact:true})).toBeVisible();await expect(page.getByText('Synthetic student email: shared the team introduction and asked for the right contact.',{exact:true})).toBeVisible();await expect(page.locator('.outreach-workspace')).not.toContainText('Engineering liaison asked for project milestones');
 expect(await page.evaluate(()=>document.body.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(async()=>{window.scrollTo(0,0);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});await page.screenshot({path:`test-results/outreach-review/student-history-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Log sent email',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByText('This form does not send an email.',{exact:false})).toBeVisible();await expect(page.getByLabel('Relationship owner')).toHaveCount(0);await expect(page.getByLabel('Profile notes')).toHaveCount(0);const capture=await page.screenshot({path:`test-results/outreach-review/student-editor-${width}.png`,fullPage:false,scale:'css'});expect(capture.readUInt32BE(16)).toBe(width);expect(capture.readUInt32BE(20)).toBe(1000);await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(errors).toEqual([]);
});
test('student creates a self-owned prospect, adds a shared contact, then manually records an email already sent',async({page})=>{
 const {ctx,writes}=await setup(page,{role:'student'});await page.goto('/#outreach');await page.getByRole('button',{name:'Add prospect',exact:true}).click();await expect(page.getByLabel('Profile type',{exact:true})).toHaveAccessibleName('Profile type');await page.getByLabel('Name',{exact:true}).fill('New student prospect (demo)');await expect(page.getByLabel('Website',{exact:true})).toHaveAccessibleName('Website');await expect(page.getByLabel('Website',{exact:true})).toHaveAccessibleDescription('Use a public HTTPS website.');await page.getByLabel('Website',{exact:true}).fill('https://new-prospect.example.invalid');await expect(page.getByLabel('Profile notes')).toHaveCount(0);await expect(page.getByLabel('Relationship owner')).toHaveCount(0);await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByRole('heading',{name:'New student prospect (demo)',exact:true})).toBeVisible();
 expect(writes).toHaveLength(1);const prospect=writes[0];expect(prospect.entity).toBe('prospect');expect(prospect.expected_actor).toBe(student);expect(ctx.engagements.find(e=>e.organization_id===prospect.p.id)?.owner_id).toBe(student);for(const key of ['notes','owner_id','created_by','active'])expect(prospect.p).not.toHaveProperty(key);
 await page.getByRole('button',{name:'Add contact',exact:true}).click();await page.getByLabel('Contact name',{exact:true}).fill('Demo Business Contact');await page.getByLabel('Email',{exact:true}).fill('business@example.invalid');await expect(page.getByLabel('Contact notes')).toHaveCount(0);await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByText('business@example.invalid',{exact:true})).toBeVisible();expect(writes[1].entity).toBe('contact');expect(writes[1].p).not.toHaveProperty('notes');expect(writes[1].p).not.toHaveProperty('active');
 await page.getByRole('button',{name:'Log sent email',exact:true}).click();await expect(page.getByLabel('Contact',{exact:true})).toHaveAccessibleName('Contact');await page.getByLabel('Contact',{exact:true}).selectOption(writes[1].p.id);await page.getByLabel('Conversation summary').fill('Synthetic manual log: I sent the introduction email outside this workspace.');await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByText('Synthetic manual log: I sent the introduction email outside this workspace.',{exact:true})).toBeVisible();expect(writes.map(row=>row.entity)).toEqual(['prospect','contact','conversation']);expect(writes[2].p.channel).toBe('email');expect(writes[2].expected_actor).toBe(student);expect(new Set(writes.map(row=>row.request_id)).size).toBe(3);
});
test('student and lead navigation exposes outreach but unassigned contacts remain read-only',async({page})=>{
 await setup(page,{role:'lead'});await page.goto(`/#outreach/${id(104)}`);await expect(page.getByRole('link',{name:'Sponsor & Outreach',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Team Management',exact:true})).toHaveCount(0);await expect(page.getByText('Shared contact profile',{exact:true})).toBeVisible();await expect(page.getByText('contact-4@sponsor.example.invalid',{exact:true})).toBeVisible();for(const name of ['Edit profile','Add contact','Edit next steps','Log sent email','Commitments & recognition'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
});
test('student assignment loss closes the stale editor and replaces its controls with refreshed read-only state',async({page})=>{
 const {ctx,writes}=await setup(page,{role:'student'});await page.route('**/rest/v1/rpc/outreach_save',r=>{writes.push(r.request().postDataJSON());ctx.engagements[0]={...ctx.engagements[0],owner_id:id(4),can_edit:false,can_log:false};ctx.organizations[0].can_add_contact=false;return r.fulfill({status:403,json:{code:'42501',message:'Assignment changed'}});});
 await page.goto(`/#outreach/${id(100)}`);await page.getByRole('button',{name:'Log sent email',exact:true}).click();await page.getByLabel('Conversation summary').fill('Synthetic unsaved log after reassignment.');await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByText('Your assignment or access changed.',{exact:false})).toBeVisible();await expect(page.getByText('Shared contact profile',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Log sent email',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Edit next steps',exact:true})).toHaveCount(0);await expect(page.locator('.outreach-workspace')).not.toContainText('Synthetic unsaved log after reassignment.');expect(writes).toHaveLength(1);
});
test('student edits preserve hidden fields and do not expose assignment or commitment controls',async({page})=>{
 const {writes}=await setup(page,{role:'student'});await page.goto(`/#outreach/${id(101)}`);await page.getByRole('button',{name:'Edit profile',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Owned sponsor updated (demo)');await expect(page.getByLabel('Profile notes')).toHaveCount(0);await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByRole('heading',{name:'Owned sponsor updated (demo)',exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit next steps',exact:true}).click();await expect(page.getByLabel('Relationship owner')).toHaveCount(0);await expect(page.getByLabel('Season notes')).toHaveCount(0);await expect(page.getByRole('option',{name:'Committed',exact:true})).toHaveCount(0);await page.getByLabel('Relationship stage').selectOption('contacted');await page.getByRole('button',{name:'Save record',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(writes).toHaveLength(2);for(const row of writes)for(const key of ['notes','owner_id','active','created_by'])expect(row.p).not.toHaveProperty(key);
});
test('student malformed private projection fails closed instead of leaking a mentor note',async({page})=>{
 const {ctx}=await setup(page,{role:'student'});ctx.organizations[0].notes='Private mentor sentinel must never render';await page.goto('/#outreach');await expect(page.getByRole('heading',{name:'Workspace unavailable',exact:true})).toBeVisible();await expect(page.locator('.outreach-workspace')).not.toContainText('Private mentor sentinel');await expect(page.getByRole('button',{name:'Add prospect',exact:true})).toHaveCount(0);
});
