import {test,expect,type Page} from '@playwright/test';
import {session} from './hub-session';
import {validateDefinition,validateUpdate} from '../src/planning/goals/model';
import {actor,goalId,goalsFixture,seasonId} from './fixtures/season-goals';
import type {GoalOperationReceipt,GoalsContext,GoalSavePayload,GoalUpdatePayload} from '../src/planning/goals/types';

async function setup(page:Page,adjust?:(context:GoalsContext)=>void){
 const external:string[]=[],mutations:{name:string;body:any}[]=[],receipts=new Map<string,GoalOperationReceipt>();
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(['127.0.0.1','localhost'].includes(url.hostname))return route.continue();external.push(url.origin+url.pathname);return route.abort('blockedbyclient');});
 await session(page);await page.clock.install({time:new Date('2026-10-06T12:00:00Z')});
 const context=goalsFixture();adjust?.(context);
 const planning=()=>({user_id:context.user_id,can_manage:context.capabilities.can_manage,season_id:context.season_id,seasons:[{...context.season,start_date:'2026-09-01',end_date:'2027-04-30',version:1}],members:context.members,areas:[],groups:[],boards:[{id:goalId(11),season_id:seasonId,name:'Robot practice',description:'',kind:'project',area_id:null,active:true,display_order:0,version:1}],items:context.milestones.map(m=>({...m,season_id:seasonId,description:'',kind:'milestone',end_date:m.start_date,group_id:null,board_id:goalId(11),owner_id:actor,area_id:null,predecessor_id:null,display_order:0,version:1})),tasks:context.tasks.filter(t=>t.available).map(t=>({...t,description:'Existing Planning task',priority:'normal',owners:context.members.filter(m=>t.owner_ids.includes(m.id)),area_id:null,start_date:null,due_date:null,blocked_reason:'',version:1}))});
 await page.route('**/rpc/planning_context',r=>r.fulfill({json:planning()}));
 await page.route('**/rpc/planning_goals_context',r=>r.fulfill({json:context}));
 await page.route('**/rpc/planning_task_detail',r=>r.fulfill({json:{steps:[],comments:[],history:[]}}));
 function apply(name:string,body:any):GoalOperationReceipt{
  mutations.push({name,body});const p=body.p as GoalSavePayload&GoalUpdatePayload;if(body.expected_actor!==context.user_id)throw Error('Fixture actor mismatch');const existing=receipts.get(p.operation_id);if(existing)return existing;
  let goal=context.goals.find(g=>g.id===(name==='planning_goal_save'?p.id:p.goal_id));
  if(name==='planning_goal_save'){
   const issue=validateDefinition(p);if(issue)throw Error('Invalid fixture payload: '+issue);
   const owner=context.members.find(m=>m.id===p.owner_id)!;
   const next={...p,owner,supporters:context.members.filter(m=>p.supporter_ids.includes(m.id)),version:p.expected_version+1,created_by:actor,created_at:'2026-10-06T12:00:00Z',updated_at:'2026-10-06T12:00:00Z',capabilities:{can_edit:true,can_update:true,can_reassign:context.capabilities.can_reassign},measurement_locked:goal?.measurement_locked||false,updates:goal?.updates||[]};
   if(goal)Object.assign(goal,next);else{context.goals.push(next);goal=next;}
  }else{
   if(!goal)throw Error('Fixture goal unavailable');const issue=validateUpdate(p,'2026-10-06');if(issue)throw Error('Invalid fixture payload: '+issue);goal.version++;goal.measurement_locked=true;goal.updates.push({...p,author_id:context.user_id,author:context.members.find(m=>m.id===context.user_id)!,created_at:`2026-10-06T12:00:${String(mutations.length).padStart(2,'0')}Z`,goal_version:goal.version});
  }
  const result:GoalOperationReceipt={status:'committed',operation_id:p.operation_id,result:{goal_id:goal!.id,version:goal!.version,update_id:name==='planning_goal_update'?p.id:null}};receipts.set(p.operation_id,result);return result;
 }
 for(const name of ['planning_goal_save','planning_goal_update'])await page.route(`**/rpc/${name}`,r=>r.fulfill({json:apply(name,r.request().postDataJSON())}));
 await page.route('**/rpc/planning_goal_operation_status',r=>{const body=r.request().postDataJSON();return r.fulfill({json:receipts.get(body.operation_id)||{status:'not_found',operation_id:body.operation_id,result:null}});});
 await page.route('**/rpc/planning_goal_operation_cancel',r=>{const body=r.request().postDataJSON();const receipt=receipts.get(body.operation_id)||{status:'cancelled' as const,operation_id:body.operation_id,result:null};receipts.set(body.operation_id,receipt);return r.fulfill({json:receipt});});
 return {context,mutations,external,apply,receipts};
}
async function checkFilterLayout(page:Page){
 const checkbox=page.getByRole('checkbox',{name:'My goals',exact:true});
 const geometry=await checkbox.evaluate(input=>{const box=input.getBoundingClientRect(),label=input.closest('label')!.querySelector('span')!.getBoundingClientRect();return {width:box.width,height:box.height,gap:label.left-box.right,alignment:Math.abs(label.top+label.height/2-box.top-box.height/2)};});
 expect(geometry.width).toBeGreaterThanOrEqual(17);expect(geometry.width).toBeLessThanOrEqual(20);expect(geometry.height).toBeGreaterThanOrEqual(17);expect(geometry.height).toBeLessThanOrEqual(20);expect(geometry.gap).toBeGreaterThanOrEqual(6);expect(geometry.gap).toBeLessThanOrEqual(12);expect(geometry.alignment).toBeLessThanOrEqual(2);
 for(const name of ['Category','Status']){const control=page.getByRole('combobox',{name,exact:true});const available=await control.evaluate(element=>{const select=element as HTMLSelectElement,style=getComputedStyle(select),context=document.createElement('canvas').getContext('2d')!;context.font=style.font;const widest=Math.max(...Array.from(select.options,option=>context.measureText(option.textContent||'').width));return {widest,inner:select.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)};});expect(available.inner).toBeGreaterThanOrEqual(available.widest-1);}
}
async function updateDraft(page:Page){await page.getByRole('button',{name:'Weekly update',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('spinbutton',{name:'Measured value',exact:true})).toHaveAccessibleDescription('seconds');await dialog.getByLabel('Measured value',{exact:true}).fill('22');await dialog.getByLabel('Observed on').fill('2026-10-05');await dialog.getByLabel('Evidence',{exact:true}).fill('Median 22 seconds across 12 timed runs.');await dialog.getByLabel('Next step',{exact:true}).fill('Repeat with defense at the next practice.');return dialog;}

for(const width of [390,768,1440])test(`Season Goals list, detail and weekly dialog render in StrictMode at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:980});const state=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#planning/goals');await expect(page.getByRole('heading',{name:'Season Goals',exact:true})).toBeVisible();await expect(page.getByRole('list',{name:'Season goals'})).toBeVisible();await expect(page.getByRole('link',{name:'Run a reliable 18-second cycle'})).toBeVisible();await checkFilterLayout(page);await page.evaluate(()=>window.scrollTo({top:0,left:0,behavior:'instant'}));await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(0);await page.screenshot({path:`test-results/season-goals-review/goals-list-${width}.png`,fullPage:true});
 await page.getByRole('link',{name:'Run a reliable 18-second cycle'}).click();await expect(page.getByRole('heading',{name:'Run a reliable 18-second cycle',exact:true})).toBeVisible();await expect(page.getByText('Lower is better',{exact:true})).toBeVisible();await expect(page.getByText('Median of 10 timed runs was 24 seconds; two pickups needed a retry.')).toBeVisible();await page.evaluate(()=>window.scrollTo({top:0,left:0,behavior:'instant'}));await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(0);await page.screenshot({path:`test-results/season-goals-review/goal-detail-${width}.png`,fullPage:true});
 await updateDraft(page);await page.getByRole('dialog').evaluate(dialog=>dialog.scrollTo({top:0,left:0,behavior:'instant'}));await page.screenshot({path:`test-results/season-goals-review/weekly-update-${width}.png`,fullPage:false});await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);expect(state.mutations).toEqual([]);expect(state.external.every(url=>url.includes('fonts.googleapis.com')||url.includes('fonts.gstatic.com'))).toBe(true);
});
test('student creates an owned goal with existing support and links, without modifying Planning records',async({page})=>{
 const {mutations}=await setup(page);await page.goto('/#planning/goals');await page.getByRole('button',{name:'Create goal',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Student owner')).toBeDisabled();await dialog.getByLabel('Goal title').fill('Train three backup pit leads');await expect(dialog.getByRole('combobox',{name:'Category',exact:true})).toBeVisible();await dialog.getByLabel('Category',{exact:true}).selectOption('team_growth');await dialog.getByLabel('Baseline',{exact:true}).fill('0');await dialog.getByLabel('Target',{exact:true}).fill('3');await dialog.getByLabel('Unit',{exact:true}).fill('students');await dialog.getByLabel('Deadline',{exact:true}).fill('2027-03-01');await dialog.getByLabel('Next milestone').selectOption(goalId(40));await dialog.getByText('Support team and linked work',{exact:true}).click();await dialog.getByRole('checkbox',{name:'Sam Teammate'}).check();await dialog.getByRole('checkbox',{name:'Tune the pickup approach'}).check();await dialog.getByRole('button',{name:'Save goal',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('link',{name:'Train three backup pit leads'})).toBeVisible();expect(mutations).toHaveLength(1);expect(mutations[0].name).toBe('planning_goal_save');expect(mutations[0].body.p.owner_id).toBe(actor);expect(mutations[0].body.p.task_ids).toEqual([goalId(30)]);expect(mutations[0].body.p.supporter_ids).toEqual([goalId(2)]);
});
test('choosing a next milestone adds its link and removing that link clears the next milestone',async({page})=>{
 const {mutations}=await setup(page);await page.goto('/#planning/goals');await page.getByRole('button',{name:'Create goal',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Goal title').fill('Maintain a tested emergency kit');await dialog.getByLabel('Baseline',{exact:true}).fill('1');await dialog.getByLabel('Target',{exact:true}).fill('1');await dialog.getByLabel('Direction').selectOption('equal');await dialog.getByLabel('Unit',{exact:true}).fill('tested kit');await dialog.getByLabel('Deadline',{exact:true}).fill('2027-03-01');await dialog.getByLabel('Next milestone').selectOption(goalId(40));await dialog.getByText('Support team and linked work',{exact:true}).click();const linked=dialog.getByRole('checkbox',{name:'First full practice match'});await expect(linked).toBeChecked();await linked.uncheck();await expect(dialog.getByLabel('Next milestone')).toHaveValue('');await dialog.getByLabel('Next milestone').selectOption(goalId(40));await dialog.getByRole('button',{name:'Save goal',exact:true}).click();await expect(dialog).toHaveCount(0);expect(mutations[0].body.p.next_milestone_id).toBe(goalId(40));expect(mutations[0].body.p.milestone_ids).toEqual([goalId(40)]);
});
test('weekly measurement keeps prior evidence and reported status; note-only updates preserve the measured value',async({page})=>{
 const state=await setup(page);await page.goto(`/#planning/goals/${goalId(20)}`);const dialog=await updateDraft(page);await dialog.getByLabel('Reported status').selectOption('at_risk');await dialog.getByRole('button',{name:'Save update',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByText('Median 22 seconds across 12 timed runs.',{exact:true})).toBeVisible();await expect(page.getByText('Median of 10 timed runs was 24 seconds; two pickups needed a retry.')).toBeVisible();
 await page.getByRole('button',{name:'Weekly update',exact:true}).click();const note=page.getByRole('dialog');await note.getByLabel('Update type').selectOption('weekly');await expect(note.getByLabel('Measured value',{exact:true})).toHaveCount(0);await note.getByLabel('Reported status').selectOption('blocked');await note.getByLabel('Evidence',{exact:true}).fill('Practice paused while a replacement wheel arrives.');await note.getByLabel('Next step',{exact:true}).fill('Fit the wheel and repeat the test.');await note.getByRole('button',{name:'Save update',exact:true}).click();await expect(note).toHaveCount(0);expect(state.context.goals[0].updates).toHaveLength(3);expect(state.mutations[1].body.p.measured_value).toBeNull();await expect(page.locator('.goal-measure.is-detail')).toContainText('22');await expect(page.locator('.goal-detail-heading .goal-status')).toHaveText('Blocked');
});
test('capabilities separately gate student definition, supporter evidence and read-only access',async({page})=>{
 const {context,mutations}=await setup(page,c=>{c.capabilities.can_create=false;c.goals[0].capabilities={can_edit:false,can_update:true,can_reassign:false};});await page.goto(`/#planning/goals/${goalId(20)}`);await expect(page.getByRole('button',{name:'Edit goal',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Weekly update',exact:true})).toBeVisible();context.goals[0].capabilities.can_update=false;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('button',{name:'Weekly update',exact:true})).toHaveCount(0);await page.getByRole('link',{name:'All goals',exact:true}).click();await expect(page.getByRole('button',{name:'Create goal',exact:true})).toHaveCount(0);expect(mutations).toHaveLength(0);
});
test('double submit sends one update and unknown outcomes reconcile without resending it',async({page})=>{
 const state=await setup(page);await page.route('**/rpc/planning_goal_update',async r=>{state.apply('planning_goal_update',r.request().postDataJSON());await r.abort('failed');});await page.goto(`/#planning/goals/${goalId(20)}`);const dialog=await updateDraft(page);await dialog.locator('form').evaluate(form=>{(form as HTMLFormElement).requestSubmit();(form as HTMLFormElement).requestSubmit();});await expect(dialog).toHaveCount(0);await expect(page.getByRole('region',{name:'Pending goal save'})).toBeVisible();await expect(page.getByRole('button',{name:'Weekly update',exact:true})).toBeDisabled();expect(state.mutations).toHaveLength(1);await page.getByRole('button',{name:'Check save status',exact:true}).click();await expect(page.getByRole('region',{name:'Pending goal save'})).toHaveCount(0);await expect(page.getByText('Median 22 seconds across 12 timed runs.',{exact:true})).toBeVisible();expect(state.mutations).toHaveLength(1);
});
test('not-found status preserves the receipt until explicit cancellation defeats a delayed write',async({page})=>{
 const state=await setup(page);let release!:()=>void,started=false;const held=new Promise<void>(resolve=>release=resolve);await page.route('**/rpc/planning_goal_update',async r=>{started=true;const body=r.request().postDataJSON();await held;await r.fulfill({json:state.apply('planning_goal_update',body)}).catch(()=>{});});await page.goto(`/#planning/goals/${goalId(20)}`);const dialog=await updateDraft(page);await dialog.getByRole('button',{name:'Save update',exact:true}).click();await expect.poll(()=>started).toBe(true);await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Check save status',exact:true}).click();await expect(page.getByText('This save has not appeared yet.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Weekly update',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Cancel pending save',exact:true}).click();await expect(page.getByRole('region',{name:'Pending goal save'})).toHaveCount(0);release();await expect.poll(()=>state.mutations.length).toBe(1);expect(state.context.goals[0].updates).toHaveLength(1);
});
test('Back and a different goal clear drafts and ignore late mutation results',async({page})=>{
 const state=await setup(page);let release!:()=>void,started=false;const held=new Promise<void>(resolve=>release=resolve);await page.route('**/rpc/planning_goal_update',async r=>{started=true;const body=r.request().postDataJSON();await held;await r.fulfill({json:state.apply('planning_goal_update',body)}).catch(()=>{});});await page.goto('/#planning/goals');await page.getByRole('link',{name:'Run a reliable 18-second cycle'}).click();const dialog=await updateDraft(page);await dialog.getByRole('button',{name:'Save update',exact:true}).click();await expect.poll(()=>started).toBe(true);await page.goBack();await expect(dialog).toHaveCount(0);await page.getByRole('link',{name:'Receive $12,000 for the season'}).click();await expect(page.getByRole('heading',{name:'Receive $12,000 for the season',exact:true})).toBeVisible();release();await expect.poll(()=>state.mutations.length).toBe(1);await expect(page).toHaveURL(new RegExp(`${goalId(21)}$`));await expect(page.getByRole('heading',{name:'Receive $12,000 for the season',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByText('Median 22 seconds across 12 timed runs.',{exact:true})).toHaveCount(0);
});
test('signout clears visible goal data immediately; late context responses cannot repopulate it',async({page})=>{
 await setup(page);let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);await page.route('**/rpc/planning_goals_context',async r=>{await held;await r.fulfill({json:goalsFixture()}).catch(()=>{});});await page.goto('/#planning/goals');await expect(page.getByText('Loading season goals…')).toBeVisible();await page.evaluate(()=>{localStorage.removeItem('4418-team-hub-auth');const channel=new BroadcastChannel('4418-team-hub-auth');channel.postMessage({event:'SIGNED_OUT',session:null});channel.close();});await expect(page.getByRole('heading',{name:'Team sign in',exact:true})).toBeVisible();release();await expect(page.locator('.season-goals')).toHaveCount(0);await expect(page.getByText('Run a reliable 18-second cycle',{exact:true})).toHaveCount(0);
});
test('opaque recovery remains available after the old season becomes inaccessible',async({page})=>{
 await setup(page);await page.addInitScript(({actor,seasonId,goalId,operationId,updateId})=>sessionStorage.setItem('4418-season-goal-receipts-v1',JSON.stringify([{actorId:actor,seasonId,operationId,goalId,expectedVersion:2,updateId}])),{actor,seasonId,goalId:goalId(20),operationId:goalId(60),updateId:goalId(51)});await page.route('**/rpc/planning_context',r=>r.fulfill({status:403,json:{message:'Season unavailable',code:'42501'}}));await page.goto('/#planning/goals');await expect(page.getByRole('region',{name:'Pending goal save'})).toBeVisible();await expect(page.getByText('Run a reliable 18-second cycle',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Check save status',exact:true}).click();await expect(page.getByText('This save has not appeared yet.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Cancel pending save',exact:true}).click();await expect(page.getByRole('region',{name:'Pending goal save'})).toHaveCount(0);expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('4418-season-goal-receipts-v1')||'[]'))).toEqual([]);
});
test('account changes hide drafts, old goal contents and another actor’s recovery receipts',async({page})=>{
 const state=await setup(page);await page.goto(`/#planning/goals/${goalId(20)}`);const dialog=await updateDraft(page);const nextActor=goalId(2);state.context.user_id=nextActor;state.context.goals=[];state.context.capabilities.can_create=false;state.context.eligible_owners=[];await page.evaluate(({actor,seasonId,goalId,operationId,updateId,nextActor})=>{sessionStorage.setItem('4418-season-goal-receipts-v1',JSON.stringify([{actorId:actor,seasonId,operationId,goalId,expectedVersion:2,updateId}]));const session={access_token:'other-synthetic-token',refresh_token:'fixture-refresh',expires_at:4000000000,token_type:'bearer',user:{id:nextActor,aud:'authenticated',app_metadata:{},user_metadata:{}}};localStorage.setItem('4418-team-hub-auth',JSON.stringify(session));const channel=new BroadcastChannel('4418-team-hub-auth');channel.postMessage({event:'SIGNED_IN',session});channel.close();},{actor,seasonId,goalId:goalId(20),operationId:goalId(60),updateId:goalId(51),nextActor});await expect(dialog).toHaveCount(0);await expect(page.getByText('Median 22 seconds across 12 timed runs.',{exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'Pending goal save'})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Run a reliable 18-second cycle',exact:true})).toHaveCount(0);expect(state.mutations).toHaveLength(0);
});
test('unavailable links stay readable and do not open an editor; available links keep existing task permission behavior',async({page})=>{
 await setup(page,c=>{c.goals[0].task_ids.push(goalId(33));c.tasks.push({id:goalId(33),board_id:null,title:'Unavailable task',status:'unavailable',owner_ids:[],available:false});});await page.goto(`/#planning/goals/${goalId(20)}`);await expect(page.getByText('Task unavailable',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Tune the pickup approach',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Title',{exact:true})).toHaveValue('Tune the pickup approach');await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Edit goal',exact:true}).click();await expect(page.getByRole('dialog').getByLabel('Baseline',{exact:true})).toBeDisabled();await page.getByRole('dialog').press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
});
test('malformed exact detail routes show a safe invalid link state',async({page})=>{
 const {mutations}=await setup(page);await page.goto(`/#planning/goals/${goalId(20)}/extra`);await expect(page.getByText('This goal link is invalid.',{exact:false})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);expect(mutations).toHaveLength(0);
});
