import {test,expect,type Page} from '@playwright/test';
import {session} from './hub-session';
const uid='00000000-0000-0000-0000-000000000001';
async function setup(page:Page,manager=true){
 await session(page);
 const c:any={user_id:uid,can_manage:manager,season_id:'season',seasons:[{id:'season',name:'2027 FRC Season',status:'active',version:1}],members:[{id:uid,name:'Aiden'},{id:'other',name:'Teammate'}],areas:[{id:'area',name:'Software'}],groups:[{id:'group',name:'Robot',active:true,display_order:0,version:1}],boards:[{id:'board',season_id:'season',name:'Intake',kind:'project',active:true,version:1},{id:'admin',season_id:null,name:'Admin',kind:'area',active:true,version:1}],items:[{id:'item',season_id:'season',title:'Intake CAD',kind:'work',start_date:'2027-01-05',end_date:'2027-02-15',status:'in_progress',group_id:'group',board_id:'board',version:1},{id:'milestone',season_id:'season',title:'Design freeze',kind:'milestone',start_date:'2027-02-16',end_date:'2027-02-16',status:'not_started',predecessor_id:'item',version:1}],tasks:[{id:'task',board_id:'board',title:'Cut shafts',description:'Measure first',status:'todo',priority:'high',owner_ids:[uid],owners:[{id:uid,name:'Aiden'}],area_id:'area',due_date:'2027-01-20',version:1},{id:'other-task',board_id:'board',title:'Fit bearing',status:'backlog',priority:'normal',owner_ids:['other'],owners:[{id:'other',name:'Teammate'}],version:1}]};
 const details:any={steps:[],comments:[],history:[]};const calls:any[]=[];
 const context=(mine=false)=>({...c,dependency_tasks:mine?c.tasks:[],tasks:c.tasks.filter((t:any)=>!mine||t.owner_ids?.includes(c.user_id)).map((t:any)=>({...t,owner_ids:t.owner_ids||[],owners:(t.owner_ids||[]).map((id:string)=>c.members.find((m:any)=>m.id===id)||t.owners?.find((m:any)=>m.id===id)||{id,name:'Team member'})}))});
 await page.route('**/rest/v1/rpc/planning_context',r=>r.fulfill({json:context()}));
 await page.route('**/rest/v1/rpc/planning_my_work_context',r=>r.fulfill({json:context(true)}));
 await page.route('**/rest/v1/rpc/planning_task_detail',r=>r.fulfill({json:details}));
 await page.route('**/rest/v1/rpc/planning_save',r=>{const {entity,p}=r.request().postDataJSON();calls.push({entity,p});const key=({season:'seasons',group:'groups',board:'boards',item:'items',task:'tasks',step:'steps',comment:'comments'} as any)[entity];const list=entity==='step'||entity==='comment'?details[key]:c[key];if(p.id)Object.assign(list.find((x:any)=>x.id===p.id),p,{version:(p.version||1)+1});else list.push({...p,id:'new-'+calls.length,version:1});return r.fulfill({json:p.id||'new-'+calls.length});});
 return {c,details,calls};
}
for(const width of [390,1440])test(`Planning Gantt, board, task and My Work at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});const {calls}=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/#planning/plan');await expect(page.getByRole('heading',{name:'Season Plan',exact:true})).toBeVisible();await page.getByRole('button',{name:'Gantt',exact:true}).click();await expect(page.getByRole('region',{name:/Season Gantt/})).toBeVisible();
 await page.getByRole('button',{name:'Edit Intake CAD',exact:true}).click();let d=page.getByRole('dialog');await d.getByLabel('Title',{exact:true}).fill('Intake design');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);expect(calls[0].entity).toBe('item');
 await page.getByRole('button',{name:'Edit Design freeze'}).click();d=page.getByRole('dialog');await expect(d.getByLabel('Milestone date')).toHaveValue('2027-02-16');await expect(d.getByLabel('Starts after')).toHaveValue('item');await d.getByRole('button',{name:'Close',exact:true}).click();
 await page.screenshot({path:`test-results/planning-gantt-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(width===390)await page.getByRole('button',{name:'Planning menu'}).click();await page.getByRole('navigation',{name:'Planning workspace'}).getByRole('link',{name:'Boards',exact:true}).click();await page.getByRole('button',{name:'Intake',exact:true}).click();await page.getByLabel('Status for Cut shafts').selectOption('in_progress');await expect(page.getByLabel('Status for Cut shafts')).toHaveValue('in_progress');
 await page.getByRole('button',{name:'Table'}).click();await page.getByLabel('Search tasks').fill('shafts');await expect(page.getByRole('button',{name:'Fit bearing',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Details for Cut shafts',exact:true}).click();d=page.getByRole('dialog');await chooseOwners(page,'Owners',['Teammate']);await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);
 await page.getByRole('button',{name:'Details for Cut shafts',exact:true}).click();d=page.getByRole('dialog');await d.getByLabel('New checklist step').fill('Measure twice');await d.getByRole('button',{name:'Add step'}).click();await expect(d.getByRole('checkbox',{name:'Measure twice'})).toBeVisible();await d.getByRole('checkbox',{name:'Measure twice'}).check();await d.getByLabel('Add a comment').fill('Ready for review');await d.getByRole('button',{name:'Post comment'}).click();await expect(d.getByText('Ready for review',{exact:true})).toBeVisible();await chooseOwners(page,'Owners',['Aiden']);await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);
 if(width===390)await page.getByRole('button',{name:'Planning menu'}).click();await page.getByRole('navigation',{name:'Planning workspace'}).getByRole('link',{name:'My Work'}).click();await expect(page.getByRole('heading',{name:'My Work',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Cut shafts',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Fit bearing',exact:true})).toHaveCount(0);
 await page.screenshot({path:`test-results/planning-my-work-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('normal member has assigned status fallback without project administration',async({page})=>{
 await setup(page,false);await page.goto('/#planning/boards/board');await expect(page.getByRole('button',{name:/New task/})).toHaveCount(0);await expect(page.getByLabel('Status for Fit bearing')).toBeDisabled();await page.getByLabel('Status for Cut shafts').selectOption('done');await expect(page.getByLabel('Status for Cut shafts')).toHaveValue('done');
 await page.getByRole('button',{name:'Details for Cut shafts',exact:true}).click();const d=page.getByRole('dialog');await expect(d.getByRole('button',{name:'Owners',exact:true})).toHaveCount(0);await expect(d.getByRole('button',{name:'Save',exact:true})).toBeVisible();await d.press('Escape');await expect(d).toHaveCount(0);
});
test('desktop drag uses the same status mutation as accessible selector',async({page})=>{
 await page.setViewportSize({width:1920,height:1000});const {calls}=await setup(page);await page.goto('/#planning/boards/board');await page.getByRole('button',{name:'Kanban',exact:true}).click();const task=page.locator('.planning-task').filter({has:page.getByRole('button',{name:'Cut shafts',exact:true})});const done=page.locator('.planning-column').filter({has:page.getByRole('heading',{name:'Done · 0',exact:true})});await task.dragTo(done);await expect(page.getByLabel('Status for Cut shafts')).toHaveValue('done');expect(calls.at(-1).entity).toBe('task');
});
test('draft season creation, board types and signed-out privacy',async({page})=>{
 const {c,calls}=await setup(page);c.seasons=[];c.season_id=null;await page.goto('/#planning');await page.getByRole('button',{name:'Create planning season'}).click();const d=page.getByRole('dialog');await d.getByLabel('Name',{exact:true}).fill('2028 FRC Season');await expect(d.getByLabel('Season status')).toHaveValue('draft');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);expect(calls[0].p.status).toBe('draft');
 await page.evaluate(()=>{localStorage.removeItem('4418-team-hub-auth');const ch=new BroadcastChannel('4418-team-hub-auth');ch.postMessage({event:'SIGNED_OUT',session:null});ch.close();});await expect(page.getByRole('heading',{name:'Team sign in',exact:true})).toBeVisible();await expect(page.locator('.planning')).toHaveCount(0);
});

for(const timezoneId of ['America/Los_Angeles','Pacific/Auckland'])test(`Planning calendar-date round trip in ${timezoneId}`,async({browser})=>{
 const context=await browser.newContext({timezoneId});const page=await context.newPage();const {c,calls}=await setup(page);
 Object.assign(c.items[0],{start_date:'2027-03-13',end_date:'2027-03-15'});Object.assign(c.tasks[0],{start_date:'2027-03-13',due_date:'2027-03-15'});
 await page.goto('http://127.0.0.1:4422/#planning/plan');await page.getByRole('button',{name:'Gantt',exact:true}).click();
 await expect(page.getByRole('button',{name:'Edit Intake CAD',exact:true})).toHaveAttribute('title',/2027-03-13 – 2027-03-15/);
 await page.getByRole('button',{name:'Edit Intake CAD',exact:true}).click();const d=page.getByRole('dialog');
 await expect(d.getByLabel('Start date',{exact:true})).toHaveValue('2027-03-13');await expect(d.getByLabel('End date',{exact:true})).toHaveValue('2027-03-15');
 await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);
 expect(calls[0].p.start_date).toBe('2027-03-13');expect(calls[0].p.end_date).toBe('2027-03-15');
 await page.goto('http://127.0.0.1:4422/#planning/boards/board');await page.getByRole('button',{name:'Gantt',exact:true}).click();await expect(page.getByRole('button',{name:'Open Cut shafts'})).toHaveAttribute('title',/2027-03-13 → 2027-03-15/);await page.getByRole('button',{name:'Open Cut shafts'}).click();await expect(page.getByRole('dialog').getByLabel('Start date',{exact:true})).toHaveValue('2027-03-13');await expect(page.getByRole('dialog').getByLabel('Due date',{exact:true})).toHaveValue('2027-03-15');await context.close();
});

for(const width of [390,1440])test(`dedicated Planning shell and Dashboard ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.clock.install({time:new Date('2027-01-06T12:00:00')});
 const {c,calls}=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 Object.assign(c.seasons[0],{start_date:'2027-01-01',end_date:'2027-03-15'});
 c.tasks=[
 {...c.tasks[0],id:'late',title:'Overdue fabrication',due_date:'2027-01-05',status:'todo'},
 {...c.tasks[0],id:'today',title:'Integrate today',due_date:'2027-01-06',status:'in_progress'},
 {...c.tasks[0],id:'week',title:'Test this week',due_date:'2027-01-08',status:'todo'},
 {...c.tasks[0],id:'blocked',title:'Waiting on CAD',due_date:'2027-01-20',status:'blocked',owner_ids:['other'],owners:[{id:'other',name:'Teammate'}]},
 {...c.tasks[0],id:'done',title:'Complete',due_date:'2027-01-01',status:'done'}];
 c.items.push({...c.items[1],id:'old',title:'Old milestone',start_date:'2026-12-01'}, {...c.items[1],id:'complete',title:'Finished milestone',status:'done'});
 c.boards.push({id:'archived',name:'Archived board',active:false});c.tasks.push({...c.tasks[0],id:'hidden',board_id:'archived'});
 await page.goto('/#planning');await expect(page.locator('.suite-brand strong')).toHaveText('Planning');await expect(page.locator('.suite-picker summary')).toContainText('Planning');
 const dash=page.locator('.planning-dashboard');await expect(dash.getByRole('heading',{name:'Active season'})).toBeVisible();await expect(dash.getByText('2027-01-01 → 2027-03-15')).toBeVisible();
 const counts=dash.locator('.planning-counts');for(const [label,n] of [['To Do','2'],['In Progress','1'],['Blocked','1'],['Done','1']])await expect(counts.locator('div').filter({has:page.getByText(label,{exact:true})}).locator('dd')).toHaveText(n);
 await expect(dash.getByText('1 overdue · 1 blocked')).toBeVisible();await expect(dash.getByText('1 overdue · 1 due today · 1 due this week')).toBeVisible();await expect(dash.getByText('Design freeze',{exact:true})).toBeVisible();await expect(dash.getByText('Old milestone')).toHaveCount(0);await expect(dash.getByText('Finished milestone')).toHaveCount(0);
 await expect(dash.getByText('1 / 5 tasks complete')).toBeVisible();await expect(dash.getByText('Archived board')).toHaveCount(0);
 if(width===390)await page.getByRole('button',{name:'Planning menu'}).click();
 const nav=page.getByRole('navigation',{name:'Planning workspace'});await expect(nav.getByRole('link')).toHaveCount(6);await expect(nav.getByRole('link',{name:'Season Goals',exact:true})).toHaveAttribute('href','#planning/goals');await expect(nav.getByRole('link',{name:'Team Hub / Home',exact:true})).toHaveAttribute('href','#');await expect(nav.getByRole('link',{name:'Dashboard',exact:true})).toHaveAttribute('aria-current','page');await expect(page.getByRole('navigation',{name:'Hub workspace'})).toHaveCount(0);
 if(width===390)await page.keyboard.press('Escape');
 await page.locator('.suite-picker summary').click();await expect(page.getByRole('navigation',{name:'Team 4418 apps'}).getByRole('link',{name:'Planning',exact:true})).toHaveAttribute('aria-current','page');await page.keyboard.press('Escape');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/planning-dashboard-shell-${width}.png`,fullPage:true});
 await dash.getByRole('button',{name:'Intake',exact:true}).click();await expect(page.getByRole('heading',{name:'Intake',exact:true})).toBeVisible();expect(calls).toHaveLength(0);expect(errors).toEqual([]);
});
test('Planning empty Dashboard, clear attention state, and Hub Systems entry',async({page})=>{
 await page.clock.setFixedTime(new Date('2027-01-06T12:00:00Z'));const {c}=await setup(page);await page.goto('/#planning');await expect(page.getByRole('heading',{name:'Needs attention'})).toBeVisible();await expect(page.getByText('No overdue or blocked tasks',{exact:true})).toBeVisible();
 c.seasons=[];c.season_id=null;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('heading',{name:'No active planning season'})).toBeVisible();await expect(page.getByText('Create a season to build the master schedule, organize project boards, and assign work.')).toBeVisible();await expect(page.locator('.planning-dashboard')).toHaveCount(0);
 await page.goto('/#attendance');const link=page.locator('.hub-nav a[href="#planning"]');await expect(link).toBeVisible();expect(await link.evaluate(e=>e.previousElementSibling?.textContent)).toBe('Systems');await link.click();await expect(page.locator('.suite-brand strong')).toHaveText('Planning');
});

for(const width of [390,1440])test(`Planning polished surfaces ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.clock.install({time:new Date('2027-01-06T12:00:00')});
 const {c,calls}=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 c.boards[1].area_id='area';c.tasks.push({...c.tasks[0],id:'blocked-review',board_id:'admin',title:'Resolve controller issue',status:'blocked',blocked_reason:'Waiting for replacement',due_date:'2027-01-05'});
 async function capture(name:string){await page.evaluate(()=>{window.scrollTo(0,0);if(document.activeElement?.classList.contains('skip-link'))(document.activeElement as HTMLElement).blur();});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/planning-polish-${name}-${width}.png`,fullPage:true});}
 await page.goto('/#planning/plan');await page.getByRole('button',{name:'Gantt',exact:true}).click();await expect(page.getByLabel('Today',{exact:true})).toBeVisible();await capture('gantt-today');
 await page.goto('/#planning/boards');await expect(page.getByRole('heading',{name:'Projects',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Functional Areas',exact:true})).toBeVisible();await expect(page.getByText('1 blocked',{exact:true})).toBeVisible();await capture('boards');
 await page.getByRole('button',{name:'Intake',exact:true}).click();await expect(page.getByLabel('Status for Cut shafts')).toHaveValue('todo');await capture('project');
 await page.getByRole('button',{name:'Table',exact:true}).click();await expect(page.getByRole('columnheader',{name:'Priority',exact:true})).toBeVisible();await capture('list');
 await page.getByRole('button',{name:'Details for Cut shafts',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'Task',exact:true})).toBeVisible();await expect(dialog.getByRole('heading',{name:'Planning',exact:true})).toBeVisible();await expect(dialog.getByText('No comments yet. Share progress or a question here.')).toBeVisible();await capture('task');await dialog.press('Escape');await expect(page.getByRole('button',{name:'Details for Cut shafts',exact:true})).toBeFocused();
 await page.goto('/#planning/boards/admin');await page.getByRole('button',{name:'Kanban',exact:true}).click();await expect(page.getByText('Blocked: Waiting for replacement')).toBeVisible();await capture('area');
 await page.goto('/#planning/my-work');await expect(page.getByText('Overdue · 2027-01-05')).toBeVisible();await expect(page.locator('.planning-task').filter({hasText:'Resolve controller issue'}).getByText('Admin',{exact:true})).toBeVisible();await capture('work');
 c.seasons=[];c.season_id=null;await page.goto('/#planning');await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('heading',{name:'No active planning season'})).toBeVisible();await expect(page.locator('.planning-intro-grid section')).toHaveCount(3);await expect(page.locator('.planning-counts')).toHaveCount(0);await capture('onboarding');expect(calls).toHaveLength(0);expect(errors).toEqual([]);
});

for(const width of [390,1440])test(`V1.1 grouped Table and Gantt share item identity ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});const {c,calls}=await setup(page);
 await page.goto('/#planning/plan');await expect(page.getByRole('button',{name:'Table',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'+ Add group',exact:true}).click();let d=page.getByRole('dialog');await expect(d.getByLabel('Display order')).toHaveCount(0);await d.getByLabel('Name',{exact:true}).fill('Manufacturing');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);
 let group=page.locator('.planning-plan-group').filter({has:page.locator('summary').filter({hasText:'Manufacturing'})});await group.getByLabel('Actions for Manufacturing',{exact:true}).click();await group.getByRole('button',{name:'Group settings'}).click();d=page.getByRole('dialog');await d.getByLabel('Name',{exact:true}).fill('Fabrication');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);
 group=page.locator('.planning-plan-group').filter({has:page.locator('summary').filter({hasText:'Fabrication'})});await group.getByLabel('Actions for Fabrication',{exact:true}).click();await group.getByRole('button',{name:'Move to top'}).click();await expect(page.locator('.planning-plan-group').first()).toContainText('Fabrication');
 await group.getByRole('button',{name:'+ Add item',exact:true}).click();await group.getByLabel('Item title').fill('Build intake');await group.getByRole('button',{name:'Add',exact:true}).click();await expect(group.getByRole('button',{name:'Build intake',exact:true})).toBeVisible();const created=c.items.find((i:any)=>i.title==='Build intake');expect(created.group_id).toBe(c.groups.find((g:any)=>g.name==='Fabrication').id);
 await group.getByRole('button',{name:'Details for Build intake',exact:true}).click();d=page.getByRole('dialog');await d.getByLabel('Title',{exact:true}).fill('Fabricate intake');await d.getByLabel('Start date',{exact:true}).fill('2027-01-07');await d.getByLabel('End date',{exact:true}).fill('2027-01-12');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);expect(calls.at(-1).p.id).toBe(created.id);
 await page.getByRole('button',{name:'Gantt',exact:true}).click();await expect(page.locator('.planning-gantt-group').first()).toHaveText('Fabrication');await page.getByRole('button',{name:'Edit Fabricate intake',exact:true}).click();d=page.getByRole('dialog');await expect(d.getByLabel('Start date',{exact:true})).toHaveValue('2027-01-07');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);expect(calls.at(-1).p.id).toBe(created.id);expect(c.items.filter((i:any)=>i.id===created.id)).toHaveLength(1);
 await page.getByRole('button',{name:'Edit Design freeze',exact:true}).click();d=page.getByRole('dialog');await expect(d.getByLabel('Starts after')).toHaveValue('item');await expect(d.getByLabel('Milestone date')).toHaveValue('2027-02-16');await d.getByRole('button',{name:'Close',exact:true}).click();
 await page.screenshot({path:`test-results/planning-v11-gantt-${width}.png`,fullPage:true});await page.getByRole('button',{name:'+ Add milestone',exact:true}).click();d=page.getByRole('dialog');await expect(d.getByLabel('Item type')).toHaveValue('milestone');await d.press('Escape');
 await page.getByRole('button',{name:'Table',exact:true}).click();await page.screenshot({path:`test-results/planning-v11-table-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
for(const width of [390,1440])test(`V1.1 quick Tasks and shared Board views ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});const {c,calls}=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/#planning/boards/board');await page.getByRole('button',{name:'Kanban',exact:true}).click();
 for(const status of ['backlog','todo','in_progress','blocked','done']){
  const column=page.locator('.planning-column').filter({has:page.locator(`h3[data-status="${status}"]`)});
  await column.getByRole('button',{name:'+ Add task',exact:true}).click();await column.getByLabel('Task title').fill('Quick '+status);await column.getByRole('button',{name:'Add',exact:true}).click();await expect(column.getByRole('button',{name:'Quick '+status,exact:true})).toBeVisible();expect(calls.at(-1).p.status).toBe(status);expect(calls.at(-1).entity).toBe('task');
 }
 await page.getByRole('button',{name:'Table',exact:true}).click();await expect(page.getByRole('button',{name:'Quick blocked',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'+ Add task',exact:true}).click();await page.getByLabel('Task title').fill('Table task');await page.getByRole('button',{name:'Add',exact:true}).click();await expect(page.getByLabel('Status for Table task')).toHaveValue('todo');const id=c.tasks.find((t:any)=>t.title==='Table task').id;
 await chooseOwners(page,'Owners for Table task',['Aiden']);await expect(page.getByRole('button',{name:'Owners for Table task'})).toContainText('Aiden');await page.getByLabel('Priority for Table task').selectOption('high');await expect(page.getByLabel('Priority for Table task')).toHaveValue('high');await page.getByRole('button',{name:'Timeline for Table task',exact:true}).click();await page.getByLabel('End',{exact:true}).fill('2027-02-01');await page.getByRole('button',{name:'Save timeline'}).click();await expect.poll(()=>c.tasks.find((t:any)=>t.id===id).due_date).toBe('2027-02-01');
 await page.getByRole('button',{name:'Kanban',exact:true}).click();await expect(page.getByRole('button',{name:'Table task',exact:true})).toBeVisible();await page.goto('/#planning/my-work');await expect(page.getByRole('button',{name:'Table task',exact:true})).toBeVisible();await page.getByLabel('Status for Table task').selectOption('in_progress');await expect(page.getByLabel('Status for Table task')).toHaveValue('in_progress');expect(calls.at(-1).p.id).toBe(id);
 await page.goto('/#planning/boards/board');await page.getByRole('button',{name:'Kanban',exact:true}).click();await expect(page.locator('.planning-column').filter({has:page.locator('h3[data-status="in_progress"]')}).getByRole('button',{name:'Table task',exact:true})).toBeVisible();expect(c.tasks.filter((t:any)=>t.id===id)).toHaveLength(1);
 await page.getByRole('button',{name:'+ New task',exact:true}).click();const d=page.getByRole('dialog');await d.getByLabel('Title',{exact:true}).fill('Full task');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);await expect(page.getByRole('button',{name:'Full task',exact:true})).toBeVisible();await page.screenshot({path:`test-results/planning-v11-kanban-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('V1.1 simple Board creation, settings and member boundaries',async({page})=>{
 const {c,calls}=await setup(page);await page.goto('/#planning/boards');
 for(const kind of ['project','area']){
  await page.getByRole('button',{name:'Create board',exact:true}).click();const d=page.getByRole('dialog');await d.getByLabel('Name',{exact:true}).fill('New '+kind);await d.getByLabel('Board type').selectOption(kind);await expect(d.getByLabel('Board state')).toHaveCount(0);await expect(d.getByLabel('Display order')).toHaveCount(0);if(kind==='area')await d.getByRole('combobox',{name:'Functional area',exact:true}).selectOption('area');else await expect(d.getByRole('combobox',{name:'Functional area',exact:true})).toHaveCount(0);await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);expect(calls.at(-1).p.active).toBe(true);expect(typeof calls.at(-1).p.display_order).toBe('number');expect(calls.at(-1).p.season_id).toBe(kind==='area'?null:'season');
 }
 await page.getByRole('button',{name:'New area',exact:true}).click();await expect(page.getByRole('heading',{name:'New area',exact:true,level:2})).toBeVisible();await page.getByLabel('Board actions',{exact:true}).click();await page.getByRole('button',{name:'Board settings',exact:true}).click();const d=page.getByRole('dialog');await expect(d.getByLabel('Board type')).toBeDisabled();await expect(d.getByLabel('Board state')).toBeVisible();await d.press('Escape');
 c.can_manage=false;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('button',{name:/Add task|New task|Board settings/})).toHaveCount(0);await page.goto('/#planning/plan');await expect(page.getByRole('button',{name:/Add item|Add group|Add milestone|Group settings/})).toHaveCount(0);
});
test('V1.1 inline stale edit and quick-create denial surface without optimistic changes',async({page})=>{
 await setup(page);await page.route('**/rest/v1/rpc/planning_save',r=>r.fulfill({status:403,json:{message:'Planning leadership required'}}));await page.goto('/#planning/boards/board');await page.getByRole('button',{name:'Kanban',exact:true}).click();const col=page.locator('.planning-column').first();await col.getByRole('button',{name:'+ Add task',exact:true}).click();await col.getByLabel('Task title').fill('Denied task');await col.getByRole('button',{name:'Add',exact:true}).click();await expect(col.getByRole('alert')).toContainText('Planning leadership required');await expect(page.getByRole('button',{name:'Denied task',exact:true})).toHaveCount(0);await col.getByRole('button',{name:'Cancel',exact:true}).click();await expect(col.getByRole('button',{name:'+ Add task',exact:true})).toBeFocused();
 await page.route('**/rest/v1/rpc/planning_save',r=>r.fulfill({status:409,json:{message:'Changed by another teammate. Refresh before saving.'}}));await page.getByRole('button',{name:'Table',exact:true}).click();await page.getByLabel('Priority for Cut shafts').selectOption('low');await expect(page.getByRole('alert')).toContainText('Changed by another teammate');await expect(page.getByLabel('Priority for Cut shafts')).toHaveValue('high');
});
for(const width of [390,1440])test(`V1.2 direct Season editing and Board timelines/dependencies ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.clock.install({time:new Date('2027-03-14T12:00:00')});
 const {c,calls,details}=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 c.dependencies=[];Object.assign(c.tasks[1],{start_date:'2027-03-16',due_date:'2027-03-18'});
 c.tasks.push({...c.tasks[0],id:'undated',title:'Undated work',start_date:null,due_date:null},{...c.tasks[0],id:'deadline',title:'Deadline only',start_date:null,due_date:'2027-03-20'},{...c.tasks[0],id:'area-task',board_id:'admin',title:'Software work',start_date:'2027-03-13',due_date:'2027-03-15'});
 const depCalls:any[]=[];
 await page.route('**/rest/v1/rpc/planning_dependency_save',r=>{const p=r.request().postDataJSON();depCalls.push(p);if(p.action==='add')c.dependencies.push({id:'dep',board_id:'board',predecessor_task_id:p.predecessor,successor_task_id:p.successor});else c.dependencies=[];details.history.push({id:depCalls.length,entity:'dependency',action:p.action==='add'?'added':'removed',actor_id:uid,created_at:'2027-03-14T12:00:00Z',before_data:null,after_data:{}});return r.fulfill({json:'dep'});});
 await page.goto('/#planning/plan');const row=page.locator('[data-item-id="item"]');
 await row.getByRole('button',{name:'Intake CAD',exact:true}).click();await row.getByLabel('Title',{exact:true}).fill('Season design');await row.getByLabel('Title',{exact:true}).press('Enter');await expect(row.getByRole('button',{name:'Season design',exact:true})).toBeVisible();
 await row.getByLabel('Owner for Season design').selectOption(uid);await row.getByLabel('Area for Season design').selectOption('area');await row.getByLabel('Status for Season design').selectOption('blocked');await expect(row.getByLabel('Status for Season design')).toHaveValue('blocked');
 await row.getByRole('button',{name:'Timeline for Season design'}).click();await row.getByLabel('Start',{exact:true}).fill('2027-03-13');await row.getByLabel('End',{exact:true}).fill('2027-03-15');await row.getByRole('button',{name:'Save timeline'}).click();
 await row.getByLabel('Linked Board for Season design').selectOption('admin');await expect(row.getByRole('button',{name:'Admin →'})).toBeVisible();
 const group=page.locator('.planning-plan-group').first();await group.locator('details').first().locator(':scope > summary').click();await expect(row).not.toBeVisible();await group.locator('details').first().locator(':scope > summary').click();await expect(row).toBeVisible();
 await page.getByLabel('Search plan').fill('Season design');await expect(page.getByRole('button',{name:'Design freeze',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Gantt',exact:true}).click();await expect(page.getByRole('button',{name:'Edit Season design',exact:true})).toHaveAttribute('title',/2027-03-13 – 2027-03-15/);expect(c.items.filter((i:any)=>i.id==='item')).toHaveLength(1);
 await page.goto('/#planning/boards/board');await expect(page.getByRole('button',{name:'Software work',exact:true})).toHaveCount(0);
 let t=page.locator('tr[data-task-id="task"]');await t.getByRole('button',{name:'Cut shafts',exact:true}).click();await t.getByLabel('Title',{exact:true}).fill('Machine shafts');await t.getByLabel('Title',{exact:true}).press('Enter');await expect(t.getByRole('button',{name:'Machine shafts',exact:true})).toBeVisible();
 await t.getByLabel('Area for Machine shafts').selectOption('');await chooseOwners(page,'Owners for Machine shafts',['Aiden']);await t.getByLabel('Priority for Machine shafts').selectOption('urgent');await expect(t.getByLabel('Priority for Machine shafts')).toHaveValue('urgent');
 await t.getByRole('button',{name:'Timeline for Machine shafts'}).click();await t.getByLabel('Start',{exact:true}).fill('2027-03-13');await t.getByLabel('End',{exact:true}).fill('2027-03-15');await t.getByRole('button',{name:'Save timeline'}).click();
 await page.getByRole('button',{name:'Details for Fit bearing',exact:true}).click();let d=page.getByRole('dialog');await expect(d.getByRole('option',{name:'Software work',exact:true})).toHaveCount(0);await d.getByRole('combobox',{name:'Depends on',exact:true}).selectOption('task');await d.getByRole('button',{name:'Add dependency'}).click();await expect(d.getByRole('button',{name:'Remove dependency on Machine shafts'})).toBeVisible();await d.press('Escape');
 await expect(page.locator('tr[data-task-id="other-task"]')).toContainText('Waiting on 1 task');await page.getByRole('button',{name:'Kanban',exact:true}).click();await expect(page.locator('.planning-task').filter({hasText:'Fit bearing'})).toContainText('Waiting on 1 task');await expect(page.getByLabel('Status for Fit bearing')).toHaveValue('backlog');
 await page.getByRole('button',{name:'Gantt',exact:true}).click();await expect(page.getByRole('button',{name:'Open Machine shafts'})).toHaveAttribute('title',/2027-03-13 → 2027-03-15/);await expect(page.locator('[data-dependency-id="dep"]')).toHaveCount(1);await expect(page.getByLabel('Today',{exact:true})).toBeVisible();await page.getByLabel('Timeline scale').selectOption('day');
 await expect(page.locator('.planning-bar[data-task-id="deadline"]')).toHaveClass(/milestone/);expect(c.tasks.find((t:any)=>t.id==='deadline').start_date).toBeNull();await expect(page.locator('.planning-bar[data-task-id="undated"]')).toHaveCount(0);await expect(page.getByRole('button',{name:'Software work',exact:true})).toHaveCount(0);
 await page.screenshot({path:`test-results/planning-v12-board-gantt-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Open Machine shafts'}).click();d=page.getByRole('dialog');await d.getByRole('combobox',{name:'Status',exact:true}).selectOption('done');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toHaveCount(0);expect(calls.at(-1).p.id).toBe('task');
 await page.getByRole('button',{name:'Table',exact:true}).click();await expect(page.locator('tr[data-task-id="other-task"]')).toContainText('Dependencies complete');expect(c.tasks[1].status).toBe('backlog');expect(c.tasks[1].start_date).toBe('2027-03-16');expect(c.tasks[1].due_date).toBe('2027-03-18');
 await page.getByRole('button',{name:'Details for Fit bearing',exact:true}).click();d=page.getByRole('dialog');await d.getByRole('button',{name:'Remove dependency on Machine shafts'}).click();await expect(d.getByText('No dependencies.',{exact:true})).toBeVisible();await d.press('Escape');expect(c.tasks.filter((t:any)=>t.id==='task')).toHaveLength(1);
 await page.getByLabel('Search tasks').fill('Machine');await page.evaluate(()=>location.hash='planning/boards/admin');await expect(page.getByLabel('Search tasks')).toHaveValue('');await expect(page.getByRole('button',{name:'Software work',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Machine shafts',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Kanban',exact:true}).click();await expect(page.getByRole('button',{name:'Software work',exact:true})).toBeVisible();await page.getByRole('button',{name:'Gantt',exact:true}).click();await expect(page.getByRole('button',{name:'Open Software work'})).toBeVisible();await expect(page.getByRole('button',{name:'Open Machine shafts'})).toHaveCount(0);
 await page.goto('/#planning/my-work');await expect(page.getByRole('button',{name:'Software work',exact:true})).toBeVisible();expect(errors).toEqual([]);
});
test('V1.2 keyboard capture, failed inline edits, dependency errors and member controls',async({page})=>{
 const {c,calls}=await setup(page);await page.goto('/#planning/boards/board');await page.getByRole('button',{name:'+ Add task',exact:true}).click();await expect(page.getByRole('button',{name:'Add',exact:true})).toBeDisabled();await page.getByLabel('Task title').fill('Keyboard task');await page.getByLabel('Task title').press('Enter');await expect(page.getByRole('button',{name:'Keyboard task',exact:true})).toBeVisible();await expect(page.getByLabel('Task title')).toBeFocused();expect(calls[0].p.board_id).toBe('board');
 await page.getByLabel('Task title').fill('Canceled');await page.getByLabel('Task title').press('Escape');await expect(page.getByRole('button',{name:'Canceled',exact:true})).toHaveCount(0);
 await page.route('**/rest/v1/rpc/planning_save',r=>r.fulfill({status:409,json:{message:'Changed by another teammate. Refresh before saving.'}}));
 const row=page.locator('tr[data-task-id="task"]');await row.getByRole('button',{name:'Cut shafts',exact:true}).click();await row.getByLabel('Title',{exact:true}).fill('Not saved');await row.getByLabel('Title',{exact:true}).press('Enter');await expect(page.getByRole('alert')).toContainText('Changed by another teammate');await expect(row.getByLabel('Title',{exact:true})).toHaveValue('Cut shafts');await row.getByLabel('Title',{exact:true}).press('Escape');
 await row.getByRole('button',{name:'Timeline for Cut shafts'}).click();await row.getByLabel('End',{exact:true}).fill('2027-02-01');await row.getByRole('button',{name:'Save timeline'}).click();await expect(row.getByLabel('End',{exact:true})).toHaveValue('2027-01-20');await row.getByLabel('End',{exact:true}).press('Escape');
 await page.route('**/rest/v1/rpc/planning_dependency_save',r=>r.fulfill({status:400,json:{message:'Dependency would create a cycle'}}));await row.getByRole('button',{name:'Details for Cut shafts',exact:true}).click();const d=page.getByRole('dialog');await d.getByRole('combobox',{name:'Depends on',exact:true}).selectOption('other-task');await d.getByRole('button',{name:'Add dependency'}).click();await expect(d.getByRole('alert')).toContainText('cycle');await expect(d.getByRole('button',{name:/Remove dependency/})).toHaveCount(0);await d.press('Escape');
 c.can_manage=false;c.dependencies=[{id:'dep',board_id:'board',predecessor_task_id:'other-task',successor_task_id:'task'}];await page.getByRole('button',{name:'Refresh',exact:true}).click();await row.getByRole('button',{name:'Details for Cut shafts',exact:true}).click();await expect(d.getByRole('button',{name:'Add dependency'})).toHaveCount(0);await expect(d.getByRole('button',{name:/Remove dependency/})).toHaveCount(0);await expect(d.getByText('Fit bearing',{exact:true})).toBeVisible();
});

test('V1.2 Gantt arrows meet rendered endpoints; start-only tasks have no fake bar or arrow',async({page})=>{
 const {c}=await setup(page);Object.assign(c.tasks[0],{start_date:null,due_date:'2027-03-13'});Object.assign(c.tasks[1],{start_date:'2027-03-15',due_date:'2027-03-15'});
 c.tasks.push({...c.tasks[0],id:'start-only',title:'Start only',start_date:'2027-03-17',due_date:null});c.dependencies=[{id:'deadline-link',board_id:'board',predecessor_task_id:'task',successor_task_id:'other-task'},{id:'no-bar-link',board_id:'board',predecessor_task_id:'other-task',successor_task_id:'start-only'}];
 await page.goto('/#planning/boards/board');await page.getByRole('button',{name:'Gantt',exact:true}).click();
 await expect(page.locator('[data-dependency-id="deadline-link"]')).toHaveAttribute('d',/^M52 /);await expect(page.locator('[data-dependency-id="no-bar-link"]')).toHaveCount(0);await expect(page.locator('.planning-bar[data-task-id="start-only"]')).toHaveCount(0);await expect(page.getByText('Starts 2027-03-17 · no end date')).toBeVisible();
 await page.getByLabel('Timeline scale').selectOption('day');await expect(page.locator('[data-dependency-id="deadline-link"]')).toHaveAttribute('d',/^M92 /);await page.getByRole('button',{name:'Start only',exact:true}).click();await expect(page.getByRole('dialog').getByRole('button',{name:'Remove dependency on Fit bearing'})).toBeVisible();
});

for(const width of [390,1440])test(`Direct manipulation keyboard and repeated capture ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});const {c}=await setup(page);await page.goto('/#planning/plan');
 const group=page.locator('.planning-plan-group').first();await group.getByRole('button',{name:'+ Add item',exact:true}).click();
 for(const title of ['Quick item one','Quick item two']){await group.getByLabel('Item title').fill(title);await group.getByLabel('Item title').press('Enter');await expect(group.getByRole('button',{name:title,exact:true})).toBeVisible();await expect(group.getByLabel('Item title')).toBeFocused();}
 await group.getByLabel('Item title').press('Escape');await expect(group.getByRole('button',{name:'+ Add item',exact:true})).toBeFocused();
 await group.getByRole('button',{name:'Quick item one',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await group.getByLabel('Title',{exact:true}).fill('Renamed inline');await group.getByLabel('Title',{exact:true}).press('Enter');await expect(group.getByRole('button',{name:'Renamed inline',exact:true})).toBeVisible();
 await group.getByRole('button',{name:'Renamed inline',exact:true}).click();await group.getByLabel('Title',{exact:true}).fill('Canceled rename');await group.getByLabel('Title',{exact:true}).press('Escape');await expect(group.getByRole('button',{name:'Renamed inline',exact:true})).toBeFocused();
 await page.goto('/#planning/boards');await page.getByRole('button',{name:'Intake',exact:true}).click();await page.getByRole('button',{name:'Kanban',exact:true}).click();const col=page.locator('.planning-column').filter({has:page.locator('h3[data-status="in_progress"]')});await col.getByRole('button',{name:'+ Add task',exact:true}).click();
 for(const title of ['Repeated task one','Repeated task two']){await col.getByLabel('Task title').fill(title);await col.getByLabel('Task title').press('Enter');await expect(col.getByRole('button',{name:title,exact:true})).toBeVisible();await expect(col.getByLabel('Task title')).toBeFocused();expect(c.tasks.find((t:any)=>t.title===title).status).toBe('in_progress');}
 await col.getByLabel('Task title').press('Escape');await expect(col.getByRole('button',{name:'+ Add task',exact:true})).toBeFocused();await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

async function chooseOwners(page:Page,label:string,names:string[]){
 await page.getByRole('button',{name:label,exact:true}).click();const picker=page.getByRole('dialog',{name:label,exact:true});
 for(const cb of await picker.getByRole('checkbox').all())await cb.uncheck();
 for(const name of names)await picker.getByRole('checkbox',{name,exact:true}).check();
 await picker.getByRole('button',{name:'Apply owners'}).click();await expect(picker).toHaveCount(0);
}

for(const width of [390,1440])test(`V1.3 multi-owner capture, shared views, filtering and phone selector ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});const {c,calls}=await setup(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 c.members.push({id:'mira',name:'Mira with a deliberately long display name for mobile layouts'});
 c.tasks[0].start_date='2027-01-01';c.tasks[0].owner_ids=[uid,'other'];c.tasks.push({...c.tasks[1],id:'third',title:'Other work',owner_ids:['other']});
 await page.goto('/#planning/boards/board');const row=page.locator('tr[data-task-id="task"]');await expect(row.getByRole('button',{name:'Owners for Cut shafts'})).toContainText('Aiden · Teammate');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('combobox',{name:'Owner / Person',exact:true}).selectOption(uid);await expect(page.locator('tr[data-task-id]')).toHaveCount(1);await page.getByRole('combobox',{name:'Owner / Person',exact:true}).selectOption('other');await expect(page.locator('tr[data-task-id]')).toHaveCount(3);await page.getByRole('combobox',{name:'Owner / Person',exact:true}).selectOption('');
 await row.getByRole('button',{name:'Owners for Cut shafts'}).click();let picker=page.getByRole('dialog',{name:'Owners for Cut shafts'});await picker.getByLabel('Search members').fill('Mira');await picker.getByLabel('Search members').press('Enter');expect(calls).toHaveLength(0);await picker.getByRole('checkbox').focus();await page.keyboard.press('Space');await expect(picker.getByRole('checkbox')).toBeChecked();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/planning-v13-owners-${width}.png`,fullPage:true});await picker.getByRole('button',{name:'Apply owners'}).click();await expect(picker).toHaveCount(0);await expect(row.getByRole('button',{name:'Owners for Cut shafts'})).toContainText('Aiden +2');expect(c.tasks[0].owner_ids).toHaveLength(3);
 await row.getByRole('button',{name:'Owners for Cut shafts'}).click();picker=page.getByRole('dialog',{name:'Owners for Cut shafts'});await picker.getByRole('button',{name:'Remove Teammate as owner'}).click();await picker.press('Escape');await expect(row.getByRole('button',{name:'Owners for Cut shafts'})).toBeFocused();expect(c.tasks[0].owner_ids).toHaveLength(3);
 await page.getByRole('button',{name:'Kanban',exact:true}).click();await expect(page.locator('.planning-task').filter({hasText:'Cut shafts'})).toContainText('Aiden +2');await expect(page.getByRole('button',{name:'Cut shafts',exact:true})).toHaveCount(1);
 await page.getByRole('button',{name:'Gantt',exact:true}).click();await expect(page.locator('.planning-gantt-label[data-task-id="task"]')).toHaveCount(1);await expect(page.locator('.planning-gantt-label[data-task-id="task"]')).toContainText('Aiden +2');await expect(page.getByRole('button',{name:'Open Cut shafts',exact:true})).toHaveCount(1);
 await page.getByRole('button',{name:'+ New task',exact:true}).click();const full=page.getByRole('dialog',{name:'New task',exact:true});await full.getByLabel('Title',{exact:true}).fill('Joint new work');await chooseOwners(page,'Owners',['Aiden','Teammate']);await expect(full).toBeVisible();await full.getByRole('button',{name:'Save',exact:true}).click();await expect(full).toHaveCount(0);expect(c.tasks.find((t:any)=>t.title==='Joint new work').owner_ids).toEqual([uid,'other']);
 await page.goto('/#planning/my-work');await expect(page.getByRole('button',{name:'Cut shafts',exact:true})).toHaveCount(1);await expect(page.getByRole('button',{name:'Other work',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Joint new work',exact:true})).toHaveCount(1);
 await page.getByLabel('Status for Cut shafts').selectOption('in_progress');c.user_id='other';await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByLabel('Status for Cut shafts')).toHaveValue('in_progress');await expect(page.getByRole('button',{name:'Other work',exact:true})).toBeVisible();
 c.tasks[0].owner_ids=[uid];await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('button',{name:'Cut shafts',exact:true})).toHaveCount(0);expect(c.tasks.filter((t:any)=>t.id==='task')).toHaveLength(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('V1.3 rejected owner edit restores authority, inactive names remain readable, and members cannot reassign',async({page})=>{
 const {c}=await setup(page);c.tasks[0].owner_ids=[uid,'retired'];c.tasks[0].owners=[{id:uid,name:'Aiden'},{id:'retired',name:'Former teammate',active:false}];
 await page.goto('/#planning/boards/board');await page.getByRole('button',{name:'Owners for Cut shafts'}).click();const picker=page.getByRole('dialog',{name:'Owners for Cut shafts'});await expect(picker.getByRole('checkbox',{name:'Former teammate'})).toHaveCount(0);await expect(picker.getByRole('button',{name:'Remove Former teammate as owner'})).toBeVisible();
 await picker.getByRole('checkbox',{name:'Teammate',exact:true}).check();await page.route('**/rest/v1/rpc/planning_save',r=>{c.tasks[0].owner_ids=[uid];return r.fulfill({status:409,json:{message:'Changed by another teammate. Refresh before saving.'}});});await picker.getByRole('button',{name:'Apply owners'}).click();await expect(picker.getByRole('alert')).toContainText('not saved');await expect(picker.getByRole('checkbox',{name:'Teammate',exact:true})).not.toBeChecked();await expect(picker.getByRole('button',{name:'Remove Former teammate as owner'})).toHaveCount(0);await picker.press('Escape');
 c.can_manage=false;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('button',{name:'Owners for Cut shafts'})).toHaveCount(0);await expect(page.getByLabel('Status for Cut shafts')).toBeEnabled();await page.getByRole('button',{name:'Details for Cut shafts'}).click();const d=page.getByRole('dialog');await expect(d.getByRole('button',{name:'Owners',exact:true})).toHaveCount(0);await expect(d.getByLabel('New checklist step')).toBeEnabled();
});
test('V1.3 My Work uses server-filtered context and batched owner data, metrics count tasks not owners',async({page})=>{
 const {c}=await setup(page);c.tasks[0].owner_ids=[uid,'other','third'];c.members.push({id:'third',name:'Mira'});const requests:string[]=[];page.on('request',r=>{if(r.url().includes('/rpc/planning_'))requests.push(r.url().split('/').at(-1)!);});
 await page.goto('/#planning/my-work');await expect(page.getByRole('button',{name:'Cut shafts',exact:true})).toBeVisible();expect([...new Set(requests)]).toEqual(['planning_my_work_context']);expect(requests.length).toBeLessThanOrEqual(2);
 await page.goto('/#planning');await expect(page.getByRole('heading',{name:'Work status'})).toBeVisible();const counts=page.locator('.planning-counts');await expect(counts.locator('div').filter({hasText:'To Do'}).locator('dd')).toHaveText('1');await expect(page.getByRole('button',{name:'Intake',exact:true})).toContainText('0 / 2 tasks complete');expect([...new Set(requests)]).toEqual(['planning_my_work_context','planning_context']);expect(requests.length).toBeLessThanOrEqual(4);
});

test('V1.3 full form stages assignments without submitting; owner activity uses names and server metadata',async({page})=>{
 const {c,details,calls}=await setup(page);await page.goto('/#planning/boards/board');await page.getByRole('button',{name:'+ New task',exact:true}).click();const form=page.getByRole('dialog',{name:'New task',exact:true});await form.getByLabel('Title',{exact:true}).fill('Full creation');await form.getByRole('button',{name:'Owners',exact:true}).click();const picker=page.getByRole('dialog',{name:'Owners',exact:true});await picker.getByRole('checkbox',{name:'Aiden',exact:true}).focus();await page.keyboard.press('Enter');expect(calls).toHaveLength(0);await page.keyboard.press('Space');await picker.press('Escape');await expect(form).toBeVisible();await expect(form.getByRole('button',{name:'Owners',exact:true})).toBeFocused();await expect(form).toContainText('Unassigned');await chooseOwners(page,'Owners',['Aiden','Teammate']);await form.getByRole('button',{name:'Save',exact:true}).click();await expect(form).toHaveCount(0);
 details.history=[{id:1,entity:'task',action:'updated',actor_id:uid,created_at:'2027-01-02T12:00:00Z',before_data:{owners:[{id:uid,name:'Aiden'}],owner_ids:[uid]},after_data:{owners:[{id:'other',name:'Teammate'}],owner_ids:['other']}}];
 await page.getByRole('button',{name:'Details for Full creation'}).click();let d=page.getByRole('dialog',{name:'Edit task'});await d.getByText('Task activity',{exact:true}).click();await expect(d).toContainText('Added owners: Teammate.');await expect(d).toContainText('Removed owners: Aiden.');await expect(d).not.toContainText(uid);await d.press('Escape');
 await chooseOwners(page,'Owners for Full creation',[]);await expect(page.getByRole('button',{name:'Owners for Full creation'})).toHaveText('Unassigned');expect(c.tasks.find((t:any)=>t.title==='Full creation').owner_ids).toEqual([]);
});

for(const width of [390,768,1440])test(`UI sweep Planning status totals and board presentation ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.clock.setFixedTime(new Date('2027-01-06T12:00:00Z'));
 const {c,calls}=await setup(page);Object.assign(c.boards[0],{description:'Design, fabricate, and validate the intake assembly.'});
 c.boards.push({id:'archived',name:'Old project',kind:'project',active:false});
 c.tasks.push({...c.tasks[0],id:'hidden',board_id:'archived',status:'blocked'});
 await page.goto('/#planning');const counts=page.locator('.planning-counts');
 await expect(counts.locator('[data-status="backlog"] dd')).toHaveText('1');await expect(counts.locator('[data-status="todo"] dd')).toHaveText('1');
 await expect(counts.locator('[data-status="blocked"] dd')).toHaveText('0');await expect(page.getByText('0 of 2 complete',{exact:true})).toBeVisible();
 await expect(page.locator('.planning-board-card').filter({hasText:'Old project'})).toHaveCount(0);
 await page.screenshot({path:`test-results/ui-review-planning-dashboard-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Intake',exact:true}).click();await expect(page.locator('.planning-board-heading')).toContainText('Intake');
 await expect(page.getByText('Design, fabricate, and validate the intake assembly.',{exact:true})).toBeVisible();
 await expect(page.getByLabel('Status for Cut shafts')).toHaveAttribute('data-status','todo');
 await page.screenshot({path:`test-results/ui-review-planning-board-${width}.png`,fullPage:true});
 await page.getByLabel('Search tasks').fill('Nothing matches');await expect(page.getByText('No tasks match these filters.')).toBeVisible();
 await page.getByLabel('Search tasks').fill('');await page.getByRole('button',{name:'Details for Cut shafts',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Details for Cut shafts',exact:true})).toBeFocused();
 expect(calls).toHaveLength(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

for(const width of [390,1440])test(`Planning edit feedback and filter reset ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});const {calls}=await setup(page);await page.goto('/#planning/boards/board');
 await page.getByLabel('Search tasks').fill('Nothing matches');await page.getByLabel('Priority',{exact:true}).selectOption('urgent');
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();await expect(page.getByLabel('Search tasks')).toHaveValue('');await expect(page.getByLabel('Priority',{exact:true})).toHaveValue('');await expect(page.getByRole('button',{name:'Cut shafts',exact:true})).toBeVisible();
 let release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve;});
 await page.route('**/rest/v1/rpc/planning_save',async route=>{await pending;await route.fallback();});
 await page.getByRole('button',{name:'Cut shafts',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Shafts ready');await page.getByRole('button',{name:'Save title',exact:true}).click();
 try{
  await expect(page.locator('.planning-save-feedback')).toHaveText('Saving changes…');await expect(page.getByRole('button',{name:'Saving…',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();
  await page.keyboard.press('Escape');await expect(page.getByLabel('Title',{exact:true})).toBeVisible();
 }finally{release();}
 await expect(page.getByRole('button',{name:'Shafts ready',exact:true})).toBeVisible();await expect(page.locator('.planning-save-feedback')).toHaveText('Task saved.');expect(calls).toHaveLength(1);expect(calls[0].p.title).toBe('Shafts ready');
 await page.route('**/rest/v1/rpc/planning_save',route=>route.fulfill({status:409,json:{message:'Changed by another teammate. Refresh before saving.'}}));
 await page.getByLabel('Status for Shafts ready').selectOption('done');await expect(page.getByRole('alert')).toContainText('Changed by another teammate');await expect(page.locator('.planning-save-feedback')).toHaveCount(0);await expect(page.getByLabel('Status for Shafts ready')).toHaveValue('todo');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('Planning dialog and quick add confirm completed saves',async({page})=>{
 await page.setViewportSize({width:390,height:900});await setup(page);await page.goto('/#planning/boards/board');
 await page.getByRole('button',{name:'Details for Cut shafts',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Edit task'});
 await dialog.getByLabel('New checklist step').fill('Measure carefully');await dialog.getByRole('button',{name:'Add step',exact:true}).click();await expect(dialog.getByRole('status')).toHaveText('Checklist saved.');
 await dialog.getByLabel('Add a comment').fill('Dimensions confirmed');await dialog.getByRole('button',{name:'Post comment',exact:true}).click();await expect(dialog.getByRole('status')).toHaveText('Comment posted.');
 await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('.planning-save-feedback')).toHaveText('Task saved.');
 await page.getByRole('button',{name:'+ Add task',exact:true}).click();await page.getByLabel('Task title').fill('Check dimensions');await page.getByRole('button',{name:'Add',exact:true}).click();
 const quick=page.locator('.planning-quick-add');await expect(quick.getByRole('status')).toHaveText('Task added: Check dimensions');await expect(page.getByLabel('Task title')).toBeFocused();
 await page.getByLabel('Task title').fill('Next task');await expect(quick.getByRole('status')).toHaveCount(0);await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('button',{name:'+ Add task',exact:true})).toBeFocused();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
