import {test,expect,type Page} from '@playwright/test';
import {sprintReviewUIFixture,uiActor,uiId,uiReview,uiSeason} from './fixtures/sprint-review-ui';
import {validateReviewPayload} from '../src/planning/reviews/model';
import type {ReviewMutation,ReviewMutationReceipt,SprintReviewContext} from '../src/planning/reviews/types';

async function setup(page:Page,adjust?:(context:SprintReviewContext)=>void){
 const external:string[]=[],mutations:ReviewMutation[]=[],receipts=new Map<string,ReviewMutationReceipt>(),context=sprintReviewUIFixture();adjust?.(context);
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(['127.0.0.1','localhost'].includes(url.hostname))return route.continue();external.push(url.origin+url.pathname);return route.abort('blockedbyclient');});
 await page.addInitScript(actor=>localStorage.setItem('4418-team-hub-auth',JSON.stringify({access_token:'synthetic-review-token',refresh_token:'synthetic-refresh',expires_at:4000000000,token_type:'bearer',user:{id:actor,aud:'authenticated',app_metadata:{},user_metadata:{}}})),context.user_id);
 await page.route('**/rest/v1/**',r=>r.fulfill({json:new URL(r.request().url()).pathname.endsWith('/profiles')?{display_name:'Synthetic team member',role:'student',active:true}:[]}));
 const planning=()=>({user_id:context.user_id,can_manage:context.can_manage,season_id:context.season_id,seasons:context.seasons.map(s=>({...s,version:1})),members:context.members,areas:[],groups:[],boards:context.boards.map(b=>({...b,kind:'project',description:'',area_id:null,display_order:0,version:1})),items:[],tasks:context.tasks.filter(t=>t.available).map(t=>({...t,description:'Existing Planning task',priority:'normal',area_id:null,start_date:null,blocked_reason:'',version:1}))});
 await page.route('**/rpc/planning_context',r=>r.fulfill({json:planning()}));
 await page.route('**/rpc/sprint_review_context',r=>{const {selected_review,selected_season}=r.request().postDataJSON();if(selected_season&&selected_season!==context.season_id)return r.fulfill({status:403,json:{code:'SR403',message:'Season unavailable'}});const reviewId=selected_review||context.selected_review_id;return r.fulfill({json:{...context,selected_review_id:reviewId,updates:reviewId===context.selected_review_id?context.updates:context.previous_updates.filter(u=>u.review_id===reviewId),previous_updates:reviewId===context.selected_review_id?context.previous_updates:[]}});});
 function apply(body:ReviewMutation):ReviewMutationReceipt{
  mutations.push(body);if(body.expected_actor!==context.user_id)throw Error('Synthetic actor mismatch');const saved=receipts.get(body.request_id);if(saved)return saved;const p:any=body.p,issue=validateReviewPayload(body.action,p);if(issue)throw Error(issue);const version=(p.version??0)+1;
  if(body.action==='review'){const item={...p,version,recorded_by:context.user_id,recorded_at:'2026-10-06T14:00:00Z'},existing=context.reviews.find(r=>r.id===p.id);if(existing)Object.assign(existing,item);else context.reviews.unshift(item);context.selected_review_id=p.id;}
  if(body.action==='assignment'){const board=context.boards.find(b=>b.id===p.board_id)!;board.assignment={...p,version,lead:context.members.find(m=>m.id===p.lead_id)||null,supporters:context.members.filter(m=>p.supporter_ids.includes(m.id))};}
  if(body.action==='update'){const prior=context.previous_updates.find(u=>u.id===p.carry_from_update_id),review=context.reviews.find(r=>r.id===prior?.review_id);const item={...p,version,reported_students:context.members.filter(m=>p.reported_by_student_ids.includes(m.id)),linked_task:context.tasks.find(t=>t.id===p.linked_task_id)||null,carried_from:prior&&review?{update_id:prior.id,review_id:review.id,review_title:review.title,review_date:review.review_date}:null,recorded_by:context.user_id,recorded_at:'2026-10-06T14:00:00Z'};const existing=context.updates.find(u=>u.id===p.id);if(existing)Object.assign(existing,item);else context.updates.push(item);}
  const receipt:ReviewMutationReceipt={request_id:body.request_id,status:'applied',action:body.action,entity_id:body.action==='assignment'?p.board_id:p.id,version};receipts.set(body.request_id,receipt);return receipt;
 }
 await page.route('**/rpc/sprint_review_save',r=>r.fulfill({json:apply(r.request().postDataJSON())}));
 await page.route('**/rpc/sprint_review_mutation_status',r=>{const p=r.request().postDataJSON();return r.fulfill({json:receipts.get(p.request_id)||{request_id:p.request_id,status:'unknown',action:null,entity_id:null,version:null}});});
 await page.route('**/rpc/sprint_review_cancel_mutation',r=>{const p=r.request().postDataJSON(),receipt=receipts.get(p.request_id)||{request_id:p.request_id,status:'cancelled' as const,action:null,entity_id:null,version:null};receipts.set(p.request_id,receipt);return r.fulfill({json:receipt});});
 return {context,mutations,external,receipts,apply};
}
const project=(page:Page,n=200)=>page.locator(`#review-project-${uiId(n)}`);
async function openUpdate(page:Page,n=201){await project(page,n).getByRole('button',{name:n===200?'Edit update':'Weekly update',exact:true}).click();return page.getByRole('dialog');}
async function changeActor(page:Page,id:string|null){await page.evaluate(actor=>{const channel=new BroadcastChannel('4418-team-hub-auth');if(actor){const session={access_token:'synthetic-other-actor-token',refresh_token:'synthetic-refresh',expires_at:4000000000,token_type:'bearer',user:{id:actor,aud:'authenticated',app_metadata:{},user_metadata:{}}};localStorage.setItem('4418-team-hub-auth',JSON.stringify(session));channel.postMessage({event:'SIGNED_IN',session});}else{localStorage.removeItem('4418-team-hub-auth');channel.postMessage({event:'SIGNED_OUT',session:null});}channel.close();},id);}

for(const width of [390,768,1440])test(`Sprint Review workspace and weekly editor screenshot set at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:980});const state=await setup(page),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#planning/reviews');await expect(page.getByRole('heading',{name:'Sprint Review',exact:true})).toBeVisible();await expect(page.getByRole('complementary',{name:'Review discussion queue'})).toBeVisible();await expect(project(page)).toContainText('Completed 12 loaded cycles.');await expect(page.locator('main')).toHaveCount(1);await page.screenshot({path:`test-results/sprint-review/workspace-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const dialog=await openUpdate(page);await expect(dialog.getByRole('button',{name:'Carry forward open items'})).toBeVisible();await dialog.getByRole('button',{name:'Carry forward open items'}).click();await expect(dialog.getByLabel('Decision needed',{exact:true})).toHaveValue('Compare two control layouts.');await dialog.getByLabel('Progress this week').fill('Synthetic new progress for this week.');await page.screenshot({path:`test-results/sprint-review/editor-progress-${width}.png`});await dialog.getByRole('tab',{name:'2 · Student decision'}).click();await page.screenshot({path:`test-results/sprint-review/editor-decision-${width}.png`});await dialog.getByRole('tab',{name:'3 · Next action'}).click();await page.screenshot({path:`test-results/sprint-review/editor-next-${width}.png`});await dialog.getByRole('button',{name:'Close',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(project(page,201).getByRole('button',{name:'Weekly update',exact:true})).toBeFocused();expect(state.mutations).toEqual([]);expect(errors).toEqual([]);expect(state.external.every(u=>u.includes('fonts.googleapis.com')||u.includes('fonts.gstatic.com'))).toBe(true);
});
test('student explicitly carries open items, records own decision and links canonical task without creating or reassigning work',async({page})=>{
 const state=await setup(page);await page.goto('/#planning/reviews');const dialog=await openUpdate(page);await dialog.getByRole('button',{name:'Carry forward open items'}).click();await dialog.getByLabel('Progress this week').fill('Compared control layouts in six synthetic runs.');await dialog.getByRole('button',{name:'Add evidence link'}).click();await dialog.getByLabel('Evidence 1 label').fill('Practice comparison');await dialog.getByLabel('Evidence 1 link').fill('https://example.com/practice');await dialog.getByLabel('Evidence 1 source ID').fill('TEST-18');await dialog.getByRole('tab',{name:'2 · Student decision'}).click();await dialog.getByLabel('Reported student decision').fill('Students chose layout B for another practice.');await dialog.getByLabel('Decision rationale').fill('Fewer missed inputs across both drivers.');await dialog.getByRole('checkbox',{name:'Alex Student'}).check();await dialog.getByRole('tab',{name:'3 · Next action'}).click();await dialog.getByLabel('Next test or action').fill('Repeat with two new drivers.');await dialog.getByLabel('Linked Planning task').selectOption(uiId(301));await expect(dialog.getByText('Owner needed',{exact:true})).toBeVisible();await expect(dialog.getByText('Due date needed',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Save weekly update'}).click();await expect(dialog).toHaveCount(0);expect(state.mutations).toHaveLength(1);const {action,p,expected_actor}=state.mutations[0];expect(action).toBe('update');expect(expected_actor).toBe(uiActor);expect(p).toMatchObject({version:null,carry_from_update_id:uiId(501),linked_task_id:uiId(301),reported_by_student_ids:[uiActor]});expect(p).not.toHaveProperty('owner_ids');expect(p).not.toHaveProperty('due_date');await expect(project(page,201)).toContainText('Compared control layouts');await expect(page.getByRole('complementary',{name:'Review discussion queue'})).toContainText('Task owner needed');
});
test('manager configures agenda/chair and assigns only eligible students and supporters',async({page})=>{
 const state=await setup(page,c=>c.can_manage=true);await page.goto('/#planning/reviews');await page.getByRole('button',{name:'Review settings',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Review title').fill('Student-led design review');await dialog.getByLabel('Meeting chair').selectOption(uiActor);await expect(dialog.getByLabel('Meeting chair').locator('option')).not.toContainText(['Jamie Observer']);await dialog.getByRole('button',{name:'Add agenda item'}).click();await dialog.getByLabel('Item 3 title').fill('Evidence check');await dialog.getByLabel('Item 3 presenter').selectOption(uiId(4));await dialog.getByLabel('Item 3 minutes').fill('7');await page.screenshot({path:'test-results/sprint-review/manager-agenda.png'});await dialog.getByRole('button',{name:'Save review'}).click();await expect(dialog).toHaveCount(0);expect(state.mutations[0].p).toMatchObject({version:1,title:'Student-led design review',chair_id:uiActor});await page.getByRole('button',{name:'Assign review team for Field setup'}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Student lead').selectOption(uiId(4));await expect(dialog.getByLabel('Student lead').locator('option')).not.toContainText(['Morgan Facilitator']);await dialog.getByRole('checkbox',{name:'Morgan Facilitator'}).check();await expect(dialog.getByRole('checkbox',{name:'Jamie Observer'})).toHaveCount(0);await dialog.getByRole('button',{name:'Save review team'}).click();await expect(dialog).toHaveCount(0);expect(state.mutations[1]).toMatchObject({action:'assignment',p:{board_id:uiId(202),lead_id:uiId(4),supporter_ids:[uiId(1)],version:null}});
});
test('readonly context never exposes writer controls even if the actor appears in an assignment',async({page})=>{const state=await setup(page,c=>{c.can_manage=false;c.boards.forEach(b=>b.can_edit_update=false);c.members.find(m=>m.id===uiActor)!.can_write=false;});await page.goto('/#planning/reviews');await expect(project(page)).toBeVisible();for(const name of ['New review','Review settings','Weekly update','Edit update'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Export PowerPoint'})).toBeVisible();expect(state.mutations).toHaveLength(0);});
test('one double-submit write with unknown response reconciles without retrying the payload',async({page})=>{const state=await setup(page);await page.route('**/rpc/sprint_review_save',async r=>{state.apply(r.request().postDataJSON());await r.abort('failed');});await page.goto('/#planning/reviews');const dialog=await openUpdate(page);await dialog.getByLabel('Progress this week').fill('One deliberate update.');await dialog.locator('form').evaluate(f=>{(f as HTMLFormElement).requestSubmit();(f as HTMLFormElement).requestSubmit();});await expect(dialog).toHaveCount(0);await expect(page.getByRole('region',{name:'Pending review save'})).toBeVisible();expect(state.mutations).toHaveLength(1);await expect(project(page,201).getByRole('button',{name:'Weekly update',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Check save status'}).click();await expect(page.getByRole('region',{name:'Pending review save'})).toHaveCount(0);await expect(project(page,201)).toContainText('One deliberate update.');expect(state.mutations).toHaveLength(1);});
test('Close clears draft, unknown status keeps receipt and explicit cancel fences a delayed write',async({page})=>{const state=await setup(page);let release!:()=>void,started=false;const held=new Promise<void>(resolve=>release=resolve);await page.route('**/rpc/sprint_review_save',async r=>{const body=r.request().postDataJSON();started=true;await held;await r.fulfill({json:state.apply(body)}).catch(()=>{});});await page.goto('/#planning/reviews');const dialog=await openUpdate(page);await dialog.getByLabel('Progress this week').fill('Draft must not be restored.');await dialog.getByRole('button',{name:'Save weekly update'}).click();await expect.poll(()=>started).toBe(true);await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Check save status'}).click();await expect(page.getByText('This save has not appeared yet.',{exact:false})).toBeVisible();const stored=await page.evaluate(()=>sessionStorage.getItem('4418-sprint-review-receipts-v1'));expect(stored).not.toContain('Draft');expect(Object.keys(JSON.parse(stored!)[0]).sort()).toEqual(['expected_actor','request_id']);await page.getByRole('button',{name:'Cancel pending save'}).click();release();await expect.poll(()=>state.mutations.length).toBe(1);await expect(project(page,201).getByRole('button',{name:'Weekly update',exact:true})).toBeEnabled();await openUpdate(page);await expect(page.getByRole('dialog').getByLabel('Progress this week')).toHaveValue('');expect(state.context.updates).toHaveLength(1);});
test('Back and review selection clear drafts and ignore late save contents',async({page})=>{const state=await setup(page);let release!:()=>void,started=false;const held=new Promise<void>(resolve=>release=resolve);await page.route('**/rpc/sprint_review_save',async r=>{const body=r.request().postDataJSON();started=true;await held;await r.fulfill({json:state.apply(body)}).catch(()=>{});});await page.goto('/#planning/reviews');await page.getByLabel('Review',{exact:true}).selectOption(uiId(401));await expect(page.getByRole('heading',{name:'Sprint Review · Week 3'})).toBeVisible();await page.getByLabel('Review',{exact:true}).selectOption(uiReview);const dialog=await openUpdate(page);await dialog.getByLabel('Progress this week').fill('Newer review only.');await dialog.getByRole('button',{name:'Save weekly update'}).click();await expect.poll(()=>started).toBe(true);await page.goBack();await expect(dialog).toHaveCount(0);await expect(page.getByRole('heading',{name:'Sprint Review · Week 3'})).toBeVisible();release();await expect.poll(()=>state.mutations.length).toBe(1);await expect(page.getByText('Newer review only.',{exact:true})).toHaveCount(0);});
test('recovery remains reachable when the former review or season becomes inaccessible',async({page})=>{await setup(page);await page.addInitScript(({actor,id})=>sessionStorage.setItem('4418-sprint-review-receipts-v1',JSON.stringify([{expected_actor:actor,request_id:id}])) ,{actor:uiActor,id:uiId(699)});await page.route('**/rpc/sprint_review_context',r=>r.fulfill({status:403,json:{code:'SR403',message:'Unavailable'}}));await page.goto('/#planning/reviews');await expect(page.getByRole('region',{name:'Pending review save'})).toBeVisible();await expect(page.getByText('Completed 12 loaded cycles.',{exact:false})).toHaveCount(0);await page.getByRole('button',{name:'Check save status'}).click();await expect(page.getByText('This save has not appeared yet.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Cancel pending save'}).click();await expect(page.getByRole('region',{name:'Pending review save'})).toHaveCount(0);});
test('signout prevents an ignored late context response from repopulating history',async({page})=>{await setup(page);let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);await page.route('**/rpc/sprint_review_context',async r=>{await held;await r.fulfill({json:sprintReviewUIFixture()}).catch(()=>{});});await page.goto('/#planning/reviews');await expect(page.getByText('Loading Sprint Review…')).toBeVisible();await changeActor(page,null);await expect(page.getByRole('heading',{name:'Team sign in',exact:true})).toBeVisible();release();await expect(page.locator('.sprint-review')).toHaveCount(0);await expect(page.getByText('Intake prototype',{exact:true})).toHaveCount(0);});
test('account change removes the old draft and another actor’s recovery receipt immediately',async({page})=>{const state=await setup(page);await page.goto('/#planning/reviews');const dialog=await openUpdate(page);await dialog.getByLabel('Progress this week').fill('Old actor draft.');await page.evaluate(({actor,id})=>sessionStorage.setItem('4418-sprint-review-receipts-v1',JSON.stringify([{expected_actor:actor,request_id:id}])),{actor:uiActor,id:uiId(698)});state.context.user_id=uiId(5);state.context.boards=[];state.context.updates=[];state.context.previous_updates=[];await changeActor(page,uiId(5));await expect(dialog).toHaveCount(0);await expect(page.getByText('Old actor draft.',{exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'Pending review save'})).toHaveCount(0);await expect(page.getByText('Intake prototype',{exact:true})).toHaveCount(0);expect(state.mutations).toHaveLength(0);});
test('stale version rejection keeps the draft reviewable and releases recovery for an explicit refresh',async({page})=>{const state=await setup(page);await page.route('**/rpc/sprint_review_save',r=>r.fulfill({status:400,json:{code:'SR409',message:'Stale version'}}));await page.goto('/#planning/reviews');const dialog=await openUpdate(page,200);await dialog.getByLabel('Progress this week').fill('Unsaved correction.');await dialog.getByRole('button',{name:'Save weekly update'}).click();await expect(dialog.getByRole('alert')).toContainText('Another teammate');await expect(dialog.getByLabel('Progress this week')).toHaveValue('Unsaved correction.');await expect(page.getByRole('region',{name:'Pending review save'})).toHaveCount(0);await dialog.press('Escape');await expect(dialog).toHaveCount(0);expect(state.mutations).toHaveLength(0);});
test('malformed review route gives a safe invalid link state without requesting context or exposing history',async({page})=>{const state=await setup(page);let reads=0;await page.route('**/rpc/sprint_review_context',r=>{reads++;return r.fulfill({json:state.context});});await page.goto(`/#planning/reviews/${uiReview}/extra`);await expect(page.getByText('This review link is invalid.',{exact:false})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);expect(reads).toBe(0);});
test('PowerPoint exports loaded data with meaningful font choice and no backend write',async({page})=>{const state=await setup(page);await page.goto('/#planning/reviews');await expect(page.getByLabel('PowerPoint style')).toHaveValue('reference');await expect(page.getByText('For the original look, install Red Hat Display Black and Red Hat Text.')).toBeVisible();await page.getByLabel('PowerPoint style').selectOption('arial');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export PowerPoint'}).click();const download=await pending;expect(download.suggestedFilename()).toBe('sprint-review-2026-10-06.pptx');expect(await download.failure()).toBeNull();await expect(page.getByRole('status').filter({hasText:'Editable PowerPoint exported'})).toBeVisible();expect(state.mutations).toHaveLength(0);});
test('navigation during lazy export loading prevents stale file delivery',async({page})=>{await setup(page);let release!:()=>void,started=false;const held=new Promise<void>(resolve=>release=resolve),downloads:string[]=[];page.on('download',d=>downloads.push(d.suggestedFilename()));await page.route('**/src/planning/reviews/export/index.ts*',async r=>{started=true;await held;await r.continue().catch(()=>{});});await page.goto('/#planning/reviews');await page.getByRole('button',{name:'Export PowerPoint'}).click();await expect.poll(()=>started).toBe(true);await page.getByLabel('Review',{exact:true}).selectOption(uiId(401));await expect(page.getByRole('heading',{name:'Sprint Review · Week 3'})).toBeVisible();release();await expect(page.getByRole('button',{name:'Export PowerPoint'})).toBeEnabled();expect(downloads).toEqual([]);});
async function twoSeasonSetup(page:Page){
 const state=await setup(page,c=>c.can_manage=true),otherSeason=uiId(101),otherReview=uiId(410),requests:any[]=[];
 const seasons=[...state.context.seasons,{id:otherSeason,name:'Synthetic draft season',status:'draft' as const}],draftReview={...state.context.reviews[0],id:otherReview,season_id:otherSeason,title:'Draft season review'};
 await page.route('**/rpc/sprint_review_context',r=>{const p=r.request().postDataJSON();requests.push(p);const reviewSeason=p.selected_review===otherReview?otherSeason:uiSeason;if(p.selected_season&&p.selected_review&&p.selected_season!==reviewSeason)return r.fulfill({status:403,json:{code:'SR403',message:'Review/season mismatch'}});const selected=p.selected_season||(p.selected_review?reviewSeason:uiSeason),other=selected===otherSeason;return r.fulfill({json:{...state.context,seasons,season_id:selected,selected_review_id:other?otherReview:uiReview,reviews:other?[draftReview]:state.context.reviews,boards:other?[]:state.context.boards,updates:other?[]:state.context.updates,previous_updates:other?[]:state.context.previous_updates,tasks:other?[]:state.context.tasks}});});
 return {...state,otherSeason,otherReview,requests};
}
test('selected season survives review navigation and refresh, and a direct review link resolves its own season',async({page})=>{
 const {otherSeason,otherReview,requests}=await twoSeasonSetup(page);
 await page.goto('/#planning/reviews');await page.getByLabel('Planning season').selectOption(otherSeason);await expect(page.getByRole('heading',{name:'Draft season review'})).toBeVisible();await page.getByLabel('Review',{exact:true}).selectOption(otherReview);await expect(page).toHaveURL(new RegExp(otherReview+'$'));await expect(page.getByLabel('Planning season')).toHaveValue(otherSeason);await page.getByRole('button',{name:'Refresh Sprint Review'}).click();await expect(page.getByRole('heading',{name:'Draft season review'})).toBeVisible();expect(requests.at(-1)).toEqual({selected_season:null,selected_review:otherReview});await page.reload();await expect(page.getByRole('heading',{name:'Draft season review'})).toBeVisible();expect(requests.at(-1)).toEqual({selected_season:null,selected_review:otherReview});
});
test('cross-season Back and direct links ignore the landing selector while Forward preserves it and clears drafts',async({page})=>{
 const {otherSeason,otherReview,requests,mutations}=await twoSeasonSetup(page);
 await page.goto(`/#planning/reviews/${uiReview}`);await expect(page.getByRole('heading',{name:'Sprint Review · Week 4'})).toBeVisible();
 await page.getByLabel('Planning season').selectOption(otherSeason);await expect(page).toHaveURL(/#planning\/reviews$/);await expect(page.getByRole('heading',{name:'Draft season review'})).toBeVisible();
 expect(requests.at(-1)).toEqual({selected_season:otherSeason,selected_review:null});
 await page.goBack();await expect(page.getByRole('heading',{name:'Sprint Review · Week 4'})).toBeVisible();await expect(page.getByLabel('Planning season')).toHaveValue(uiSeason);
 expect(requests.at(-1)).toEqual({selected_season:null,selected_review:uiReview});
 await page.goForward();await expect(page.getByRole('heading',{name:'Draft season review'})).toBeVisible();await expect(page.getByLabel('Planning season')).toHaveValue(otherSeason);
 expect(requests.at(-1)).toEqual({selected_season:otherSeason,selected_review:null});
 await page.getByLabel('Review',{exact:true}).selectOption(otherReview);await expect(page).toHaveURL(new RegExp(otherReview+'$'));await expect(page.getByRole('heading',{name:'Draft season review'})).toBeVisible();
 await page.evaluate(id=>{location.hash=`planning/reviews/${id}`;},uiReview);await expect(page.getByRole('heading',{name:'Sprint Review · Week 4'})).toBeVisible();
 expect(requests.at(-1)).toEqual({selected_season:null,selected_review:uiReview});
 const dialog=await openUpdate(page);await dialog.getByLabel('Progress this week').fill('Unsaved old review draft.');
 await page.goBack();await expect(dialog).toHaveCount(0);await expect(page.getByRole('heading',{name:'Draft season review'})).toBeVisible();await expect(page.getByText('Unsaved old review draft.',{exact:true})).toHaveCount(0);
 await page.goBack();await expect(page).toHaveURL(/#planning\/reviews$/);await expect(page.getByLabel('Planning season')).toHaveValue(otherSeason);expect(requests.at(-1)).toEqual({selected_season:otherSeason,selected_review:null});expect(mutations).toHaveLength(0);
});
