import {test,expect} from '@playwright/test';
import {handle,type Services} from '../supabase/functions/team-invitations/handler';
import {readFileSync} from 'node:fs';
const id='00000000-0000-0000-0000-000000000001';
const request=(body:unknown={id},token='user-session')=>new Request('https://edge.test',{method:'POST',headers:{Origin:'https://team.frc4418.org',Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
function fixture(){const calls:string[]=[];let reserved=false;const s:Services={verify:async()=>{calls.push('verify');},reserve:async()=>{calls.push('reserve');const send=!reserved;reserved=true;return{id,send,status:'pending',email:'new@example.test',display_name:'New'};},invite:async()=>{calls.push('invite');return 'new-user';},finish:async(_id,user)=>{calls.push(user?'finish':'review');}};return{s,calls};}
for(const role of ['mentor','admin'])test(`${role} authorized reservation invites once without returning privileged Auth data`,async()=>{const {s,calls}=fixture();const r=await handle(request({id,role}),s);expect(r.status).toBe(202);expect(await r.json()).toEqual({id,status:'pending'});expect((await handle(request({id,role}),s)).status).toBe(200);expect(calls.filter(c=>c==='invite')).toHaveLength(1);expect(calls.slice(0,4)).toEqual(['verify','reserve','invite','finish']);});
test('invalid session, non-manager and untrusted origin never invoke privileged invite',async()=>{const {s,calls}=fixture();s.verify=async()=>{throw Error();};expect((await handle(request(),s)).status).toBe(401);s.verify=async()=>{};s.reserve=async()=>{throw Error('42501');};expect((await handle(request(),s)).status).toBe(403);expect((await handle(new Request('https://edge.test',{method:'POST',headers:{Origin:'https://evil.test'}}),s)).status).toBe(403);expect(calls).not.toContain('invite');});
test('uncertain invite and profile completion failures persist review and never resend',async()=>{for(const stage of ['invite','finish']){const {s,calls}=fixture();if(stage==='invite')s.invite=async()=>{calls.push('invite');throw Error('Provider secret must not leak');};else s.finish=async(_id,user)=>{calls.push(user?'finish':'review');if(user)throw Error('DB unavailable');};const r=await handle(request(),s);expect(r.status).toBe(502);expect(await r.text()).not.toContain('secret');expect(calls).toContain('review');await handle(request(),s);expect(calls.filter(c=>c==='invite')).toHaveLength(1);}});
test('browser source contains no privileged invite credentials; server callback is fixed',()=>{const ui=readFileSync('src/team/TeamManagement.tsx','utf8')+readFileSync('src/team/ManagementForms.tsx','utf8');expect(ui).not.toMatch(/SERVICE_ROLE|auth\.admin|\/auth\/v1\/invite/);const server=readFileSync('supabase/functions/team-invitations/index.ts','utf8');expect(server).toContain('https://team.frc4418.org/?password-reset=1');expect(server).toContain("'/auth/v1/user'");});
