import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {supabase} from '../attendance/service';
import {announcementData,saveAnnouncement,uploadImage,removeImage,sendAnnouncementUpdate,mediaBucket,type Announcement} from './service';
const errorText=(e:unknown)=>e&&typeof e==='object'&&'message' in e?String(e.message):'Unable to complete this action.';
const audiences=[['all','All active members'],['registered','Registered students'],['leadership','Mentors/admins'],['area','Functional area'],['position','Team position']];
export function AnnouncementImage({path}:{path?:string|null}){
 const [url,setUrl]=useState(''),[failed,setFailed]=useState(false);
 useEffect(()=>{setUrl('');setFailed(false);if(!path)return;let live=true,objectUrl='';void supabase!.storage.from(mediaBucket).download(path).then(({data,error})=>{if(!live)return;if(error||!data){setFailed(true);return;}objectUrl=URL.createObjectURL(data);setUrl(objectUrl);});return()=>{live=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[path]);
 return url?<img className="announcement-image" src={url} alt="Announcement attachment"/>:failed?<small>Image unavailable. Refresh to try again.</small>:path?<small>Loading image…</small>:null;
}
function Editor({item,data,close,saved}:{item:Partial<Announcement>;data:Awaited<ReturnType<typeof announcementData>>;close:()=>void;saved:()=>Promise<void>}){
 const ref=useRef<HTMLDialogElement>(null),requestId=useRef(crypto.randomUUID()),uploads=useRef<string[]>([]),retained=useRef<string|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[audience,setAudience]=useState(item.audience||(item.area_id?'area':'all')),[imagePath,setImagePath]=useState(item.image_path||null);
 useLayoutEffect(()=>{const d=ref.current!;const opener=document.activeElement as HTMLElement|null;d.showModal();return()=>{d.close();opener?.focus();for(const path of uploads.current)if(path!==retained.current)void removeImage(path).catch(()=>{});};},[]);
 const local=(s?:string|null)=>s?new Date(new Date(s).getTime()-new Date(s).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
 async function save(form:HTMLFormElement){const f=Object.fromEntries(new FormData(form));setBusy(true);setError('');try{await saveAnnouncement({...f,id:item.id,version:item.version,audience,area_id:audience==='area'?f.area_id:null,position_key:audience==='position'?f.position_key:null,image_path:imagePath,active:f.active==='true',send_email:f.send_email==='on',email_request_id:requestId.current,expires_at:f.expires_at?new Date(String(f.expires_at)).toISOString():null});retained.current=imagePath;if(item.image_path&&item.image_path!==imagePath)await removeImage(item.image_path).catch(()=>{});await saved();close();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <dialog ref={ref} className="my-dialog" aria-label="Announcement editor" onCancel={e=>{e.preventDefault();if(!busy)close();}}><h2>{item.id?'Edit announcement':'Create announcement'}</h2><form onSubmit={e=>{e.preventDefault();void save(e.currentTarget);}}><fieldset disabled={busy}>
 <label>Title<input name="title" defaultValue={item.title} required maxLength={150}/></label><label>Message<textarea name="body" defaultValue={item.body} required maxLength={5000} rows={4}/></label>
 <div className="my-fields"><label>Priority<select name="severity" defaultValue={item.severity||'normal'}>{['normal','important','urgent'].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label><label>Audience<select value={audience} onChange={e=>setAudience(e.target.value)}>{audiences.map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label></div>
 {audience==='area'&&<label>Functional area<select name="area_id" required defaultValue={item.area_id||''}><option value="">Choose area</option>{data.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}
 {audience==='position'&&<label>Team position<select name="position_key" required defaultValue={item.position_key||''}><option value="">Choose position</option>{data.positions.map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</select></label>}
 <label>Image (optional)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');void uploadImage(file).then(path=>{uploads.current.push(path);setImagePath(path);}).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}/><small>JPG, PNG, or WebP · up to 6 MB</small></label>
 <AnnouncementImage path={imagePath}/>{imagePath&&<button type="button" onClick={()=>setImagePath(null)}>Remove image</button>}
 {!item.id?<label className="announcement-checkbox"><input type="checkbox" name="send_email"/>Send email notification <small>Off by default. Emails the selected audience once when published.</small></label>:<p className="announcement-hint">Saving edits does not send email. Use “Send update email” after saving if needed.</p>}
 <details><summary>Visibility and expiration</summary><label>Status<select name="active" defaultValue={String(item.active??true)}><option value="true">Active</option><option value="false">Inactive</option></select></label><label>Expires at (local time)<input name="expires_at" type="datetime-local" defaultValue={local(item.expires_at)}/></label></details>
 {error&&<p role="alert">{error}</p>}<div className="my-actions"><button className="primary" type="submit">{busy?'Saving…':'Save announcement'}</button><button type="button" onClick={close}>Cancel</button></div></fieldset></form></dialog>;
}
export function AnnouncementManager(){
 const [data,setData]=useState<Awaited<ReturnType<typeof announcementData>>|null>(null),[error,setError]=useState(''),[edit,setEdit]=useState<Partial<Announcement>|null>(null),[archive,setArchive]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const requests=useRef(new Map<string,string>());
 async function load(){setError('');setData(await announcementData());}
 useEffect(()=>{void load().catch(e=>setError(errorText(e)));},[]);
 const current=(a:Announcement)=>a.active&&(!a.expires_at||Date.parse(a.expires_at)>Date.now());
 async function send(a:Announcement){if(!window.confirm(`Send an update email for “${a.title}” to its current audience?`))return;const key=`${a.id}/${a.version}`;if(!requests.current.has(key))requests.current.set(key,crypto.randomUUID());setBusy(true);setError('');setNotice('');try{await sendAnnouncementUpdate(a,requests.current.get(key)!);requests.current.delete(key);setNotice('Update email queued for the current audience.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <><div className="my-actions"><button className="primary" onClick={()=>setEdit({})}>Create announcement</button><button aria-pressed={archive} onClick={()=>setArchive(!archive)}>{archive?'Show active':'Show expired / inactive'}</button></div>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error} <button onClick={()=>void load().catch(e=>setError(errorText(e)))}>Retry</button></p>}{!data&&!error?<p role="status">Loading announcements…</p>:data&&<><div className="my-announcements">{data.announcements.filter(a=>Boolean(current(a))!==archive).map(a=><article className={`my-card announcement ${a.severity}`} key={a.id}><h3>{a.title}</h3><p>{a.body}</p><AnnouncementImage path={a.image_path}/><small>{a.audience==='position'?data.positions.find(p=>p.key===a.position_key)?.name:a.area_id?data.areas.find(x=>x.id===a.area_id)?.name:audiences.find(([key])=>key===(a.audience||'all'))?.[1]} · {current(a)?'Active':'Expired / inactive'}</small><div className="my-actions"><button disabled={busy} onClick={()=>setEdit(a)}>Edit {a.title}</button>{a.active&&<button disabled={busy} onClick={()=>{setBusy(true);void saveAnnouncement({...a,active:false}).then(load).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}>Deactivate</button>}{current(a)&&<button disabled={busy} onClick={()=>void send(a)}>Send update email</button>}</div></article>)}</div>{!data.announcements.some(a=>Boolean(current(a))!==archive)&&<p className="my-empty">No {archive?'expired or inactive':'active'} announcements.</p>}{edit&&<Editor item={edit} data={data} close={()=>setEdit(null)} saved={load}/>}</>}</>;
}
