import {ArrowLeft,ArrowUpRight,CheckCircle2,Target} from 'lucide-react';
import type {GoalsContext,SeasonGoal} from './types';
import {categories,statuses,directions,latestUpdate,measurementSummary,numberLabel,validEvidenceUrl} from './model';

export function GoalStatus({goal}:{goal:SeasonGoal}){const update=latestUpdate(goal);return <span className="goal-status" data-status={update?.status||'unreported'}>{update?statuses[update.status]:'No update yet'}</span>;}
export function GoalMeasure({goal,detail=false}:{goal:SeasonGoal;detail?:boolean}){
 const measurement=measurementSummary(goal);
 return <div className={`goal-measure ${detail?'is-detail':''}`}><div><span className="planning-eyebrow">{goal.category==='fundraising'?`Manually reported ${goal.fundraising_measure}`:'Latest measurement'}</span><strong>{measurement.value===null?'Not measured':numberLabel(measurement.value)}{measurement.value!==null&&<small> {goal.unit}</small>}</strong><span className="goal-target">Target {numberLabel(goal.target)} {goal.unit}</span></div>{detail&&<div><span className="planning-eyebrow">Starting point</span><strong>{numberLabel(goal.baseline)}<small> {goal.unit}</small></strong><span className="goal-target">{directions[goal.direction]}</span></div>}{detail&&<div><span className="planning-eyebrow">Observed on</span><strong className="goal-observed">{measurement.observedOn||'No measurement yet'}</strong>{measurement.reached&&<span className="goal-target"><CheckCircle2 size={14} aria-hidden="true"/> Measured target met</span>}</div>}</div>;
}
export function GoalList({goals,onCreate,canCreate,disabled}:{goals:SeasonGoal[];onCreate:()=>void;canCreate:boolean;disabled:boolean}){
 if(!goals.length)return <div className="planning-card goal-empty"><Target size={28} aria-hidden="true"/><h2>No goals here yet</h2><p>Start with a result your team can measure. Pick a student owner, then bring evidence to each weekly check-in.</p>{canCreate&&<button className="planning-primary" disabled={disabled} onClick={onCreate}>Create goal</button>}</div>;
 return <ul className="goal-list" aria-label="Season goals">{goals.map(goal=>{const update=latestUpdate(goal);return <li key={goal.id}><div className="goal-list-main"><div className="goal-list-labels"><span className="planning-eyebrow">{categories[goal.category]}</span><GoalStatus goal={goal}/></div><a className="goal-title" href={`#planning/goals/${goal.id}`}>{goal.title}<ArrowUpRight size={16} aria-hidden="true"/></a><p>{goal.owner.name}<span aria-hidden="true"> · </span>Due {goal.deadline}</p>{update&&<p className="goal-next"><span>Next:</span> {update.next_step}</p>}</div><GoalMeasure goal={goal}/></li>;})}</ul>;
}
export function GoalDetail({goal,data,onEdit,onUpdate,onOpenTask,onOpenMilestone,disabled}:{goal:SeasonGoal;data:GoalsContext;onEdit:()=>void;onUpdate:()=>void;onOpenTask:(id:string)=>void;onOpenMilestone:(id:string)=>void;disabled:boolean}){
 const recent=latestUpdate(goal),milestone=data.milestones.find(m=>m.id===goal.next_milestone_id);
 return <article className="goal-detail">
  <a className="goal-back" href="#planning/goals"><ArrowLeft size={15} aria-hidden="true"/>All goals</a>
  <section className="planning-card goal-detail-heading"><div className="goal-list-labels"><span className="planning-eyebrow">{categories[goal.category]}</span><GoalStatus goal={goal}/></div><h2>{goal.title}</h2><p className="goal-owner">Student owner: <strong>{goal.owner.name}</strong>{!goal.owner.active&&' · inactive'}<span>Due {goal.deadline}</span></p>{goal.description&&<p className="goal-description">{goal.description}</p>}<div className="goal-actions">{goal.capabilities.can_update&&<button className="planning-primary" disabled={disabled} onClick={onUpdate}>Weekly update</button>}{goal.capabilities.can_edit&&<button disabled={disabled} onClick={onEdit}>Edit goal</button>}</div><p className="goal-caption">Status is reported by the team. Measurements and linked work never change it automatically.</p></section>
  <section className="planning-card"><GoalMeasure goal={goal} detail/>{goal.category==='fundraising'&&<p className="goal-caption">This goal tracks manually reported {goal.fundraising_measure} funds. Pledges are promises; received funds have arrived. No Finance records are included.</p>}</section>
  <div className="goal-detail-grid"><section className="planning-card"><h3>Next step</h3><p>{recent?.next_step||'Add a weekly update to share the next concrete step.'}</p>{goal.next_milestone_id&&<div className="goal-link-item"><span>Next milestone</span>{milestone?.available?<button onClick={()=>onOpenMilestone(milestone.id)}>{milestone.title}<ArrowUpRight size={14} aria-hidden="true"/></button>:<span className="goal-unavailable">Milestone unavailable</span>}</div>}</section><section className="planning-card"><h3>Support team</h3>{goal.supporters.length?<ul className="goal-people">{goal.supporters.map(person=><li key={person.id}>{person.name}{!person.active&&<small> · inactive</small>}</li>)}</ul>:<p className="goal-caption">No supporters added yet.</p>}<p className="goal-caption">Named supporters can add evidence and weekly updates.</p></section></div>
  <section className="planning-card goal-history"><h3>Evidence and weekly updates <span>{goal.updates.length}</span></h3>{!goal.updates.length?<p className="goal-caption">No evidence recorded yet. A plan is a next step; record a measurement only after observing it.</p>:<ol>{[...goal.updates].sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(update=><li key={update.id}><div className="goal-history-meta"><strong>{update.kind==='measurement'?`${numberLabel(update.measured_value!)} ${goal.unit}`:'Weekly check-in'}</strong><span className="goal-status" data-status={update.status}>{statuses[update.status]}</span></div><p className="goal-evidence">{update.evidence}</p>{update.evidence_url&&(validEvidenceUrl(update.evidence_url)?<a href={new URL(update.evidence_url).href} target="_blank" rel="noopener noreferrer">View evidence<ArrowUpRight size={13} aria-hidden="true"/></a>:<span className="goal-caption">Evidence link unavailable</span>)}<p className="goal-next"><span>Next:</span> {update.next_step}</p><small>Observed {update.observed_on} · {update.author.name} · Recorded {update.created_at.slice(0,10)}</small></li>)}</ol>}</section>
  <section className="planning-card"><h3>Linked work</h3><p className="goal-caption">Links give context. They do not change task permissions or count as measured progress.</p>{!goal.task_ids.length&&!goal.milestone_ids.length?<p className="goal-caption">No linked tasks or milestones.</p>:<ul className="goal-links">{goal.task_ids.map(id=>{const task=data.tasks.find(t=>t.id===id);return <li key={id}><span>Task</span>{task?.available?<button onClick={()=>onOpenTask(id)}>{task.title}<ArrowUpRight size={14} aria-hidden="true"/></button>:<span className="goal-unavailable">Task unavailable</span>}</li>;})}{goal.milestone_ids.map(id=>{const item=data.milestones.find(m=>m.id===id);return <li key={id}><span>Milestone</span>{item?.available?<button onClick={()=>onOpenMilestone(id)}>{item.title}<ArrowUpRight size={14} aria-hidden="true"/></button>:<span className="goal-unavailable">Milestone unavailable</span>}</li>;})}</ul>}</section>
 </article>;
}
