import {useEffect,useId,useRef,useState,type ReactNode} from 'react';
import type {GoalsContext,SeasonGoal,GoalSavePayload,GoalUpdatePayload,GoalCategory,GoalDirection,GoalStatus} from './types';
import {categories,directions,statuses,finiteValue,latestUpdate,today,validateDefinition,validateUpdate,validEvidenceUrl} from './model';

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const dialog=useRef<HTMLDialogElement>(null),titleId=useId();
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,node=dialog.current;node?.showModal();return()=>{node?.close();if(previous?.isConnected)previous.focus();};},[]);
 return <dialog ref={dialog} className="planning-dialog goal-dialog" aria-labelledby={titleId} onCancel={event=>{event.preventDefault();onClose();}}><h2 id={titleId}>{title}</h2>{children}</dialog>;
}
function Choices({label,values,options,onChange}:{label:string;values:string[];options:{id:string;name:string;available:boolean}[];onChange:(values:string[])=>void}){
 const choices=[...options,...values.filter(id=>!options.some(o=>o.id===id)).map(id=>({id,name:'Unavailable record',available:false}))];
 return <fieldset className="goal-choices"><legend>{label}</legend>{choices.length?<div>{choices.map(option=><label key={option.id}><input type="checkbox" checked={values.includes(option.id)} onChange={e=>onChange(e.target.checked?[...values,option.id]:values.filter(id=>id!==option.id))} disabled={!option.available&&!values.includes(option.id)}/><span>{option.available?option.name:'Unavailable record'}{!option.available&&values.includes(option.id)&&<small> · remove link if no longer needed</small>}</span></label>)}</div>:<p className="goal-caption">None available.</p>}</fieldset>;
}
export function DefinitionDialog({goal,data,busy,error,onClose,onSave}:{goal:SeasonGoal|null;data:GoalsContext;busy:boolean;error:string;onClose:()=>void;onSave:(payload:GoalSavePayload)=>void}){
 const [draft,setDraft]=useState(()=>({id:goal?.id||crypto.randomUUID(),title:goal?.title||'',description:goal?.description||'',category:goal?.category||'engineering' as GoalCategory,owner_id:goal?.owner_id||data.eligible_owners.find(p=>p.id===data.user_id)?.id||data.eligible_owners[0]?.id||'',baseline:String(goal?.baseline??''),target:String(goal?.target??''),unit:goal?.unit||'',direction:goal?.direction||'increase' as GoalDirection,deadline:goal?.deadline||'',fundraising_measure:goal?.fundraising_measure||'received',supporter_ids:goal?.supporter_ids||[],task_ids:goal?.task_ids||[],milestone_ids:goal?.milestone_ids||[],next_milestone_id:goal?.next_milestone_id||''}));
 const fieldId=useId(),[validation,setValidation]=useState(''),locked=!!goal?.measurement_locked;
 const set=<K extends keyof typeof draft>(key:K,value:typeof draft[K])=>setDraft(previous=>({...previous,[key]:value}));
 function submit(){if(busy)return;const baseline=finiteValue(draft.baseline),target=finiteValue(draft.target);if(baseline===null||target===null){setValidation('Enter finite numbers for both baseline and target.');return;}const payload:GoalSavePayload={...draft,baseline,target,operation_id:crypto.randomUUID(),season_id:data.season_id!,expected_version:goal?.version||0,fundraising_measure:draft.category==='fundraising'?draft.fundraising_measure:null,next_milestone_id:draft.next_milestone_id||null};const issue=validateDefinition(payload);setValidation(issue||'');if(!issue)onSave(payload);}
 const owners=data.eligible_owners.some(p=>p.id===draft.owner_id)?data.eligible_owners:[...data.eligible_owners,...(goal?[goal.owner]:[])];
 return <Modal title={goal?'Edit goal':'New season goal'} onClose={onClose}><p className="goal-caption">One outcome, a student owner, and a measurement you can check.</p><form onSubmit={event=>{event.preventDefault();submit();}}>
 {(validation||error)&&<p className="planning-error" role="alert">{validation||error}</p>}
 <fieldset className="goal-form-fields" disabled={busy}><div className="planning-form">
  <label className="wide">Goal title<input autoFocus required maxLength={200} value={draft.title} onChange={e=>set('title',e.target.value)} placeholder="What will be different by the end of the season?"/></label>
  <div className="goal-field"><label htmlFor={`${fieldId}-category`}>Category</label><select id={`${fieldId}-category`} value={draft.category} disabled={locked} onChange={e=>set('category',e.target.value as GoalCategory)}>{Object.entries(categories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
  <div className="goal-field"><label htmlFor={`${fieldId}-owner`}>Student owner</label><select id={`${fieldId}-owner`} value={draft.owner_id} disabled={!!goal&&!goal.capabilities.can_reassign||!goal&&!data.capabilities.can_reassign} onChange={e=>{set('owner_id',e.target.value);set('supporter_ids',draft.supporter_ids.filter(id=>id!==e.target.value));}}>{owners.map(person=><option key={person.id} value={person.id}>{person.name}{!person.active?' · inactive':''}</option>)}</select></div>
  <label>Baseline<input type="number" step="any" required value={draft.baseline} disabled={locked} onChange={e=>set('baseline',e.target.value)}/></label>
  <label>Target<input type="number" step="any" required value={draft.target} disabled={locked} onChange={e=>set('target',e.target.value)}/></label>
  <label>Unit<input required maxLength={60} value={draft.unit} disabled={locked} onChange={e=>set('unit',e.target.value)} placeholder="seconds, successful runs, USD…"/></label>
  <div className="goal-field"><label htmlFor={`${fieldId}-direction`}>Direction</label><select id={`${fieldId}-direction`} value={draft.direction} disabled={locked} onChange={e=>set('direction',e.target.value as GoalDirection)}>{Object.entries(directions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
  {draft.category==='fundraising'&&<><div className="goal-field"><label htmlFor={`${fieldId}-funds`}>Funds measured</label><select id={`${fieldId}-funds`} value={draft.fundraising_measure} disabled={locked} onChange={e=>set('fundraising_measure',e.target.value as 'pledged'|'received')}><option value="received">Received funds</option><option value="pledged">Pledged funds</option></select></div><p className="wide goal-caption">Pledged means promised; received means funds have arrived. All amounts are manually reported, without Finance data.</p></>}
  {locked&&<p className="wide goal-caption">The measurement definition is fixed after evidence is recorded, so earlier updates stay comparable.</p>}
  <label>Deadline<input type="date" required value={draft.deadline} onChange={e=>set('deadline',e.target.value)}/></label>
  <div className="goal-field"><label htmlFor={`${fieldId}-milestone`}>Next milestone</label><select id={`${fieldId}-milestone`} value={draft.next_milestone_id} onChange={e=>{const id=e.target.value;setDraft(previous=>({...previous,next_milestone_id:id,milestone_ids:id&&!previous.milestone_ids.includes(id)?[...previous.milestone_ids,id]:previous.milestone_ids}));}}><option value="">No milestone selected</option>{data.milestones.filter(m=>m.available||m.id===draft.next_milestone_id).map(m=><option value={m.id} key={m.id}>{m.available?m.title:'Unavailable milestone'}</option>)}{draft.next_milestone_id&&!data.milestones.some(m=>m.id===draft.next_milestone_id)&&<option value={draft.next_milestone_id}>Unavailable milestone</option>}</select></div>
  <label className="wide">Why this matters<textarea maxLength={5000} value={draft.description} onChange={e=>set('description',e.target.value)} rows={2}/></label>
 </div><details className="goal-definition-extras"><summary>Support team and linked work</summary><Choices label="Support team" values={draft.supporter_ids} options={data.members.filter(m=>m.id!==draft.owner_id).map(m=>({id:m.id,name:m.name,available:m.active}))} onChange={values=>set('supporter_ids',values)}/><Choices label="Linked tasks" values={draft.task_ids} options={data.tasks.map(t=>({id:t.id,name:t.title,available:t.available}))} onChange={values=>set('task_ids',values)}/><Choices label="Linked milestones" values={draft.milestone_ids} options={data.milestones.map(m=>({id:m.id,name:m.title,available:m.available}))} onChange={values=>setDraft(previous=>({...previous,milestone_ids:values,next_milestone_id:values.includes(previous.next_milestone_id)?previous.next_milestone_id:''}))}/><p className="goal-caption">Only existing, available Planning records can be linked. Their progress never updates the goal measurement.</p></details></fieldset>
 <div className="planning-toolbar"><button type="button" onClick={onClose}>Close</button><button className="planning-primary" disabled={busy} type="submit">{busy?'Saving…':'Save goal'}</button></div>{busy&&<p className="goal-caption" role="status">Saving. If you close this dialog, you can check the result from the goals list.</p>}</form></Modal>;
}
export function UpdateDialog({goal,busy,error,onClose,onSave}:{goal:SeasonGoal;busy:boolean;error:string;onClose:()=>void;onSave:(payload:GoalUpdatePayload)=>void}){
 const fieldId=useId();
 const [kind,setKind]=useState<'weekly'|'measurement'>('measurement'),[value,setValue]=useState(''),[status,setStatus]=useState<GoalStatus>(latestUpdate(goal)?.status||'on_track'),[observed,setObserved]=useState(today()),[evidence,setEvidence]=useState(''),[url,setUrl]=useState(''),[next,setNext]=useState(''),[validation,setValidation]=useState('');
 function submit(){if(busy)return;const payload:GoalUpdatePayload={id:crypto.randomUUID(),operation_id:crypto.randomUUID(),goal_id:goal.id,expected_version:goal.version,kind,measured_value:kind==='measurement'?finiteValue(value):null,status,evidence,evidence_url:url.trim()?(validEvidenceUrl(url.trim())?new URL(url.trim()).href:url.trim()):null,next_step:next,observed_on:observed};const issue=validateUpdate(payload);setValidation(issue||'');if(!issue)onSave(payload);}
 return <Modal title="Weekly update" onClose={onClose}><p className="goal-caption">{goal.title}</p><form onSubmit={e=>{e.preventDefault();submit();}}>{(validation||error)&&<p className="planning-error" role="alert">{validation||error}</p>}<fieldset className="goal-form-fields" disabled={busy}><div className="planning-form"><div className="goal-field"><label htmlFor={`${fieldId}-kind`}>Update type</label><select id={`${fieldId}-kind`} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="measurement">Observed measurement</option><option value="weekly">Weekly note only</option></select></div><label>Observed on<input type="date" required max={today()} value={observed} onChange={e=>setObserved(e.target.value)}/></label>{kind==='measurement'&&<div className="goal-field"><label htmlFor={`${fieldId}-value`}>Measured value</label><input id={`${fieldId}-value`} aria-describedby={`${fieldId}-unit`} autoFocus required type="number" step="any" value={value} onChange={e=>setValue(e.target.value)}/><small id={`${fieldId}-unit`}>{goal.unit}{goal.category==='fundraising'?` · manually reported ${goal.fundraising_measure}`:''}</small></div>}<div className="goal-field"><label htmlFor={`${fieldId}-status`}>Reported status</label><select id={`${fieldId}-status`} value={status} onChange={e=>setStatus(e.target.value as GoalStatus)}>{Object.entries(statuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><p className="wide goal-caption">{kind==='measurement'?'Record what you observed, with enough detail for someone else to check it.':'A weekly note preserves your last measurement.'} Status is your assessment of the goal.</p><label className="wide">Evidence<textarea required maxLength={5000} rows={3} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="What happened? Include the test, sample size, or result. Keep plans in Next step."/></label><label className="wide">Evidence link<input type="url" maxLength={2000} placeholder="https://… (optional)" value={url} onChange={e=>setUrl(e.target.value)}/></label><label className="wide">Next step<textarea required maxLength={2000} rows={2} value={next} onChange={e=>setNext(e.target.value)} placeholder="What happens next, and who can help?"/></label><p className="wide goal-caption">Updates remain in the history. Add a new update to correct earlier evidence.</p></div></fieldset><div className="planning-toolbar"><button type="button" onClick={onClose}>Close</button><button className="planning-primary" type="submit" disabled={busy}>{busy?'Saving…':'Save update'}</button></div>{busy&&<p className="goal-caption" role="status">Saving. Closing keeps only a receipt so you can check the result.</p>}</form></Modal>;
}
