import {useEffect,useRef,useState} from 'react';
import {RefreshCw} from 'lucide-react';
import {supabase} from '../../attendance/service';
import {GoalSession,pendingGoalOperations,finishGoalOperation,goalReceiptStorageAvailable,type PendingGoalOperation} from './session';
import {reconcileGoal,assertReceiptMatches} from './service';
import './goals.css';

type Props={actorId:string;route:string;onResolved:()=>void};
/** Recovery is actor-scoped, independent of whether the original season remains visible. */
export function GoalRecovery(props:Props){return <Recovery key={`${props.actorId}:${props.route}`} {...props}/>;}
function Recovery({actorId,route,onResolved}:Props){
 const [receipts,setReceipts]=useState(()=>pendingGoalOperations(actorId)),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState(''),[error,setError]=useState('');
 const session=useRef(new GoalSession({actorId,seasonId:'receipt-recovery',route})).current,checking=useRef(false);
 const actualRoute=()=>typeof location==='undefined'?route:location.hash;
 useEffect(()=>{session.activate();const sync=()=>{if(session.current(session.ticket(),actualRoute()))setReceipts(pendingGoalOperations(actorId));},leave=()=>{if(location.hash!==route){session.dispose();setReceipts([]);setMessage('');setError('');}};window.addEventListener('goal-receipt-change',sync);window.addEventListener('hashchange',leave);const auth=supabase?.auth.onAuthStateChange((_event,next)=>{if(next?.user.id!==actorId){session.dispose();setReceipts([]);setMessage('');setError('');}});return()=>{session.dispose();window.removeEventListener('goal-receipt-change',sync);window.removeEventListener('hashchange',leave);auth?.data.subscription.unsubscribe();};},[]);
 async function recover(receipt:PendingGoalOperation,cancel:boolean){if(checking.current)return;const ticket=session.ticket();if(!session.current(ticket,actualRoute()))return;const controller=session.controller();checking.current=true;setBusy(receipt.operationId);setError('');setMessage('');try{const outcome=await reconcileGoal(actorId,receipt.operationId,cancel,controller.signal,undefined,()=>session.current(ticket,actualRoute()));assertReceiptMatches(outcome,receipt);if(!session.current(ticket,actualRoute()))return;if(outcome.status==='not_found')setMessage('This save has not appeared yet. Check again, or cancel the pending save before creating a replacement.');else{finishGoalOperation(receipt);setReceipts(pendingGoalOperations(actorId));setMessage(outcome.status==='committed'?'The save completed. Reloading the goals you can currently access.':'The pending save was cancelled. You can start a new update.');onResolved();}}catch(e){if(session.current(ticket,actualRoute()))setError((e as Error).message);}finally{session.release(controller);checking.current=false;if(session.current(ticket,actualRoute()))setBusy(null);}}
 return <>{message&&<p className="goal-feedback" role="status">{message}</p>}{error&&<p className="planning-error" role="alert">{error}</p>}{receipts.map((receipt,index)=><section className="goal-recovery" aria-label="Pending goal save" key={receipt.operationId}><strong>{receipts.length===1?'One save needs checking':`Pending save ${index+1} of ${receipts.length}`}</strong><p>A response was interrupted. Your draft has been cleared, and a save receipt lets you check whether it completed, even if that season is no longer available. New saves for that season are paused until this is resolved.</p><div className="goal-actions"><button disabled={!!busy} onClick={()=>void recover(receipt,false)}><RefreshCw size={14} aria-hidden="true"/>{busy===receipt.operationId?'Checking…':'Check save status'}</button><button disabled={!!busy} onClick={()=>void recover(receipt,true)}>Cancel pending save</button></div><small>{!goalReceiptStorageAvailable()&&'Browser storage is unavailable. Keep this tab open until the save is resolved. '}Cancel stops the save if it has not completed. A completed save stays in the goal history.</small></section>)}</>;
}
