import {useEffect,useId,useRef,useState} from 'react';
import {AlertTriangle,ArrowLeft,ArrowUpRight,Check,CheckCircle2,Clock3,Download,ExternalLink,FolderKanban,Layers3,Plus,RefreshCw,Search,UserRound} from 'lucide-react';
import {supabase} from '../attendance/service';
import type {FabricationAction,FabricationContext,FabricationFileKind,FabricationPart,FabricationProject,FabricationRevision,FabricationSubmission} from './types';
import {fabricationRoute,fabricationStatuses,projectProgress,readyQueue,safeOnshapeUrl} from './model';
import {fabricationStorageAvailable,finishFabricationSave,pendingFabricationSave,rememberFabricationSave,FabricationSession} from './session';
import {downloadFabricationFile,FabricationServiceError,loadFabrication,mutateFabrication,readFabricationPartVersion,reconcileFabrication,uploadRevision} from './service';
import {FabricationDialog,RevisionEditor} from './Editor';
import './fabrication.css';

type Props={actorId:string;route:string};
type Editor={project:FabricationProject;part:FabricationPart|null};
const actionLabels:Record<FabricationAction,string>={claim:'Claim part',release:'Release claim',acknowledge:'Acknowledge revision',ready:'Mark Ready',start:'Start work',done:'Mark Done',hold:'Put on hold',rework:'Return for review'};
const actionDone:Record<FabricationAction,string>={claim:'Part claimed.',release:'Claim released.',acknowledge:'Current revision acknowledged.',ready:'Part is Ready.',start:'Work started on the current revision.',done:'Part marked Done.',hold:'Part put on hold.',rework:'Part returned for review.'};
const dateLabel=(date:string)=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${date}T12:00:00`));
const stampLabel=(stamp:string)=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(stamp));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const sizeLabel=(size:number)=>size>=1024*1024?`${(size/1024/1024).toFixed(1)} MB`:`${Math.ceil(size/1024)} KB`;

/** Route, season and account changes remount drafts before another scope is displayed. */
export function FabricationWorkspace(props:Props){return <FabricationScope key={props.actorId} {...props}/>;}
function FabricationScope(props:Props){const [seasonId,setSeasonId]=useState<string|null>(null);const parsed=fabricationRoute(props.route);return <Workspace key={`${props.actorId}:${props.route}:${seasonId||''}`} {...props} seasonId={parsed.id?null:seasonId} onSeasonChange={id=>{setSeasonId(id);if(location.hash!=='#fabrication')location.hash='fabrication';}}/>;}
function Workspace({actorId,route,seasonId,onSeasonChange}:Props&{seasonId:string|null;onSeasonChange:(id:string)=>void}){
 const fieldId=useId(),parsed=fabricationRoute(route);
 const [data,setData]=useState<FabricationContext|null>(null),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[editor,setEditor]=useState<Editor|null>(null),[detailId,setDetailId]=useState<string|null>(null),[editorError,setEditorError]=useState(''),[busy,setBusy]=useState(false),[downloading,setDownloading]=useState<string|null>(null),[receipt,setReceipt]=useState(()=>pendingFabricationSave(actorId));
 const [view,setView]=useState<'projects'|'ready'>('projects'),[search,setSearch]=useState(''),[showInactive,setShowInactive]=useState(false);
 const session=useRef(new FabricationSession({actorId,route,seasonId})).current,saving=useRef(false),downloadRef=useRef(false),readGeneration=useRef(0),reading=useRef<AbortController|null>(null);
 const actualRoute=()=>typeof location==='undefined'?route:location.hash;
 async function refresh(keepData=false){if(reading.current&&!reading.current.signal.aborted)return;const ticket=session.ticket();if(!session.current(ticket,actualRoute()))return;const generation=++readGeneration.current,controller=session.controller();reading.current=controller;if(!keepData)setData(null);setError('');try{const next=await loadFabrication(actorId,seasonId,parsed.id,controller.signal,undefined,()=>session.current(ticket,actualRoute()));if(session.current(ticket,actualRoute())&&generation===readGeneration.current){setData(next);setReceipt(pendingFabricationSave(actorId));}}catch(e){if(session.current(ticket,actualRoute())&&generation===readGeneration.current){setError((e as Error).message);if(keepData){setData(null);setDetailId(null);setEditor(null);}}}finally{session.release(controller);if(reading.current===controller)reading.current=null;}}
 useEffect(()=>{session.activate();if(parsed.valid)void refresh();const clear=()=>{session.dispose();readGeneration.current++;setData(null);setEditor(null);setDetailId(null);setEditorError('');setError('');setFeedback('');setReceipt(null);setDownloading(null);},leave=()=>{if(actualRoute()!==route)clear();},sync=()=>{if(session.current(session.ticket(),actualRoute()))setReceipt(pendingFabricationSave(actorId));};window.addEventListener('hashchange',leave);window.addEventListener('fabrication-receipt-change',sync);const auth=supabase?.auth.onAuthStateChange((_event,next)=>{if(next?.user.id!==actorId)clear();});return()=>{session.dispose();readGeneration.current++;window.removeEventListener('hashchange',leave);window.removeEventListener('fabrication-receipt-change',sync);auth?.data.subscription.unsubscribe();};},[]);
 // Focus refreshes the current view; the timer only checks the open part's version.
 // A shared read controller prevents a version probe and a full context read racing.
 useEffect(()=>{
  const eligible=()=>document.visibilityState==='visible'&&!!data&&!editor&&!busy&&!saving.current&&!pendingFabricationSave(actorId)&&session.current(session.ticket(),actualRoute());
  const focus=()=>{if(eligible())void refresh(true);};
  async function checkVersion(){
   const part=data?.parts.find(p=>p.id===detailId);if(!part||!eligible()||reading.current&&!reading.current.signal.aborted)return;
   const ticket=session.ticket(),generation=++readGeneration.current,controller=session.controller();reading.current=controller;let changed=false;
   try{const version=await readFabricationPartVersion(actorId,part.id,controller.signal,undefined,()=>session.current(ticket,actualRoute()));if(session.current(ticket,actualRoute())&&generation===readGeneration.current)changed=version!==part.version;}
   catch(e){if(session.current(ticket,actualRoute())&&generation===readGeneration.current){close();setData(null);setError((e as Error).message);}}
   finally{session.release(controller);if(reading.current===controller)reading.current=null;}
   if(changed&&session.current(ticket,actualRoute())&&eligible())void refresh(true);
  }
  const interval=detailId?window.setInterval(()=>void checkVersion(),30000):null;
  window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);
  return()=>{if(interval!==null)window.clearInterval(interval);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);};
 },[data,detailId,editor,busy,receipt]);
 const selectedSeason=data?.seasons.find(s=>s.id===data.season_id),archived=selectedSeason?.status==='archived';
 const selectedProject=data?.projects.find(p=>p.id===parsed.id),detail=data?.parts.find(p=>p.id===detailId),detailProject=data?.projects.find(p=>p.id===detail?.board_id);
 const locked=!!receipt||busy;
 function close(){session.closeEditor();setEditor(null);setDetailId(null);setEditorError('');setBusy(false);setDownloading(null);setReceipt(pendingFabricationSave(actorId));}
 function openPart(part:FabricationPart){if(saving.current||editor||!data)return;session.openEditor();setDetailId(part.id);setEditorError('');setFeedback('');setDownloading(null);}
 function openEditor(project:FabricationProject,part:FabricationPart|null){if(saving.current||pendingFabricationSave(actorId)||!data||archived||!project.active||(!part&&!project.can_submit)||(part&&!part.can_revise))return;session.openEditor();setDetailId(null);setEditor({project,part});setEditorError('');setFeedback('');setDownloading(null);}
 async function submit(p:FabricationSubmission,dxf:File,pdf:File|null){if(!editor||saving.current||pendingFabricationSave(actorId)||archived)return;const current=editor.part?data?.parts.find(part=>part.id===editor.part?.id):null;if(editor.part?!current?.can_revise:!editor.project.can_submit)return;await save('revision',p,dxf,pdf);}
 async function action(part:FabricationPart,action:FabricationAction,note:string){if(saving.current||pendingFabricationSave(actorId)||archived||!part.allowed_actions.includes(action))return;await save(action,{part_id:part.id,version:part.version,revision_id:part.current_revision_id,note});}
 async function save(action:FabricationAction|'revision',p:FabricationSubmission|{part_id:string;version:number;revision_id:string;note:string},dxf?:File,pdf:File|null=null){
  if(saving.current||pendingFabricationSave(actorId)||!data)return;const ticket=session.ticket();if(!session.current(ticket,actualRoute()))return;readGeneration.current++;reading.current?.abort();reading.current=null;
  const recovery={request_id:crypto.randomUUID(),expected_actor:actorId};try{rememberFabricationSave(recovery);}catch(e){setEditorError((e as Error).message);return;}saving.current=true;setBusy(true);setReceipt(recovery);setEditorError('');setFeedback('');const controller=session.controller();
  try{const result=action==='revision'?await uploadRevision({...recovery,p:p as FabricationSubmission},dxf!,pdf,controller.signal,undefined,()=>session.current(ticket,actualRoute())):await mutateFabrication({...recovery,action,p:p as {part_id:string;version:number;revision_id:string;note:string}},controller.signal,undefined,()=>session.current(ticket,actualRoute()));if(result.status==='unknown'||result.status==='pending')throw new FabricationServiceError('The save has not been confirmed. Check its status.','unknown');if(session.current(ticket,actualRoute())){finishFabricationSave(recovery);setReceipt(null);if(action==='revision'){close();setFeedback(result.status==='applied'?'Revision submitted for review.':'The pending submission was cancelled.');await refresh();}else{setFeedback(result.status==='applied'?actionDone[action]:'The pending change was cancelled.');await refresh(true);}}}
  catch(e){if(e instanceof FabricationServiceError&&e.outcome==='rejected'&&session.current(ticket,actualRoute()))finishFabricationSave(recovery);if(session.current(ticket,actualRoute())){if(pendingFabricationSave(actorId)){close();setFeedback('The response was interrupted. Check the save status before making another change.');}else{setReceipt(null);setEditorError((e as Error).message);}}}
  finally{session.release(controller);saving.current=false;if(session.current(ticket,actualRoute()))setBusy(false);}
 }
 async function download(revision:FabricationRevision,kind:FabricationFileKind){if(downloadRef.current||busy)return;const ticket=session.ticket(),controller=session.controller();if(!session.current(ticket,actualRoute()))return;downloadRef.current=true;setDownloading(`${revision.id}:${kind}`);setEditorError('');try{const result=await downloadFabricationFile(actorId,revision.id,kind,controller.signal,undefined,()=>session.current(ticket,actualRoute()));if(!session.current(ticket,actualRoute()))return;const url=URL.createObjectURL(result.blob),anchor=document.createElement('a');anchor.href=url;anchor.download=result.filename;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){if(session.current(ticket,actualRoute()))setEditorError((e as Error).message);}finally{session.release(controller);downloadRef.current=false;if(session.current(ticket,actualRoute()))setDownloading(null);}}
 const parts=data?.parts||[],query=search.trim().toLowerCase(),queue=readyQueue(parts),visibleProjects=(data?.projects||[]).filter(p=>(!parsed.id||p.id===parsed.id)&&(showInactive||p.active||!!parsed.id)&&(p.name.toLowerCase().includes(query)||parts.some(part=>part.board_id===p.id&&`${part.current_revision.name} ${part.current_revision.material}`.toLowerCase().includes(query))));
 const filteredQueue=queue.filter(p=>{const project=data?.projects.find(project=>project.id===p.board_id);return (!parsed.id||p.board_id===parsed.id)&&`${p.current_revision.name} ${p.current_revision.material} ${project?.name||''}`.toLowerCase().includes(query);});
 return <section className="fabrication" aria-label="Fabrication workspace">
 <header className="fab-page-heading"><div><span className="fab-eyebrow">4418 · Design to build</span><h1>Fabrication</h1><p>Project parts, reviewed revisions, and a clear queue for the next build.</p></div><div className="fab-actions"><button disabled={busy||!!editor||!!detailId} aria-label="Refresh Fabrication" onClick={()=>void refresh()}><RefreshCw size={15}/>Refresh</button>{selectedProject?.can_submit&&selectedProject.active&&!archived&&<button className="fab-primary" disabled={locked} onClick={()=>openEditor(selectedProject,null)}><Plus size={16}/>Add part</button>}</div></header>
 <FabricationRecovery key={`${actorId}:${route}`} actorId={actorId} route={route} onResolved={()=>{setReceipt(pendingFabricationSave(actorId));close();void refresh();}}/>
 {!parsed.valid?<p className="fab-error" role="alert">This Fabrication link is invalid. <a href="#fabrication">Open Fabrication</a></p>:<>
 {error&&<p className="fab-error" role="alert">{error} <button onClick={()=>void refresh()}>Retry Fabrication</button></p>}{feedback&&<p className="fab-notice" role="status">{feedback}</p>}{!data&&!error&&<p className="fab-loading" role="status">Loading Fabrication…</p>}
 {data&&<>
 <div className="fab-toolbar">{parsed.id?<a className="fab-link" href="#fabrication"><ArrowLeft size={14}/>All projects</a>:<div className="fab-field"><label htmlFor={`${fieldId}-season`} className="fab-sr-only">Planning season</label><select id={`${fieldId}-season`} value={data.season_id||''} disabled={busy||!!editor||!!detailId||!data.seasons.length} onChange={e=>onSeasonChange(e.target.value)}>{!data.seasons.length&&<option value="">No Planning season</option>}{data.seasons.map(s=><option value={s.id} key={s.id}>{s.name} · {s.status}</option>)}</select></div>}<span className="fab-caption">Linked to existing <a href="#planning/boards">Planning projects</a></span></div>
 {archived&&<p className="fab-notice">This archived season is read only. Parts, revision history, and files are available for reference.</p>}
 {data.parts_limit_reached&&<p className="fab-warning">Showing the first 200 parts for this selection. Open a project to see its parts. Counts below describe the loaded parts only.</p>}
 <div className="fab-stats" aria-label="Fabrication progress"><Stat label="Total parts" count={parts.length} caption={`${data.projects.filter(p=>p.active).length} active projects`} icon={<Layers3 size={14}/>}/><Stat label="Ready to make" count={queue.length} caption="Reviewed current revisions" icon={<CheckCircle2 size={14}/>}/><Stat label="In progress" count={parts.filter(p=>p.status==='in_progress').length} caption="Claimed and underway" icon={<Clock3 size={14}/>}/><Stat label="Done" count={parts.filter(p=>p.status==='done').length} caption="Completed parts" icon={<Check size={14}/>}/></div>
 <div className="fab-toolbar"><div className="fab-segment" role="group" aria-label="Fabrication view"><button aria-pressed={view==='projects'} onClick={()=>setView('projects')}>Projects</button><button aria-pressed={view==='ready'} onClick={()=>setView('ready')}>Ready queue <span className="fab-count">{queue.length}</span></button></div><div className="fab-filter-controls"><label className="fab-search"><Search size={15}/><span className="fab-sr-only">Search fabrication parts or projects</span><input type="search" value={search} placeholder="Find a part or project…" onChange={e=>setSearch(e.target.value)}/></label>{!parsed.id&&view==='projects'&&data.projects.some(p=>!p.active)&&<label className="fab-check"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/>Inactive projects</label>}</div></div>
 {!selectedSeason?<div className="fab-empty"><FolderKanban size={30}/><h2>No Planning season available</h2><p>Fabrication parts belong to existing Planning projects. Open Planning to find your team's season and project boards.</p><a href="#planning">Open Planning</a></div>:!data.projects.length?<div className="fab-empty"><FolderKanban size={30}/><h2>No project boards yet</h2><p>Use your existing Planning projects to group related fabrication parts. Once a project is available, add its first part here.</p><a href="#planning/boards">Open Planning boards</a></div>:view==='projects'?<>
 {visibleProjects.length?visibleProjects.map(project=>{const projectParts=parts.filter(p=>p.board_id===project.id),displayParts=query&&!project.name.toLowerCase().includes(query)?projectParts.filter(p=>`${p.current_revision.name} ${p.current_revision.material}`.toLowerCase().includes(query)):projectParts,progress=projectProgress(parts,project.id);return <section className="fab-project" key={project.id} id={`fabrication-project-${project.id}`} aria-label={`${project.name} fabrication parts`}><header className="fab-project-header"><div className="fab-project-title"><span className="fab-project-icon"><FolderKanban size={18}/></span><div><h2><a href={`#fabrication/projects/${project.id}`}>{project.name}</a></h2><p>{projectParts.length} {projectParts.length===1?'part':'parts'}{!project.active?' · Inactive project':''}</p></div></div><div className="fab-actions"><a className="fab-link" href={`#planning/boards/${project.id}`}>Planning <ArrowUpRight size={13}/></a>{project.can_submit&&project.active&&!archived&&<button disabled={locked} aria-label={`Add part to ${project.name}`} onClick={()=>openEditor(project,null)}><Plus size={14}/>Add part</button>}</div></header><div className="fab-progress"><progress value={progress.done} max={progress.total||1} aria-label={`${project.name} parts completed`}/><span>{progress.done} of {progress.total} done</span>{projectParts.some(p=>p.status==='needs_review')&&<span>{projectParts.filter(p=>p.status==='needs_review').length} need review</span>}</div>{displayParts.length?<ul className="fab-part-list">{displayParts.map(part=><PartRow key={part.id} part={part} onOpen={()=>openPart(part)}/>)}</ul>:<div className="fab-project-empty"><p>{projectParts.length?'No parts match your search.':'No parts submitted yet.'} {!projectParts.length&&project.can_submit&&project.active&&!archived?'Add the first part with its DXF drawing and material requirements.':'Files and current revisions will appear here.'}</p></div>}</section>}):<div className="fab-empty"><Search size={28}/><h2>No matching projects</h2><p>Try another part name, material, or project.</p><button onClick={()=>{setSearch('');setShowInactive(true);}}>Show all projects</button></div>}
 </>:<section className="fab-queue" aria-label="Ready fabrication queue"><header className="fab-queue-heading"><h2>{parsed.id?'Project Ready queue':'Across all projects'}</h2><p>Ready parts, ordered by needed date. Open a part to review its current files and claim it.</p></header>{filteredQueue.length?<ul className="fab-part-list">{filteredQueue.map(part=><PartRow key={part.id} part={part} projectName={data.projects.find(p=>p.id===part.board_id)?.name} onOpen={()=>openPart(part)}/>)}</ul>:<div className="fab-empty"><CheckCircle2 size={30}/><h3>{query?'No Ready parts match':'The Ready queue is clear'}</h3><p>{query?'Try another search or clear the filter.':'Parts appear here after the current revision has been reviewed and marked Ready.'}</p>{query?<button onClick={()=>setSearch('')}>Clear search</button>:<button onClick={()=>setView('projects')}>View project parts</button>}</div>}</section>}
 {editor&&<RevisionEditor key={editor.part?.id||editor.project.id} project={editor.project} part={editor.part} busy={busy} error={editorError} onClose={close} onSave={(p,dxf,pdf)=>void submit(p,dxf,pdf)}/>}
 {detail&&detailProject&&<PartDetail key={`${detail.id}:${detail.current_revision_id}:${detail.version}`} part={detail} project={detailProject} revisions={data.revisions.filter(r=>r.part_id===detail.id)} actorId={actorId} archived={!!archived||!detailProject.active} busy={busy} locked={locked} error={editorError} downloading={downloading} onClose={close} onRevise={()=>openEditor(detailProject,detail)} onAction={(a,note)=>void action(detail,a,note)} onDownload={(revision,kind)=>void download(revision,kind)}/>}
 </>}
 </>}
 </section>;
}
function Stat({label,count,caption,icon}:{label:string;count:number;caption:string;icon:React.ReactNode}){return <div className="fab-stat"><span>{icon}{label}</span><strong>{count}</strong><small>{caption}</small></div>;}
function Status({part}:{part:FabricationPart}){return <span className={`fab-status fab-status-${part.status}`}>{part.status==='done'?<Check size={12}/>:part.status==='in_progress'?<Clock3 size={12}/>:part.status==='needs_review'?<AlertTriangle size={12}/>:null}{fabricationStatuses[part.status]}</span>;}
function PartRow({part,projectName,onOpen}:{part:FabricationPart;projectName?:string;onOpen:()=>void}){
 const revision=part.current_revision,late=revision.needed_date<today()&&part.status!=='done',newer=!!part.claimed_by&&part.acknowledged_revision_id!==part.current_revision_id;
 return <li className="fab-part-row" data-part-id={part.id}><div className="fab-part-name"><button className="fab-part-button" onClick={onOpen}>{revision.name}</button><div className="fab-part-sub"><span>Rev {revision.revision_number}</span><span>DXF{revision.pdf?' + PDF':''}</span>{projectName&&<span>{projectName}</span>}</div></div><div className="fab-part-spec"><strong>{revision.material} · {revision.thickness} {revision.thickness_unit}</strong><small>Qty {revision.quantity} · DXF in {revision.drawing_unit}</small></div><div className="fab-part-status"><Status part={part}/>{newer&&<small className="fab-revision-note"><AlertTriangle size={11}/>Revision needs acknowledgement</small>}</div><div className="fab-part-owner"><span className={late?'fab-due-overdue':''}>{late?'Overdue · ':''}{dateLabel(revision.needed_date)}</span><span><UserRound size={11}/>{part.claimant?.name||(part.claimed_by?'Claimed team member':'Unclaimed')}</span></div></li>;
}
function PartDetail({part,project,revisions,actorId,archived,busy,locked,error,downloading,onClose,onRevise,onAction,onDownload}:{part:FabricationPart;project:FabricationProject;revisions:FabricationRevision[];actorId:string;archived:boolean;busy:boolean;locked:boolean;error:string;downloading:string|null;onClose:()=>void;onRevise:()=>void;onAction:(action:FabricationAction,note:string)=>void;onDownload:(revision:FabricationRevision,kind:FabricationFileKind)=>void}){
 const [checked,setChecked]=useState(false),[note,setNote]=useState(''),[validation,setValidation]=useState('');
 const current=part.current_revision,actions=archived?[]:part.allowed_actions,acknowledged=part.acknowledged_revision_id===current.id,reviewed=part.reviewed_revision_id===current.id,onshape=current.onshape_url&&safeOnshapeUrl(current.onshape_url);
 function apply(action:FabricationAction){if(busy||locked)return;if(['hold','rework'].includes(action)&&!note.trim()){setValidation('Add a short reason before putting this part on hold or returning it for review.');return;}if(['ready','acknowledge'].includes(action)&&!checked){setValidation('Confirm you reviewed the current revision and drawing units.');return;}setValidation('');onAction(action,note.trim());}
 const fileButton=(revision:FabricationRevision,kind:FabricationFileKind,history=false)=><button disabled={busy||!!downloading} onClick={()=>onDownload(revision,kind)} aria-label={`Download ${kind.toUpperCase()} revision ${revision.revision_number}`}><Download size={history?12:14}/>{downloading===`${revision.id}:${kind}`?'Downloading…':`${kind.toUpperCase()}${history?'':` · ${sizeLabel(revision[kind]!.size)}`}`}</button>;
 return <FabricationDialog title={current.name} eyebrow={project.name} onClose={onClose}>
 <div className="fab-detail-meta"><Status part={part}/><span>Current revision {current.revision_number}</span><span>{part.claimant?.name?`Claimed by ${part.claimant.name}`:part.claimed_by?'Claimed team member':'Unclaimed'}</span></div>
 {(validation||error)&&<p className="fab-error" role="alert">{validation||error}</p>}
 {archived&&<p className="fab-notice">This project is read only.</p>}
 {part.claimed_by&&!acknowledged&&<p className="fab-warning"><strong>Current revision needs acknowledgement</strong>{part.claimed_by===actorId?'Review these files and acknowledge this revision before starting or completing work.':'The claimant must review and acknowledge the latest revision before starting or completing work.'}</p>}
 <dl className="fab-spec-grid"><div><dt>Material</dt><dd>{current.material}</dd></div><div><dt>Thickness</dt><dd>{current.thickness} {current.thickness_unit}</dd></div><div><dt>Quantity</dt><dd>{current.quantity}</dd></div><div><dt>Needed by</dt><dd>{dateLabel(current.needed_date)}</dd></div><div><dt>DXF drawing units</dt><dd>{current.drawing_unit==='mm'?'Millimeters (mm)':'Inches (in)'}</dd></div><div><dt>Revision check</dt><dd>{reviewed?'Reviewed':'Needs review'} · {acknowledged?'Acknowledged':'Not acknowledged'}</dd></div></dl>
 <div className="fab-file-actions">{fileButton(current,'dxf')}{current.pdf&&fileButton(current,'pdf')}{onshape&&<a className="fab-link" href={onshape} target="_blank" rel="noopener noreferrer">Open Onshape <ExternalLink size={12}/></a>}</div>
 <p className="fab-caption">{current.dxf.name}{current.pdf?` · ${current.pdf.name}`:''}</p>
 {current.notes&&<p className="fab-detail-note">{current.notes}</p>}
 {part.status_note&&<p className="fab-notice"><strong>Status note:</strong> {part.status_note}</p>}
 {!archived&&<section className="fab-workflow" aria-label="Part workflow"><h3>Next step</h3><p>{part.status==='done'?'This part is complete. Send it back through review if rework is needed.':part.status==='on_hold'?'Resolve the hold, then return this part through review.':part.status==='needs_review'?'Check the current DXF, material, thickness, quantity, and drawing units before marking Ready.':part.status==='ready'?'Claim the part and acknowledge its current revision before starting work.':'Use the acknowledged current revision. Mark Done when the requested quantity is complete.'}</p>{actions.some(a=>a==='ready'||a==='acknowledge')&&<label className="fab-check"><input type="checkbox" checked={checked} disabled={locked} onChange={e=>setChecked(e.target.checked)}/>I reviewed revision {current.revision_number}, including the DXF and drawing units.</label>}{actions.some(a=>a==='hold'||a==='rework')&&<label>Workflow note <span className="fab-caption">Required for a hold or rework</span><textarea rows={2} maxLength={2000} value={note} disabled={locked} onChange={e=>setNote(e.target.value)} placeholder="Why is this part on hold, or what needs another review?"/></label>}<div className="fab-action-group">{actions.map(action=><button key={action} className={['claim','ready','start','done','acknowledge'].includes(action)?'fab-primary':''} disabled={locked||!!downloading||(['ready','acknowledge'].includes(action)&&!checked)} onClick={()=>apply(action)}>{busy?'Saving…':action==='acknowledge'?`Acknowledge revision ${current.revision_number}`:actionLabels[action]}</button>)}</div>{!actions.length&&<p className="fab-caption">No workflow changes are available for this part with your current access.</p>}</section>}
 <section className="fab-history" aria-label="Immutable revision history"><h3>Revision history</h3><p>Every revision keeps its original specifications and files. Download the matching revision together.</p><ol>{[...revisions].sort((a,b)=>b.revision_number-a.revision_number).map(revision=><li className="fab-revision" key={revision.id}><div className="fab-revision-heading"><div><strong>Revision {revision.revision_number}{revision.id===current.id?' · Current':''}</strong><small>{stampLabel(revision.created_at)} · {revision.name}</small></div><div className="fab-actions">{fileButton(revision,'dxf',true)}{revision.pdf&&fileButton(revision,'pdf',true)}</div></div><div className="fab-revision-spec">{revision.material} · {revision.thickness} {revision.thickness_unit} · Qty {revision.quantity} · DXF {revision.drawing_unit} · Needed {dateLabel(revision.needed_date)}</div>{revision.notes&&<p>{revision.notes}</p>}</li>)}</ol></section>
 <div className="fab-dialog-footer"><button onClick={onClose}>Close</button>{part.can_revise&&!archived&&<button disabled={locked||!!downloading} onClick={onRevise}><Plus size={15}/>New revision</button>}{busy&&<small role="status">Closing clears this view. You can check the change's status from the workspace.</small>}</div>
 </FabricationDialog>;
}
function FabricationRecovery({actorId,route,onResolved}:{actorId:string;route:string;onResolved:()=>void}){
 const [receipt,setReceipt]=useState(()=>pendingFabricationSave(actorId)),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const session=useRef(new FabricationSession({actorId,route,seasonId:null})).current,checking=useRef(false),actualRoute=()=>typeof location==='undefined'?route:location.hash;
 useEffect(()=>{session.activate();const sync=()=>{if(session.current(session.ticket(),actualRoute()))setReceipt(pendingFabricationSave(actorId));},leave=()=>{if(actualRoute()!==route){session.dispose();setReceipt(null);setMessage('');setError('');}};window.addEventListener('fabrication-receipt-change',sync);window.addEventListener('hashchange',leave);const auth=supabase?.auth.onAuthStateChange((_event,next)=>{if(next?.user.id!==actorId){session.dispose();setReceipt(null);setMessage('');setError('');}});return()=>{session.dispose();window.removeEventListener('fabrication-receipt-change',sync);window.removeEventListener('hashchange',leave);auth?.data.subscription.unsubscribe();};},[]);
 async function recover(cancel:boolean){if(!receipt||checking.current)return;const ticket=session.ticket();if(!session.current(ticket,actualRoute()))return;const controller=session.controller();checking.current=true;setBusy(true);setError('');setMessage('');try{const result=await reconcileFabrication(actorId,receipt.request_id,cancel,controller.signal,undefined,()=>session.current(ticket,actualRoute()));if(!session.current(ticket,actualRoute()))return;if(result.status==='unknown'||result.status==='pending')setMessage('This save is not confirmed yet. Check again, or cancel the pending save before starting a replacement.');else{finishFabricationSave(receipt);setReceipt(null);setMessage(result.status==='applied'?'The change completed. Refreshing the parts you can currently access.':'The pending save was cancelled. You can start a new change.');onResolved();}}catch(e){if(session.current(ticket,actualRoute()))setError((e as Error).message);}finally{session.release(controller);checking.current=false;if(session.current(ticket,actualRoute()))setBusy(false);}}
 return <>{message&&<p className="fab-notice" role="status">{message}</p>}{error&&<p className="fab-error" role="alert">{error}</p>}{receipt&&<section className="fab-recovery" aria-label="Pending fabrication save"><strong>One change needs checking</strong><p>A response is pending or was interrupted. New changes are paused until its result is known. A private receipt lets you check the result without submitting the files or draft again.</p><div className="fab-actions"><button disabled={busy} onClick={()=>void recover(false)}>{busy?'Checking…':'Check save status'}</button><button disabled={busy} onClick={()=>void recover(true)}>Cancel pending save</button></div><small>{!fabricationStorageAvailable()&&'Browser storage is unavailable. Keep this tab open until the save is resolved. '}Cancel stops a save that has not completed. It does not undo a completed change.</small></section>}</>;
}
