import {useEffect,useId,useRef,useState,type ReactNode} from 'react';
import {ClipboardCheck,PackageCheck,Plus,RefreshCw,Wrench,X} from 'lucide-react';
import type {Task} from '../service';
import {taskStatuses} from '../service';
import {fabricationStatuses} from '../../fabrication/model';
import type {AssemblyAction,AssemblyComponent,AssemblyContext,AssemblyPayload,AssemblyCheck,CheckInput,ComponentInput} from './types';
import {componentStatuses,checkKinds,checkOutcomes,validateComponent,validateCheck,isStaleCheck,latestChecks,snapshotText} from './model';
import {AssemblyServiceError,loadAssembly,mutateAssembly,reconcileAssembly} from './service';
import {pendingAssemblySave,rememberAssemblySave,finishAssemblySave,assemblyStorageAvailable} from './session';
import './assembly.css';

type Edit={kind:'component';value:AssemblyComponent|null}|{kind:'check';value:AssemblyCheck|null}|{kind:'snapshot'}|{kind:'tasks'};
export function Assembly({actorId,boardId,route,onTask}:{actorId:string;boardId:string;route:string;onTask:(task:Task)=>void}){
 const [data,setData]=useState<AssemblyContext|null>(null),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[edit,setEdit]=useState<Edit|null>(null),[pending,setPending]=useState(()=>pendingAssemblySave(actorId));
 const live=useRef(true),epoch=useRef(0),requests=useRef(new Set<AbortController>()),saving=useRef(false),editor=useRef<Edit|null>(null);editor.current=edit;
 const current=()=>live.current&&location.hash===route;
 const controller=()=>{const c=new AbortController();requests.current.add(c);return c;};
 async function refresh(){const g=++epoch.current,c=controller();setLoading(true);setError('');try{const value=await loadAssembly(actorId,boardId,c.signal,undefined,()=>current()&&epoch.current===g);if(current()&&epoch.current===g)setData(value);}catch(e){if(current()&&epoch.current===g){setData(null);setError((e as Error).message);}}finally{requests.current.delete(c);if(current()&&epoch.current===g)setLoading(false);}}
 useEffect(()=>{live.current=true;void refresh();const changed=()=>setPending(pendingAssemblySave(actorId));window.addEventListener('assembly-receipt-change',changed);return()=>{live.current=false;epoch.current++;requests.current.forEach(c=>c.abort());requests.current.clear();window.removeEventListener('assembly-receipt-change',changed);};},[actorId,boardId,route]);
 function close(){setEdit(null);editor.current=null;requests.current.forEach(c=>c.abort());requests.current.clear();if(saving.current){setFeedback('The editor was closed. Check the pending save before making another change.');}}
 function open(next:Edit){if(pendingAssemblySave(actorId)){setError('Check the pending save before making another change.');return;}setError('');setFeedback('');setEdit(next);}
 async function save(action:AssemblyAction,input:Record<string,unknown>){if(!data||saving.current||pendingAssemblySave(actorId)||!current())return;const captured=editor.current,c=controller(),mutation={action,request_id:crypto.randomUUID(),expected_actor:actorId,p:{...input,board_id:boardId,version:data.version} as AssemblyPayload};saving.current=true;setBusy(true);setError('');setFeedback('');try{rememberAssemblySave(mutation);const result=await mutateAssembly(mutation,c.signal,undefined,()=>current()&&editor.current===captured);if(result.status==='unknown')throw new AssemblyServiceError('The save result is unconfirmed. Check its status before making another change.','unknown');if(result.status==='applied'||result.status==='cancelled')finishAssemblySave(mutation);if(current()&&editor.current===captured){setEdit(null);editor.current=null;setFeedback(result.status==='applied'?'Saved. The project record has been refreshed.':'The request was cancelled.');await refresh();}}catch(e){if(e instanceof AssemblyServiceError&&e.outcome==='rejected')finishAssemblySave(mutation);if(current())setError((e as Error).message);}finally{requests.current.delete(c);saving.current=false;if(current()){setBusy(false);setPending(pendingAssemblySave(actorId));}}}
 async function recover(cancel=false){if(!pending||saving.current)return;const c=controller();saving.current=true;setBusy(true);setError('');try{const result=await reconcileAssembly(actorId,pending.request_id,cancel,c.signal,undefined,current);if(result.status==='unknown'){setFeedback('No committed result was found. Check again, or cancel this pending request before starting a new change.');}else{finishAssemblySave(pending);setEdit(null);editor.current=null;setFeedback(result.status==='applied'?'The earlier save completed.':'The pending request is cancelled.');await refresh();}}catch(e){if(current())setError((e as Error).message);}finally{requests.current.delete(c);saving.current=false;if(current()){setBusy(false);setPending(pendingAssemblySave(actorId));}}}
 const canEdit=!!data?.can_edit&&!busy&&!loading&&!pending;
 return <section className="assembly" aria-label="Project assembly and testing"><header className="assembly-heading"><div><span className="assembly-eyebrow">From parts to a tested subsystem</span><h3>Assembly & testing</h3><p>Track what is on hand, the work still open, and the evidence from each check.</p></div><button disabled={loading||busy} onClick={()=>void refresh()}><RefreshCw size={15}/>Refresh assembly</button></header>
 {pending&&<aside className="assembly-notice" aria-label="Pending assembly save"><strong>A save needs to be checked</strong><p>Its result is unconfirmed. Check before creating another change.{!assemblyStorageAvailable()?' Keep this tab open until the result is resolved.':''}</p><div className="assembly-actions"><button disabled={busy} onClick={()=>void recover()}>Check save status</button><button disabled={busy} onClick={()=>void recover(true)}>Cancel pending request</button></div></aside>}
 {error&&<p className="assembly-error" role="alert">{error}</p>}{feedback&&<p role="status" className="assembly-feedback">{feedback}</p>}{loading&&<p role="status">Loading assembly record…</p>}
 {data&&<><AssemblyFacts data={data} boardId={boardId} canEdit={canEdit} onTask={onTask} open={open} save={save}/> {edit&&<AssemblyEditor key={edit.kind+('value' in edit?edit.value?.id||'new':'')} edit={edit} data={data} busy={busy||!!pending} error={error} onClose={close} onSave={(action,p)=>void save(action,p)}/>}</>}
 </section>;
}
/** Shared presentation for the authenticated workspace and synthetic, read-only local previews. */
export function AssemblyFacts({data,boardId,canEdit,onTask,open,save}:{data:AssemblyContext;boardId:string;canEdit:boolean;onTask:(task:Task)=>void;open:(edit:Edit)=>void;save:(action:AssemblyAction,input:Record<string,unknown>)=>void}){
 const latest=latestChecks(data),linked=data.tasks.filter(t=>data.linked_task_ids.includes(t.id));
 return <><div className="assembly-metrics" aria-label="Project facts"><Metric icon={<Wrench size={18}/>} value={`${data.facts.parts_done}/${data.facts.parts_total}`} label="Parts made" note="Part records, current revisions"/><Metric icon={<PackageCheck size={18}/>} value={`${data.facts.components_available}/${data.facts.components_total}`} label="Components on hand" note="Manually recorded line items"/><Metric icon={<ClipboardCheck size={18}/>} value={`${data.facts.tasks_done}/${data.facts.tasks_total}`} label="Assembly tasks done" note={`${data.facts.tasks_blocked} blocked`}/><Metric icon={<ClipboardCheck size={18}/>} value={String(data.facts.checks_passed)} label="Current checks passed" note={`${data.facts.checks_failed} failed · ${data.facts.checks_blocked} blocked · ${data.facts.checks_stale} older revision`}/></div>
 <p className="assembly-caption">These are recorded facts, not an automatic readiness or performance judgment. No recorded checks means testing has not been documented here.</p>
 {!data.can_edit&&<p className="assembly-notice">The assigned project review team can update this record while the project and season are open.</p>}
 <div className="assembly-columns"><section className="assembly-panel"><div className="assembly-section-heading"><div><h4>Manufactured parts</h4><p>Source: this project's Fabrication record</p></div><a href={`#fabrication/projects/${boardId}`}>Open Fabrication →</a></div>{data.parts.length?<ul className="assembly-rows">{data.parts.map(p=><li key={p.id}><div><strong>{p.name}</strong><small>Revision {p.revision_number} · Qty {p.quantity}</small></div><span className={`assembly-badge ${p.status==='done'?'is-good':''}`}>{fabricationStatuses[p.status as keyof typeof fabricationStatuses]||p.status}</span></li>)}</ul>:<p className="assembly-empty">No manufactured parts recorded for this project yet.</p>}</section>
 <section className="assembly-panel"><div className="assembly-section-heading"><div><h4>Purchased components</h4><p>Needed, ordered, on hand, or installed</p></div>{data.can_edit&&<button disabled={!canEdit} onClick={()=>open({kind:'component',value:null})}><Plus size={15}/>Add component</button>}</div>{data.components.length?<ul className="assembly-rows">{data.components.map(c=><li key={c.id}><div>{data.can_edit?<button className="assembly-text-button" disabled={!canEdit} onClick={()=>open({kind:'component',value:c})}>{c.name}</button>:<strong>{c.name}</strong>}<small>Qty {c.quantity}{c.notes?` · ${c.notes}`:''}</small></div><span className={`assembly-badge ${['received','installed'].includes(c.status)?'is-good':''}`}>{componentStatuses[c.status]}</span></li>)}</ul>:<p className="assembly-empty">Add the purchased parts this assembly still needs.</p>}<p className="assembly-caption">Manual project status only. Inventory quantities and purchasing records stay unchanged.</p></section></div>
 <section className="assembly-panel"><div className="assembly-section-heading"><div><h4>Assembly tasks & blockers</h4><p>Linked directly to the existing Planning tasks, owners, and due dates</p></div>{data.can_edit&&<button disabled={!canEdit} onClick={()=>open({kind:'tasks'})}>Link Planning task</button>}</div>{linked.length?<div className="assembly-task-grid">{linked.map(t=><article key={t.id} className={`assembly-task ${t.status==='blocked'?'is-blocked':''}`}><div className="assembly-section-heading"><button className="assembly-text-button" onClick={()=>onTask(t)}>{t.title}</button><span className={`assembly-badge ${t.status==='done'?'is-good':''}`}>{taskStatuses[t.status as keyof typeof taskStatuses]||t.status}</span></div><p>{t.owners.length?t.owners.map(o=>o.name).join(', '):'No owner assigned'}{t.due_date?` · Due ${t.due_date}`:''}</p>{t.status==='blocked'&&t.blocked_reason&&<p className="assembly-blocker">{t.blocked_reason}</p>}{data.can_edit&&<button className="assembly-text-button assembly-subtle" disabled={!canEdit} onClick={()=>void save('task_link',{task_id:t.id,linked:false})}>Unlink from assembly</button>}</article>)}</div>:<p className="assembly-empty">Link existing tasks for assembly and rework. Create or assign tasks using the project's normal Planning controls.</p>}</section>
 <section className="assembly-panel"><div className="assembly-section-heading"><div><h4>Fit checks & test results</h4><p>Record the method, expected result, observation, and evidence</p></div>{data.can_edit&&<button disabled={!canEdit} onClick={()=>open({kind:'check',value:null})}><Plus size={15}/>Record a check</button>}</div>{latest.length?<div className="assembly-check-grid">{latest.map(check=><CheckCard key={check.id} check={check} data={data} onTask={onTask} onRevise={data.can_edit?()=>open({kind:'check',value:check}):undefined} disabled={!canEdit}/>)}</div>:<p className="assembly-empty">No checks recorded. A completed part does not establish fit or subsystem performance.</p>}{data.checks.length>latest.length&&<details className="assembly-history"><summary>Previous check records ({data.checks.length-latest.length})</summary>{data.checks.filter(c=>!latest.some(l=>l.id===c.id)).map(c=><CheckCard key={c.id} check={c} data={data} onTask={onTask} disabled/>)}</details>}</section>
 <section className="assembly-panel assembly-review"><div className="assembly-section-heading"><div><span className="assembly-eyebrow">Saturday Sprint Review</span><h4>Freeze the facts for discussion</h4><p>Capture a dated snapshot, then explicitly add it to a weekly update. Later assembly changes do not rewrite a saved update or exported deck.</p></div>{data.can_edit&&<button className="planning-primary" disabled={!canEdit} onClick={()=>open({kind:'snapshot'})}>Capture review snapshot</button>}</div>{data.snapshots.length?<details open><summary>Latest snapshot · {formatTime(data.snapshots[0].created_at)}</summary><p className="assembly-caption">Snapshot {data.snapshots[0].id}</p><pre className="assembly-snapshot-text">{snapshotText(data.snapshots[0])}</pre><a href="#planning/reviews">Open Sprint Review →</a>{data.snapshots.length>1&&<details><summary>Earlier snapshots ({data.snapshots.length-1})</summary>{data.snapshots.slice(1).map(s=><div className="assembly-old-snapshot" key={s.id}><strong>{formatTime(s.created_at)}</strong><pre className="assembly-snapshot-text">{snapshotText(s)}</pre></div>)}</details>}</details>:<p className="assembly-empty">No review snapshot yet. This creates a meeting reference, not a readiness sign-off.</p>}</section>
</>;
}
function formatTime(v:string){return new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});}
function Metric({icon,value,label,note}:{icon:ReactNode;value:string;label:string;note:string}){return <div className="assembly-metric"><div>{icon}<span>{label}</span></div><strong>{value}</strong><small>{note}</small></div>;}
function CheckCard({check:c,data,onTask,onRevise,disabled}:{check:AssemblyCheck;data:AssemblyContext;onTask:(task:Task)=>void;onRevise?:()=>void;disabled:boolean}){const revision=data.revisions.find(r=>r.id===c.revision_id),task=data.tasks.find(t=>t.id===c.rework_task_id),stale=isStaleCheck(c,data);return <article className={`assembly-check ${c.outcome==='failed'?'is-failed':''}`}><div className="assembly-section-heading"><h5>{c.title}</h5><span className={`assembly-badge ${c.outcome==='passed'&&!stale?'is-good':c.outcome==='failed'?'is-alert':''}`}>{checkOutcomes[c.outcome]}</span></div><p className="assembly-caption">{checkKinds[c.kind]} · {revision?`${revision.name}, revision ${revision.revision_number}`:'Project / subsystem'} · {formatTime(c.created_at)}</p>{stale&&<p className="assembly-revision-warning">Older part revision. This result does not establish the current revision's performance.</p>}<dl><div><dt>Method</dt><dd>{c.procedure}</dd></div><div><dt>Expected</dt><dd>{c.expected}</dd></div><div><dt>Observed</dt><dd>{c.observed}</dd></div></dl><div className="assembly-actions">{c.evidence_url&&<a href={c.evidence_url} target="_blank" rel="noopener noreferrer">Open evidence ↗</a>}{task?<button className="assembly-text-button" onClick={()=>onTask(task)}>Rework: {task.title}</button>:c.rework_task_id?<span className="assembly-caption">The linked rework task is no longer available in this project.</span>:null}{onRevise&&<button disabled={disabled} onClick={onRevise}>Record follow-up check</button>}</div>{c.supersedes_id&&<small>Follows an earlier immutable check record.</small>}</article>;}
function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null),id=useId();useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>{ref.current?.close();if(previous?.isConnected)previous.focus();};},[]);return <dialog ref={ref} className="assembly-dialog" aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose();}}><header><h3 id={id}>{title}</h3><button aria-label="Close assembly editor" type="button" onClick={onClose}><X size={18}/></button></header>{children}</dialog>;}
function AssemblyEditor({edit,data,busy,error,onClose,onSave}:{edit:Edit;data:AssemblyContext;busy:boolean;error:string;onClose:()=>void;onSave:(action:AssemblyAction,p:Record<string,unknown>)=>void}){
 const [component,setComponent]=useState<ComponentInput>(()=>edit.kind==='component'&&edit.value?{id:edit.value.id,name:edit.value.name,quantity:edit.value.quantity,status:edit.value.status,notes:edit.value.notes}:{id:crypto.randomUUID(),name:'',quantity:1,status:'needed',notes:''});
 const [check,setCheck]=useState<CheckInput>(()=>edit.kind==='check'&&edit.value?{...edit.value,id:crypto.randomUUID(),outcome:'blocked',observed:'',evidence_url:'',supersedes_id:edit.value.id}:{id:crypto.randomUUID(),title:'',kind:'fit',outcome:'blocked',procedure:'',expected:'',observed:'',evidence_url:'',revision_id:null,rework_task_id:null,supersedes_id:null});
 const [notes,setNotes]=useState(''),[task,setTask]=useState(''),[validation,setValidation]=useState(''),snapshotId=useRef(crypto.randomUUID());
 const change=<K extends keyof CheckInput>(key:K,value:CheckInput[K])=>setCheck(c=>({...c,[key]:value}));
 const title=edit.kind==='component'?(edit.value?'Update component':'Add purchased component'):edit.kind==='check'?(edit.value?'Record follow-up check':'Record a check'):edit.kind==='tasks'?'Link a Planning task':'Capture review snapshot';
 function submit(){if(busy)return;if(edit.kind==='component'){const issue=validateComponent(component);setValidation(issue||'');if(!issue)onSave('component',component);}else if(edit.kind==='check'){const p:CheckInput={id:check.id,title:check.title,kind:check.kind,outcome:check.outcome,procedure:check.procedure,expected:check.expected,observed:check.observed,evidence_url:check.evidence_url,revision_id:check.revision_id,rework_task_id:check.outcome==='passed'?null:check.rework_task_id,supersedes_id:check.supersedes_id};const issue=validateCheck(p);setValidation(issue||'');if(!issue)onSave('check',p);}else if(edit.kind==='tasks'){if(task)onSave('task_link',{task_id:task,linked:true});else setValidation('Choose an existing Planning task.');}else onSave('snapshot',{id:snapshotId.current,notes});}
 return <Dialog title={title} onClose={onClose}><form onSubmit={e=>{e.preventDefault();submit();}}>{(validation||error)&&<p className="assembly-error" role="alert">{validation||error}</p>}<fieldset disabled={busy} className="assembly-fields">
 {edit.kind==='component'&&<><label>Component name<input autoFocus required maxLength={200} value={component.name} onChange={e=>setComponent(c=>({...c,name:e.target.value}))}/></label><div className="assembly-form-grid"><label>Quantity needed<input type="number" required min={1} max={100000} step={1} value={component.quantity} onChange={e=>setComponent(c=>({...c,quantity:Number(e.target.value)}))}/></label><label>Component status<select value={component.status} onChange={e=>setComponent(c=>({...c,status:e.target.value as ComponentInput['status']}))}>{Object.entries(componentStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label>Component notes<textarea maxLength={2000} rows={3} placeholder="Supplier, specification, or what is still needed" value={component.notes} onChange={e=>setComponent(c=>({...c,notes:e.target.value}))}/></label><p className="assembly-caption">Received or installed means the full quantity for this line is available. For partial arrivals, keep the line Needed or Ordered and explain the remainder in notes.</p></>}
 {edit.kind==='check'&&<><p className="assembly-caption">Each result is preserved. A follow-up check supersedes the earlier result without changing its history.</p><label>Check title<input autoFocus required maxLength={200} value={check.title} onChange={e=>change('title',e.target.value)}/></label><div className="assembly-form-grid"><label>Check type<select value={check.kind} onChange={e=>change('kind',e.target.value as CheckInput['kind'])}>{Object.entries(checkKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Result<select value={check.outcome} onChange={e=>{change('outcome',e.target.value as CheckInput['outcome']);if(e.target.value==='passed')change('rework_task_id',null);}}>{Object.entries(checkOutcomes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label>Part revision<select disabled={!!check.supersedes_id} value={check.revision_id||''} onChange={e=>change('revision_id',e.target.value||null)}><option value="">Project / subsystem check</option>{data.revisions.map(r=><option key={r.id} value={r.id}>{r.name} · Revision {r.revision_number}{data.parts.some(p=>p.current_revision_id===r.id)?' · current':' · older revision'}</option>)}</select></label>{check.revision_id&&!data.parts.some(p=>p.current_revision_id===check.revision_id)&&<p className="assembly-revision-warning">This is an older revision. The result will be retained as historical evidence.</p>}<label>Method / test conditions<textarea required maxLength={2000} rows={3} value={check.procedure} onChange={e=>change('procedure',e.target.value)}/></label><label>Expected result<textarea required maxLength={2000} rows={2} value={check.expected} onChange={e=>change('expected',e.target.value)}/></label><label>Observed result<textarea required maxLength={2000} rows={3} value={check.observed} onChange={e=>change('observed',e.target.value)}/></label><label>Evidence link <span>(optional)</span><input type="url" maxLength={2000} placeholder="https://…" value={check.evidence_url} onChange={e=>change('evidence_url',e.target.value)}/></label><p className="assembly-caption">Use an existing team-accessible link. Adding it does not upload files or change who can open them.</p>{check.outcome!=='passed'&&<label>Rework task <span>(optional)</span><select value={check.rework_task_id||''} onChange={e=>change('rework_task_id',e.target.value||null)}><option value="">No task linked yet</option>{data.tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>}</>}
 {edit.kind==='tasks'&&<><p>Link an existing task from this project. Its owners, status, due date, and blockers remain in Planning.</p><label>Planning task<select autoFocus required value={task} onChange={e=>setTask(e.target.value)}><option value="">Choose task</option>{data.tasks.filter(t=>!data.linked_task_ids.includes(t.id)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label></>}
 {edit.kind==='snapshot'&&<><p>This saves the current counts and timestamp for your Saturday discussion. Nothing is inserted into a review or deck until you choose that snapshot in the weekly update.</p><label>Discussion notes <span>(optional)</span><textarea autoFocus maxLength={2000} rows={4} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What do these results mean? What should the team discuss?"/></label></>}
 </fieldset><footer><button type="button" onClick={onClose}>Close</button><button className="planning-primary" type="submit" disabled={busy}>{busy?'Saving…':edit.kind==='snapshot'?'Capture snapshot':'Save'}</button>{busy&&<small role="status">Closing clears the draft. Check the save result from the project.</small>}</footer></form></Dialog>;
}
