import {useState} from 'react';
import {localDate,taskStatuses,type Context,type Task} from './service';
import {DependencyHint} from './TaskDependencies';
const day=86400000,stamp=(s:string)=>Date.parse(s+'T00:00:00Z');
export function BoardGantt({tasks,data,onOpen}:{tasks:Task[];data:Context;onOpen:(t:Task)=>void}){
 const [scale,setScale]=useState('week');const dates=tasks.flatMap(t=>[t.start_date,t.due_date].filter((d):d is string=>!!d));
 if(!dates.length)return <div className="planning-empty"><p>No timelines yet. Set dates in Table; undated tasks remain available below.</p>{tasks.map(t=><p key={t.id}><button onClick={()=>onOpen(t)}>{t.title}</button><DependencyHint task={t} data={data}/></p>)}</div>;
 const start=Math.min(...dates.map(stamp))-day*2,end=Math.max(...dates.map(stamp))+day*3,days=Math.round((end-start)/day),unit=scale==='day'?34:14,width=Math.max(600,days*unit),height=tasks.length*52+40;
 const x=(s:string)=>(stamp(s)-start)/day*unit,today=x(localDate());
 const barWidth=(t:Task)=>t.start_date?Math.max(28,x(t.due_date!)-x(t.start_date)+unit):24;
 return <><label className="planning-scale">Timeline scale<select value={scale} onChange={e=>setScale(e.target.value)}><option value="week">Weeks</option><option value="day">Days</option></select></label><div className="planning-gantt" role="region" tabIndex={0} aria-label="Board Gantt; scroll horizontally for dates"><div style={{position:'relative',width:width+220,height}}>
 <div className="planning-gantt-labels"><div className="planning-axis">Tasks</div>{tasks.map(t=><div className="planning-gantt-label" key={t.id} data-task-id={t.id}><button onClick={()=>onOpen(t)}>{t.title}</button><small>{taskStatuses[t.status as keyof typeof taskStatuses]} · {data.members.find(m=>m.id===t.owner_id)?.name||'Unassigned'}{!t.due_date?(t.start_date?' · No end date':' · No dates'):!t.start_date?' · Deadline only':''}</small></div>)}</div>
 <div className="planning-timeline" style={{left:220,width,height}}><svg className="planning-lines" aria-hidden="true" width={width} height={height}><defs><marker id="board-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="currentColor"/></marker></defs>{(data.dependencies||[]).map(d=>{const a=tasks.findIndex(t=>t.id===d.predecessor_task_id),z=tasks.findIndex(t=>t.id===d.successor_task_id);if(a<0||z<0||!tasks[a].due_date||!tasks[z].due_date)return null;const ax=x((tasks[a].start_date||tasks[a].due_date)!)+barWidth(tasks[a]),zx=x((tasks[z].start_date||tasks[z].due_date)!);return <path key={d.id} data-dependency-id={d.id} d={`M${ax} ${a*52+62} H${ax+8} V${z*52+62} H${zx}`} stroke="currentColor" fill="none" markerEnd="url(#board-arrow)"/>;})}</svg>
 {Array.from({length:Math.ceil(days/(scale==='day'?1:7))},(_,n)=>{const d=n*(scale==='day'?1:7);return <span className="planning-tick" key={n} style={{left:d*unit,height}}>{new Date(start+d*day).toLocaleDateString(undefined,{month:'short',day:'numeric',timeZone:'UTC'})}</span>;})}
 {today>=0&&today<=width&&<span className="planning-today" aria-label="Today" style={{left:today,height}}><span>Today</span></span>}
 {tasks.map((t,n)=>t.due_date?<button key={t.id} data-task-id={t.id} className={`planning-bar ${t.status} ${t.start_date?'':'milestone'}`} style={{top:n*52+48,left:x(t.start_date||t.due_date),width:barWidth(t)}} aria-label={`Open ${t.title}`} title={`${t.title}: ${t.start_date||'No start'} → ${t.due_date}; ${taskStatuses[t.status as keyof typeof taskStatuses]}`} onClick={()=>onOpen(t)}>{t.start_date?t.title:'◆'}</button>:<span className="planning-unscheduled" key={t.id} style={{position:'absolute',top:n*52+48,left:8}}>{t.start_date?`Starts ${t.start_date} · no end date`:'No dates'}</span>)}
 </div></div></div><p className="planning-hint">◆ Deadline only. Arrows show dependencies, not automatic scheduling. Dependency names are available in task details.</p></>;
}
