import {TaskDependencies} from './TaskDependencies';
import {useEffect,useRef,useState} from 'react';
import {type Context,type Detail,type Task,savePlanning,taskDetail,planStatuses,taskStatuses,priorities} from './service';
export type Edit={entity:'season'|'group'|'board'|'item'|'task';p:Record<string,unknown>};
export function Editor({edit,data,onClose,onSaved}:{edit:Edit;data:Context;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [p,setP]=useState(edit.p),[error,setError]=useState(''),[busy,setBusy]=useState(false),[detail,setDetail]=useState<Detail|null>(null),[step,setStep]=useState(''),[comment,setComment]=useState('');
 const returnFocus=useRef(document.activeElement as HTMLElement);
 const dialog=useRef<HTMLDialogElement>(null),entity=edit.entity,isTask=entity==='task',existing=!!p.id;
 const season=data.seasons.find(s=>s.id===data.season_id),board=data.boards.find(b=>b.id===p.board_id);
 const editable=(data.can_manage||isTask&&p.owner_id===data.user_id)&&!(season?.status==='archived'&&(!isTask||board?.kind!=='area'))&&(!isTask||board?.active!==false);
 const canComment=isTask&&existing&&board?.active!==false&&(board?.kind==='area'||season?.status==='active'||data.can_manage&&season?.status==='draft');
 const set=(key:string,value:unknown)=>setP(p=>({...p,[key]:value}));
 useEffect(()=>{const node=dialog.current;node?.showModal();return()=>{node?.close();returnFocus.current?.focus();};},[]);
 useEffect(()=>{if(isTask&&p.id)void taskDetail(String(p.id)).then(setDetail).catch(e=>setError(e.message));},[isTask,p.id]);
 async function submit(){setBusy(true);setError('');try{const payload={...p};if(entity==='board'&&payload.kind==='area')payload.season_id=null;if(entity==='item'&&payload.kind==='milestone')payload.end_date=payload.start_date;await savePlanning(entity,payload);await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function extra(kind:'step'|'comment',payload:Record<string,unknown>){setBusy(true);setError('');try{await savePlanning(kind,{...payload,task_id:p.id});setDetail(await taskDetail(String(p.id)));if(kind==='step')setStep('');else setComment('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const input=(key:string,label:string,type='text',required=false)=><label key={key}>{label}<input type={type} required={required} maxLength={type==='text'?200:undefined} value={String(p[key]??'')} onChange={e=>set(key,type==='number'?Number(e.target.value):e.target.value)} /></label>;
 const select=(key:string,label:string,options:Record<string,string>,optional=false,disabled=false)=><label key={key}>{label}<select disabled={disabled} value={String(p[key]??'')} onChange={e=>set(key,e.target.value||null)}>{optional&&<option value="">Unassigned</option>}{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;
 const named=(xs:{id:string;name:string}[])=>Object.fromEntries(xs.map(x=>[x.id,x.name]));
 const activeBoards=data.boards.filter(b=>b.active||b.id===p.board_id);
 return <dialog ref={dialog} className="planning-dialog" aria-labelledby="planning-editor-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}>
 <h2 id="planning-editor-title">{existing?'Edit':'New'} {entity==='item'?(p.kind==='milestone'?'milestone':'item'):entity}</h2>
 {error&&<p role="alert">{error}</p>}
 <form onSubmit={e=>{e.preventDefault();void submit();}}><fieldset disabled={!editable||busy} style={{border:0,padding:0,margin:0}}><div className="planning-form">
 {isTask&&<h3 className="wide planning-form-heading">Task</h3>}
 {input(entity==='task'||entity==='item'?'title':'name',entity==='task'||entity==='item'?'Title':'Name','text',true)}
 {entity==='season'&&<>{select('status','Season status',{draft:'Draft',active:'Active',archived:'Archived'})}{input('start_date','Start date','date')}{input('end_date','Target date','date')}<p className="wide planning-hint">Only one season can be active. Archive the current season before activating another. Archived season plans and project boards are read only.</p></>}
 {(entity==='item'||entity==='board'||isTask)&&<label className="wide">Description<textarea maxLength={5000} value={String(p.description??'')} onChange={e=>set('description',e.target.value)}/></label>}
 {entity==='group'&&existing&&<>{select('active','Group state',{'true':'Active','false':'Archived'})}</>}
 {entity==='board'&&<>{select('kind','Board type',{project:'Project',area:'Functional Area'},false,existing)}{(p.kind==='area'||existing&&p.area_id)&&select('area_id','Functional area',named(data.areas),true)}{existing&&select('active','Board state',{'true':'Active','false':'Archived'})}<p className="wide planning-hint">Functional Area boards stay available across seasons. Project boards belong to this season.</p></>}
 {entity==='item'&&<>{select('kind','Item type',{work:'Work item',milestone:'Milestone'})}{select('status','Status',planStatuses)}{input('start_date',p.kind==='milestone'?'Milestone date':'Start date','date',true)}{p.kind!=='milestone'&&input('end_date','End date','date',true)}{select('group_id','Group',named(data.groups.filter(g=>g.active||g.id===p.group_id)),true)}{select('board_id','Linked board',named(activeBoards),true)}{select('owner_id','Owner',named(data.members),true)}{select('area_id','Responsible area',named(data.areas),true)}{select('predecessor_id','Starts after',Object.fromEntries(data.items.filter(i=>i.id!==p.id).map(i=>[i.id,i.title])),true)}<p className="wide planning-hint">Finish-to-start dependency only. Changing dates will not move other items.</p></>}
 {isTask&&<><h3 className="wide planning-form-heading">Planning</h3>{select('status','Status',taskStatuses)}{select('priority','Priority',priorities)}{select('owner_id','Owner',named(data.members),true,!data.can_manage)}{select('area_id','Functional area',named(data.areas),true,!data.can_manage)}{input('start_date','Start date','date')}{input('due_date','Due date','date')}{p.status==='blocked'&&input('blocked_reason','What is blocking this task?')}</>}
 </div></fieldset><div className="planning-toolbar"><button type="button" disabled={busy} onClick={onClose}>Close</button>{editable&&<button className="planning-primary" type="submit" disabled={busy}>{busy?'Saving…':'Save'}</button>}</div></form>
 {isTask&&existing&&<><TaskDependencies task={p as Task} data={data} editable={!!editable&&data.can_manage&&!busy} onChanged={async()=>{await onSaved();setDetail(await taskDetail(String(p.id)));}}/><h3>Checklist</h3>{!detail?<p>Loading task details…</p>:<><ul className="planning-detail-list">{detail.steps.map(s=><li key={s.id}><label><input type="checkbox" checked={s.done} disabled={!editable||busy} onChange={e=>void extra('step',{...s,done:e.target.checked})}/>{s.text}</label></li>)}</ul>{!detail.steps.length&&<p>Break this task into smaller checks with Add step.</p>}</>}
 {editable&&<form className="planning-toolbar" onSubmit={e=>{e.preventDefault();void extra('step',{text:step,display_order:detail?.steps.length||0});}}><label>New checklist step<input required maxLength={500} value={step} onChange={e=>setStep(e.target.value)}/></label><button disabled={busy}>Add step</button></form>}
 <h3>Comments</h3>{detail&&!detail.comments.length&&<p className="planning-hint">No comments yet. Share progress or a question here.</p>}<ul className="planning-detail-list">{detail?.comments.map(c=><li key={c.id}><p>{c.text}</p><small>{data.members.find(m=>m.id===c.author_id)?.name||'Team member'} · {new Date(c.created_at).toLocaleString()}</small></li>)}</ul>{canComment&&<form onSubmit={e=>{e.preventDefault();void extra('comment',{text:comment});}}><label>Add a comment<textarea required maxLength={5000} value={comment} onChange={e=>setComment(e.target.value)}/></label><button disabled={busy}>Post comment</button></form>}
 <details><summary>Task activity</summary><ul className="planning-detail-list">{detail?.history.map(h=><li key={h.id}>{h.entity==='task'?h.action==='created'?'Task created':Object.keys(h.after_data).filter(k=>!['version','updated_at'].includes(k)&&JSON.stringify(h.before_data?.[k])!==JSON.stringify(h.after_data[k])).map(k=>k.replaceAll('_',' ')).join(', ')+' changed':`${h.entity==='dependency'?'Dependency':h.entity==='step'?'Checklist step':'Comment'} ${h.action}`}{h.entity==='dependency'&&<span> · {String((h.after_data||h.before_data)?.predecessor_title||'Task')} → {String((h.after_data||h.before_data)?.successor_title||'Task')}</span>}<small>{data.members.find(m=>m.id===h.actor_id)?.name||'Team member'} · {new Date(h.created_at).toLocaleString()}</small></li>)}</ul></details></>}
 </dialog>;
}
