import {useRef,useState} from 'react';
export type Commit=(patch:Record<string,unknown>)=>Promise<boolean|undefined>;
export function InlineTitle({title,disabled,onSave,onDetails}:{title:string;disabled:boolean;onSave:Commit;onDetails?:()=>void}){
 const [open,setOpen]=useState(false),[value,setValue]=useState(title);const trigger=useRef<HTMLButtonElement>(null);
 function close(){setOpen(false);setValue(title);requestAnimationFrame(()=>trigger.current?.focus());}
 return <div className="planning-inline planning-inline-title"><button ref={trigger} hidden={open} disabled={disabled} onClick={()=>{setValue(title);setOpen(true);}}>{title}</button>{onDetails&&!open&&<button className="planning-details-button" aria-label={`Details for ${title}`} onClick={onDetails}>↗</button>}{open&&<form onSubmit={async e=>{e.preventDefault();if(value.trim()&&await onSave({title:value.trim()}))close();else setValue(title);}} onKeyDown={e=>{if(e.key==='Escape'&&!disabled){e.preventDefault();close();}}}><label>Title<input autoFocus required maxLength={200} disabled={disabled} value={value} onChange={e=>setValue(e.target.value)}/></label><button disabled={disabled||!value.trim()}>{disabled?'Saving…':'Save title'}</button><button type="button" disabled={disabled} onClick={close}>Cancel</button></form>}</div>;
}
export function InlineTimeline({title,start,end,milestone=false,required=false,disabled,onSave}:{title:string;start:string|null;end:string|null;milestone?:boolean;required?:boolean;disabled:boolean;onSave:(start:string|null,end:string|null)=>Promise<boolean|undefined>}){
 const [open,setOpen]=useState(false),[a,setA]=useState(start||''),[z,setZ]=useState(end||'');const trigger=useRef<HTMLButtonElement>(null);
 function close(){setOpen(false);requestAnimationFrame(()=>trigger.current?.focus());}
 return <div className="planning-inline"><button ref={trigger} aria-label={`Timeline for ${title}`} disabled={disabled} onClick={()=>{setA(start||'');setZ(end||'');setOpen(!open);}}>{start||'No start'} → {end||'No end'}</button>{open&&<form onSubmit={async e=>{e.preventDefault();if(await onSave(a||null,milestone?a||null:z||null))close();else{setA(start||'');setZ(end||'');}}} onKeyDown={e=>{if(e.key==='Escape'&&!disabled){e.preventDefault();close();}}}><label>Start<input autoFocus type="date" required={required} disabled={disabled} value={a} onChange={e=>setA(e.target.value)}/></label>{!milestone&&<label>End<input type="date" required={required} min={a||undefined} disabled={disabled} value={z} onChange={e=>setZ(e.target.value)}/></label>}<button disabled={disabled}>{disabled?'Saving…':'Save timeline'}</button><button type="button" disabled={disabled} onClick={close}>Cancel</button></form>}</div>;
}
