import {OwnerPicker,OwnerSummary} from './Owners';
import {ContextActions} from './ContextActions';
import {BoardGantt} from './BoardGantt';
import {InlineTitle,InlineTimeline} from './InlineFields';
import {DependencyHint} from './TaskDependencies';
import {QuickAdd} from './QuickAdd';
import {SeasonTable} from './SeasonTable';
import {nextOrder} from './plan-groups';
import {ChartNoAxesGantt,Columns3,ListTodo,Plus,RefreshCw} from 'lucide-react';
import {BoardSummary} from './BoardSummary';
import {useEffect,useRef,useState} from 'react';
import {loadPlanning,savePlanning,localDate,workGroup,taskStatuses,priorities,type Context,type Task,type Group,type Item,planStatuses} from './service';
import {Editor,type Edit} from './Editor';
import {PlanningDashboard} from './PlanningDashboard';
import {Gantt} from './Gantt';
import './planning.css';
export function Planning({route}:{route:string}){
 const [data,setData]=useState<Context|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<Edit|null>(null),[view,setView]=useState('table'),[planView,setPlanView]=useState('table');
 const [search,setSearch]=useState(''),[owner,setOwner]=useState(''),[area,setArea]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[feedback,setFeedback]=useState('');
 const generation=useRef(0),selected=useRef<string|null>(null);
 const tab=route.split('/')[1]||'dashboard',boardId=route.split('/')[2];
 async function refresh(sid=selected.current){const g=++generation.current;setError('');try{const c=await loadPlanning(sid,tab==='my-work');if(g===generation.current){setData(c);selected.current=c.season_id;}}catch(e){if(g===generation.current)setError((e as Error).message);}}
 useEffect(()=>{setData(null);void refresh();return()=>{generation.current++;};},[tab==='my-work']);
 useEffect(()=>{setSearch('');setOwner('');setArea('');setStatus('');setPriority('');setEdit(null);setFeedback('');},[boardId,tab]);
 const season=data?.seasons.find(s=>s.id===data.season_id),board=data?.boards.find(b=>b.id===boardId),readOnly=season?.status==='archived',manage=!!data?.can_manage;
 async function updateTask(t:Task,patch:Partial<Task>){if(busy)return;setBusy(true);setError('');setFeedback('');try{await savePlanning('task',{...t,...patch});await refresh();setFeedback('Task saved.');return true;}catch(e){await refresh();setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function updateItem(i:Item,patch:Partial<Item>){if(busy)return;setBusy(true);setError('');setFeedback('');try{await savePlanning('item',{...i,...patch});await refresh();setFeedback('Plan item saved.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const move=(t:Task,next:string)=>updateTask(t,{status:next});
 const openTask=(t:Task)=>setEdit({entity:'task',p:{...t}});
 const openBoard=(id:string)=>{location.hash=`planning/boards/${id}`;setSearch('');setOwner('');setArea('');setStatus('');setPriority('');};
 const defaults=(entity:Edit['entity'])=>({season_id:data?.season_id,status:entity==='season'?'draft':entity==='item'?'not_started':entity==='task'?'todo':'backlog',kind:entity==='board'?'project':'work',active:true,display_order:nextOrder(entity==='group'?data?.groups||[]:entity==='board'?data?.boards||[]:data?.items||[]),board_id:board?.id,priority:'normal',...(entity==='task'?{owner_ids:[]}:{owner_id:null}),area_id:null,start_date:entity==='item'?localDate():null,end_date:entity==='item'?localDate():null});
 const newEntity=(entity:Edit['entity'],overrides:Record<string,unknown>={})=>setEdit({entity,p:{...defaults(entity),...overrides}});
 const canCreateTask=manage&&!!board?.active&&(!readOnly||board.kind==='area');
 async function quickCreate(entity:'item'|'task',title:string,extra:Record<string,unknown>){await savePlanning(entity,{...defaults(entity),title,...extra});if(entity==='task'){setSearch('');setOwner('');setArea('');setStatus('');setPriority('');}await refresh();}
 async function orderGroup(group:Group,edge:'top'|'bottom'){
  if(busy||!data)return;const orders=data.groups.map(g=>g.display_order),order=edge==='top'?Math.min(...orders)-1:Math.max(...orders)+1;
  if(order< -2147483648||order>2147483647){setError('Group order limit reached. Refresh before trying again.');return;}
  setBusy(true);setError('');setFeedback('');try{await savePlanning('group',{...group,display_order:order});await refresh();setFeedback('Group order saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 const clearFilters=()=>{setSearch('');setOwner('');setArea('');setStatus('');setPriority('');};
 const filtersActive=!!(search||owner||area||status||priority);
 const canEdit=(t:Task)=>!!data&&(manage||t.owner_ids.includes(data.user_id))&&!!data.boards.find(b=>b.id===t.board_id&&b.active&&(b.kind==='area'||!readOnly));
 const statusControl=(t:Task)=><select aria-label={`Status for ${t.title}`} className="planning-status-select" data-status={t.status} value={t.status} disabled={!canEdit(t)||busy} onChange={e=>void move(t,e.target.value)}>{Object.entries(taskStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>;
 const name=(id:string|null,list:'members'|'areas')=>data?.[list].find(x=>x.id===id)?.name||'Unassigned';
 const card=(t:Task)=><article className={`planning-task ${t.status==='blocked'?'is-blocked':''}`} key={t.id} draggable={canEdit(t)} onDragStart={e=>e.dataTransfer.setData('application/x-planning-task',t.id)}><div className="planning-task-title">{canEdit(t)?<InlineTitle title={t.title} disabled={busy} onSave={p=>updateTask(t,p)} onDetails={()=>openTask(t)}/>:<button onClick={()=>openTask(t)}>{t.title}</button>}</div><div className="planning-task-meta"><OwnerSummary owners={t.owners}/><span className={`planning-badge priority-${t.priority}`}>{priorities[t.priority as keyof typeof priorities]}</span></div>{tab==='my-work'&&<small>{data?.boards.find(b=>b.id===t.board_id)?.name}</small>}{t.area_id&&<small>{name(t.area_id,'areas')}</small>}{t.due_date&&<small className={t.status!=='done'&&t.due_date<localDate()?'planning-overdue':''}>{t.status!=='done'&&t.due_date<localDate()?'Overdue · ':'Due '}{t.due_date}</small>}{t.status==='blocked'&&t.blocked_reason&&<small className="planning-blocked-reason">Blocked: {t.blocked_reason}</small>}{data&&<DependencyHint task={t} data={data}/ >}{statusControl(t)}</article>;
 const rows=(tasks:Task[])=><div className="planning-table-scroll"><table><thead><tr>{['Task','Owners','Status','Priority','Timeline','Area'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{tasks.map(t=><tr key={t.id} data-task-id={t.id}><td><>{canEdit(t)?<InlineTitle title={t.title} disabled={busy} onSave={p=>updateTask(t,p)} onDetails={()=>openTask(t)}/>:<button onClick={()=>openTask(t)}>{t.title}</button>}</>{data&&<DependencyHint task={t} data={data}/>}</td><td>{canEdit(t)&&manage?<OwnerPicker label={`Owners for ${t.title}`} ids={t.owner_ids} owners={t.owners} members={data!.members} disabled={busy} onSave={owner_ids=>updateTask(t,{owner_ids})}/>:<OwnerSummary owners={t.owners}/>}</td><td>{statusControl(t)}</td><td>{canEdit(t)?<select aria-label={`Priority for ${t.title}`} value={t.priority} disabled={busy} onChange={e=>void updateTask(t,{priority:e.target.value})}>{Object.entries(priorities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>:priorities[t.priority as keyof typeof priorities]}</td><td><InlineTimeline title={t.title} start={t.start_date} end={t.due_date} disabled={!canEdit(t)||busy} onSave={(start_date,due_date)=>updateTask(t,{start_date,due_date})}/></td><td>{canEdit(t)&&manage?<select aria-label={`Area for ${t.title}`} value={t.area_id||''} disabled={busy} onChange={e=>void updateTask(t,{area_id:e.target.value||null})}><option value="">Unassigned</option>{data?.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>:name(t.area_id,'areas')}</td></tr>)}</tbody></table>{!tasks.length&&<p className="planning-empty">No tasks match these filters.</p>}</div>;
 const planData=data?{...data,items:data.items.filter(i=>i.title.toLowerCase().includes(search.toLowerCase())&&(!owner||i.owner_id===owner)&&(!area||i.area_id===area)&&(!status||i.status===status))}:null;
 const tasks=(data?.tasks||[]).filter(t=>t.board_id===boardId&&t.title.toLowerCase().includes(search.toLowerCase())&&(!owner||t.owner_ids.includes(owner))&&(!area||t.area_id===area)&&(!status||t.status===status)&&(!priority||t.priority===priority));
 return <section className="planning"><header><div><span className="planning-eyebrow planning-page-eyebrow">Team workspace</span><h1>{({dashboard:'Planning',plan:'Season Plan',boards:'Boards','my-work':'My Work'} as Record<string,string>)[tab]||'Planning'}</h1><p>{tab==='dashboard'?'Season planning, project boards, and team assignments.':tab==='plan'?'Major work, milestones, and the season ahead.':tab==='boards'?'Projects and functional areas where the team gets work done.':'Everything assigned to you across the active season.'}</p></div>{data&&data.seasons.length>0&&<label>Planning season<select value={data.season_id||''} onChange={e=>{selected.current=e.target.value;setData(null);location.hash='planning';void refresh(e.target.value);}}>{data.seasons.map(s=><option key={s.id} value={s.id}>{s.name} · {s.status}</option>)}</select></label>}<button className="planning-refresh" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={15} aria-hidden="true"/>Refresh</button></header>
 {error&&<p className="planning-error" role="alert">{error}</p>}{!error&&(busy||feedback)&&<p className={`planning-save-feedback ${busy?'is-busy':''}`} role="status" aria-live="polite">{busy?'Saving changes…':feedback}</p>}{!data&&!error&&<p className="planning-loading" role="status">Loading Planning…</p>}
 {data&&<>
 {!season?<div className="planning-onboarding"><div className="planning-empty planning-welcome"><ChartNoAxesGantt size={32} aria-hidden="true"/><h2>No active planning season</h2><p>Create a season to build the master schedule, organize project boards, and assign work.</p>{manage?<button className="planning-primary" onClick={()=>newEntity('season')}><Plus size={16} aria-hidden="true"/>Create planning season</button>:<p>Leadership will share the season plan here.</p>}</div><div className="planning-intro-grid">{[{name:'Season Plan',icon:ChartNoAxesGantt,text:"Build the team's master Gantt, phases, dependencies and milestones."},{name:'Boards',icon:Columns3,text:'Run projects and functional areas with focused Kanban boards.'},{name:'My Work',icon:ListTodo,text:'See your assignments, deadlines and blocked work in one place.'}].map(x=><section key={x.name} className="planning-card"><x.icon size={22} aria-hidden="true"/><h3>{x.name}</h3><p>{x.text}</p></section>)}</div></div>:<>
 <div className="planning-toolbar planning-season-context">{tab!=='dashboard'&&<h2>{season.name}</h2>}{tab!=='dashboard'&&<span className="planning-badge">{season.status}</span>}{manage&&<details><summary>Season settings</summary><button disabled={readOnly} onClick={()=>setEdit({entity:'season',p:{...season}})}>Edit season</button><button onClick={()=>newEntity('season')}>Create season</button></details>}</div>
 {tab==='dashboard'&&<PlanningDashboard data={data} season={season} onTask={openTask} onBoard={openBoard}/>}
 {tab==='plan'&&<><div className="planning-toolbar"><div role="group" aria-label="Season Plan view"><button aria-pressed={planView==='table'} onClick={()=>setPlanView('table')}>Table</button><button aria-pressed={planView==='gantt'} onClick={()=>setPlanView('gantt')}>Gantt</button></div>{manage&&!readOnly&&<><button className="planning-primary" onClick={()=>newEntity('item')}>+ Add item</button><button onClick={()=>newEntity('group')}>+ Add group</button><button onClick={()=>newEntity('item',{kind:'milestone'})}>+ Add milestone</button></>}</div>
 <div className="planning-filters"><label>Search plan<input type="search" placeholder="Find an item or milestone…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{([['Owner',owner,setOwner,Object.fromEntries(data.members.map(m=>[m.id,m.name]))],['Area',area,setArea,Object.fromEntries(data.areas.map(a=>[a.id,a.name]))],['Status',status,setStatus,planStatuses]] as const).map(([label,value,set,options])=><label key={label}>{label}<select value={value} onChange={e=>set(e.target.value)}><option value="">All</option>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>)}{filtersActive&&<button className="planning-filter-reset" onClick={clearFilters}>Clear filters</button>}</div>
 {planView==='gantt'?<Gantt data={planData!} onOpen={i=>setEdit({entity:'item',p:{...i}})} onBoard={openBoard}/>:<SeasonTable data={planData!} onUpdate={updateItem} editable={manage&&!readOnly} busy={busy} onItem={i=>setEdit({entity:'item',p:{...i}})} onGroup={g=>setEdit({entity:'group',p:{...g}})} onBoard={openBoard} onAdd={(title,group_id)=>quickCreate('item',title,{group_id})} onOrder={(g,edge)=>void orderGroup(g,edge)}/>}
 </>}
 {tab==='boards'&&!boardId&&<><div className="planning-toolbar planning-board-actions">{manage&&<button className="planning-primary" onClick={()=>newEntity('board')}><Plus size={16} aria-hidden="true"/>Create board</button>}</div>{(['project','area'] as const).map(kind=>{const bs=data.boards.filter(b=>b.kind===kind);return bs.length?<section className="planning-board-group" key={kind}><h2>{kind==='project'?'Projects':'Functional Areas'}</h2><div className="planning-grid">{bs.map(b=><BoardSummary key={b.id} board={b} tasks={data.tasks.filter(t=>t.board_id===b.id)} area={data.areas.find(a=>a.id===b.area_id)?.name} onOpen={()=>openBoard(b.id)} onEdit={manage&&(!readOnly||b.kind==='area')?()=>setEdit({entity:'board',p:{...b}}):undefined}/>)}</div></section>:null;})}{!data.boards.length&&<div className="planning-empty"><h3>No boards yet</h3><p>Create a project board for detailed work, or a Functional Area board for ongoing team responsibilities.</p></div>}</>}
 {tab==='boards'&&boardId&&(board?<><div className="planning-toolbar planning-board-heading"><a href="#planning/boards">← Boards</a><h2>{board.name}</h2><span className="planning-badge">{board.kind==='area'?'Functional Area':'Project'} · {data.tasks.filter(t=>t.board_id===board.id&&t.status==='done').length}/{data.tasks.filter(t=>t.board_id===board.id).length} done</span>{canCreateTask&&<button className="planning-primary" onClick={()=>newEntity('task')}>+ New task</button>}{manage&&(!readOnly||board.kind==='area')&&<ContextActions label="Board actions"><button onClick={()=>setEdit({entity:'board',p:{...board}})}>Board settings</button></ContextActions>}<div role="group" aria-label="Board view">{['table','kanban','gantt'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div></div>{board.description&&<p className="planning-board-intro">{board.description}</p>}{!board.active&&<p>Archived board — tasks are read only.</p>}
 <div className="planning-filters"><label>Search tasks<input type="search" placeholder="Find a task…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{([['Owner / Person',owner,setOwner,Object.fromEntries(data.members.map(m=>[m.id,m.name]))],['Area',area,setArea,Object.fromEntries(data.areas.map(a=>[a.id,a.name]))],['Status',status,setStatus,taskStatuses],['Priority',priority,setPriority,priorities]] as const).map(([label,value,set,options])=><label key={label}>{label}<select value={value} onChange={e=>set(e.target.value)}><option value="">All</option>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>)}{filtersActive&&<button className="planning-filter-reset" onClick={clearFilters}>Clear filters</button>}</div>
 {!data.tasks.some(t=>t.board_id===boardId)&&<p className="planning-empty">No tasks yet. {manage&&board.active&&(!readOnly||board.kind==='area')?'Use New task or Add task to break this board’s work into clear next steps.':'Tasks added to this board will appear here.'}</p>}
 {view==='gantt'?<BoardGantt key={board.id} tasks={tasks} data={data} onOpen={openTask}/>:view==='table'?<>{rows(tasks)}{canCreateTask&&<QuickAdd key={board.id} kind="task" onAdd={title=>quickCreate('task',title,{status:'todo'})}/>}</>:<div className="planning-kanban" aria-label="Kanban board">{Object.entries(taskStatuses).map(([k,v])=><section key={`${board.id}-${k}`} className="planning-column" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const t=data.tasks.find(t=>t.id===e.dataTransfer.getData('application/x-planning-task')&&t.board_id===boardId);if(t&&canEdit(t))void move(t,k);}}><h3 data-status={k}>{v} · <span>{tasks.filter(t=>t.status===k).length}</span></h3>{tasks.filter(t=>t.status===k).map(card)}{!tasks.some(t=>t.status===k)&&<p className="planning-column-empty">No {v.toLowerCase()} tasks</p>}{canCreateTask&&<QuickAdd kind="task" onAdd={title=>quickCreate('task',title,{status:k})}/>}</section>)}</div>}</>:<p className="planning-empty">Board unavailable. <a href="#planning/boards">View boards</a></p>)}
 {tab==='my-work'&&<>{['Overdue','Today','This week','Later','Blocked'].map(group=>{const ts=data.tasks.filter(t=>t.owner_ids.includes(data.user_id)&&t.status!=='done'&&data.boards.some(b=>b.id===t.board_id&&b.active)&&workGroup(t)===group);return ts.length?<section className="planning-work-group" data-group={group} key={group}><h3>{group} · {ts.length}</h3><div className="planning-grid">{ts.map(card)}</div></section>:null;})}{!data.tasks.some(t=>t.owner_ids.includes(data.user_id)&&t.status!=='done'&&data.boards.some(b=>b.id===t.board_id&&b.active))&&<p className="planning-empty">You’re caught up. Tasks assigned to you will appear here.</p>}</>}
 </>}{edit&&<Editor key={`${edit.entity}-${edit.p.id||'new'}`} edit={edit} data={data} onClose={()=>setEdit(null)} onSaved={async message=>{await refresh();if(message)setFeedback(message);}}/>}</>}
 </section>;
}
