import {ChartNoAxesGantt,Columns3,ListTodo,Plus,RefreshCw} from 'lucide-react';
import {BoardSummary} from './BoardSummary';
import {useEffect,useRef,useState} from 'react';
import {loadPlanning,savePlanning,localDate,workGroup,taskStatuses,priorities,planStatuses,type Context,type Task} from './service';
import {Editor,type Edit} from './Editor';
import {PlanningDashboard} from './PlanningDashboard';
import {Gantt} from './Gantt';
import './planning.css';
export function Planning({route}:{route:string}){
 const [data,setData]=useState<Context|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<Edit|null>(null),[view,setView]=useState('kanban'),[planView,setPlanView]=useState('gantt');
 const [search,setSearch]=useState(''),[owner,setOwner]=useState(''),[area,setArea]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState('');
 const generation=useRef(0),selected=useRef<string|null>(null);
 const tab=route.split('/')[1]||'dashboard',boardId=route.split('/')[2];
 async function refresh(sid=selected.current){const g=++generation.current;setError('');try{const c=await loadPlanning(sid);if(g===generation.current){setData(c);selected.current=c.season_id;}}catch(e){if(g===generation.current)setError((e as Error).message);}}
 useEffect(()=>{void refresh();return()=>{generation.current++;};},[]);
 const season=data?.seasons.find(s=>s.id===data.season_id),board=data?.boards.find(b=>b.id===boardId),readOnly=season?.status==='archived',manage=!!data?.can_manage;
 async function move(t:Task,next:string){if(busy||t.status===next)return;setBusy(true);try{await savePlanning('task',{...t,status:next});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const openTask=(t:Task)=>setEdit({entity:'task',p:{...t}});
 const openBoard=(id:string)=>{location.hash=`planning/boards/${id}`;setSearch('');setOwner('');setArea('');setStatus('');setPriority('');};
 const newEntity=(entity:Edit['entity'])=>setEdit({entity,p:{season_id:data?.season_id,status:entity==='season'?'draft':entity==='item'?'not_started':'backlog',kind:entity==='board'?'project':'work',active:true,display_order:0,board_id:board?.id,priority:'normal',owner_id:null,area_id:null,start_date:entity==='item'?localDate():null,end_date:entity==='item'?localDate():null}});
 const canEdit=(t:Task)=>!!data&&(manage||t.owner_id===data.user_id)&&!!data.boards.find(b=>b.id===t.board_id&&b.active&&(b.kind==='area'||!readOnly));
 const statusControl=(t:Task)=><select aria-label={`Status for ${t.title}`} value={t.status} disabled={!canEdit(t)||busy} onChange={e=>void move(t,e.target.value)}>{Object.entries(taskStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>;
 const name=(id:string|null,list:'members'|'areas')=>data?.[list].find(x=>x.id===id)?.name||'Unassigned';
 const card=(t:Task)=><article className={`planning-task ${t.status==='blocked'?'is-blocked':''}`} key={t.id} draggable={canEdit(t)} onDragStart={e=>e.dataTransfer.setData('application/x-planning-task',t.id)}><button className="planning-task-title" onClick={()=>openTask(t)}>{t.title}</button><div className="planning-task-meta"><span>{name(t.owner_id,'members')}</span><span className={`planning-badge priority-${t.priority}`}>{priorities[t.priority as keyof typeof priorities]}</span></div>{tab==='my-work'&&<small>{data?.boards.find(b=>b.id===t.board_id)?.name}</small>}{t.area_id&&<small>{name(t.area_id,'areas')}</small>}{t.due_date&&<small className={t.status!=='done'&&t.due_date<localDate()?'planning-overdue':''}>{t.status!=='done'&&t.due_date<localDate()?'Overdue · ':'Due '}{t.due_date}</small>}{t.status==='blocked'&&t.blocked_reason&&<small className="planning-blocked-reason">Blocked: {t.blocked_reason}</small>}{statusControl(t)}</article>;
 const rows=(tasks:Task[])=><div className="planning-table-scroll"><table><thead><tr>{['Task','Owner','Area','Status','Priority','Due'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{tasks.map(t=><tr key={t.id} className={t.status!=='done'&&!!t.due_date&&t.due_date<localDate()?'is-overdue':''}><td><button onClick={()=>openTask(t)}>{t.title}</button></td><td>{name(t.owner_id,'members')}</td><td>{name(t.area_id,'areas')}</td><td>{statusControl(t)}</td><td><span className={`planning-badge priority-${t.priority}`}>{priorities[t.priority as keyof typeof priorities]}</span></td><td>{t.status!=='done'&&!!t.due_date&&t.due_date<localDate()&&<span className="planning-overdue">Overdue · </span>}{t.due_date||'No date'}</td></tr>)}</tbody></table>{!tasks.length&&<p className="planning-empty">No tasks match these filters.</p>}</div>;
 const tasks=(data?.tasks||[]).filter(t=>t.board_id===boardId&&t.title.toLowerCase().includes(search.toLowerCase())&&(!owner||t.owner_id===owner)&&(!area||t.area_id===area)&&(!status||t.status===status)&&(!priority||t.priority===priority));
 return <section className="planning"><header><div><h1>{({dashboard:'Planning',plan:'Season Plan',boards:'Boards','my-work':'My Work'} as Record<string,string>)[tab]||'Planning'}</h1><p>{tab==='dashboard'?'Season planning, project boards, and team assignments.':tab==='plan'?'Major work, milestones, and the season ahead.':tab==='boards'?'Projects and functional areas where the team gets work done.':'Everything assigned to you across the active season.'}</p></div>{data&&data.seasons.length>0&&<label>Planning season<select value={data.season_id||''} onChange={e=>{selected.current=e.target.value;setData(null);location.hash='planning';void refresh(e.target.value);}}>{data.seasons.map(s=><option key={s.id} value={s.id}>{s.name} · {s.status}</option>)}</select></label>}<button className="planning-refresh" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={15} aria-hidden="true"/>Refresh</button></header>
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Loading Planning…</p>}
 {data&&<>
 {!season?<div className="planning-onboarding"><div className="planning-empty planning-welcome"><ChartNoAxesGantt size={32} aria-hidden="true"/><h2>No active planning season</h2><p>Create a season to build the master schedule, organize project boards, and assign work.</p>{manage?<button className="planning-primary" onClick={()=>newEntity('season')}><Plus size={16} aria-hidden="true"/>Create planning season</button>:<p>Leadership will share the season plan here.</p>}</div><div className="planning-intro-grid">{[{name:'Season Plan',icon:ChartNoAxesGantt,text:"Build the team's master Gantt, phases, dependencies and milestones."},{name:'Boards',icon:Columns3,text:'Run projects and functional areas with focused Kanban boards.'},{name:'My Work',icon:ListTodo,text:'See your assignments, deadlines and blocked work in one place.'}].map(x=><section key={x.name} className="planning-card"><x.icon size={22} aria-hidden="true"/><h3>{x.name}</h3><p>{x.text}</p></section>)}</div></div>:<>
 <div className="planning-toolbar planning-season-context">{tab!=='dashboard'&&<h2>{season.name}</h2>}{tab!=='dashboard'&&<span className="planning-badge">{season.status}</span>}{manage&&<details><summary>Season settings</summary><button disabled={readOnly} onClick={()=>setEdit({entity:'season',p:{...season}})}>Edit season</button><button onClick={()=>newEntity('season')}>Create season</button></details>}</div>
 {tab==='dashboard'&&<PlanningDashboard data={data} season={season} onTask={openTask} onBoard={openBoard}/>}
 {tab==='plan'&&<><div className="planning-toolbar"><button aria-pressed={planView==='gantt'} onClick={()=>setPlanView('gantt')}>Gantt</button><button aria-pressed={planView==='list'} onClick={()=>setPlanView('list')}>List</button>{manage&&!readOnly&&<button className="planning-primary" onClick={()=>newEntity('item')}>Add plan item</button>}</div>
 {planView==='gantt'?<Gantt data={data} onOpen={i=>setEdit({entity:'item',p:{...i}})} onBoard={openBoard}/>:<div className="planning-table-scroll"><table><thead><tr><th>Work / milestone</th><th>Dates</th><th>Status</th><th>Starts after</th><th>Board</th></tr></thead><tbody>{data.items.map(i=><tr key={i.id}><td><button onClick={()=>setEdit({entity:'item',p:{...i}})}>{i.kind==='milestone'?'◆ ':''}{i.title}</button></td><td>{i.start_date} → {i.end_date}</td><td>{planStatuses[i.status as keyof typeof planStatuses]}</td><td>{data.items.find(p=>p.id===i.predecessor_id)?.title||'—'}</td><td>{i.board_id&&<button onClick={()=>openBoard(i.board_id!)}>{data.boards.find(b=>b.id===i.board_id)?.name||'Board'} →</button>}</td></tr>)}</tbody></table></div>}
 {manage&&!readOnly&&<details><summary>Plan groups</summary><div className="planning-toolbar">{data.groups.map(g=><button key={g.id} onClick={()=>setEdit({entity:'group',p:{...g}})}>{g.name}{!g.active?' (archived)':''}</button>)}<button onClick={()=>newEntity('group')}>Add group</button></div></details>}</>}
 {tab==='boards'&&!boardId&&<><div className="planning-toolbar planning-board-actions">{manage&&<button className="planning-primary" onClick={()=>newEntity('board')}><Plus size={16} aria-hidden="true"/>Create board</button>}</div>{(['project','area'] as const).map(kind=>{const bs=data.boards.filter(b=>b.kind===kind);return bs.length?<section className="planning-board-group" key={kind}><h2>{kind==='project'?'Projects':'Functional Areas'}</h2><div className="planning-grid">{bs.map(b=><BoardSummary key={b.id} board={b} tasks={data.tasks.filter(t=>t.board_id===b.id)} area={data.areas.find(a=>a.id===b.area_id)?.name} onOpen={()=>openBoard(b.id)} onEdit={manage&&(!readOnly||b.kind==='area')?()=>setEdit({entity:'board',p:{...b}}):undefined}/>)}</div></section>:null;})}{!data.boards.length&&<div className="planning-empty"><h3>No boards yet</h3><p>Create a project board for detailed work, or a Functional Area board for ongoing team responsibilities.</p></div>}</>}
 {tab==='boards'&&boardId&&(board?<><div className="planning-toolbar"><a href="#planning/boards">← Boards</a><h2>{board.name}</h2>{manage&&board.active&&(!readOnly||board.kind==='area')&&<button className="planning-primary" onClick={()=>newEntity('task')}>Add task</button>}<button onClick={()=>setView(view==='kanban'?'list':'kanban')}>{view==='kanban'?'List view':'Kanban view'}</button></div>{!board.active&&<p>Archived board — tasks are read only.</p>}
 <div className="planning-filters"><label>Search tasks<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label>{([['Owner',owner,setOwner,Object.fromEntries(data.members.map(m=>[m.id,m.name]))],['Area',area,setArea,Object.fromEntries(data.areas.map(a=>[a.id,a.name]))],['Status',status,setStatus,taskStatuses],['Priority',priority,setPriority,priorities]] as const).map(([label,value,set,options])=><label key={label}>{label}<select value={value} onChange={e=>set(e.target.value)}><option value="">All</option>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>)}</div>
 {!data.tasks.some(t=>t.board_id===boardId)&&<p className="planning-empty">No tasks yet. {manage&&board.active&&(!readOnly||board.kind==='area')?'Use Add task to break this board’s work into clear next steps.':'Tasks added to this board will appear here.'}</p>}
 {view==='list'?rows(tasks):<div className="planning-kanban" aria-label="Kanban board">{Object.entries(taskStatuses).map(([k,v])=><section key={k} className="planning-column" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const t=data.tasks.find(t=>t.id===e.dataTransfer.getData('application/x-planning-task')&&t.board_id===boardId);if(t&&canEdit(t))void move(t,k);}}><h3 data-status={k}>{v} · <span>{tasks.filter(t=>t.status===k).length}</span></h3>{tasks.filter(t=>t.status===k).map(card)}{!tasks.some(t=>t.status===k)&&<p className="planning-column-empty">No {v.toLowerCase()} tasks</p>}</section>)}</div>}</>:<p className="planning-empty">Board unavailable. <a href="#planning/boards">View boards</a></p>)}
 {tab==='my-work'&&<>{['Overdue','Today','This week','Later','Blocked'].map(group=>{const ts=data.tasks.filter(t=>t.owner_id===data.user_id&&t.status!=='done'&&data.boards.some(b=>b.id===t.board_id&&b.active)&&workGroup(t)===group);return ts.length?<section className="planning-work-group" data-group={group} key={group}><h3>{group} · {ts.length}</h3><div className="planning-grid">{ts.map(card)}</div></section>:null;})}{!data.tasks.some(t=>t.owner_id===data.user_id&&t.status!=='done'&&data.boards.some(b=>b.id===t.board_id&&b.active))&&<p className="planning-empty">You’re caught up. Tasks assigned to you will appear here.</p>}</>}
 </>}{edit&&<Editor key={`${edit.entity}-${edit.p.id||'new'}`} edit={edit} data={data} onClose={()=>setEdit(null)} onSaved={()=>refresh()}/>}</>}
 </section>;
}
