import {InlineTitle,InlineTimeline} from './InlineFields';
import type {Context,Group,Item} from './service';
import {localDate,planStatuses} from './service';
import {planGroups} from './plan-groups';
import {QuickAdd} from './QuickAdd';
export function SeasonTable({data,editable,busy,onItem,onGroup,onBoard,onAdd,onOrder,onUpdate}:{onUpdate:(i:Item,p:Partial<Item>)=>Promise<boolean|undefined>;data:Context;editable:boolean;busy:boolean;onItem:(i:Item)=>void;onGroup:(g:Group)=>void;onBoard:(id:string)=>void;onAdd:(title:string,group:string|null)=>Promise<void>;onOrder:(g:Group,edge:'top'|'bottom')=>void}){
 const groups=planGroups(data);
 return <div className="planning-season-table">{groups.map(({group,items},n)=><section key={group?.id||'ungrouped'} className="planning-plan-group">
 <details open><summary>{group?.name||'Ungrouped'}{group&&!group.active?' · Archived':''} <span className="planning-badge">{items.length}</span></summary>
 {editable&&group&&<div className="planning-group-actions"><button onClick={()=>onGroup(group)}>Group settings</button><button disabled={busy||n===0} onClick={()=>onOrder(group,'top')}>Move to top</button><button disabled={busy||n===groups.length-2} onClick={()=>onOrder(group,'bottom')}>Move to bottom</button></div>}
 {items.length>0&&<div className="planning-table-scroll"><table><thead><tr>{['Item','Owner / Area','Status','Timeline','Linked Board'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.map(i=><tr key={i.id} data-item-id={i.id}><td><button onClick={()=>onItem(i)}>{i.kind==='milestone'?'◆ ':''}{i.title}</button>{editable&&<InlineTitle title={i.title} disabled={busy} onSave={p=>onUpdate(i,p)}/>}</td><td>{editable?<><select aria-label={`Owner for ${i.title}`} disabled={busy} value={i.owner_id||''} onChange={e=>void onUpdate(i,{owner_id:e.target.value||null})}><option value="">Unassigned</option>{data.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><select aria-label={`Area for ${i.title}`} disabled={busy} value={i.area_id||''} onChange={e=>void onUpdate(i,{area_id:e.target.value||null})}><option value="">Unassigned area</option>{data.areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></>:<>{data.members.find(m=>m.id===i.owner_id)?.name||'Unassigned'}<small>{data.areas.find(a=>a.id===i.area_id)?.name}</small></>}</td><td><select aria-label={`Status for ${i.title}`} disabled={!editable||busy} value={i.status} onChange={e=>void onUpdate(i,{status:e.target.value})}>{Object.entries(planStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td><td><InlineTimeline title={i.title} start={i.start_date} end={i.end_date} required milestone={i.kind==='milestone'} disabled={!editable||busy} onSave={(start_date,end_date)=>onUpdate(i,{start_date:start_date!,end_date:end_date!})}/></td><td>{editable&&<select aria-label={`Linked Board for ${i.title}`} disabled={busy} value={i.board_id||''} onChange={e=>void onUpdate(i,{board_id:e.target.value||null})}><option value="">No linked Board</option>{data.boards.filter(b=>b.active||b.id===i.board_id).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}{i.board_id&&<button onClick={()=>onBoard(i.board_id!)}>{data.boards.find(b=>b.id===i.board_id)?.name||'Board'} →</button>}</td></tr>)}</tbody></table></div>}
 {!items.length&&<p className="planning-hint">No items in this group yet.</p>}{editable&&(!group||group.active)&&<QuickAdd kind="item" hint={`Starts and ends today (${localDate()}). Edit the timeline after adding.`} onAdd={title=>onAdd(title,group?.id||null)}/>}
 </details></section>)}</div>;
}
