-- Read-only compatibility snapshot. Compare with the reviewed definitions before rollout.
-- No private user data, provider payloads or credentials are selected.
begin read only;
select jsonb_build_object(
'functions',(select jsonb_agg(jsonb_build_object('name',p.oid::regprocedure::text,'body',pg_get_functiondef(p.oid),'acl',p.proacl)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.prokind='f' and (n.nspname in ('notifications_private','finance_private','team_attendance_private') or n.nspname='public' and (p.proname like 'team_notification_%' or p.proname like 'team_announcement_%' or p.proname like 'team_attendance_%' or p.proname in ('team_has_position','team_has_any_position','team_my_positions','finance_mutate')) or n.nspname='team_private' and p.proname in ('announcement_audience','enqueue_announcement') or n.nspname='auth' and p.proname='uid')),
'columns',(select jsonb_agg(to_jsonb(c)) from (select table_schema,table_name,column_name,data_type,is_nullable,column_default from information_schema.columns where (table_schema='public' and table_name in ('profiles','team_positions','team_member_positions','team_notifications','team_announcements','team_attendance','team_attendance_history','team_attendance_strikes','team_meetings','finance_purchase_orders','finance_po_approvals','finance_assignments')) or table_schema='finance_private' and table_name='history' order by table_schema,table_name,ordinal_position)c),
'relations',(select jsonb_agg(jsonb_build_object('name',c.oid::regclass::text,'kind',c.relkind,'rls',c.relrowsecurity,'acl',c.relacl)) from pg_class c join pg_namespace n on n.oid=c.relnamespace where (n.nspname='public' and c.relname in ('team_notifications','team_announcements','team_attendance','team_attendance_history','team_attendance_strikes','profiles','team_positions','team_member_positions')) or n.nspname='finance_private' and c.relname='history'),
'constraints',(select jsonb_agg(jsonb_build_object('table',conrelid::regclass::text,'name',conname,'definition',pg_get_constraintdef(oid))) from pg_constraint where conrelid in ('public.team_notifications'::regclass,'public.team_attendance'::regclass,'public.team_announcements'::regclass)),
'triggers',(select jsonb_agg(jsonb_build_object('table',tgrelid::regclass::text,'definition',pg_get_triggerdef(oid))) from pg_trigger where not tgisinternal and tgrelid in ('finance_private.history'::regclass,'public.team_notifications'::regclass,'public.team_attendance'::regclass,'public.team_attendance_history'::regclass,'public.team_attendance_strikes'::regclass,'public.team_announcements'::regclass)),
'policies',(select jsonb_agg(to_jsonb(p)) from pg_policies p where tablename in ('team_notifications','team_announcements','team_attendance','team_attendance_history','team_attendance_strikes','profiles')),
'indexes',(select jsonb_agg(to_jsonb(i)) from pg_indexes i where tablename in ('team_notifications','finance_po_approvals','team_attendance','team_member_positions')),
'conflicts',jsonb_build_object('events',to_regclass('notifications_private.events'),'recipients',to_regclass('notifications_private.recipients'),'epoch',to_regclass('notifications_private.center_epoch'),'rpc',to_regprocedure('public.notification_center(text,timestamptz,uuid)'),'read',to_regprocedure('public.notification_read(uuid,boolean)'),'delivery',to_regprocedure('public.team_attendance_delivery_allowed(uuid)')),
'private_schema_acl',(select nspacl from pg_namespace where nspname='notifications_private'),
'default_grants',(select jsonb_agg(to_jsonb(a)) from pg_default_acl a),
'ledger',to_regclass('supabase_migrations.schema_migrations')) as review;
rollback;
