import {useEffect,useState} from 'react';
import {supabase} from './attendance/service';
import {AuthSurface,authGateway} from './AuthSurface';
import type {Session} from '@supabase/supabase-js';
export function useHubAuth(){
 const [session,setSession]=useState<Session|null>(null),[state,setState]=useState(supabase?'loading':'error'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[name,setName]=useState('Team member'),[recovery,setRecovery]=useState(new URLSearchParams(location.search).has('password-reset')||/type=(recovery|invite)/.test(location.hash));
 useEffect(()=>{if(!supabase)return;let alive=true;const timer=setTimeout(()=>{if(alive){setState('error');setError('Connection timed out. Please try again.');}},15000);const {data}=supabase.auth.onAuthStateChange((event,s)=>{clearTimeout(timer);setSession(s);setState(s?'ready':'signed-out');if(event==='PASSWORD_RECOVERY')setRecovery(true);if(!s){setRecovery(false);history.replaceState(null,'',location.pathname);}});return()=>{alive=false;clearTimeout(timer);data.subscription.unsubscribe();};},[]);
 useEffect(()=>{let alive=true;setName('Team member');if(session&&supabase)void supabase.from('profiles').select('display_name').eq('id',session.user.id).single().then(({data})=>{if(alive&&data?.display_name)setName(data.display_name);});return()=>{alive=false;};},[session?.user.id]);
 const home=()=>{setRecovery(false);history.replaceState(null,'',location.pathname);window.dispatchEvent(new HashChangeEvent('hashchange'));window.scrollTo(0,0);};
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e&&typeof e==='object'&&'message' in e?String(e.message):'Unable to connect. Please try again.');}finally{setBusy(false);}};
 const signOut=()=>void run(async()=>{const {error}=await supabase!.auth.signOut({scope:'local'});if(error)throw error;});
 const panel=<AuthSurface><h1>{recovery&&session?'Set your password':'Team sign in'}</h1><p>Sign in with your Team 4418 account.</p>{state==='loading'?<p role="status">Connecting securely…</p>:state==='error'?<><p role="alert">Team sign in is unavailable. Please try again.</p><button onClick={()=>location.reload()}>Retry</button></>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{if(recovery&&session){if(f.get('password')!==f.get('confirm'))throw Error('Passwords must match.');const {error}=await supabase!.auth.updateUser({password:String(f.get('password'))});if(error)throw error;}else{const {error}=await supabase!.auth.signInWithPassword({email:String(f.get('email')).trim(),password:String(f.get('password'))});if(error)throw error;}home();});}}>{!recovery&&<label>Email<input name="email" type="email" autoComplete="username" required/></label>}<label>{recovery?'New password':'Password'}<input name="password" type="password" autoComplete={recovery?'new-password':'current-password'} minLength={recovery?12:undefined} required/></label>{recovery&&<label>Confirm password<input name="confirm" type="password" autoComplete="new-password" required/></label>}<button disabled={busy}>{busy?'Please wait…':recovery?'Save password':'Sign in'}</button>{!recovery&&<button type="button" disabled={busy} onClick={e=>{const f=new FormData(e.currentTarget.form!);void run(async()=>{const email=String(f.get('email')||'').trim();if(!email)throw Error('Enter your email address first.');const {error}=await supabase!.auth.resetPasswordForEmail(email,{redirectTo:authGateway+'?password-reset=1'});if(error)throw error;setMessage('If an account exists, a password reset email is on its way.');});}}>Forgot password?</button>}</form>}{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}</AuthSurface>;
 return {signed:!!session&&!recovery,state,name,signOut,busy,panel,error};
}
