import {useEffect,useState} from 'react';
import {supabase} from './attendance/service';
import type {Session} from '@supabase/supabase-js';
export function useHubAuth(){
 const [session,setSession]=useState<Session|null>(null),[state,setState]=useState(supabase?'loading':'setup'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!supabase)return;const timer=setTimeout(()=>{setState('error');setError('Sign-in is taking longer than expected. Please reload to try again.');},15000);const {data}=supabase.auth.onAuthStateChange((_event,s)=>{clearTimeout(timer);setSession(s);setState(s?'ready':'signed-out');});return()=>{clearTimeout(timer);data.subscription.unsubscribe();};},[]);
 const run=async(action:()=>Promise<{error:unknown}>)=>{setBusy(true);setError('');try{const {error}=await action();if(error)throw error;}catch(e){setError(e&&typeof e==='object'&&'message' in e?String(e.message):'Unable to sign in. Please try again.');}finally{setBusy(false);}};
 return {signed:!!session,account:session?<><span className="account-name">Team account</span><button disabled={busy} onClick={()=>void run(()=>supabase!.auth.signOut({scope:'local'}))}>Sign out</button></>:null,panel:state==='ready'?(error?<p role="alert">{error}</p>:null):<section className="hub-auth" aria-labelledby="hub-auth-title"><h2 id="hub-auth-title">Sign in to Team Hub</h2><p>One Team 4418 account for your dashboard and every team workspace.</p>{state==='loading'?<p role="status">Restoring your session…</p>:state==='setup'?<p role="alert">Team sign-in is not configured yet. Contact a mentor.</p>:state==='error'?<button onClick={()=>location.reload()}>Reload sign-in</button>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>supabase!.auth.signInWithPassword({email:String(f.get('email')).trim(),password:String(f.get('password'))}));}}><label>Email<input name="email" type="email" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form>}{error&&<p role="alert">{error}</p>}</section>};
}
