import {cloneDecisionWorkflow,decisionWorkflowIssue,normalizeDecisionWorkflow} from './decision-model';
import type {AssignmentSave,ProjectReviewUpdate,ReviewBoard,ReviewReference,ReviewSave,ReviewSaveAction,ReviewSavePayload,SprintReviewContext,UpdateSave} from './types';

export const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export function reviewRoute(route:string){const match=/^#planning\/reviews(?:\/([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})(?:\/project\/([0-9a-fA-F-]{36}))?)?$/.exec(route);return {valid:!!match&&(!match[2]||uuid.test(match[2])),id:match?.[1]?.toLowerCase()||null};}
export function reviewProjectFocus(route:string):string|null{if(!reviewRoute(route).valid)return null;const match=/\/project\/([^/]+)$/.exec(route);return match?.[1].toLowerCase()||null;}
export function validDate(value:unknown):value is string{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||value.startsWith('0000'))return false;const date=new Date(value+'T12:00:00Z');return Number.isFinite(date.valueOf())&&date.toISOString().slice(0,10)===value;}
export function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function safeReferenceUrl(value:string):string|null{if(value.length>2000||/[\s\\\u0000-\u001f\u007f]/.test(value)||!/^https?:\/\/[^/?#@]+(?:[/?#]|$)/.test(value))return null;try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password?url.href:null;}catch{return null;}}
const obj=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const id=(v:unknown):v is string=>typeof v==='string'&&uuid.test(v);
const nullableId=(v:unknown)=>v===null||id(v);
const text=(v:unknown,max=5000):v is string=>typeof v==='string'&&v.length<=max;
const bool=(v:unknown)=>typeof v==='boolean';
const version=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>0;
const identityList=(v:unknown)=>Array.isArray(v)&&v.every(id)&&new Set(v).size===v.length;
const ids=(v:unknown)=>Array.isArray(v)&&v.length<=30&&identityList(v);
const array=(v:unknown,check:(v:any)=>boolean)=>Array.isArray(v)&&v.every(check);
const unique=(v:{id:string}[])=>new Set(v.map(x=>x.id)).size===v.length;
const person=(p:unknown)=>obj(p)&&id(p.id)&&text(p.name,150)&&bool(p.active)&&bool(p.is_student)&&bool(p.can_write);
const reference=(r:unknown)=>obj(r)&&text(r.label,200)&&text(r.url,2000)&&(r.url===''||!!safeReferenceUrl(r.url))&&text(r.reference_id,200);
const references=(v:unknown)=>Array.isArray(v)&&v.length<=20&&v.every(reference);
const task=(t:unknown)=>obj(t)&&id(t.id)&&nullableId(t.board_id)&&text(t.title,150)&&(t.status===null||text(t.status,100))&&bool(t.available)&&identityList(t.owner_ids)&&array(t.owners,person)&&t.owners.every((p:any)=>t.owner_ids.includes(p.id))&&(t.due_date===null||validDate(t.due_date))&&bool(t.due_date_unavailable)&&(!t.due_date_unavailable||t.due_date===null)&&(!t.available?t.board_id===null&&t.status===null&&t.owner_ids.length===0&&t.owners.length===0&&t.due_date===null:true);
const assignment=(a:unknown)=>obj(a)&&id(a.board_id)&&nullableId(a.lead_id)&&ids(a.supporter_ids)&&version(a.version)&&(a.lead===null?a.lead_id===null:person(a.lead)&&a.lead.id===a.lead_id)&&array(a.supporters,person)&&a.supporters.every((p:any)=>a.supporter_ids.includes(p.id))&&!a.supporter_ids.includes(a.lead_id);
const agenda=(a:unknown)=>Array.isArray(a)&&a.length<=30&&a.every(x=>obj(x)&&text(x.title,200)&&!!x.title.trim()&&nullableId(x.presenter_id)&&Number.isInteger(x.duration_minutes)&&x.duration_minutes>=1&&x.duration_minutes<=240);
const review=(r:unknown)=>obj(r)&&id(r.id)&&id(r.season_id)&&text(r.title,200)&&validDate(r.review_date)&&nullableId(r.chair_id)&&agenda(r.agenda)&&version(r.version)&&id(r.recorded_by)&&text(r.recorded_at,100)&&Number.isFinite(Date.parse(r.recorded_at));
const update=(u:unknown)=>obj(u)&&!decisionWorkflowIssue(u.decision_workflow,undefined,true)&&(u.decision_owner===undefined||(u.decision_owner===null?!u.decision_workflow?.owner_id:person(u.decision_owner)&&u.decision_owner.id===u.decision_workflow?.owner_id))&&id(u.id)&&id(u.review_id)&&id(u.board_id)&&['progress','blockers','tradeoffs','decisions_needed','reported_decision','decision_rationale','next_test'].every(k=>text(u[k]))&&references(u.evidence)&&references(u.decision_references)&&ids(u.reported_by_student_ids)&&array(u.reported_students,person)&&u.reported_students.every((p:any)=>u.reported_by_student_ids.includes(p.id))&&nullableId(u.linked_task_id)&&(u.linked_task===null?u.linked_task_id===null:task(u.linked_task)&&u.linked_task.id===u.linked_task_id)&&nullableId(u.carry_from_update_id)&&(u.carried_from===null||obj(u.carried_from)&&id(u.carried_from.update_id)&&u.carried_from.update_id===u.carry_from_update_id&&id(u.carried_from.review_id)&&text(u.carried_from.review_title,200)&&validDate(u.carried_from.review_date))&&bool(u.unresolved)&&version(u.version)&&id(u.recorded_by)&&text(u.recorded_at,100)&&Number.isFinite(Date.parse(u.recorded_at));

/** Reject actor/scope changes and malformed read models before rendering any history. */
export function assertReviewContext(value:unknown,actorId:string,seasonId:string|null=null,reviewId:string|null=null):SprintReviewContext{
 // Optional legacy links remain readable as unavailable sources; never make them actionable.
 if(obj(value)){const normalize=(entries:unknown)=>Array.isArray(entries)?entries.map(u=>obj(u)?{...u,...(u.decision_workflow===undefined?{}:{decision_workflow:normalizeDecisionWorkflow(u.decision_workflow)}),...Object.fromEntries(['evidence','decision_references'].map(key=>[key,Array.isArray(u[key])?u[key].map((r:unknown)=>obj(r)&&typeof r.url==='string'?{...r,url:safeReferenceUrl(r.url)?r.url:''}:r):u[key]]))}:u):entries;value={...value,updates:normalize(value.updates),previous_updates:normalize(value.previous_updates)};}
 if(!obj(value)||value.user_id!==actorId||!id(value.user_id)||!bool(value.can_manage)||!nullableId(value.season_id)||!nullableId(value.selected_review_id)||!text(value.loaded_at,100)||!Number.isFinite(Date.parse(value.loaded_at))||!array(value.seasons,s=>obj(s)&&id(s.id)&&text(s.name,150)&&['draft','active','archived'].includes(s.status))||!array(value.members,person)||!array(value.boards,b=>obj(b)&&id(b.id)&&id(b.season_id)&&text(b.name,150)&&bool(b.active)&&bool(b.can_edit_update)&&(b.assignment===null||assignment(b.assignment)&&b.assignment.board_id===b.id))||!array(value.reviews,review)||!bool(value.reviews_limit_reached)||!array(value.updates,update)||!array(value.previous_updates,update)||!array(value.tasks,task))throw Error('Sprint Review returned an invalid response. Refresh to try again.');
 const c=value as SprintReviewContext;
 if(seasonId!==null&&c.season_id!==seasonId||reviewId!==null&&c.selected_review_id!==reviewId||c.season_id!==null&&!c.seasons.some(s=>s.id===c.season_id)||c.selected_review_id!==null&&!c.reviews.some(r=>r.id===c.selected_review_id)||c.season_id===null&&(c.selected_review_id!==null||c.boards.length>0||c.reviews.length>0||c.updates.length>0||c.previous_updates.length>0||c.tasks.length>0)||[c.seasons,c.members,c.boards,c.reviews,c.updates,c.previous_updates,c.tasks].some(list=>!unique(list))||c.boards.some(b=>b.season_id!==c.season_id)||c.reviews.some(r=>r.season_id!==c.season_id)||c.updates.some(u=>u.review_id!==c.selected_review_id||!c.boards.some(b=>b.id===u.board_id))||c.previous_updates.some(u=>u.review_id===c.selected_review_id||!c.boards.some(b=>b.id===u.board_id))||new Set(c.updates.map(u=>u.board_id)).size!==c.updates.length||new Set(c.previous_updates.map(u=>u.board_id)).size!==c.previous_updates.length)throw Error('This review no longer matches the selected account or season. Reload Sprint Review.');
 return c;
}

function validateReferences(rows:ReviewReference[]){return rows.length<=20&&rows.every(r=>r.label.trim()&&r.label.length<=200&&r.reference_id.length<=200&&!!safeReferenceUrl(r.url));}
export function validateReviewPayload(action:ReviewSaveAction,p:ReviewSavePayload):string|null{
 if(new TextEncoder().encode(JSON.stringify(p)).length>60000)return 'This update is too long. Shorten the text or remove a few links.';
 if(p.version!==null&&!version(p.version))return 'Refresh before saving this version.';
 if(action==='review'){const r=p as ReviewSave;if(!id(r.id)||!id(r.season_id)||!r.title.trim()||r.title.length>200)return 'Add a review title of up to 200 characters.';if(!validDate(r.review_date))return 'Choose a valid review date.';if(!nullableId(r.chair_id)||!agenda(r.agenda))return 'Each agenda item needs a title and 1–240 minutes.';}
 if(action==='assignment'){const a=p as AssignmentSave;if(!id(a.board_id)||!nullableId(a.lead_id)||!ids(a.supporter_ids)||a.supporter_ids.includes(a.lead_id||''))return 'Choose a student lead and a support team without duplicates.';}
 if(action==='update'){const u=p as UpdateSave;const issue=decisionWorkflowIssue(u.decision_workflow,u);if(issue)return issue;if(![u.id,u.review_id,u.board_id].every(id)||!nullableId(u.linked_task_id)||!nullableId(u.carry_from_update_id)||!ids(u.reported_by_student_ids)||!bool(u.unresolved))return 'Check the linked project, students and next task.';if(!['progress','blockers','tradeoffs','decisions_needed','reported_decision','decision_rationale','next_test'].every(k=>text(u[k as keyof UpdateSave])))return 'Keep each update field within 5,000 characters.';if(!validateReferences(u.evidence)||!validateReferences(u.decision_references))return 'Each reference needs a label and a valid http or https link without credentials. Use up to 20 references per section.';}
 return null;
}

export type QueueReason='update'|'lead'|'evidence'|'tradeoffs'|'decision'|'rationale'|'participants'|'test'|'task'|'owner'|'date'|'carry';
export const queueLabels:Record<QueueReason,string>={update:'Update needed',lead:'Student lead needed',evidence:'Evidence needed',tradeoffs:'Trade-offs needed',decision:'Decision to discuss',rationale:'Decision rationale needed',participants:'Student participants needed',test:'Next test needed',task:'Planning task needed',owner:'Task owner needed',date:'Task due date needed',carry:'Prior open items'};
/** Transparent prompts, not grades: every reason names a concrete missing field. */
export function reviewQueueReasons(board:ReviewBoard,entry:ProjectReviewUpdate|undefined,prior?:ProjectReviewUpdate):QueueReason[]{
 const result:QueueReason[]=[];if(!board.assignment?.lead?.active||!board.assignment.lead.is_student||!board.assignment.lead.can_write)result.push('lead');
 if(!entry){result.push('update');if(prior?.unresolved)result.push('carry');return result;}
 if(!entry.evidence.some(r=>!!safeReferenceUrl(r.url)))result.push('evidence');if(!entry.tradeoffs.trim())result.push('tradeoffs');if(entry.decision_workflow&&entry.decision_workflow.status!=='recorded'||entry.unresolved&&entry.decisions_needed.trim())result.push('decision');
 if(entry.reported_decision.trim()){if(!entry.decision_rationale.trim())result.push('rationale');if(!entry.reported_by_student_ids.length)result.push('participants');}
 if(!entry.next_test.trim())result.push('test');if(!entry.linked_task?.available)result.push('task');else{if(!entry.linked_task.owner_ids.length)result.push('owner');if(!entry.linked_task.due_date||entry.linked_task.due_date_unavailable)result.push('date');}return result;
}
export function blankUpdate(reviewId:string,boardId:string):UpdateSave{return {id:crypto.randomUUID(),review_id:reviewId,board_id:boardId,progress:'',blockers:'',evidence:[],tradeoffs:'',decisions_needed:'',decision_references:[],reported_decision:'',decision_rationale:'',reported_by_student_ids:[],next_test:'',linked_task_id:null,carry_from_update_id:null,unresolved:true,version:null};}
export function updatePayload(entry:ProjectReviewUpdate):UpdateSave{return {id:entry.id,review_id:entry.review_id,board_id:entry.board_id,...(entry.decision_workflow===undefined?{}:{decision_workflow:cloneDecisionWorkflow(entry.decision_workflow)}),progress:entry.progress,blockers:entry.blockers,evidence:entry.evidence.map(r=>({...r})),tradeoffs:entry.tradeoffs,decisions_needed:entry.decisions_needed,decision_references:entry.decision_references.map(r=>({...r})),reported_decision:entry.reported_decision,decision_rationale:entry.decision_rationale,reported_by_student_ids:[...entry.reported_by_student_ids],next_test:entry.next_test,linked_task_id:entry.linked_task_id,carry_from_update_id:entry.carry_from_update_id,unresolved:entry.unresolved,version:entry.version};}
/** Explicitly carry open questions only; prior evidence/decisions stay in their original review. */
export function carryOpenItems(draft:UpdateSave,source:ProjectReviewUpdate):UpdateSave{if(source.board_id!==draft.board_id||source.review_id===draft.review_id||!source.unresolved)throw Error('Choose an earlier unresolved update for this project.');return {...draft,blockers:source.blockers,tradeoffs:source.tradeoffs,decisions_needed:source.decisions_needed,next_test:source.next_test,linked_task_id:source.linked_task?.available?source.linked_task_id:null,carry_from_update_id:source.id,unresolved:true};}
