import {AssemblySnapshotPicker} from '../assembly/SnapshotPicker';
import {useEffect,useId,useRef,useState,type ReactNode} from 'react';
import {X,Plus,ArrowUp,ArrowDown} from 'lucide-react';
import type {AssignmentSave,ProjectReviewUpdate,ReviewBoard,ReviewPerson,ReviewSave,SprintReview,SprintReviewContext,UpdateSave} from './types';
import {blankUpdate,carryOpenItems,safeReferenceUrl,today,updatePayload,validateReviewPayload} from './model';
import {TaskReference} from './ReviewViews';
import {DecisionEditor,DecisionRecordFields,ReferencesEditor} from './DecisionEditor';
import {blankDecisionWorkflow,decisionWorkflowIssue} from './decision-model';

type BaseProps={busy:boolean;error:string;onClose:()=>void};
function Dialog({title,onClose,children,className=''}:{title:string;onClose:()=>void;children:ReactNode;className?:string}){const ref=useRef<HTMLDialogElement>(null),id=useId();useEffect(()=>{const previous=document.activeElement as HTMLElement|null,dialog=ref.current;dialog?.showModal();return()=>{dialog?.close();if(previous?.isConnected)previous.focus();};},[]);return <dialog ref={ref} className={`sr-dialog ${className}`} aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose();}}><header><h2 id={id}>{title}</h2><button type="button" className="sr-icon-button" onClick={onClose} aria-label="Close editor"><X size={19}/></button></header>{children}</dialog>;}
function Footer({busy,onClose,label}:{busy:boolean;onClose:()=>void;label:string}){return <div className="sr-dialog-footer"><button type="button" onClick={onClose}>Close</button><button type="submit" className="sr-primary" disabled={busy}>{busy?'Saving…':label}</button>{busy&&<small role="status">Closing clears the draft. You can check the save result from the workspace.</small>}</div>;}
function PersonSelect({label,value,people,onChange,placeholder='Choose later'}:{label:string;value:string|null;people:ReviewPerson[];onChange:(id:string|null)=>void;placeholder?:string}){const id=useId();return <div className="sr-field"><label htmlFor={id}>{label}</label><select id={id} value={value||''} onChange={e=>onChange(e.target.value||null)}><option value="">{placeholder}</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}{!p.active||!p.can_write?' · no longer active':''}</option>)}{value&&!people.some(p=>p.id===value)&&<option value={value}>Previously selected person</option>}</select></div>;}
function PeopleChoices({label,ids,people,onChange}:{label:string;ids:string[];people:ReviewPerson[];onChange:(ids:string[])=>void}){const choices=[...people,...ids.filter(id=>!people.some(p=>p.id===id)).map(id=>({id,name:'Previously selected person',active:false,can_write:false,is_student:false}))];return <fieldset className="sr-choices"><legend>{label}</legend>{choices.length?<div>{choices.map(p=><label key={p.id}><input type="checkbox" checked={ids.includes(p.id)} disabled={(!p.active||!p.can_write)&&!ids.includes(p.id)} onChange={e=>onChange(e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/><span>{p.name}{(!p.active||!p.can_write)&&<small> · previously selected; can be removed</small>}</span></label>)}</div>:<p className="sr-caption">No eligible people are available.</p>}</fieldset>;}

export function ReviewSettingsDialog({review,data,busy,error,onClose,onSave}:BaseProps&{review:SprintReview|null;data:SprintReviewContext;onSave:(p:ReviewSave)=>void}){
 const [draft,setDraft]=useState<ReviewSave>(()=>review?{id:review.id,season_id:review.season_id,title:review.title,review_date:review.review_date,chair_id:review.chair_id,agenda:review.agenda.map(a=>({...a})),version:review.version}:{id:crypto.randomUUID(),season_id:data.season_id!,title:'Weekly Sprint Review',review_date:today(),chair_id:null,agenda:[{title:'Project updates & decisions',presenter_id:null,duration_minutes:20}],version:null});
 const [validation,setValidation]=useState('');const people=data.members.filter(p=>p.active&&p.can_write);const change=<K extends keyof ReviewSave>(key:K,value:ReviewSave[K])=>setDraft(d=>({...d,[key]:value}));
 function move(index:number,offset:number){const items=[...draft.agenda];[items[index],items[index+offset]]=[items[index+offset],items[index]];change('agenda',items);}
 return <Dialog title={review?'Review settings':'Create a review'} onClose={onClose}><p className="sr-dialog-intro">Set the rhythm. Students bring evidence and lead the discussion.</p><form onSubmit={e=>{e.preventDefault();if(busy)return;const issue=validateReviewPayload('review',draft);setValidation(issue||'');if(!issue)onSave(draft);}}>{(validation||error)&&<p className="sr-error" role="alert">{validation||error}</p>}<fieldset className="sr-fields" disabled={busy}><div className="sr-form-grid"><label className="sr-wide">Review title<input autoFocus required maxLength={200} value={draft.title} onChange={e=>change('title',e.target.value)}/></label><label>Review date<input type="date" required value={draft.review_date} onChange={e=>change('review_date',e.target.value)}/></label><PersonSelect label="Meeting chair" value={draft.chair_id} people={people} onChange={id=>change('chair_id',id)}/></div><div className="sr-section-heading"><h3>Agenda</h3><span>{draft.agenda.reduce((n,a)=>n+(Number(a.duration_minutes)||0),0)} min total</span></div><ol className="sr-agenda-editor">{draft.agenda.map((item,index)=><li key={index}><div className="sr-agenda-number">{index+1}</div><div className="sr-agenda-fields"><label>Item {index+1} title<input required maxLength={200} value={item.title} onChange={e=>change('agenda',draft.agenda.map((a,i)=>i===index?{...a,title:e.target.value}:a))}/></label><div className="sr-form-grid"><PersonSelect label={`Item ${index+1} presenter`} value={item.presenter_id} people={people} onChange={id=>change('agenda',draft.agenda.map((a,i)=>i===index?{...a,presenter_id:id}:a))}/><label>Minutes<input aria-label={`Item ${index+1} minutes`} required type="number" min={1} max={240} value={item.duration_minutes||''} onChange={e=>change('agenda',draft.agenda.map((a,i)=>i===index?{...a,duration_minutes:Number(e.target.value)}:a))}/></label></div></div><div className="sr-agenda-order"><button type="button" className="sr-icon-button" disabled={index===0} aria-label={`Move item ${index+1} up`} onClick={()=>move(index,-1)}><ArrowUp size={15}/></button><button type="button" className="sr-icon-button" disabled={index===draft.agenda.length-1} aria-label={`Move item ${index+1} down`} onClick={()=>move(index,1)}><ArrowDown size={15}/></button><button type="button" className="sr-icon-button" aria-label={`Remove item ${index+1}`} onClick={()=>change('agenda',draft.agenda.filter((_,i)=>i!==index))}><X size={15}/></button></div></li>)}</ol><button type="button" disabled={draft.agenda.length>=30} onClick={()=>change('agenda',[...draft.agenda,{title:'',presenter_id:null,duration_minutes:5}])}><Plus size={14}/>Add agenda item</button></fieldset><Footer busy={busy} onClose={onClose} label={review?'Save review':'Create review'}/></form></Dialog>;
}
export function AssignmentDialog({board,data,busy,error,onClose,onSave}:BaseProps&{board:ReviewBoard;data:SprintReviewContext;onSave:(p:AssignmentSave)=>void}){
 const [draft,setDraft]=useState<AssignmentSave>({board_id:board.id,lead_id:board.assignment?.lead_id||null,supporter_ids:board.assignment?.supporter_ids||[],version:board.assignment?.version||null});
 const students=data.members.filter(p=>p.active&&p.can_write&&p.is_student),supporters=data.members.filter(p=>p.active&&p.can_write&&p.id!==draft.lead_id);
 return <Dialog title="Project review team" onClose={onClose}><p className="sr-dialog-intro">{board.name}. The student lead and assigned supporters can update this project's review.</p><form onSubmit={e=>{e.preventDefault();if(!busy)onSave(draft);}}>{error&&<p className="sr-error" role="alert">{error}</p>}<fieldset className="sr-fields" disabled={busy}><PersonSelect label="Student lead" value={draft.lead_id} people={students} onChange={id=>setDraft(d=>({...d,lead_id:id,supporter_ids:d.supporter_ids.filter(x=>x!==id)}))}/><PeopleChoices label="Support team" ids={draft.supporter_ids} people={supporters} onChange={ids=>setDraft(d=>({...d,supporter_ids:ids}))}/><p className="sr-caption">This is the review team. Task owners and due dates stay in Planning.</p></fieldset><Footer busy={busy} onClose={onClose} label="Save review team"/></form></Dialog>;
}
export function UpdateDialog({board,review,data,entry,prior,busy,error,onClose,onSave}:BaseProps&{board:ReviewBoard;review:SprintReview;data:SprintReviewContext;entry?:ProjectReviewUpdate;prior?:ProjectReviewUpdate;onSave:(p:UpdateSave)=>void}){
 const fieldId=useId(),fieldsRef=useRef<HTMLDivElement>(null);
 const [draft,setDraft]=useState<UpdateSave>(()=>entry?updatePayload(entry):blankUpdate(review.id,board.id)),[tab,setTab]=useState('progress'),[validation,setValidation]=useState('');
 const change=<K extends keyof UpdateSave>(key:K,value:UpdateSave[K])=>setDraft(d=>({...d,[key]:value}));
 const linked=data.tasks.find(t=>t.id===draft.linked_task_id)||entry?.linked_task?.id===draft.linked_task_id&&entry.linked_task||null;
 const source=prior?.id===draft.carry_from_update_id?data.reviews.find(r=>r.id===prior.review_id):null;
 useEffect(()=>{fieldsRef.current?.scrollTo({top:0});},[tab]);
 const workflow=draft.decision_workflow;
 const tabs=workflow?[['progress','1 · Progress'],['compare','2 · Compare options'],['decision','3 · Student decision'],['next','4 · Next action']]:[['progress','1 · Progress'],['decision','2 · Student decision'],['next','3 · Next action']];
 function startComparison(){change('decision_workflow',blankDecisionWorkflow());setTab('compare');}
 function submit(){
  if(busy)return;
  const issue=validateReviewPayload('update',draft);setValidation(issue||'');
  if(issue){
   if(draft.evidence.some(r=>!r.label.trim()||!safeReferenceUrl(r.url)))setTab('progress');
   else if(draft.decision_references.some(r=>!r.label.trim()||!safeReferenceUrl(r.url)))setTab('decision');
   else if(workflow&&decisionWorkflowIssue(workflow,draft)){
    const comparisonIssue=decisionWorkflowIssue({...workflow,status:'comparing'},draft);
    setTab(comparisonIssue||!workflow.owner_id?'compare':'decision');
   }
   return;
  }
  onSave(draft);
 }
 const comparisonInvite=<section className="sr-comparison-invite"><h3>Have a design choice to make?</h3><p>Compare measurable engineering criteria and requirements, add optional SWOT, then record the students' choice. One focused comparison per project and review.</p><button type="button" onClick={startComparison}><Plus size={14}/>Compare design options</button></section>;
 const textarea=(key:'progress'|'blockers'|'tradeoffs'|'decisions_needed'|'reported_decision'|'decision_rationale'|'next_test',label:string,placeholder:string,rows=3)=><div className="sr-field"><label htmlFor={`${fieldId}-${key}`}>{label}</label><textarea id={`${fieldId}-${key}`} maxLength={5000} rows={rows} value={draft[key]} onChange={e=>change(key,e.target.value)} placeholder={placeholder}/></div>;
 return <Dialog title={entry?'Edit weekly update':'Weekly update'} className="sr-update-dialog" onClose={onClose}><p className="sr-dialog-intro"><strong>{board.name}</strong><span>{review.title} · {review.review_date}</span></p><form noValidate onSubmit={e=>{e.preventDefault();submit();}}>{(validation||error)&&<p className="sr-error" role="alert">{validation||error}</p>}<div ref={fieldsRef} className="sr-update-scroll"><fieldset className="sr-fields" disabled={busy}>
 {prior?.unresolved&&!entry&&!draft.carry_from_update_id&&<section className="sr-carry-prompt"><strong>Open items from the previous review</strong><p>{prior.decisions_needed||prior.blockers||prior.next_test||'This project was left open.'}</p><button type="button" onClick={()=>setDraft(d=>carryOpenItems(d,prior))}>Carry forward open items</button><small>Copies blockers, trade-offs, questions and the next test. Add this week's evidence.</small></section>}
 {draft.carry_from_update_id&&<p className="sr-carry-note">Carried from {source?.title||entry?.carried_from?.review_title||'an earlier review'}{source?` · ${source.review_date}`:''}. Earlier evidence and decisions remain in that review.</p>}
 <div className={`sr-editor-tabs${workflow?' has-comparison':''}`} role="tablist" aria-label="Weekly update sections">{tabs.map(([value,label])=><button key={value} type="button" role="tab" aria-selected={tab===value} tabIndex={tab===value?0:-1} onKeyDown={e=>{const order=tabs.map(([value])=>value);let index=order.indexOf(tab);if(e.key==='ArrowRight')index=(index+1)%order.length;else if(e.key==='ArrowLeft')index=(index+order.length-1)%order.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=order.length-1;else return;e.preventDefault();setTab(order[index]);document.getElementById(`${fieldId}-tab-${order[index]}`)?.focus();}} aria-controls={`${fieldId}-panel-${value}`} id={`${fieldId}-tab-${value}`} onClick={()=>setTab(value)}>{label}</button>)}</div>
 <div role="tabpanel" id={`${fieldId}-panel-progress`} aria-labelledby={`${fieldId}-tab-progress`} hidden={tab!=='progress'}><div className="sr-form-stack"><AssemblySnapshotPicker actorId={data.user_id} boardId={board.id} progress={draft.progress} onInsert={value=>change('progress',value)}/>{textarea('progress','Progress this week','What changed? Describe the test, result or working improvement.')}{textarea('blockers','Blockers','What is stopping progress, and what help would unlock it?',2)}<ReferencesEditor label="Evidence" rows={draft.evidence} onChange={rows=>change('evidence',rows)}/>{textarea('tradeoffs','Trade-offs considered','Which options did students compare? What did each gain or give up?',2)}{!workflow&&<>{textarea('decisions_needed','Decision needed','What should the team discuss at this review?',2)}{comparisonInvite}</>}</div></div>
 {workflow&&<div role="tabpanel" id={`${fieldId}-panel-compare`} aria-labelledby={`${fieldId}-tab-compare`} hidden={tab!=='compare'}><div className="sr-form-stack">{textarea('decisions_needed','Decision needed','What design question should this comparison answer?',2)}<DecisionEditor workflow={workflow} people={data.members} decisionOwner={entry?.decision_owner} onChange={value=>change('decision_workflow',value)}/><div className="sr-actions"><button type="button" onClick={()=>setTab('decision')}>Continue to student decision</button><button type="button" className="sr-text-button" onClick={()=>{change('decision_workflow',null);setTab('progress');}}>Remove comparison from update</button></div></div></div>}
 <div role="tabpanel" id={`${fieldId}-panel-decision`} aria-labelledby={`${fieldId}-tab-decision`} hidden={tab!=='decision'}><div className="sr-form-stack"><p className="sr-caption">Record the students' reported choice. Link existing architecture or decision records when relevant. Their IDs and links remain authoritative.</p>{workflow?<DecisionRecordFields workflow={workflow} onChange={value=>change('decision_workflow',value)}/>:comparisonInvite}{textarea('reported_decision','Reported student decision','What did the students decide or propose?')}{textarea('decision_rationale','Decision rationale','Why this choice? Name the evidence and trade-off that mattered.')}<PeopleChoices label="Student participants" ids={draft.reported_by_student_ids} people={data.members.filter(p=>p.active&&p.can_write&&p.is_student)} onChange={ids=>change('reported_by_student_ids',ids)}/><ReferencesEditor label="Decision reference" rows={draft.decision_references} onChange={rows=>change('decision_references',rows)}/>{workflow&&<button type="button" onClick={()=>setTab('next')}>Continue to next action</button>}</div></div>
 <div role="tabpanel" id={`${fieldId}-panel-next`} aria-labelledby={`${fieldId}-tab-next`} hidden={tab!=='next'}><div className="sr-form-stack">{textarea('next_test','Next test or action','What will students test next, and what result will inform the next decision?')}<div className="sr-field"><label htmlFor={`${fieldId}-task`}>Linked Planning task</label><select id={`${fieldId}-task`} value={draft.linked_task_id||''} onChange={e=>change('linked_task_id',e.target.value||null)}><option value="">Choose an existing task</option>{data.tasks.filter(t=>t.available).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}{draft.linked_task_id&&!data.tasks.some(t=>t.id===draft.linked_task_id&&t.available)&&<option value={draft.linked_task_id}>Linked task unavailable</option>}</select></div>{linked&&<TaskReference task={linked}/>}<p className="sr-caption">The task's current owners and due date come from Planning. Update them on the project board.</p><label className="sr-check"><input type="checkbox" checked={draft.unresolved} onChange={e=>change('unresolved',e.target.checked)}/><span>Keep this discussion open for the next review</span></label></div></div>
 </fieldset></div><Footer busy={busy} onClose={onClose} label="Save weekly update"/></form></Dialog>;
}
