import {useEffect,useRef,useState} from 'react';
import {supabase} from '../../attendance/service';
import {finishReviewSave,pendingReviewSave,ReviewSession,reviewStorageAvailable} from './session';
import {reconcileReview} from './service';
export function ReviewRecovery({actorId,route,onResolved}:{actorId:string;route:string;onResolved:()=>void}){
 const [receipt,setReceipt]=useState(()=>pendingReviewSave(actorId)),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const session=useRef(new ReviewSession({actorId,route,seasonId:null})).current,checking=useRef(false);
 const actualRoute=()=>typeof location==='undefined'?route:location.hash;
 useEffect(()=>{session.activate();const sync=()=>{if(session.current(session.ticket(),actualRoute()))setReceipt(pendingReviewSave(actorId));},leave=()=>{if(actualRoute()!==route){session.dispose();setReceipt(null);setMessage('');setError('');}};window.addEventListener('sprint-review-receipt-change',sync);window.addEventListener('hashchange',leave);const auth=supabase?.auth.onAuthStateChange((_event,next)=>{if(next?.user.id!==actorId){session.dispose();setReceipt(null);setMessage('');setError('');}});return()=>{session.dispose();window.removeEventListener('sprint-review-receipt-change',sync);window.removeEventListener('hashchange',leave);auth?.data.subscription.unsubscribe();};},[]);
 async function recover(cancel:boolean){if(!receipt||checking.current)return;const ticket=session.ticket();if(!session.current(ticket,actualRoute()))return;const controller=session.controller();checking.current=true;setBusy(true);setError('');setMessage('');try{const result=await reconcileReview(actorId,receipt.request_id,cancel,controller.signal,undefined,()=>session.current(ticket,actualRoute()));if(!session.current(ticket,actualRoute()))return;if(result.status==='unknown')setMessage('This save has not appeared yet. Check again, or cancel the pending save before starting a replacement.');else{finishReviewSave(receipt);setReceipt(null);setMessage(result.status==='applied'?'The save completed. Refreshing the review you can currently access.':'The pending save was cancelled. You can start a new update.');onResolved();}}catch(e){if(session.current(ticket,actualRoute()))setError((e as Error).message);}finally{session.release(controller);checking.current=false;if(session.current(ticket,actualRoute()))setBusy(false);}}
 return <>{message&&<p className="sr-notice" role="status">{message}</p>}{error&&<p className="sr-error" role="alert">{error}</p>}{receipt&&<section className="sr-recovery" aria-label="Pending review save"><strong>One save needs checking</strong><p>A response was interrupted. The draft is cleared; a private receipt lets you check whether it completed. New saves are paused until you resolve it.</p><div className="sr-actions"><button disabled={busy} onClick={()=>void recover(false)}>{busy?'Checking…':'Check save status'}</button><button disabled={busy} onClick={()=>void recover(true)}>Cancel pending save</button></div><small>{!reviewStorageAvailable()&&'Browser storage is unavailable. Keep this tab open until the save is resolved. '}Cancel stops a save that has not completed. It does not undo a completed change.</small></section>}</>;
}
