import {ArrowUpRight,Check,Clock3,FileText,Link2,MessageSquare,Users} from 'lucide-react';
import {queueLabels,reviewQueueReasons,safeReferenceUrl} from './model';
import type {ProjectReviewUpdate,ReviewBoard,ReviewReference,ReviewTask,SprintReview,SprintReviewContext} from './types';

export function TaskReference({task,onOpenTask}:{task:ReviewTask|null;onOpenTask?:(id:string)=>void}){
 if(!task)return <p className="sr-empty-field">No Planning task linked yet.</p>;
 if(!task.available)return <div className="sr-task-reference"><strong>Linked task unavailable</strong><p>The current task details are no longer accessible.</p></div>;
 return <div className="sr-task-reference"><span className="sr-eyebrow">Next Planning task</span>{onOpenTask?<button type="button" className="sr-text-button" onClick={()=>onOpenTask(task.id)}>{task.title}<ArrowUpRight size={15}/></button>:<a href={`#planning/boards/${task.board_id}`}>{task.title}<ArrowUpRight size={15}/></a>}<div className="sr-task-meta"><span><Users size={13}/>{task.owners.length?task.owners.map(p=>p.name).join(', '):'Owner needed'}</span><span><Clock3 size={13}/>{task.due_date?`Due ${task.due_date}`:task.due_date_unavailable?'Due date unavailable':'Due date needed'}</span></div><small>Current Planning record{task.status?` · ${task.status.replaceAll('_',' ')}`:''}</small></div>;
}
export function ReferenceList({rows,label}:{rows:ReviewReference[];label:string}){return rows.length?<ul className="sr-references" aria-label={label}>{rows.map((r,i)=>{const url=safeReferenceUrl(r.url);return <li key={i}><Link2 size={13}/><div>{url?<a href={url} target="_blank" rel="noopener noreferrer">{r.label}<ArrowUpRight size={12}/></a>:<span>{r.label} · link unavailable</span>}{r.reference_id&&<small>{r.reference_id}</small>}</div></li>;})}</ul>:<p className="sr-empty-field">No {label.toLowerCase()} linked yet.</p>;}
function Field({label,value}:{label:string;value:string}){return <div className="sr-update-field"><h4>{label}</h4>{value.trim()?<p>{value}</p>:<p className="sr-empty-field">Not recorded yet.</p>}</div>;}
export function ProjectReviewCard({board,entry,prior,canManage,disabled,onUpdate,onAssignment,onOpenTask}:{board:ReviewBoard;entry?:ProjectReviewUpdate;prior?:ProjectReviewUpdate;canManage:boolean;disabled:boolean;onUpdate:()=>void;onAssignment:()=>void;onOpenTask?:(id:string)=>void}){
 const reasons=reviewQueueReasons(board,entry,prior),lead=board.assignment?.lead,supporters=board.assignment?.supporters||[];
 return <article className="sr-project-card" id={`review-project-${board.id}`} aria-labelledby={`review-project-title-${board.id}`}>
 <header className="sr-project-heading"><div><a className="sr-project-title" id={`review-project-title-${board.id}`} href={`#planning/boards/${board.id}`}>{board.name}<ArrowUpRight size={15}/></a><p className="sr-project-team"><span className="sr-avatar" aria-hidden="true">{lead?.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('')||'–'}</span><span>{lead?`${lead.name} · student lead`:'Student lead needed'}{lead&&!lead.active?' · inactive':''}{supporters.length>0&&<small>With {supporters.map(p=>p.name).join(', ')}</small>}</span></p></div><div className="sr-project-actions">{board.can_edit_update&&<button className={entry?'':'sr-primary'} disabled={disabled} onClick={onUpdate}>{entry?'Edit update':'Weekly update'}</button>}{canManage&&board.active&&<button className="sr-icon-button" disabled={disabled} onClick={onAssignment} aria-label={`Assign review team for ${board.name}`} title="Assign review team"><Users size={17}/></button>}</div></header>
 {!board.active&&<p className="sr-caption sr-inactive">This project is inactive. Its review record is read only.</p>}
 <div className="sr-project-status"><span className={`sr-status ${entry?'':'is-muted'}`}>{entry?<><Check size={12}/>Update recorded</>:<><FileText size={12}/>Awaiting update</>}</span>{entry?.unresolved&&<span className="sr-status is-open">Discussion open</span>}{reasons.filter(r=>!['update','lead','carry'].includes(r)).slice(0,3).map(r=><span className="sr-gap" key={r}>{queueLabels[r]}</span>)}</div>
 {entry?<><div className="sr-project-summary"><Field label="Progress this week" value={entry.progress}/>{entry.blockers.trim()&&<Field label="Blockers" value={entry.blockers}/>}<ReferenceList rows={entry.evidence} label="Evidence"/>{entry.decisions_needed.trim()&&<div className="sr-decision-prompt"><MessageSquare size={16}/><div><h4>Decision to discuss</h4><p>{entry.decisions_needed}</p></div></div>}</div><details className="sr-update-details"><summary>Trade-offs & student decision</summary><Field label="Trade-offs considered" value={entry.tradeoffs}/><Field label="Reported student decision" value={entry.reported_decision}/>{entry.reported_decision.trim()&&<><Field label="Rationale" value={entry.decision_rationale}/><p className="sr-caption">Students: {entry.reported_students.length?entry.reported_students.map(p=>p.name).join(', '):'Participants not recorded yet'}</p></>}<ReferenceList rows={entry.decision_references} label="Decision references"/></details><div className="sr-next-action"><Field label="Next test or action" value={entry.next_test}/><TaskReference task={entry.linked_task} onOpenTask={onOpenTask}/></div><div className="sr-record-meta"><span>Updated {new Date(entry.recorded_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · version {entry.version}</span>{entry.carried_from&&<a href={`#planning/reviews/${entry.carried_from.review_id}`}>Carried from {entry.carried_from.review_date}</a>}</div></>:<div className="sr-project-empty"><p>Bring the week's progress, evidence and open decisions here.</p>{prior?.unresolved&&<p className="sr-prior-hint"><Clock3 size={14}/>This project has open items from an earlier review. {board.can_edit_update?'Open Weekly update to carry them forward.':'They can be carried forward by the review team.'}</p>}{!board.can_edit_update&&<small>{lead?'The assigned review team can add this update.':'A facilitator can assign the project review team.'}</small>}</div>}
 </article>;
}
export function ReviewQueue({data,boards,onProject}:{data:SprintReviewContext;boards:ReviewBoard[];onProject:(boardId:string)=>void}){const items=boards.filter(b=>b.active).map(board=>({board,reasons:reviewQueueReasons(board,data.updates.find(u=>u.board_id===board.id),data.previous_updates.find(u=>u.board_id===board.id))})).filter(x=>x.reasons.length);return <aside className="sr-queue" aria-label="Review discussion queue"><header><span className="sr-eyebrow">Before we wrap</span><h2>Review queue <span>{items.length}</span></h2><p>Prompts for a useful discussion.</p></header>{items.length?<ol>{items.map(({board,reasons})=><li key={board.id}><button className="sr-text-button" onClick={()=>onProject(board.id)}>{board.name}<ArrowUpRight size={13}/></button><ul>{reasons.map(reason=><li key={reason}>{queueLabels[reason]}</li>)}</ul></li>)}</ol>:<div className="sr-queue-clear"><Check size={20}/><strong>All prompts covered</strong><p>Keep the conversation focused on what the evidence means.</p></div>}<details className="sr-queue-rules"><summary>How these prompts work</summary><p>A prompt appears when a project has no update or active student lead; evidence, trade-offs, next test, or linked task owner/date are missing; an open question needs discussion; or a reported decision has no rationale or student participants. Prior open items appear only when this review has no update.</p><p>These are field checks. They do not score the quality of students' work.</p></details></aside>;}
export function ReviewAgenda({review,data}:{review:SprintReview;data:SprintReviewContext}){return <details className="sr-agenda"><summary><span>Meeting agenda</span><span>{review.agenda.length} items · {review.agenda.reduce((n,a)=>n+a.duration_minutes,0)} min</span></summary>{review.agenda.length?<ol>{review.agenda.map((a,i)=><li key={i}><span className="sr-agenda-number">{i+1}</span><div><strong>{a.title}</strong><small>{data.members.find(p=>p.id===a.presenter_id)?.name||(a.presenter_id?'Previously selected presenter':'Presenter to be confirmed')}</small></div><span>{a.duration_minutes} min</span></li>)}</ol>:<p className="sr-caption">The facilitator has not added agenda items yet.</p>}</details>;}
