import type {SupabaseClient} from '@supabase/supabase-js';
import {supabase} from '../../attendance/service';
import {assertReviewContext,uuid} from './model';
import type {ReviewMutation,ReviewMutationReceipt} from './types';

export class ReviewServiceError extends Error{constructor(message:string,readonly outcome:'rejected'|'unknown'='rejected'){super(message);}}
export function assertReviewReceipt(value:unknown,requestId:string):ReviewMutationReceipt{
 const r=value as ReviewMutationReceipt;
 if(!r||r.request_id!==requestId||!['applied','cancelled','unknown'].includes(r.status)||(r.status==='applied'?(!['review','assignment','update'].includes(r.action||'')||!r.entity_id||!uuid.test(r.entity_id)||!Number.isSafeInteger(r.version)||Number(r.version)<1):(r.action!==null||r.entity_id!==null||r.version!==null)))throw new ReviewServiceError('The save result could not be verified. Check its status before trying again.','unknown');return r;
}
export function assertReviewReceiptMatches(value:unknown,mutation:ReviewMutation){const receipt=assertReviewReceipt(value,mutation.request_id);const id=mutation.action==='assignment'?'board_id' in mutation.p?mutation.p.board_id:null:'id' in mutation.p?mutation.p.id:null;if(receipt.status==='applied'&&(receipt.action!==mutation.action||receipt.entity_id!==id||receipt.version!==(mutation.p.version??0)+1))throw new ReviewServiceError('The save result did not match this change. Check its status before trying again.','unknown');return receipt;}
async function checkedSession(client:SupabaseClient,signal:AbortSignal){let cancel=()=>{};try{return await Promise.race([client.auth.getSession(),new Promise<never>((_,reject)=>{cancel=()=>reject(new ReviewServiceError('Your account changed. Reload Sprint Review.'));signal.addEventListener('abort',cancel,{once:true});if(signal.aborted)cancel();})]);}finally{signal.removeEventListener('abort',cancel);}}
async function request(name:string,args:Record<string,unknown>,actorId:string,signal:AbortSignal,write:boolean,client:SupabaseClient|null,isCurrent:()=>boolean):Promise<unknown>{
 if(!client)throw new ReviewServiceError('Team connection unavailable.');if(signal.aborted||!isCurrent())throw new ReviewServiceError('This request was closed.');
 const abandoned=new AbortController(),timeout=AbortSignal.any([signal,abandoned.signal,AbortSignal.timeout(15000)]);let dispatched=false;
 const leave=()=>{if(!isCurrent())abandoned.abort();};const subscription=client.auth.onAuthStateChange((_event,next)=>{if(next?.user.id!==actorId)abandoned.abort();}).data.subscription;
 if(typeof window!=='undefined')window.addEventListener('hashchange',leave);
 try{const {data:auth,error}=await checkedSession(client,timeout);if(timeout.aborted||!isCurrent()||error||auth.session?.user.id!==actorId||!auth.session.access_token)throw new ReviewServiceError('Your account changed. Reload Sprint Review.');
  // Pin the exact token checked above across the SDK's later lazy token lookup.
  dispatched=true;const result=await client.rpc(name,args).setHeader('Authorization',`Bearer ${auth.session.access_token}`).retry(false).abortSignal(timeout);
  if(timeout.aborted||!isCurrent())throw new ReviewServiceError('This view changed before the result could be confirmed.',write?'unknown':'rejected');
  if(result.error){const code=result.error.code||'',rejected=!!code&&![408,429].includes(result.status)&&(/^SR(401|403|409|412|422)$/.test(code)||!code.startsWith('SR')&&(result.status>=400&&result.status<500||/^(22|23|40|42|P0)/.test(code)));const message=code==='SR409'?'Another teammate changed this record. Close the editor and refresh before saving.':code==='SR403'?'Your access to this project or review changed. Close the editor and refresh.':code==='SR401'?'Your account changed. Reload Sprint Review.':code==='SR422'?'Check the fields, active participants and linked Planning records.':code==='SR412'?'This request could not be reused. Check its status before starting another.':rejected?'This change could not be saved. Refresh before trying again.':'The connection ended before the result could be confirmed.';throw new ReviewServiceError(message,write&&!rejected?'unknown':'rejected');}return result.data;
 }catch(e){if(e instanceof ReviewServiceError)throw e;throw new ReviewServiceError(write&&dispatched?'The save may have completed. Check its status.':'Sprint Review could not be loaded. Refresh to try again.',write&&dispatched?'unknown':'rejected');}
 finally{subscription.unsubscribe();if(typeof window!=='undefined')window.removeEventListener('hashchange',leave);}
}
export async function loadReview(actorId:string,seasonId:string|null,reviewId:string|null,signal:AbortSignal,client:SupabaseClient|null=supabase,isCurrent:()=>boolean=()=>true){return assertReviewContext(await request('sprint_review_context',{selected_season:seasonId,selected_review:reviewId},actorId,signal,false,client,isCurrent),actorId,seasonId,reviewId);}
export async function saveReview(mutation:ReviewMutation,signal:AbortSignal,client:SupabaseClient|null=supabase,isCurrent:()=>boolean=()=>true){return assertReviewReceiptMatches(await request('sprint_review_save',mutation,mutation.expected_actor,signal,true,client,isCurrent),mutation);}
export async function reconcileReview(actorId:string,requestId:string,cancel:boolean,signal:AbortSignal,client:SupabaseClient|null=supabase,isCurrent:()=>boolean=()=>true){return assertReviewReceipt(await request(cancel?'sprint_review_cancel_mutation':'sprint_review_mutation_status',{request_id:requestId,expected_actor:actorId},actorId,signal,cancel,client,isCurrent),requestId);}
