import {useEffect,useRef,useState} from 'react';
import {CalendarDays,Download,Plus,RefreshCw,Settings2,Users} from 'lucide-react';
import {supabase} from '../../attendance/service';
import type {ProjectReviewUpdate,ReviewBoard,ReviewSaveAction,ReviewSavePayload,SprintReview,SprintReviewContext} from './types';
import {reviewRoute,validateReviewPayload} from './model';
import {finishReviewSave,pendingReviewSave,rememberReviewSave,ReviewSession} from './session';
import {loadReview,ReviewServiceError,saveReview} from './service';
import {AssignmentDialog,ReviewSettingsDialog,UpdateDialog} from './ReviewDialogs';
import {ProjectReviewCard,ReviewAgenda,ReviewQueue} from './ReviewViews';
import {ReviewRecovery} from './ReviewRecovery';
import './reviews.css';

export type SprintReviewProps={actorId:string;route:string;seasonId?:string|null;onSeasonChange?:(id:string)=>void;onOpenTask?:(id:string)=>void};
type Editor={kind:'review';review:SprintReview|null}|{kind:'assignment';board:ReviewBoard}|{kind:'update';board:ReviewBoard;review:SprintReview;entry?:ProjectReviewUpdate;prior?:ProjectReviewUpdate};
/** Remount scope changes before old data, editors or exports can be displayed. */
export function SprintReviewWorkspace(props:SprintReviewProps){return <ScopedReview key={`${props.actorId}:${props.seasonId||''}`} {...props}/>;}
function ScopedReview(props:SprintReviewProps){
 const [selectedSeason,setSelectedSeason]=useState(props.seasonId||null);
 // A review link determines its own authorized season. Keep the dropdown choice
 // for the landing page without applying it to Back/Forward or another direct link.
 const requestSeason=reviewRoute(props.route).id?null:selectedSeason;
 return <ReviewWorkspace key={`${props.actorId}:${props.route}:${selectedSeason||''}`} {...props} seasonId={requestSeason} onSeasonChange={id=>{setSelectedSeason(id);props.onSeasonChange?.(id);if(location.hash!=='#planning/reviews')location.hash='planning/reviews';}}/>;
}
function ReviewWorkspace({actorId,route,seasonId=null,onSeasonChange,onOpenTask}:SprintReviewProps){
 const [data,setData]=useState<SprintReviewContext|null>(null),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[editor,setEditor]=useState<Editor|null>(null),[editorError,setEditorError]=useState(''),[busy,setBusy]=useState(false),[exporting,setExporting]=useState(false),[receipt,setReceipt]=useState(()=>pendingReviewSave(actorId));
 const [filter,setFilter]=useState<'all'|'mine'>('all'),[search,setSearch]=useState(''),[fontMode,setFontMode]=useState<'reference'|'arial'>('reference');
 const parsed=reviewRoute(route),session=useRef(new ReviewSession({actorId,route,seasonId})).current,saving=useRef(false),exportingRef=useRef(false),readGeneration=useRef(0);
 const actualRoute=()=>typeof location==='undefined'?route:location.hash;
 async function refresh(){const ticket=session.ticket(),generation=++readGeneration.current,controller=session.controller();setData(null);setError('');try{const context=await loadReview(actorId,seasonId,parsed.id,controller.signal,undefined,()=>session.current(ticket,actualRoute()));if(session.current(ticket,actualRoute())&&generation===readGeneration.current){setData(context);setReceipt(pendingReviewSave(actorId));}}catch(e){if(session.current(ticket,actualRoute())&&generation===readGeneration.current)setError((e as Error).message);}finally{session.release(controller);}}
 useEffect(()=>{session.activate();if(parsed.valid)void refresh();const clear=()=>{session.dispose();setData(null);setEditor(null);setEditorError('');setFeedback('');setError('');setReceipt(null);setExporting(false);},leave=()=>{if(actualRoute()!==route)clear();},sync=()=>{if(session.current(session.ticket(),actualRoute()))setReceipt(pendingReviewSave(actorId));};window.addEventListener('hashchange',leave);window.addEventListener('sprint-review-receipt-change',sync);const auth=supabase?.auth.onAuthStateChange((_event,next)=>{if(next?.user.id!==actorId)clear();});return()=>{session.dispose();readGeneration.current++;window.removeEventListener('hashchange',leave);window.removeEventListener('sprint-review-receipt-change',sync);auth?.data.subscription.unsubscribe();};},[]);
 const selected=data?.reviews.find(r=>r.id===data.selected_review_id),season=data?.seasons.find(s=>s.id===data.season_id),canManage=!!data?.can_manage&&!!season&&season.status!=='archived';
 function open(next:Editor){if(saving.current||pendingReviewSave(actorId)||!data)return;if(next.kind==='update'?!next.board.can_edit_update:!canManage)return;session.openEditor();setEditor(next);setEditorError('');setFeedback('');setExporting(false);}
 function close(){session.closeEditor();setEditor(null);setEditorError('');setBusy(false);setReceipt(pendingReviewSave(actorId));}
 async function submit(action:ReviewSaveAction,p:ReviewSavePayload){
  if(saving.current||!editor||!data||pendingReviewSave(actorId))return;const ticket=session.ticket();if(!session.current(ticket,actualRoute())||action!==editor.kind)return;
  if(action==='update'?editor.kind!=='update'||!editor.board.can_edit_update:!canManage)return;const issue=validateReviewPayload(action,p);if(issue){setEditorError(issue);return;}
  const recovery={request_id:crypto.randomUUID(),expected_actor:actorId};try{rememberReviewSave(recovery);}catch(e){setEditorError((e as Error).message);return;}saving.current=true;setBusy(true);setReceipt(recovery);setEditorError('');const controller=session.controller();
  try{const result=await saveReview({...recovery,action,p},controller.signal,undefined,()=>session.current(ticket,actualRoute()));if(result.status==='unknown')throw new ReviewServiceError('The save has not been confirmed. Check its status.','unknown');if(session.current(ticket,actualRoute())){finishReviewSave(recovery);close();setFeedback(result.status==='applied'?(action==='review'?'Review saved.':action==='assignment'?'Project review team saved.':'Weekly update saved.'):'The pending save was cancelled.');if(action==='review'&&result.status==='applied'&&result.entity_id&&result.entity_id!==selected?.id){location.hash=`planning/reviews/${result.entity_id}`;}else await refresh();}}
  catch(e){if(e instanceof ReviewServiceError&&e.outcome==='rejected'&&session.current(ticket,actualRoute()))finishReviewSave(recovery);if(session.current(ticket,actualRoute())){if(pendingReviewSave(actorId)){close();setFeedback('The save may have completed. Check its status before starting another save.');}else setEditorError((e as Error).message);}}
  finally{session.release(controller);saving.current=false;if(session.current(ticket,actualRoute()))setBusy(false);}
 }
 async function exportDeck(){if(!data||!selected||exportingRef.current||editor)return;const ticket=session.ticket(),context=data;exportingRef.current=true;setExporting(true);setError('');setFeedback('');try{const {createReviewPptx}=await import('./export');if(!session.current(ticket,actualRoute()))return;const result=await createReviewPptx(context,selected.id,{fontMode});if(!session.current(ticket,actualRoute())||pendingReviewSave(actorId))return;const url=URL.createObjectURL(result.blob),link=document.createElement('a');link.href=url;link.download=result.filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setFeedback(`Editable PowerPoint exported · ${result.slideCount} slides. ${result.warnings.join(' ')}`);}catch(e){if(session.current(ticket,actualRoute()))setError(`PowerPoint export failed. ${(e as Error).message}`);}finally{exportingRef.current=false;if(session.current(ticket,actualRoute()))setExporting(false);}}
 const boards=data?.boards.filter(b=>b.name.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||b.assignment?.lead_id===actorId||b.assignment?.supporter_ids.includes(actorId)))||[],activeBoards=data?.boards.filter(b=>b.active)||[],updated=activeBoards.filter(b=>data?.updates.some(u=>u.board_id===b.id)).length;
 function revealProject(boardId:string){setFilter('all');setSearch('');requestAnimationFrame(()=>{const element=document.getElementById(`review-project-${boardId}`);element?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});element?.querySelector<HTMLElement>('.sr-project-title')?.focus({preventScroll:true});});}
 return <section className="sprint-review" aria-label="Sprint Review workspace"><header className="sr-page-heading"><div><span className="sr-eyebrow">Planning · Weekly rhythm</span><h1>Sprint Review</h1><p>Student-led progress, evidence, and the next decision.</p></div><div className="sr-header-actions"><button disabled={busy||!!editor||exporting} onClick={()=>void refresh()} aria-label="Refresh Sprint Review"><RefreshCw size={15}/><span>Refresh</span></button>{canManage&&<button disabled={!!receipt||busy||exporting} onClick={()=>open({kind:'review',review:null})}><Plus size={15}/>New review</button>}</div></header>
 <ReviewRecovery key={`${actorId}:${route}`} actorId={actorId} route={route} onResolved={()=>{setReceipt(pendingReviewSave(actorId));close();void refresh();}}/>
 {!parsed.valid?<p className="sr-error" role="alert">This review link is invalid. <a href="#planning/reviews">Open Sprint Review</a></p>:<>
 {error&&<p className="sr-error" role="alert">{error}{!data&&<button onClick={()=>void refresh()}>Retry review</button>}</p>}{feedback&&<p className="sr-notice" role="status">{feedback}</p>}{!data&&!error&&<p className="sr-loading" role="status">Loading Sprint Review…</p>}
 {data&&<>{data.seasons.length>0&&<div className="sr-selectors"><label>Planning season<select value={data.season_id||''} onChange={e=>onSeasonChange?.(e.target.value)} disabled={busy||!!editor}>{data.seasons.map(s=><option key={s.id} value={s.id}>{s.name} · {s.status}</option>)}</select></label><label>Review<select value={data.selected_review_id||''} disabled={!data.reviews.length||busy||!!editor} onChange={e=>{location.hash=`planning/reviews/${e.target.value}`;}}>{!data.reviews.length&&<option value="">No reviews yet</option>}{data.reviews.map(r=><option key={r.id} value={r.id}>{r.review_date} · {r.title}</option>)}</select></label></div>}{data.reviews_limit_reached&&<p className="sr-caption">Showing the latest 100 reviews and this selected review. Older reviews remain available from their direct links.</p>}
 {!season?<div className="sr-empty"><CalendarDays size={30}/><h2>No planning season available</h2><p>A planning season gives weekly reviews their projects and shared context.</p><a href="#planning">Open Planning</a></div>:!selected?<div className="sr-empty"><CalendarDays size={30}/><h2>Start your weekly rhythm</h2><p>Bring project updates into one focused conversation. Set an agenda, hear the evidence, and leave with a clear next test.</p>{canManage?<button className="sr-primary" disabled={!!receipt} onClick={()=>open({kind:'review',review:null})}><Plus size={16}/>Create first review</button>:<p>Your facilitator will add the first review here.</p>}</div>:<>
 {season.status==='archived'&&<p className="sr-notice">This archived season is read only.</p>}<section className="sr-meeting" aria-labelledby="sr-meeting-title"><div className="sr-meeting-top"><div><span className="sr-eyebrow">Selected review</span><h2 id="sr-meeting-title">{selected.title}</h2><div className="sr-meeting-meta"><span><CalendarDays size={14}/>{selected.review_date}</span><span><Users size={14}/>{data.members.find(p=>p.id===selected.chair_id)?.name||(selected.chair_id?'Previously selected chair':'Chair to be confirmed')}</span><span>{updated}/{activeBoards.length} project updates</span></div></div><div className="sr-actions">{canManage&&<button disabled={!!receipt||busy||exporting} onClick={()=>open({kind:'review',review:selected})}><Settings2 size={15}/>Review settings</button>}<div className="sr-export"><label><span className="sr-sr-only">PowerPoint style</span><select aria-describedby="sr-export-help" value={fontMode} disabled={exporting} onChange={e=>setFontMode(e.target.value as typeof fontMode)}><option value="reference">Original deck style</option><option value="arial">Common-font compatibility</option></select></label><button disabled={exporting||!!editor||!!receipt} onClick={()=>void exportDeck()}><Download size={15}/>{exporting?'Preparing PowerPoint…':'Export PowerPoint'}</button><small id="sr-export-help">{fontMode==='reference'?'For the original look, install Red Hat Display Black and Red Hat Text.':'Uses Arial for easier editing across computers.'}</small></div></div></div><ReviewAgenda review={selected} data={data}/></section>
 <div className="sr-workspace-grid"><section className="sr-projects" aria-labelledby="sr-projects-title"><div className="sr-projects-toolbar"><div><h2 id="sr-projects-title">Project updates</h2><span>{activeBoards.length} current projects · one update per review</span></div><div className="sr-filter-controls"><label className="sr-search"><span className="sr-sr-only">Search projects</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a project…"/></label><div className="sr-segment" role="group" aria-label="Project filter"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>All</button><button aria-pressed={filter==='mine'} onClick={()=>setFilter('mine')}>My projects</button></div></div></div>{boards.length?boards.map(board=><ProjectReviewCard key={board.id} board={board} entry={data.updates.find(u=>u.board_id===board.id)} prior={data.previous_updates.find(u=>u.board_id===board.id)} canManage={canManage} disabled={!!receipt||busy||exporting} onUpdate={()=>open({kind:'update',board,review:selected,entry:data.updates.find(u=>u.board_id===board.id),prior:data.previous_updates.find(u=>u.board_id===board.id)})} onAssignment={()=>open({kind:'assignment',board})} onOpenTask={onOpenTask}/>):<div className="sr-empty sr-empty-projects"><h3>{data.boards.length?'No projects match':'No project boards yet'}</h3><p>{data.boards.length?'Try All projects or clear the search.':'Create project boards in Planning, then assign their student review leads here.'}</p>{data.boards.length?<button onClick={()=>{setFilter('all');setSearch('');}}>Show all projects</button>:<a href="#planning/boards">Open Planning boards</a>}</div>}</section><ReviewQueue data={data} boards={data.boards} onProject={revealProject}/></div>
 </>}{editor?.kind==='review'&&<ReviewSettingsDialog review={editor.review} data={data} busy={busy} error={editorError} onClose={close} onSave={p=>void submit('review',p)}/>} {editor?.kind==='assignment'&&<AssignmentDialog board={editor.board} data={data} busy={busy} error={editorError} onClose={close} onSave={p=>void submit('assignment',p)}/>} {editor?.kind==='update'&&<UpdateDialog {...editor} data={data} busy={busy} error={editorError} onClose={close} onSave={p=>void submit('update',p)}/>}</>}
 </>}</section>;
}
